games/punchy: unbreak build with clang 16 on aarch64
In file included from cargo-crates/v8-0.47.1/v8/src/compiler/backend/instruction-selector.cc:5:
In file included from cargo-crates/v8-0.47.1/v8/src/compiler/backend/instruction-selector.h:12:
In file included from cargo-crates/v8-0.47.1/v8/src/compiler/backend/instruction-scheduler.h:10:
In file included from cargo-crates/v8-0.47.1/v8/src/compiler/backend/instruction.h:13:
In file included from cargo-crates/v8-0.47.1/v8/src/codegen/external-reference.h:9:
In file included from cargo-crates/v8-0.47.1/v8/src/runtime/runtime.h:11:
cargo-crates/v8-0.47.1/v8/src/base/bit-field.h:43:29: error: integer value 31 is outside the valid range of values [0, 15] for the enumeration type 'AddressingMode' [-Wenum-constexpr-conversion]
  static constexpr T kMax = static_cast<T>(kNumValues - 1);
                            ^

Reported by:	pkg-fallout

(cherry picked from commit 316a89ed4e72fc2c5c49589c0c797ef535ac11af)