devel/py-llfuse: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
devel/py-llfuse failed to build with clang 15:

  src/llfuse.c:41839:21: error: incompatible pointer to integer conversion assigning to 'uintptr_t' (aka 'unsigned int') from 'pthread_t' (aka 'struct pthread *') [-Wint-conversion]
          __pyx_v_tid = __pyx_t_7;
                      ^ ~~~~~~~~~
  src/llfuse.c:42467:3: warning: 'PyEval_InitThreads' is deprecated [-Wdeprecated-declarations]
    PyEval_InitThreads();
    ^
  /usr/local/include/python3.9/ceval.h:130:1: note: 'PyEval_InitThreads' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
  ^
  /usr/local/include/python3.9/pyport.h:508:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  1 warning and 1 error generated.

The conversion from pthread_t to uintptr_t needs an explicit cast.

PR:		268226
Approved by:	maintainer timeout (2 weeks)
MFH:		2022Q4