print/harfbuzz-icu: pacify check-plist after r471882
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: include/harfbuzz/hb-map.h

PR:		228795
Reported by:	rakuco
Pointy hat to:	jbeich