graphics/drm-66-kmod: fix build with clang 21
With clang 21 graphics/drm-66-kmod fails to compile, with errors similar
to:

    In file included from /wrkdirs/usr/ports/graphics/drm-66-kmod/work/drm-kmod-drm_v6.6.25_9/drivers/gpu/drm/i915/i915_active.c:12:
    /wrkdirs/usr/ports/graphics/drm-66-kmod/work/drm-kmod-drm_v6.6.25_9/drivers/gpu/drm/i915/gt/intel_ring.h:63:2: error: default initialization of an object of type 'typeof (ring->size)' (aka 'const unsigned int') leaves the object uninitialized [-Werror,-Wdefault-const-init-var-unsafe]
       63 |         typecheck(typeof(ring->size), next);
          |         ^
    /usr/src/sys/compat/linuxkpi/common/include/linux/typecheck.h:31:9: note: expanded from macro 'typecheck'
       31 | ({      type __var1; \
          |              ^

The thread at https://lkml.org/lkml/2025/5/6/1681 appears to imply that
it is safe to suppress the new -Wdefault-const-init-var-unsafe warning.

PR:		292192
Approved by:	emaste (maintainer)
MFH:		2026Q1

(cherry picked from commit 2b49118158d0aa7cb20d98e470ee080ee0fdc931)