Fix build with LibreSSL
Even though building worked ok, linking to the resulting library
libxmlsec1-openssl.so caused various symbol lookup errors such as:

/usr/local/lib/libxmlsec1-openssl.so: undefined reference to `X509_OBJECT_get0_X509'
/usr/local/lib/libxmlsec1-openssl.so: undefined reference to `ASN1_STRING_get0_data'

As the problem only appears at runtime I bumped the revision.

Approved by:	ssl blanket