devel/gwenhywfar-fox16: Fix build with llvm16
theme.cpp:20:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  register FXint rr,gg,bb,dr,dg,db,r1,g1,b1,r2,g2,b2,yl,yh,yy,dy,n,t;

Reported by:	pkg-fallout
MFH:		2023Q3

(cherry picked from commit 2617740e97b47aac9e57bf4c3bd738868fbcff6a)