net/clash: Unbreak on aarch64
===>  Building clash from .
# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go:400:12: undefined: uint128

http://thunderx1.nyi.freebsd.org/data/head-arm64-default/p518685_s355218/logs/errors/clash-0.16.0_1.log

Unbreak by updating golang.org/x/sys to 33540a1f6037 and golang.org/x/net to
83d349e8ac1a which adds support for freebsd/arm64.

PR:		242577
Approved by:	yuri (maintainer)