Mark broken everywhere source='aliases.c' object='aliases.o' libtool=no  depfile='.deps/aliases.Po' tmpdepfile='.deps/aliases.TPo'  depmode=gcc3 /bin/sh ../depcomp  cc -DHAVE_CONFIG_H -I. -I. -I..      -O2 -pipe  -fno-strict-aliasing  -Wall -c `test -f aliases.c || echo './'`aliases.c In file included from aliases.c:31: gyach.h:66:21: error: gtk/gtk.h: No such file or directory gyach.h:67:21: error: gdk/gdk.h: No such file or directory
Reported by:	pkg-fallout (since several months)