x11/grim: pacify stage-qa after ab18f9711a3f
====> Running Q/A tests (stage-qa)
Error: /usr/local/bin/grim is linked to /usr/local/lib/libpixman-1.so.0 from x11/pixman but it is not declared as a dependency
Warning: you need USE_XORG+=pixman
Error: /usr/local/bin/grim is linked to /usr/local/lib/libpng16.so.16 from graphics/png but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libpng16.so:graphics/png

https://github.com/emersion/grim/commit/af000f990061
https://github.com/emersion/grim/commit/fcaba96aab42
(cherry picked from commit 592d3df5c0bf52862398041cbc55e5e1d83c8102)