misc/openvdb: fix build with clang 19
Clang 19 now implements CWG 96 [1], which requires a template argument
list after a 'template' keyword, resulting in errors similar to:

    /wrkdirs/usr/ports/misc/openvdb/work/openvdb-11.0.0/openvdb/openvdb/../openvdb/tree/NodeManager.h:330:31: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
      330 |                 OpT::template eval(mNodeOp, it);
          |                               ^
    /wrkdirs/usr/ports/misc/openvdb/work/openvdb-11.0.0/openvdb/openvdb/../openvdb/tree/NodeManager.h:350:31: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
      350 |                 OpT::template eval(mNodeOp, it);
          |                               ^
    /wrkdirs/usr/ports/misc/openvdb/work/openvdb-11.0.0/openvdb/openvdb/../openvdb/tree/NodeManager.h:375:31: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
      375 |                 OpT::template eval(*mNodeOp, it);
          |                               ^

In these cases, appending "<>" is enough to satisfy the constraint.

PR:		281418
Approved by:	yuri (maintainer)
MFH:		2024Q3