x11-toolkits/guile-gnome-platform: Fix plist error
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%DATADIR%%/gnome/glade.scm
Error: Orphaned: share/info/guile-gnome-gconf.info
Error: Orphaned: share/info/guile-gnome-libgnome.info
Error: Orphaned: share/info/guile-gnome-libgnomeui.info
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/x11-toolkits/guile-gnome-platform
=>> Error: check-plist failures detected

PR:		266076
Approved by:	maintainer timeout
MFH:		2022Q3

(cherry picked from commit a41d258f25974edae899a96b6ae4991d33bbb12c)