net-p2p/ktorrent: register build-time conflict against net-p2p/libtorrent
Both `net-p2p/libktorrent' (direct dependency) and `net-p2p/libtorrent'
(unrelated port) install `torrent/torrent.h' header file, albeit in the
different locations:

    /usr/local/include/torrent/torrent.h
    /usr/local/include/KF5/libktorrent/torrent/torrent.h

The problem is that when both ports are installed, the first header is
being included which in turn breaks the build in a not-so-obvious way:

    In file included from libktcore/ktcore_autogen/mocs_compilation.cpp:22:
    In file included from libktcore/ktcore_autogen/WEMDBQPFF4/moc_magnetmanager.cpp:10:
    In file included from libktcore/ktcore_autogen/WEMDBQPFF4/../../../../ktorrent-21.04.0/libktcore/torrent/magnetmanager.h:26:
    /usr/local/include/KF5/libktorrent/magnet/magnetdownloader.h:104:5: error: unknown type name 'Torrent'
        Torrent tor;
        ^
    In file included from libktcore/ktcore_autogen/mocs_compilation.cpp:22:
    libktcore/ktcore_autogen/WEMDBQPFF4/moc_magnetmanager.cpp:86:34: error: cannot initialize object parameter of type 'bt::MagnetDownloader' with an expression of type 'kt::MagnetDownloader'
        return bt::MagnetDownloader::qt_metacast(_clname);
                                     ^~~~~~~~~~~
    libktcore/ktcore_autogen/WEMDBQPFF4/moc_magnetmanager.cpp:91:33: error: cannot initialize object parameter of type 'bt::MagnetDownloader' with an expression of type 'kt::MagnetDownloader'
        _id = bt::MagnetDownloader::qt_metacall(_c, _id, _a);
                                    ^~~~~~~~~~~