graphics/libjxl: fix build on powerpc / powerpc64
/usr/local/include/hwy/ops/ppc_vsx-inl.h:2719:34: error: use of 'long long' with '__vector' requires VSX support (available on POWER7 or later) to be enabled

(cherry picked from commit c6132c766da2e4cf17cce9a001331560f6d330ab)