sysutils/logstash94: Fix runtime: restrict JAVA_VERSION for 21 only
Logstash 9.4 supports Java 21 only.

1) Logstash 9.4 doesn't support Java 17:
https://www.elastic.co/docs/release-notes/logstash#logstash-9.4.0-release-notes
"Logstash now also requires Java 21 or later, and Java 17 is no longer supported."

2) Logstash 9.4 in the port (precompiled) doesn't support Java 25.
There's an error after start:
===
[2026-08-14T09:38:23,211][FATAL][org.logstash.Logstash    ][main] uncaught error (in thread Ruby-0-Thread-11: /usr/local/logstash/logstash-core/lib/logstash/java_pipeline.rb:335)
java.lang.NoSuchMethodError: 'java.util.Queue com.sun.tools.javac.util.Log$DeferredDiagnosticHandler.getDiagnostics()'
  at com.google.googlejavaformat.java.JavaInput.buildToks(com/google/googlejavaformat/java/JavaInput.java:367)
  at com.google.googlejavaformat.java.JavaInput.buildToks(com/google/googlejavaformat/java/JavaInput.java:335)
  at com.google.googlejavaformat.java.JavaInput.<init>(com/google/googlejavaformat/java/JavaInput.java:277)
  at com.google.googlejavaformat.java.Formatter.getFormatReplacements(com/google/googlejavaformat/java/Formatter.java:270)
  at com.google.googlejavaformat.java.Formatter.formatSource(com/google/googlejavaformat/java/Formatter.java:257)
  at com.google.googlejavaformat.java.Formatter.formatSource(com/google/googlejavaformat/java/Formatter.java:223)
  at org.logstash.config.ir.compiler.ComputeStepSyntaxElement.generateCode(org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java:174)
  at org.logstash.config.ir.compiler.ComputeStepSyntaxElement.<init>(org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java:118)
  at org.logstash.config.ir.compiler.ComputeStepSyntaxElement.create(org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java:89)
  at org.logstash.config.ir.compiler.DatasetCompiler.prepare(org/logstash/config/ir/compiler/DatasetCompiler.java:353)
===
DeferredDiagnosticHandler::getDiagnostics is no longer binary compatible as it returns a List<JCDiagnostic> in Java 25 instead of a Queue<JCDiagnostic>
https://github.com/diffplug/spotless/issues/2468

PR:		297528
Approved by:	elastic (maintainer, implicit - fix runtime)
Sponsored by:	UNIS Labs
MFH:		2026Q3