devel/gnome-builder: unbreak after 6134fd351428
../src/gstyle/gstyle-color-panel.c:33:10: fatal error: 'libportal/portal-gtk3.h' file not found
 #include <libportal/portal-gtk3.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~

Reported by:	pkg-fallout

(cherry picked from commit 442ee94e6f38ac9919b60328827de9eefaf5fe0c)