textproc/raptor2: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
textproc/raptor2 failed to build with clang 15:

  raptor_parse.c:260:66: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'int' [-Wint-conversion]
    RAPTOR_ASSERT_OBJECT_POINTER_RETURN_VALUE(world, raptor_world, NULL);
                                                                   ^~~~
  /usr/include/sys/_null.h:34:14: note: expanded from macro 'NULL'
  #define NULL    ((void *)0)
                  ^~~~~~~~~~~
  ./raptor_internal.h:168:12: note: expanded from macro 'RAPTOR_ASSERT_OBJECT_POINTER_RETURN_VALUE'
      return ret; \
             ^~~

This was fixed in https://github.com/dajobe/raptor/commit/567d4d1a by
upstream.

PR:		268336
Approved by:	tcberner (maintainer)
MFH:		2022Q4