databases/pgagroal: Mark BROKEN on i386
Fails to build with:
error: format specifies type 'unsigned long' but the argument has type
'unsigned int' [-Werror,-Wformat]

(cherry picked from commit 8a648e3368f2c927ba1acd3bea56d00870a38cd3)