devel/llvm17: fix build with clang 21
Recent versions of clang complain about explicit copy constructors,
leading to errors similar to:

    /wrkdirs/usr/ports/devel/llvm17/work-default/llvm-project-17.0.6.src/llvm/tools/sancov/sancov.cpp
    /wrkdirs/usr/ports/devel/llvm17/work-default/llvm-project-17.0.6.src/llvm/tools/sancov/sancov.cpp:521:42: error: chosen constructor is explicit in copy-initialization
      521 |     return SpecialCaseList::createOrDie({{ClIgnorelist}},
          |                                          ^~~~~~~~~~~~~~
    /usr/include/c++/v1/string:1153:64: note: explicit constructor declared here
     1153 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 explicit basic_string(const _Tp& __t) {
          |                                                                ^
    /usr/include/c++/v1/__vector/vector.h:276:91: note: passing argument to parameter '__il' here
      276 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector(initializer_list<value_type> __il) {
          |                                                                                           ^

In this case, `ClIgnoreList` is an instance of `cl::opt`, not a
`std::string` as expected. Use `getValue()` to get the actual
`std::string` value.

PR:		292113
Approved by:	brooks (maintainer)
MFH:		2026Q1

(cherry picked from commit 39d6b5aaaf453db99e7834e643563381ecfa19e3)