- Unbreak the build on -CURRENT by explicitly linking against libm as a   remedy to the following error:
    [100%] Linking C executable bmpanel2
    /usr/bin/ld: undefined reference to symbol `truncf@@FBSD_1.0' (try
    adding -lm)
    //lib/libm.so.5: could not read symbols: Bad value

- While here fix long standing issue of -L${LOCALBASE}/lib being required
  in LDFLAGS while USES=pkgconfig due to missing LINK_DIRECTORIES() call
  in the top-level `CMakeLists.txt'