Explicitly build with -std=gnu++98
clang 6.0 will default to -std=gnu++14, which breaks the build:

    /wrkdirs/usr/ports/math/rocs/work/rocs-4.14.3/VisualEditor/Actions/SelectMoveHandAction.cpp:86:52: error: no viable conversion from 'int' to 'QPainter::RenderHints' (aka 'QFlags<QPainter::RenderHint>')
            _graphScene->views().at(0)->setRenderHints(QPainter::Antialiasing

PR:		224945