net-p2p/c-lightning: attempt to unbreak on arm64
Since arm64 uses two's complement (char)0xff is the same as -1.
Changing to use the latter should silence this compiler error:

ccan/ccan/base64/base64.c:34:10: error: result of comparison of constant 255 with expression of type 'int8_t' (aka 'signed char') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
        if (ret == (char)0xff) {
            ~~~ ^  ~~~~~~~~~~