devel/py-virtualenv: Update to 21.7.9
- Disable test target due to the following startup error:

pluggy._manager.PluginValidationError: Plugin 'black' for hook 'pytest_collect_file'
hookimpl definition: pytest_collect_file(file_path, path, parent)
Argument(s) {'path'} are declared in the hookimpl but can not be found in the hookspec

See https://github.com/pytest-dev/pytest/issues/14651

- Pet portfmt

ChangeLog:	https://github.com/pypa/virtualenv/releases/tag/21.7.9

Reported by:	"github-actions[bot]" <notifications@github.com>