emulators/yuzu: unbreak on FreeBSD < 12 after c8b56ee72403
externals/./cpp-httplib/httplib.h: In constructor 'httplib::SSLServer::SSLServer(const char*, const char*, const char*, const char*)':
externals/./cpp-httplib/httplib.h:6728:22: error: 'TLS_method' was not declared in this scope; did you mean 'DTLS_method'?
 6728 |   ctx_ = SSL_CTX_new(TLS_method());
      |                      ^~~~~~~~~~
      |                      DTLS_method

Reported by:	pkg-fallout

(cherry picked from commit 31538e49e28778b1f69491fea6cc1119463d3a6f)