MFH: r455917
graphics/vigra: unbreak consumers on 10.* for NUMPY=on

Passing -std=gnu++11 also matches Boost since r450557.

/usr/local/lib/libvigraimpex.so: undefined reference to `operator delete(void*, unsigned int)'

Reported by:	antoine (via bug 223922 -exp run)
Submitted by:	rakuco (adapted from bug 219484 fix)
Approved by:	ports-secteam blanket