- Mark BROKEN: does not build   gmcs -t:exe -r:../IronPython.dll -out:../ipy.exe -recurse:IronPythonConsole/*.cs   IronPythonConsole/PythonCommandLine.cs(512,36): error CS0012: The type   `IronMath.ISlice' is defined in an assembly that is not referenced. Consider   adding a reference to assembly `IronMath, Version=1.0.60816.1877,   Culture=neutral, PublicKeyToken=null'
Reported by:	pointyhat