net/cloudquery: fix build on 32 bit architectures
Compilation failed on 32 bit archtectures with the following error
message:

vendor/github.com/cloudquery/plugin-sdk/v4/schema/testdata.go:463:27:
  3600000000 (untyped int constant) overflows int
vendor/github.com/cloudquery/plugin-sdk/v4/schema/testdata.go:467:27:
  3600000000000 (untyped int constant) overflows int
vendor/github.com/cloudquery/plugin-sdk/v4/schema/testdata.go:467:45:
  60000000000 (untyped int constant) overflows int

The reason is that strconv.Itoa() accepts only 32 bit arguments.
Attempt to fix by conversion of strconv.Itoa() to strconv.FormatInt()
with native int variables casted to 64 integers.