The patch introduced in r383995 to fix the build on perl-5.21.6+ broke building against other perl versions.
byterun.c:1886:3: warning: implicit declaration of function 'PadnamelistMAXNAMED' is invalid in C99 [-Wimplicit-function-declaration]
                BSET_padl_name(bstate->bs_sv, arg);
                ^
./bytecode.h:798:5: note: expanded from macro 'BSET_padl_name'
    PadnamelistMAXNAMED((PAD*)pad) = AvFILL((AV*)pad)
    ^
byterun.c:1886:3: error: expression is not assignable
                BSET_padl_name(bstate->bs_sv, arg);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./bytecode.h:798:36: note: expanded from macro 'BSET_padl_name'
    PadnamelistMAXNAMED((PAD*)pad) = AvFILL((AV*)pad)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
1 warning and 1 error generated.

I'm not clear exactly why it's failing, but only applying the patch against
affected perl versions should fix the issue.