audio/zinf: unbreak with gcc5 or earlier after r433187
src/player.cpp: In member function 'void Player::HandlePrefsChanged(Event*)':
src/player.cpp:1970:40: error: 'stoi' was not declared in this scope
         nPort = stoi(buffer.substr(pos));
                                        ^

Reported by:	marino
Pointy hat to:	jbeich (forgot libc++ leaks C++11)