graphis/reallyslick: Fix build with Clang 6
hyperspace.cpp:387:19: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
        float diff[3] = {flarepos[0] - camPos[0], flarepos[1] - camPos[1], flarepos[2] - camPos[2]};
                         ^~~~~~~~~~~~~~~~~~~~~~~

http://beefy11.nyi.freebsd.org/data/head-i386-default/p478276_s338342/logs/errors/reallyslick-0.9.1_20.log

- Attempt build on arm* again; the error message is the same as on amd64/i386
- Mark as LLD_UNSAFE when compiled with FREEALUT=on because of OpenAL [1]

PR:		226980 [1]