misc/py-pexpect: update to 4.6.0
async is the registered keyword since python 3.7, so current version of pexpect
fails to work with py37:

  File "/usr/local/lib/python3.7/site-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax
*** Error code 1

Update to latest version solves the issue.

Also pass maintainership to python@ at maintainer's request

PR:		230188
Approved by:	wg (maintainer)