x11-toolkits/gtk-sharp20: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
x11-toolkits/gtk-sharp20 failed to build with clang 15:

  windowmanager.c:113:12: error: incompatible integer to pointer conversion assigning to 'gpointer' (aka 'void *') from 'long' [-Wint-conversion]
                  list [i] = data [i];
                           ^ ~~~~~~~~

This is because gdk_property_get() always returns an array of longs, and
these have to be cast to whatever the desired outcome type is.

PR:		268812
Approved by:	portmgr (tcberner)
MFH:		2023Q1