devel/libgee: fix build with clang 16
Clang 16 has a new error about incompatible function types, which shows
up when building devel/libgee:

  hashmap.c:4089:23: error: incompatible function pointer types assigning to 'gboolean (*)(GeeMapIterator *)' (aka 'int (*)(struct _GeeMapIterator *)') from 'gboolean (GeeHashMapNodeIterator *)' (aka 'int (struct _GeeHashMapNodeIterator *)') [-Wincompatible-function-pointer-types]
          iface->get_read_only = gee_hash_map_map_iterator_real_get_read_only;
                               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Since the error occurs in vala-generated code, it does not make sense to
patch the .c file. Suppress the warning instead.

PR:		271485
Approved by:	maintainer timeout (2 weeks)
MFH:		2023Q2