java/openjfx14: unbreak build with LLVM15
Pass -Wno-int-conversion to CFLAGS fixes error with strict conversion rules introduced in LLVM15

/wrkdirs/usr/ports/java/openjfx14/work/jfx-14.0.2.1-1/modules/javafx.graphics/src/main/native-font/pango.c:245:73: error: incompatible integer to pointer conversion passing 'jlong' (aka 'long long') to parameter of type 'void *' [-Wint-conversion]
                rc = (jboolean)((jboolean (*)(void *, const char *))fp)(arg0, text);
                                                                        ^~~~