databases/py-tiledb: Mark BROKEN on i386
[ 32%] Building CXX object tiledb/CMakeFiles/main.dir/tests/test_serialization.cc.o
In file included from /wrkdirs/usr/ports/databases/py-tiledb/work-py311/tiledb-0.34.0/tiledb/tests/test_serialization.cc:2:
In file included from /usr/local/lib/python3.11/site-packages/pybind11/include/pybind11/numpy.h:12:
In file included from /usr/local/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:12:
In file included from /usr/local/lib/python3.11/site-packages/pybind11/include/pybind11/detail/class.h:12:
In file included from /usr/local/lib/python3.11/site-packages/pybind11/include/pybind11/attr.h:13:
/usr/local/lib/python3.11/site-packages/pybind11/include/pybind11/detail/common.h:513:19: error: static assertion failed due to requirement 'sizeof(unsigned long long) <= sizeof(int)': Implicit narrowing is not permitted.
  513 |     static_assert(sizeof(IntType) <= sizeof(ssize_t), "Implicit narrowing is not permitted.");
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/lib/python3.11/site-packages/pybind11/include/pybind11/pytypes.h:1678:57: note: in instantiation of function template specialization 'pybind11::ssize_t_cast<unsigned long long>' requested here
 1678 |         : object(PYBIND11_BYTES_FROM_STRING_AND_SIZE(c, ssize_t_cast(n)), stolen_t{}) {
      |                                                         ^
/wrkdirs/usr/ports/databases/py-tiledb/work-py311/tiledb-0.34.0/tiledb/tests/test_serialization.cc:77:19: note: in instantiation of function template specialization 'pybind11::bytes::bytes<unsigned long long, 0>' requested here
   77 |         py::bytes output((char*)buff_data, buff_num_bytes);
      |                   ^
/usr/local/lib/python3.11/site-packages/pybind11/include/pybind11/detail/common.h:513:35: note: expression evaluates to '8 <= 4'
  513 |     static_assert(sizeof(IntType) <= sizeof(ssize_t), "Implicit narrowing is not permitted.");
      |                   ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Reference:	https://pkg-status.freebsd.org/beefy21/data/142i386-default/e03a218e573f/logs/py311-tiledb-0.34.0.log
		https://pkg-status.freebsd.org/beefy15/data/135i386-default/348365c30511/logs/py311-tiledb-0.34.0.log
(cherry picked from commit 0dea6bb2d9ad81b2ce4af49432b2ba5c6b10e09c)