audio/muse-sequencer: Try to fix build order bug (D29353)
Uncovered while building with devel/samurai but can probably also
happen with ninja eventually.  There are some missing dependencies
on the components module.

In file included from /wrkdirs/usr/ports/audio/muse-sequencer/work/muse-muse_3_1_1/muse3/muse/waveedit/wavecanvas.cpp:72:
/wrkdirs/usr/ports/audio/muse-sequencer/work/muse-muse_3_1_1/muse3/muse/components/copy_on_write.h:26:10: fatal error: 'ui_copy_on_write_base.h' file not found
 #include "ui_copy_on_write_base.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~

http://package18.nyi.freebsd.org/data/122amd64-default-foo/2021-04-05_21h03m50s/logs/errors/muse-sequencer-3.1.1_1.log

https://github.com/michaelforney/samurai/issues/70

PR:		254678
Obtained from:	upstream (midieedit, waveedit patches)