x11-wm/gamescope: check libliftoff package version after ef2d0a35dd40
Dependency libliftoff found: NO found 0.1.0 but need: '>= 0.2.0' ; matched: '< 0.3.0'

../src/drm.cpp:1174:8: error: use of undeclared identifier 'liftoff_output_needs_composition'
                if ( liftoff_output_needs_composition( drm->lo_output ) )
                     ^

(cherry picked from commit 63b39d29994a75ce5696d3c1f0db9e4623f1d95d)