graphics/qt5-wayland: fix build with clang 13 by adding <array>
During an exp-run for llvm 13 (see bug 258209), it turned out that
graphics/qt5-wayland fails to build with clang 13:

In file included from main.cpp:32:
In file included from ../../../../hardwareintegration/compositor/linux-dmabuf-unstable-v1/linuxdmabufclientbufferintegration.h:33:
../../../../hardwareintegration/compositor/linux-dmabuf-unstable-v1/linuxdmabuf.h:145:40: error: implicit instantiation of undefined template 'std::array<Plane, 4>'
    std::array<Plane, MaxDmabufPlanes> m_planes;
                                       ^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
In file included from main.cpp:32:
In file included from ../../../../hardwareintegration/compositor/linux-dmabuf-unstable-v1/linuxdmabufclientbufferintegration.h:33:
../../../../hardwareintegration/compositor/linux-dmabuf-unstable-v1/linuxdmabuf.h:148:46: error: implicit instantiation of undefined template 'std::array<void *, 4>'
    std::array<EGLImageKHR, MaxDmabufPlanes> m_eglImages = { {EGL_NO_IMAGE_KHR, EGL_NO_IMAGE_KHR, EGL_NO_IMAGE_KHR, EGL_NO_IMAGE_KHR} };
                                             ^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
In file included from main.cpp:32:
In file included from ../../../../hardwareintegration/compositor/linux-dmabuf-unstable-v1/linuxdmabufclientbufferintegration.h:33:
../../../../hardwareintegration/compositor/linux-dmabuf-unstable-v1/linuxdmabuf.h:149:51: error: implicit instantiation of undefined template 'std::array<QOpenGLTexture *, 4>'
    std::array<QOpenGLTexture *, MaxDmabufPlanes> m_textures = { {nullptr, nullptr, nullptr, nullptr} };
                                                  ^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
3 errors generated.

This is because linuxdmabuf.h doesn't include the <array> header. Fix it
by adding the include.

PR:		259288
Approved by:	tcberner (maintainer)
MFH:		2021Q4