Fix build on 9.3 amd64 after lang/gcc upgrade by switching to USE_GCC=4.8
gcc 4.9 fails to link on 9.3 amd64 with:
/usr/local/lib/libtinyxml.so: error: undefined reference to 'std::istream::get()'
/usr/local/lib/libtinyxml.so: error: undefined reference to 'std::__throw_out_of_range(char const*)'
/usr/local/lib/libtinyxml.so: error: undefined reference to 'std::istream::peek()'

PR:		196712