science/silo: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
science/silo failed to build with clang 15:

  /wrkdirs/usr/ports/science/silo/work/Silo-4.11-68-g819658e/src/hdf5_drv/silo_hdf5.c:1869:13: error: incompatible integer to pointer conversion passing 'char' to parameter of type 'const char *'; take the address with & [-Wint-conversion]
              DB_OBJ_CASE(DB_CURVE, DBcurve_mt, npts?1:1, yvarname)
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /wrkdirs/usr/ports/science/silo/work/Silo-4.11-68-g819658e/src/hdf5_drv/silo_hdf5.c:1812:36: note: expanded from macro 'DB_OBJ_CASE'
              (*dsnames)[i] = strdup(m.MEMNAME[i]);                \
                              ~~~~~~~^~~~~~~~~~~~~
  /wrkdirs/usr/ports/science/silo/work/Silo-4.11-68-g819658e/src/silo/silo_private.h:939:35: note: expanded from macro 'strdup'
  #define strdup(s) _db_safe_strdup(s)
                                    ^
  /wrkdirs/usr/ports/science/silo/work/.build/include/silo.h:2214:68: note: passing argument to parameter here
  SILO_API extern char *                 _db_safe_strdup(const char *);
                                                                     ^

This turns out to be a bug in silo, which I reported upstream in
https://github.com/LLNL/Silo/issues/296, and which was fixed in
https://github.com/LLNL/Silo/commit/be29ddf.

PR:		268864
Approved by:	yuri (maintainer)
MFH:		2023Q1