devel/py-virtualenv: Update to 20.18.0
- Use Python pep517 feature, because the upstream removed setuptools support
- Compile and install Python bytecode (pending a definitive decision regarding
 this: see: https://reviews.freebsd.org/D38429 )
- Update build/test dependencies
- Add a patch to pyproject.toml to fix the following Exception (build stage):

    from virtualenv.version import __version__
ImportError: cannot import name '__version__' from 'virtualenv.version' (/usr/local/poudriere/ports/default/devel/py-virtualenv/work-py39/virtualenv-20.18.0/dist/virtualenv-20.18.0-py3-none-any.whl/virtualenv/
version.py)

Changes: https://github.com/pypa/virtualenv/releases/tag/20.18.0