emulators/yuzu: pacify stage-qa after 8065f30c010d/d1d6df7c230b
Error: /usr/local/bin/yuzu is linked to /usr/local/lib/libbrotlidec.so.1 from archivers/brotli but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libbrotlidec.so:archivers/brotli
Error: /usr/local/bin/yuzu is linked to /usr/local/llvm15/lib/libLLVM-15.so from devel/llvm15 but it is not declared as a dependency
(cherry picked from commit 78163f4fb12f940564c786eb1bcedeba617e0277)