games/veloren-weekly: mark BROKEN on aarch64 after 016cd848e57e
error[E0412]: cannot find type `ucontext_t` in crate `libc`
   --> cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:219:57
    |
219 |               let ucontext = &mut *(context as *mut libc::ucontext_t);
    |                                                           ^^^^^^^^^^ help: a struct with a similar name exists: `mcontext_t`
    |
   ::: cargo-crates/libc-0.2.133/src/unix/bsd/freebsdlike/freebsd/aarch64.rs:20:1
    |
20  | / s_no_extra_traits! {
21  | |     pub struct gpregs {
22  | |         pub gp_x: [::register_t; 30],
23  | |         pub gp_lr: ::register_t,
..   |
44  | |     }
45  | | }
    | |_- similarly named struct `mcontext_t` defined here

error[E0412]: cannot find type `ucontext_t` in crate `libc`
   --> cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:259:45
    |
259 |           unsafe fn get_pc_sp(context: &libc::ucontext_t) -> (usize, usize) {
    |                                               ^^^^^^^^^^ help: a struct with a similar name exists: `mcontext_t`
    |
   ::: cargo-crates/libc-0.2.133/src/unix/bsd/freebsdlike/freebsd/aarch64.rs:20:1
    |
20  | / s_no_extra_traits! {
21  | |     pub struct gpregs {
22  | |         pub gp_x: [::register_t; 30],
23  | |         pub gp_lr: ::register_t,
..   |
44  | |     }
45  | | }
    | |_- similarly named struct `mcontext_t` defined here

error[E0412]: cannot find type `ucontext_t` in crate `libc`
   --> cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:314:54
    |
314 |           unsafe fn update_context(context: &mut libc::ucontext_t, regs: TrapHandlerRegs) {
    |                                                        ^^^^^^^^^^ help: a struct with a similar name exists: `mcontext_t`
    |
   ::: cargo-crates/libc-0.2.133/src/unix/bsd/freebsdlike/freebsd/aarch64.rs:20:1
    |
20  | / s_no_extra_traits! {
21  | |     pub struct gpregs {
22  | |         pub gp_x: [::register_t; 30],
23  | |         pub gp_lr: ::register_t,
..   |
44  | |     }
45  | | }
    | |_- similarly named struct `mcontext_t` defined here

error[E0425]: cannot find value `pc` in this scope
   --> cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:420:59
    |
420 |                     context.uc_mcontext.mc_gpregs.gp_pc = pc as libc::register_t;
    |                                                           ^^ not found in this scope

error[E0425]: cannot find value `sp` in this scope
   --> cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:421:59
    |
421 |                     context.uc_mcontext.mc_gpregs.gp_sp = sp as libc::register_t;
    |                                                           ^^ not found in this scope

error[E0425]: cannot find value `x0` in this scope
   --> cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:422:61
    |
422 |                     context.uc_mcontext.mc_gpregs.gp_x[0] = x0 as libc::register_t;
    |                                                             ^^ not found in this scope

error[E0425]: cannot find value `x1` in this scope
   --> cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:423:61
    |
423 |                     context.uc_mcontext.mc_gpregs.gp_x[1] = x1 as libc::register_t;
    |                                                             ^^ not found in this scope

error[E0425]: cannot find value `x29` in this scope
   --> cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:424:62
    |
424 |                     context.uc_mcontext.mc_gpregs.gp_x[29] = x29 as libc::register_t;
    |                                                              ^^^ not found in this scope

error[E0425]: cannot find value `lr` in this scope
   --> cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:425:62
    |
425 |                     context.uc_mcontext.mc_gpregs.gp_x[30] = lr as libc::register_t;
    |                                                              ^^ not found in this scope

(cherry picked from commit 357f24f91ba02b5f95612482e4cd2f6075239fa0)