security/john: fix build on powerpc64
./pseudo_intrinsics.h:110:25: error: use of 'long long' with '__vector' requires VSX support (available on POWER7 or later) to be enabled

(cherry picked from commit b28e464e75cf8be0cbb413220e00b2feba17f3fb)