Mark as broken on powerpc64.  This port first failed to build on 20180819:
  /usr/local/GNUstep/System/Library/Headers/GNUstepBase/GSVersionMacros.h:295:8: error:
  #error "Your gnustep-base was configured for the objc-nonfragile-abi but you are not using it now."

This port is blocked by gnustep-base, so this is mainly a reminder for
later.

Approved by:	portmgr (tier-2 blanket)