emulators/ppsspp: unbreak on DragonFly after deb6e280f48b
In file included from Core/HLE/sceAudiocodec.cpp:25:
Core/HW/SimpleAudioDec.h:26:1: error: 'const' can only be specified for objects and functions
 const struct AVCodec;
 ^~~~~

Reported by:	DPorts

(cherry picked from commit e316451d37e1454bd32e03d3a0ffb0b094ceb63f)