lang/intel-compute-runtime: unbreak build after 41f2281cb356
shared/source/gen8/hw_info_bdw.cpp:20:10: error: use of undeclared identifier 'IBDW_GT0_DESK_DEVICE_F0_ID'
    case IBDW_GT0_DESK_DEVICE_F0_ID:
         ^
shared/source/gen8/hw_info_bdw.cpp:21:10: error: use of undeclared identifier 'IBDW_GT1_DESK_DEVICE_F0_ID'
    case IBDW_GT1_DESK_DEVICE_F0_ID:
         ^
shared/source/gen8/hw_info_bdw.cpp:22:10: error: use of undeclared identifier 'IBDW_GT2_DESK_DEVICE_F0_ID'
    case IBDW_GT2_DESK_DEVICE_F0_ID:
         ^
shared/source/gen8/hw_info_bdw.cpp:23:10: error: use of undeclared identifier 'IBDW_GT3_DESK_DEVICE_F0_ID'
    case IBDW_GT3_DESK_DEVICE_F0_ID:
         ^
shared/source/gen8/hw_info_bdw.cpp:24:10: error: use of undeclared identifier 'IBDW_GT4_DESK_DEVICE_F0_ID'
    case IBDW_GT4_DESK_DEVICE_F0_ID:
         ^

PR:		274891
Reported by:	pkg-fallout

(cherry picked from commit 5bae779cbf3ecff19b7c6ff95dd7809d0863b7b5)