devel/llvm12: fix build with clang 21
Recent versions of clang complain about explicit copy constructors,
leading to errors similar to:

    In file included from /wrkdirs/usr/ports/devel/llvm12/work/llvm-project-12.0.1.src/llvm/tools/sancov/sancov.cpp:16:
    In file included from /wrkdirs/usr/ports/devel/llvm12/work/llvm-project-12.0.1.src/llvm/include/llvm/MC/MCContext.h:12:
    /wrkdirs/usr/ports/devel/llvm12/work/llvm-project-12.0.1.src/llvm/include/llvm/ADT/DenseMap.h:128:16: warning: variable 'NumEntries' set but not used [-Wunused-but-set-variable]
      128 |       unsigned NumEntries = getNumEntries();
          |                ^
    /wrkdirs/usr/ports/devel/llvm12/work/llvm-project-12.0.1.src/llvm/tools/sancov/sancov.cpp:512:42: error: chosen constructor is explicit in copy-initialization
      512 |     return SpecialCaseList::createOrDie({{ClBlacklist}},
          |                                          ^~~~~~~~~~~~~
    /usr/include/c++/v1/string:1153:64: note: explicit constructor declared here
     1153 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 explicit basic_string(const _Tp& __t) {
          |                                                                ^
    /usr/include/c++/v1/__vector/vector.h:276:91: note: passing argument to parameter '__il' here
      276 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector(initializer_list<value_type> __il) {
          |                                                                                           ^

In this case, `ClBlacklist` is an instance of `cl::opt`, not a
`std::string` as expected. Use `getValue()` to get the actual
`std::string` value.

PR:		292108
Approved by:	brooks (maintainer)
MFH:		2026Q1

(cherry picked from commit 525f740a3b35276c8da8f703d5e15fb7d09a8d1d)