graphics/qgis-ltr: Fix on CURRENT after llvm13 intro
Right after replacing llvm12 with llvm13 in base (commits b61bce17f346d79cecfd8f195a64b10f77be43b1 to 397a8ba05313cc3815d219c9d1b2de1372fcb561) graphics/qgis-ltr was broken on 14.0-CURRENT with

/usr/ports/graphics/qgis/work/QGIS-final-3_16_14/src/core/providers/ogr/qgsogrproviderutils.cpp:5971:34: error: no matching constructor for initialization of 'QgsOgrDatasetSharedPtr' (aka 'shared_ptr<QgsOgrDataset>')
  QgsOgrDatasetSharedPtr dsRet = QgsOgrDatasetSharedPtr( new QgsOgrDataset(), QgsOgrProviderUtils::releaseDataset );

Thanks to dim@ for the analysis and solution. Much appreciated!

PR:		259967
(cherry picked from commit af60a61a9333df126249d5659c350c4a7b969a9a)