x11/libexo: fix build on GCC architectures
C11 compiler is required:
In file included from /usr/local/include/xfce4/libxfce4util/libxfce4util.h:33,
                 from ../exo/exo-enum-types.h:6,
                 from ../exo/exo.h:39,
                 from exo-enum-types.c:6:
/usr/local/include/xfce4/libxfce4util/xfce-kiosk.h:37: error: redefinition of typedef 'XfceKiosk'
/usr/local/include/xfce4/libxfce4util/xfce-kiosk.h:35: error: previous declaration of 'XfceKiosk' was here

Approved by:	mentors (implicit approval)