MFH: r456088
devel/spdlog: require C++11 toolchain (on powerpc*, mips*, sparc*)

CMake Error in tests/CMakeLists.txt:
  Target "catch_tests" requires the language dialect "CXX11" (with compiler
  extensions), but CMake does not know the compile flags to use to enable it.

tests/includes.h:7:10: fatal error: 'chrono' file not found
 #include <chrono>
          ^~~~~~~~
1 error generated.

Reported by:	pkg-fallout (mips64)
Approved by:	ports-secteam blanket