- Mark BROKEN, fails to install
===>  Checking if sysutils/rubygem-chef-expander already installed
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: chef-expander requires bunny (~> 0.6.0), fast_xs (~> 0.7.3)
*** [do-install] Error code 1