games/jumpy: disable LTO on armv7 (similar to games/punchy)
thread 'coordinator' panicked at compiler/rustc_middle/src/util/bug.rs:36:26:
/wrkdirs/usr/ports/lang/rust/work/rustc-1.77.0-src/compiler/rustc_codegen_ssa/src/back/write.rs:1588:29: worker thread panicked
stack backtrace:
fatal runtime error: Rust cannot catch foreign exceptions
(signal: 6, SIGABRT: process abort signal)

Reported by:	pkg-fallout

(cherry picked from commit d00f19675f28e63aefed456dc34eb415a3ac1c1b)