emulators/qemu: fix build on powerpc
Define _CALL_SYSV to fix error:
In file included from /wrkdirs/usr/ports/emulators/qemu/work/qemu-5.0.1/tcg/tcg.c:344:                                                                                                                                                      
/wrkdirs/usr/ports/emulators/qemu/work/qemu-5.0.1/tcg/ppc/tcg-target.inc.c:2290:3: error: "Unhandled abi"

Use gcc because clang hangs.