textproc/xmlstarlet: fix build with clang 16
Clang 16 has a new error about incompatible function types, which shows
up when building textproc/xmlstarlet:

  src/xml_elem.c:271:27: error: incompatible function pointer types passing 'void (void *, void *, xmlChar *)' (aka 'void (void *, void *, unsigned char *)') to parameter of type 'xmlHashScanner' (aka 'void (*)(void *, void *, const unsigned char *)') [-Wincompatible-function-pointer-types]
          xmlHashScan(uniq, hash_key_put, &lines);
                            ^~~~~~~~~~~~
  /usr/local/include/libxml2/libxml/hash.h:213:22: note: passing argument to parameter 'f' here
                                           xmlHashScanner f,
                                                          ^

In this case, the libxml2 callback function requires a const xmlChar
pointer, so fix the parameter in the definition.

PR:		271413
Approved by:	portmgr (build fix blanket)
MFH:		2023Q2