x11/hyprpaper: ignore on big-endian architectures
src/helpers/Jpeg.cpp:8:2: error: "your system is not little endian, jpeg will not work, ping vaxry or something"
 #error "your system is not little endian, jpeg will not work, ping vaxry or something"
  ^

Reported by:	pkg-fallout (powerpc64)

(cherry picked from commit 827d888b22f23e8aeb8e4205262f9d6845d7af85)
(cherry picked from commit e807fb8510bd63fba611e6200fec4f7ba1cd7a8c)