java/openjdk21: fix build on powerpc64*
/wrkdirs/usr/ports/java/openjdk21/work/jdk21u-jdk-21.0.1-12-1/src/hotspot/share/runtime/javaThread.hpp:1117:10: fatal error: 'javaThread_bsd_ppc.hpp' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/java/openjdk21/work/jdk21u-jdk-21.0.1-12-1/src/hotspot/share/utilities/macros.hpp:618:40: note: expanded from macro 'OS_CPU_HEADER'
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/java/openjdk21/work/jdk21u-jdk-21.0.1-12-1/src/hotspot/share/utilities/macros.hpp:35:17: note: expanded from macro 'XSTR'
                ^~~~~~
/wrkdirs/usr/ports/java/openjdk21/work/jdk21u-jdk-21.0.1-12-1/src/hotspot/share/utilities/macros.hpp:32:17: note: expanded from macro 'STR'
                ^~
<scratch space>:74:1: note: expanded from here
"javaThread_bsd_ppc.hpp"
^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

(cherry picked from commit e7710c85bfc9949b7bd235822b49c7ad82816820)