misc/ola: Change LIB_DEPENDS from protobuf to protobuf3
- While I'm here, fix PLIST
- Bump PORTREVISION for dependency and package change

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/libolaftdidmx.a
Error: Orphaned: lib/libolaftdidmx.so
Error: Orphaned: lib/libolaftdidmx.so.0
Error: Orphaned: lib/libolaftdidmx.so.0.0.0
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Reference:	https://github.com/OpenLightingProject/ola/issues/1879