devel/qscintilla2-qt5: Fix 5bcefb9d57ea5511961abf307b56fc804101423e
- Remove duplicate PLIST entry which is already added by USE_LDCONFIG

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: libdata/ldconfig/qscintilla2-qt5
===> Error: Plist issues found.
*** Error code 1

Approved by:	portmgr (blanket)