x11-wm/swayfx: unbreak with wlroots/X11=off after e83c39ced11e
../sway/tree/root.c:63:7: error: implicit declaration of function 'wlr_surface_is_xwayland_surface' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                if (wlr_surface_is_xwayland_surface(con->view->surface)) {
                    ^
../sway/tree/root.c:63:7: note: did you mean 'wlr_surface_is_layer_surface'?
/usr/local/include/wlr/types/wlr_layer_shell_v1.h:144:6: note: 'wlr_surface_is_layer_surface' declared here
bool wlr_surface_is_layer_surface(struct wlr_surface *surface);
     ^
../sway/tree/root.c:64:44: error: implicit declaration of function 'wlr_xwayland_surface_from_wlr_surface' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        struct wlr_xwayland_surface *xsurface = wlr_xwayland_surface_from_wlr_surface(con->view->surface);
                                                                ^
../sway/tree/root.c:64:44: note: did you mean 'wlr_xdg_surface_from_wlr_surface'?
/usr/local/include/wlr/types/wlr_xdg_shell.h:494:25: note: 'wlr_xdg_surface_from_wlr_surface' declared here
struct wlr_xdg_surface *wlr_xdg_surface_from_wlr_surface(
                        ^
../sway/tree/root.c:64:33: error: incompatible integer to pointer conversion initializing 'struct wlr_xwayland_surface *' with an expression of type 'int' [-Werror,-Wint-conversion]
                        struct wlr_xwayland_surface *xsurface = wlr_xwayland_surface_from_wlr_surface(con->view->surface);
                                                     ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sway/tree/root.c:65:4: error: implicit declaration of function 'wlr_xwayland_surface_set_minimized' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        wlr_xwayland_surface_set_minimized(xsurface, minimize);
                        ^

(cherry picked from commit af7f9d91cd35e4dbdce78c18734b073bcd435368)