- Unbreak the build on 9.x (against GCC 4.2): it was failing due to -ansi   option passed by default, which does not allow C++-style comments in C   source code (Clang is more forgiving):
    /usr/local/include/clamav.h:170: error: expected identifier or '('
    before '/' token
    /usr/local/include/clamav.h:170: error: stray '#' in program

- Really respect CFLAGS by fixing configure script
- Do not hardcode DISTVERSION in MASTER_SITES
- Do not install COPYING file as part of portdocs: it's installed via
  LICENSE_FILE already
- Convert the port to use option helpers, fix a typo (VIRUSTAGSC ->
  VIRUSTAG_DESC), wrap overly long lines
- Augment port description text while I'm at it