games/xsc: Fix build with Clang 6
buzzer.C:36:8: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
    {  COS00 / 2.0, -SIN00 / 2.0 }, { -COS00 / 2.0,  SIN00 / 2.0 },
       ^~~~~~~~~~~

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p475478_s336801/logs/errors/xsc-1.6_1.log

- While here also fix segfault due to some uninitialized variables