MFH: r522054
net-p2p/namecoin: fix build on GCC architectures

It looks like some update caused src/httpserver.c to need to include deque when building with GCC. Otherwise it fails to compile with:
httpserver.cpp:74:10: error: 'deque' in namespace 'std' does not name a template type
   74 |     std::deque<std::unique_ptr<WorkItem>> queue;
      |          ^~~~~
httpserver.cpp:33:1: note: 'std::deque' is defined in header '<deque>'; did you forget to '#include <deque>'?
   32 | #include <support/events.h>
  +++ |+#include <deque>
   33 |
httpserver.cpp: In member function 'bool WorkQueue<WorkItem>::Enqueue(WorkItem*)':
httpserver.cpp:92:13: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
   92 |         if (queue.size() >= maxDepth) {
      |             ^~~~~
      |             Enqueue
httpserver.cpp:95:9: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
   95 |         queue.emplace_back(std::unique_ptr<WorkItem>(item));
      |         ^~~~~
      |         Enqueue
httpserver.cpp: In member function 'void WorkQueue<WorkItem>::Run()':
httpserver.cpp:106:35: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
  106 |                 while (running && queue.empty())
      |                                   ^~~~~
      |                                   Enqueue
httpserver.cpp:110:31: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
  110 |                 i = std::move(queue.front());
      |                               ^~~~~
      |                               Enqueue

PR:             242710
Approved by:    milios@ccsys.com (maintainer timeout)
Approved by:	portmgr (fix build blanket)