irc/py-limnoria: Mark as not compatible with Python 3.10+
Since Python 3.10 the method "collections.MutableMapping" has been
renamed to "collections.abc.MutableMapping" which leads to run time
errors:

[..]
    class CacheDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
[..]

PR:		259979
Reviewed by:	koobs (maintainer)
Approved by:	portmgr (blanket)
MFH:		2021Q4