x11/kitty: unbreak build after aec9c6c9cf90
glfw/wl_window.c:522:17: error: enumeration value 'XDG_TOPLEVEL_STATE_SUSPENDED' not handled in switch [-Werror,-Wswitch]
        switch (*state) {
                ^

PR:		272372
Reported by:	pkg-fallout

(cherry picked from commit a72282f6b37af162f8c51791a411e5e71cd84848)