x11-toolkits/pangox-compat: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
x11-toolkits/pangox-compat failed to build with clang 15:

  pangox.c:983:15: error: incompatible integer to pointer conversion assigning to 'PangoFontMetrics *' (aka 'struct _PangoFontMetrics *') from 'int' [-Wint-conversion]
        metrics = pango_font_metrics_new ();
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
  pangox-fontmap.c:944:9: error: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
    char *files_str = pango_config_key_get ("PangoX/AliasFiles");
          ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is because pangox-compat uses two private functions from the main
pango library, which are not declared in the public pango headers.

Fix the errors by adding the two private functions in
pango-impl-utils.h, copying the declarations from pango-font-private.h
and pango-utils-private.h.

PR:		268301
Approved by:	fluffy (maintainer)
MFH:		2022Q4