print/scribus: unbreak with hunspell 1.5
-- Could NOT find HUNSPELL (missing:  HUNSPELL_LIBRARIES)
HunSpell or its developer libraries NOT found - Disabling support for spell checking
[...]
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/scribus/plugins/libhunspellplugin.so

scribus/plugins/tools/hunspellcheck/hunspelldict.cpp:22:9: error: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
                char* dictEncoding = m_hunspell->get_dic_encoding();
                      ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://github.com/hunspell/hunspell/commit/971f8a9cf52e

PR:		214837
Approved by:	portmgr blanket