net/nss_ldap: Fix LLVM15 build
./configure's test for Heimdal results in,

conftest.c:47:12: error: incompatible pointer to integer conversion initializing
 'const char' with an expression of type 'const char *'; dereference with * [-Wi
nt-conversion]
const char hv = heimdal_version;
           ^    ~~~~~~~~~~~~~~~
                *

This causes ./configure to erroneously assume 14-CURRENT uses MIT instead
of Heimdal, resulting in a subsequent build failure because MIT's
<profile.h> cannot be found.

MFH:		2023Q3