audio/ardour: fix build on powerpc64*
In file included from ../libs/ardour/ardour/plugin.h:37:
../libs/ardour/ardour/cycles.h:75:10: fatal error: 'sys/platform/ppc.h' file not found

(cherry picked from commit 3729900bf2f7a644fea876448a1cc1e25314b609)