x11-servers/xarcan: unbreak build with clang 16
../hw/kdrive/arcan/arcan.c:1523:21: error: incompatible function pointer types initializing 'present_abort_vblank_ptr' (aka 'void (*)(struct _rrCrtc *, unsigned long, unsigned long)') with an expression of type 'void (void *)' [-Wincompatible-function-pointer-types]
    .abort_vblank = arcanPresentAbortVblank,
                    ^~~~~~~~~~~~~~~~~~~~~~~

Reported by:	pkg-fallout

(cherry picked from commit 109051cff449fa3c24630d0f164c85a88936e035)