math/dune-common: fix build with clang 19
Clang 19 is more strict about errors in member functions, which results
in:

  /wrkdirs/usr/ports/math/dune-common/work/dune-common-df65b1282ea89ad40d2cb6565983f7e633ccce31/dune/common/parallel/remoteindices.hh:936:58: error: reference to non-static member function must be called
    936 |     return localIndex_==ri.localIndex_ && attribute_==ri.attribute;
        |                                                       ~~~^~~~~~~~~

This is a typo, which has been fixed by upstream in
<https://gitlab.dune-project.org/core/dune-common/-/commit/d36ce92a18>.

PR:		281412
Approved by:	yuri (maintainer)
MFH:		2024Q3