graphics/gthumb: track libjxl dependency after 316b58b68075
====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/gthumb/extensions/libcairo_io.so is linked to /usr/local/lib/libjxl.so.0.7 from graphics/libjxl but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libjxl.so:graphics/libjxl
Error: /usr/local/lib/gthumb/extensions/libcairo_io.so is linked to /usr/local/lib/libjxl_threads.so.0.7 from graphics/libjxl but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libjxl_threads.so:graphics/libjxl

Reported by:	QAT

(cherry picked from commit 2c188852ef5092cec3949da36c7e3015121a3c1e)