devel/git-cinnabar: unbreak with git/CURL=off (track direct dependency)
In file included from helper/hg-bundle.c:3:
./http.h:6:10: fatal error: 'curl/curl.h' file not found
 #include <curl/curl.h>
          ^~~~~~~~~~~~~

Error: /usr/local/libexec/git-core/git-cinnabar-helper is linked to /usr/local/lib/libcurl.so.4 from ftp/curl but it is not declared as
a dependency
Warning: you need LIB_DEPENDS+=libcurl.so:ftp/curl

Regressed by:	https://github.com/glandium/git-cinnabar/commit/fb3292fa908a
See also:	https://github.com/glandium/git-cinnabar/commit/76edb8c76bbb