deskutils/health: unbreak runtime
thread 'main' panicked at 'Failed to retrieve template child. Please check that it has been bound and has a #[template_child] attribute.', cargo-crates/gtk4-0.4.8/src/subclass/widget.rs:1305:17

https://gitlab.gnome.org/World/Health/-/issues/174
(cherry picked from commit cb4024226bda71e6548745e4aa565022dc399a64)