audio/csound: Fix build with math/gmm++ >= 5.4.3
gmm::lapack_ipvt is a typedef to std::vector since 5.4.3 [1], so using
the .get() accessor no longer works. Removing the added CXXFLAGS fixes
the issue.

/wrkdirs/usr/ports/audio/csound/work/csound-6.15.0/Opcodes/linear_algebra.cpp:3507:30:
error: no member named 'get' in 'std::vector<unsigned long>'
 3507 |       pivot->vr[i] = pivot__.get(i);

[1] https://github.com/getfem/getfem/commit/cbe1442c4bb2b4fea804d47054ab55dc0bfe238c

Approved by:	portmgr (blanket)