devel/spirv-llvm-translator: unbreak build by dropping llvm13 flavor
-- SPIR-V Headers location is not specified. Will try to download
          spirv.hpp from https://github.com/KhronosGroup/SPIRV-Headers into
          /wrkdirs/usr/ports/devel/spirv-llvm-translator/work-llvm13/.build/SPIRV-Headers
CMake Error at /usr/local/share/cmake/Modules/ExternalProject.cmake:2650 (message):
  error: could not find git for clone of spirv-headers-populate
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/ExternalProject.cmake:3700 (_ep_add_download_command)
  CMakeLists.txt:22 (ExternalProject_Add)

This reverts commit 1b058e5769cb7aa554bbfe1c476bf354eb33a62e.