devel/ignition-msgs: Fix build with protobuf 22+
Note that this port has a PLIST issue.
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/ignition/ignition-%%MSGS_IGN_VER%%_0/ignition-%%MSGS_IGN_VER%%.tag.xml
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1