textproc/ripgrep: Fix build with rust 1.71.0
Summary:
Do not abort if documentation is missing.

error: missing documentation for an extern crate
  --> crates/grep/src/lib.rs:17:1
   |
17 | pub extern crate grep_cli as cli;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |

PR:		272602
Reviewed by:	mikael
Approved by:	portmgr (build fix blanket)
Sponsored by:	The FreeBSD Foundation
Differential Revision:	https://reviews.freebsd.org/D41095