Mark broken, fails to build On 8 and 9: Generating i386 object code for Tcl ... In file included from OCS/Tcl.c:80: ./Tcl.hc.c: In function 'execFun': ./Tcl.hc.c:264: error: 'Tcl_Interp' has no member named 'result' ./Tcl.hc.c: In function 'execCom': ./Tcl.hc.c:308: error: 'Tcl_Interp' has no member named 'result' ./Tcl.hc.c:311: error: 'Tcl_Interp' has no member named 'result' ...
On 10 and head:
OCS/INLINE.c:19:36: error: non-void function 'init_AINLINE' should return a value [-Wreturn-type]
 static int visited=0; if(visited) return; visited=1;
                                   ^

Reported by:	pkg-fallout (maybe since august 2013)
With hat:	portmgr