x11/hypridle: avoid casting integer to string
src/core/Hypridle.cpp:508:131: error: non-constant-expression cannot be narrowed from type 'pid_t' (aka 'int') to 'uint32_t' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
  508 |         proxy->callMethod("GetSessionByPID").onInterface("org.freedesktop.ConsoleKit.Manager").withArguments(std::string{uint32_t{getpid()}}).storeResultsTo(path);
      |                                                                                                                                   ^~~~~~~~
src/core/Hypridle.cpp:508:131: note: insert an explicit cast to silence this issue
  508 |         proxy->callMethod("GetSessionByPID").onInterface("org.freedesktop.ConsoleKit.Manager").withArguments(std::string{uint32_t{getpid()}}).storeResultsTo(path);
      |                                                                                                                                   ^~~~~~~~
      |                                                                                                                                   static_cast<uint32_t>( )
src/core/Hypridle.cpp:508:122: error: non-constant-expression cannot be narrowed from type 'uint32_t' (aka 'unsigned int') to 'char' in initializer list [-Wc++11-narrowing]
  508 |         proxy->callMethod("GetSessionByPID").onInterface("org.freedesktop.ConsoleKit.Manager").withArguments(std::string{uint32_t{getpid()}}).storeResultsTo(path);
      |                                                                                                                          ^~~~~~~~~~~~~~~~~~
src/core/Hypridle.cpp:508:122: note: insert an explicit cast to silence this issue
  508 |         proxy->callMethod("GetSessionByPID").onInterface("org.freedesktop.ConsoleKit.Manager").withArguments(std::string{uint32_t{getpid()}}).storeResultsTo(path);
      |                                                                                                                          ^~~~~~~~~~~~~~~~~~
      |                                                                                                                          static_cast<char>()

Exposed by -Wno-narrowing removal in v0.1.6.