science/step: Fix build with LLVM >= 19.1.0-rc1
Clang >= 19.1.0-rc1 requires a template argument list after an identifier
prefixed by the template keyword. [1]

/wrkdirs/usr/ports/science/step/work/step-23.08.5/stepcore/object.h:252:45:
error: a template argument list is expected after a name prefixed by the
template keyword [-Wmissing-template-arg-list-after-template-kw]
  252 |     if(!src || !src->metaObject()->template inherits(_Dst())) return NULL;

[1] https://github.com/llvm/llvm-project/commit/f46d1463b835560d90ad3ac02b63c771e4ebe566

Reported by:	pkg-fallout
MFH:		2024Q2

(cherry picked from commit f812d021d79f6a4034640eece6b7ae1b32df21a0)