www/firefox: fix build on powerpc64
Cast to uint32_t on big-endian, since byte-swapping to big-endian function, which returns uint32_t, doesn't run on big-endian:
/wrkdirs/usr/ports/www/firefox/work/firefox-114.0.1/gfx/skia/skia/src/encode/SkICC.cpp:122:13: error: non-constant-expression cannot be narrowed from type 'SkFixed' (aka 'int') to 'uint32_t' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]