During the exp-run in bug 206074, it was found that www/libxul gives errors with a recent clang 3.8.0 snapshot:
../../dist/include/mozilla/dom/MessageEvent.h:61:32: error: reference to 'MessagePort' is ambiguous
  void SetSource(mozilla::dom::MessagePort* aPort);
                               ^

This is caused by unneeded forward declarations of class MessagePort,
MessagePortBase and MessagePortList.  These can be removed.

Obtained from:	pkgsrc
Approved by:	jbeich (maintainer)
PR:		206333
MFH:		2016Q1