textproc/sigil: add missing dependency
$ sigil
[Embedded Python Error]
Traceback (most recent call last):

  File "/usr/local/share/sigil/python3lib/xmlprocessor.py", line 6, in <module>
    from sigil_bs4.builder._lxml import LXMLTreeBuilderForXML

  File "/usr/local/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 26, in <module>
    from lxml import etree

ImportError: No module named 'lxml'