graphics/blender: fix build on powerpc*
In file included from /wrkdirs/usr/ports/graphics/blender/work/blender-3.4.1/intern/cycles/util/simd.cpp:8:
/wrkdirs/usr/ports/graphics/blender/work/blender-3.4.1/intern/cycles/util/../util/simd.h:50:14: error: unknown type name '__m128'
extern const __m128 _mm_lookupmask_ps[16];
             ^

(cherry picked from commit 2fcfc8fc29ce6fc956cdb84f0adbc00e8ee3c5e3)