databases/tiledb: Fix build on non-x86 (due to -Werror)
Build on non-x86 currently fails with:
/wrkdirs/usr/ports/databases/tiledb/work/TileDB-1.6.2/external/src/blosc/shuffle.cc:280:4: error: #warning Hardware-acceleration detection not implemented for the target architecture. Only the generic shuffle/unshuffle routines will be available. [-Werror=cpp]
  280 |   #warning Hardware-acceleration detection not implemented for the target architecture. Only the generic shuffle/unshuffle routines will be available.
      |    ^~~~~~~
/wrkdirs/usr/ports/databases/tiledb/work/TileDB-1.6.2/external/src/blosc/shuffle.cc: In function 'blosc::shuffle_implementation_t blosc::get_shuffle_implementation()':
/wrkdirs/usr/ports/databases/tiledb/work/TileDB-1.6.2/external/src/blosc/shuffle.cc:290:22: error: unused variable 'cpu_features' [-Werror=unused-variable]
  290 |   blosc_cpu_features cpu_features = blosc_get_cpu_features();
      |                      ^~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Don't add -Werror to fix build.

PR:		240618
Approved by:	portmgr (blanket: build fix), linimon (mentor)