emulators/xsystem35: unbreak build with clang 15
nDEMO.c:22:6: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'int *'; dereference with * [-Wint-conversion]
        int p1 = getCaliVariable();
            ^    ~~~~~~~~~~~~~~~~~
                 *
nDEMO.c:28:6: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'int *'; dereference with * [-Wint-conversion]
        int p1 = getCaliVariable();
            ^    ~~~~~~~~~~~~~~~~~
                 *
nt_msg.c:189:9: error: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
                char *b = sjis2euc(msg);
                      ^   ~~~~~~~~~~~~~
nt_msg.c:261:10: error: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
                        char *b = sjis2euc(mbuf);
                              ^   ~~~~~~~~~~~~~~
sactcg.c:211:9: error: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
                char *b = sjis2euc(cText);
                      ^   ~~~~~~~~~~~~~~~

Reported by:	pkg-fallout

(cherry picked from commit 3968779d8b3bc78928f508f2d90a9f30eb633f32)