astro/mepo: revert 3ee2eb616ce6 to unbreak build
./src/api/bind_signal.zig:48:21: error: expected error union type, found 'void'
    std.os.sigaction(signal_name, &signal_action, null)
                    ^

Reported by:	pkg-fallout

This reverts commit 3ee2eb616ce616ebfa5d542d80993274c19d60e9.