benchmarks/glmark2: backport --fullscreen fix for WAYLAND option
$ glmark2-wayland --fullscreen
Error: eglCreateWindowSurface failed with error: 0x300b
Error: eglCreateWindowSurface failed with error: 0x300b
Error: CanvasGeneric: Invalid EGL state
Error: main: Could not initialize canvas

(cherry picked from commit 1307312bf475a3457d54c8ea2b3ff871519db22a)