www/node22: fix build on powerpc64
../deps/simdjson/simdjson.cpp:27141:5: error: use of undeclared identifier 'vec_vsx_st'
 27141 |     vec_vsx_st(this->value, 0, reinterpret_cast<__m128i *>(dst));
       |     ^

(cherry picked from commit 4858047a7ce5e2bd1e33ef07e9c2b23afece848f)