archivers/lazperf: fix build on big-endian architectures
/wrkdirs/usr/ports/archivers/lazperf/work/laz-perf-2.0.0/cpp/lazperf/vlr.cpp:188:28: error: constant expression evaluates to 16777216 which cannot be narrowed to type 'uint8_t' (aka 'unsigned char') [-Wc++11-narrowing]
    reserved{}, data_type{ htole32(1) }, options{}, name{}, unused{},
                           ^~~~~~~~~~
/usr/include/sys/endian.h:88:20: note: expanded from macro 'htole32'
                        ^~~~~~~~~~~~
/usr/include/sys/endian.h:62:20: note: expanded from macro 'bswap32'
                        ^~~~~~~~~~~~
/usr/include/machine/endian.h:136:22: note: expanded from macro '__bswap32'
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/archivers/lazperf/work/laz-perf-2.0.0/cpp/lazperf/vlr.cpp:188:28: note: insert an explicit cast to silence this issue
    reserved{}, data_type{ htole32(1) }, options{}, name{}, unused{},
                           ^~~~~~~~~~
                           static_cast<uint8_t>( )
/usr/include/sys/endian.h:88:20: note: expanded from macro 'htole32'
                        ^~~~~~~~~~~~
/usr/include/sys/endian.h:62:20: note: expanded from macro 'bswap32'
                        ^~~~~~~~~~~~
/usr/include/machine/endian.h:136:22: note: expanded from macro '__bswap32'
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/archivers/lazperf/work/laz-perf-2.0.0/cpp/lazperf/vlr.cpp:188:28: warning: implicit conversion from 'unsigned int' to 'uint8_t' (aka 'unsigned char') changes value from 16777216 to 0 [-Wconstant-conversion]
    reserved{}, data_type{ htole32(1) }, options{}, name{}, unused{},
                         ~ ^~~~~~~~~~
/usr/include/sys/endian.h:88:20: note: expanded from macro 'htole32'
                        ^~~~~~~~~~~~
/usr/include/sys/endian.h:62:20: note: expanded from macro 'bswap32'
                        ^~~~~~~~~~~~
/usr/include/machine/endian.h:136:42: note: expanded from macro '__bswap32'
                                            ^~~~~~~~~~~~~~~~~~
/usr/include/machine/endian.h:98:37: note: expanded from macro '__bswap32_const'
        (((__uint32_t)(x)<< 8) & 0xff0000) |                            \
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.