- Mark BROKEN, fails to resolve dependencies
  ===>  Installing for rubygem-pry-0.9.12.2
  ===>   Generating temporary packing list
  ===>  Checking if devel/rubygem-pry already installed
  ERROR:  While executing gem ... (Gem::DependencyError)
      Unable to resolve dependencies: pry requires coderay (~> 1.0.5)
  *** Error code 1

  Stop in /usr/ports/devel/rubygem-pry.