Mark broken: Does not compile
On 8 and 9:
src/words.c: In function 'void ifParen(FICL_VM*)':
src/words.c:1086: error: cast from 'ficl_word*' to 'int' loses precision

On 10 and head:
g++ -O2 -pipe -fno-strict-aliasing -Wall -W -fno-rtti `perl -MExtUtils::Embed -e ccopts` -DUNIX -Ihpp -I/usr/local/include -O2 -pipe -fno-strict-aliasing -c src/ficl.c
g++: not found

Reported by:	pkg-fallout since august 2013