audio/openal-soft: fix build with clang 19
With clang 19 and gcc 15, audio/openal-soft fails to compile, with an
error similar to:

    /wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.21.1/common/aloptional.h:119:48: error: no member named 'mValue' in 'optional<T>'; did you mean 'value'?
      119 |     const T& operator*() const& { return this->mValue; }
          |                                                ^~~~~~
          |                                                value
    /wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.21.1/common/aloptional.h:127:8: note: 'value' declared here
      127 |     T& value() & { return mStore.mValue; }
          |        ^

Upstream commit <https://github.com/kcat/openal-soft/440b5970> fixes
this this, so add it as a PATCHFILES entry in the Makefile, until a
newer version of openal-soft is imported.

PR:		280677
Approved by:	maintainer timeout (2 weeks)
MFH:		2024Q3

(cherry picked from commit 6832814ba1f9a7dfa39fcc1cba8781ecfea6d568)