benchmarks/postal: Fix build with Clang 6
bhm.cpp:420:25: error: value of type '__bind<int &, sockaddr *, unsigned long>' is
      not contextually convertible to 'bool'
  if(listen_fd == -1 || bind(listen_fd, (sockaddr *)&in, sizeof(in))
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bhm.cpp:420:22: error: invalid operands to binary expression ('bool' and '__bind<int
      &, sockaddr *, unsigned long>')
  if(listen_fd == -1 || bind(listen_fd, (sockaddr *)&in, sizeof(in))

http://beefy11.nyi.freebsd.org/data/head-i386-default/p477696_s338122/logs/errors/postal-0.73_3.log