PySide2: Add workaround for devel/shiboken2 issues with LLVM >= 16
Shiboken2 itself builds fine, but the code it generates for devel/pyside2
is broken.

In file included from /wrkdirs/usr/ports/devel/pyside2/work-py311/.build/PySide2/QtGui/PySide2/QtGui/qdragmoveevent_wrapper.cpp:63:
/wrkdirs/usr/ports/devel/pyside2/work-py311/.build/PySide2/QtGui/PySide2/QtGui/qdragmoveevent_wrapper.h:55:220:
error: no member named 'DragMove' in 'QOpenGLShader'; did you mean simply 'DragMove'?

PR:		270715, 282433
Obtained from:	OpenMandriva
MFH:		2024Q4

(cherry picked from commit 1c4bdeedd071d370e693f36fb18b0735a1734f1a)