graphics/libjxl: unbreak JPEG=off build after 70e2590d63b0
In file included from lib/extras/dec/jpegli.cc:16:
In file included from lib/extras/enc/jpegli.cc:27:
In file included from lib/jpegli/common.h:23:
lib/jxl/base/include_jpeglib.h:15:10: fatal error: 'jpeglib.h' file not found
   15 | #include <jpeglib.h>  // IWYU pragma: keep
      |          ^~~~~~~~~~~

PR:		282926
Reported by:	amdmi3

(cherry picked from commit ada3d2df83fc99e6ac855984a6cecb034bdcd743)