MFH: r431335
lang/spidermonkey170: unbreak with clang 4.0

Fix quoting failure handling in JSOP_CALLPROP and JSOP_STRING.

jsopcode.cpp:6070:45: error: ordered comparison between pointer and zero ('char *' and 'int')
    return QuoteString(&sprinter, s, quote) >= 0;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~

PR:		215861
Regressed by:	https://github.com/llvm-mirror/clang/commit/4b6ad14285f3
Obtained from:	upstream (only the specific fix)
Approved by:	portmgr blanket
Approved by:	ports-secteam (junovitch)