lang/python3([6-9]|10): disable detection of multiarch
It breaks with clang >= 13, which adds a major.minor version number in
-print-multiarch output, and the dot confuses Python:

ModuleNotFoundError: No module named '_sysconfigdata__freebsd14_x86_64-unknown-freebsd14'

Since we do not support multiarch, and the configure script has no way
to disable the multiarch check, stub it out during post-patch.

PR:		258377
Approved by:	maintainer timeout (2 weeks)
MFH:		2021Q3