devel/py-qt6-pyqt: Fix build with Qt 6.8.2
/wrkdirs/usr/ports/devel/py-qt6-pyqt/work-py311/PyQt6-6.8.0/build/QtCore/sipQtCoreQStringConverterBase.cpp:58:26:
error: call to implicitly-deleted copy constructor of '::QStringConvert
   58 |             sipCpp = new ::QStringConverterBase(*a0);

MFH:		2025Q1
(cherry picked from commit 93ae5ca9b65bf3768fc55aca3761f5cf7470bb7d)