emulators/uae: the port had been improved (+)
- Unbreak the build on modern FreeBSD versions by avoiding
  injecting duplicate symbols in the object files
- Drop MAKE_JOBS_UNSAFE: it was added back in 2013 in the
  commit 2a5c8652e56c1 to fix the build error:

    crt1.c:(.text+0xa8): undefined reference to `main'
    gmake[2]: *** [build68k] Error 1

  which no longer manifests itself

PR:	256577