x11/xdm: fix build with clang 16
Clang 16 has a new error about incompatible function types, which shows
up when x11/xdm:

  greet.c:451:20: error: incompatible function pointer types assigning to 'void (*)(void)' from 'int (*)(void)' [-Wincompatible-function-pointer-types]
      __xdm_setgrent = dlfuncs->_setgrent;
		     ^ ~~~~~~~~~~~~~~~~~~

This is because it assumes setgrent(3) returns int, which it has not
done since a very long time.

Reported by:	O. Hartmann <ohartmann@walstatt.org>
PR:		272209
MFH:		2023Q2