textproc/html2text: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because textproc/html2text's Makefile does not explicitly set its C++
standard, this leads to several errors:

  /usr/local/lib/bison.cc:429:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register int yystate;
    ^~~~~~~~~
  /usr/local/lib/bison.cc:430:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register int yyn;
    ^~~~~~~~~
  /usr/local/lib/bison.cc:431:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register short *yyssp;
    ^~~~~~~~~
  /usr/local/lib/bison.cc:432:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register YY_HTMLParser_STYPE *yyvsp;
    ^~~~~~~~~

Add USE_CXXSTD=gnu++98 to avoid these errors.

PR:		271031
Approved by:	maintainer timeout (2 weeks)
MFH:		2023Q2