- Mark BROKEN: does not compile
/wrkdirs/usr/ports/lang/J/work/jsource-j807-release/jsrc/ar.c:254:70: error: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-const-int-float-conversion]

- Fix CONFLICTS_INSTALL on openjdk* (conflict of bin/jconsole binary from J vs. symlink installed by openjdk* from post-install scripts) [1]
- Fix WWW

PR:		236427 [1]
Reported by:	bojan_petrovic@fastmail.fm [1]