devel/git-cinnabar: drop unused dependencies
Error: /usr/local/libexec/git-core/git-cinnabar-helper is linked to /usr/local/lib/libintl.so.8 from devel/gettext-runtime but it is not declared as a dependency
Warning: you need USES+=gettext-runtime

Error: /usr/local/libexec/git-core/git-cinnabar-helper is linked to /usr/local/lib/libpcre2-8.so.0 from devel/pcre2 but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libpcre2-8.so:devel/pcre2