benchmarks/vkmark: unbreak without explicit --winsys after 2f23f1c7829d
$ vkmark
Error: Failed to get VT control mode: Inappropriate ioctl for device

(cherry picked from commit a8f179d5f29c0392909d98f8780ae84f078e925f)