devel/libgtop: unbreak build with clang 15
main.c:226:35: error: incompatible pointer to integer conversion passing 'char[1024]' to parameter of type 'pid_t' (aka 'int') [-Wint-conversion]
                (server, &resp->u.data.proc_io, parameter);
                                                ^~~~~~~~~
../../include/glibtop/procio.h:78:74: note: passing argument to parameter 'pid' here
void glibtop_get_proc_io_l (glibtop *server, glibtop_proc_io *buf, pid_t pid);
                                                                         ^

PR:		268260
Reported by:	antoine (via bug 265425 exp-run)

(cherry picked from commit 2fef1dbd478ea473588cc0f8ec4ff1b3654012a2)