During the exp-run in bug 208158, it was found that x11-toolkits/wxgtk30 gives errors with libc++ 3.8.0:
./src/stc/scintilla/src/Editor.cxx:5844:6: error: call to 'abs' is ambiguous
        if (abs(pt1.x - pt2.x) > 3)
            ^~~

This is because pt1.x and pt2.x are float values, but <cmath> is not
included, and abs() for float values comes from that header.  Fix it by
including <cmath>.

Approved by:	portmaster@bsdforge.com (maintainer)
Approved by:	vlad-fbsd@acheronmedia.com (maintainer)
PR:		209694
MFH:		2016Q2