emulators/yuzu: unbreak build after 3eff87c4dc8d
Boost 1.80 seems to be incompatible with libc++ 16. As ebbef4b5f84b is
slated for 2023Q2 downgrade 2023Q1 to the last good snapshot.

In file included from externals/dynarmic/src/dynarmic/ir/ir_emitter.cpp:6:
In file included from externals/dynarmic/src/dynarmic/../dynarmic/ir/ir_emitter.h:11:
In file included from externals/dynarmic/src/dynarmic/../dynarmic/ir/basic_block.h:18:
In file included from externals/dynarmic/src/dynarmic/../dynarmic/ir/terminal.h:8:
In file included from /usr/local/include/boost/variant.hpp:17:
In file included from /usr/local/include/boost/variant/variant.hpp:21:
In file included from /usr/local/include/boost/type_index.hpp:29:
In file included from /usr/local/include/boost/type_index/stl_type_index.hpp:47:
/usr/local/include/boost/container_hash/hash.hpp:132:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
        struct hash_base : std::unary_function<T, std::size_t> {};
                           ~~~~~^
libcxx_prefix/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^

Reported by:	pkg-fallout

This reverts commit 29a004faf6639fcf3028177b0e32c4fa1312fd45.
This reverts commit 10fa39ec869df8f056ffee0e3cf50c84a28cfdab.
This reverts commit 787091ab9135602e2be137ddf10b1fbe467ea091.
This reverts commit 41bd9b325c3908523790d8a77f4a8c194b04eb86.
This reverts commit 3eff87c4dc8d063ac99abb4569c90a20291cbfd5.