IGNORE port on FreeBSD 9.
The port has been broken on 9 since the 0.9.3 update:

  src/thrift/transport/TSSLSocket.cpp: In constructor 'apache::thrift::transport::SSLContext::SSLContext(const apache::thrift::transport::SSLProtocol&)':
  src/thrift/transport/TSSLSocket.cpp:147: error: 'TLSv1_1_method' was not declared in this scope
  src/thrift/transport/TSSLSocket.cpp:149: error: 'TLSv1_2_method' was not declared in this scope

Conditionally adding USE_OPENSSL=yes + WITH_OPENSSL_PORT=yes does not work
out of the box:

  In file included from /usr/local/include/openssl/x509.h:107,
                   from /usr/local/include/openssl/ssl.h:156,
                   from src/thrift/transport/TSSLSocket.cpp:35:
  /usr/local/include/openssl/sha.h:184: error: ISO C++ does not support 'long long'
  /usr/local/include/openssl/sha.h:185: error: ISO C++ does not support 'long long'
  /usr/local/include/openssl/sha.h:187: error: ISO C++ does not support 'long long'

Mark it IGNOREd for now until somebody comes up with a proper fix.