science/rdkit: Mark BROKEN on FreeBSD 14
Fails to compile as clang crashes with:
error: clang frontend command failed with exit code 134

Have tried to build with llvm14 and llvm15 and it builds but there are
lots of modules which are not built.

Approved by:	portmgr (blanket)
Sponsored by:	The FreeBSD Foundation