devel/jujutsu: fix build on big-endian architectures
While functions for converting to LE are suffixed _le, functions for converting to BE don't have any suffix:
error[E0599]: no method named `put_i16_be` found for struct `Vec<u8>` in the current scope
   --> /wrkdirs/usr/ports/devel/jujutsu/work/jj-0.19.0/cargo-crates/serde_bser-0.4.0/src/ser/mod.rs:136:22
    |
136 |         self.scratch.put_i16_be(v);
    |                      ^^^^^^^^^^
    |
help: there is a method `put_i16_le` with a similar name
    |
136 |         self.scratch.put_i16_le(v);
    |                      ~~~~~~~~~~

error[E0599]: no method named `put_i32_be` found for struct `Vec<u8>` in the current scope