emulators/virtualbox-ose: fix build emulators/virtualbox-ose-additions{,-nox11} on main: error: unknown type name 'uma_zone_t'
In file included from /wrkdirs/usr/ports/emulators/virtualbox-ose-additions/work/VirtualBox-6.1.50/src/VBox/Additions/freebsd/vboxvfs/vboxvfs_prov.c:42:
/wrkdirs/usr/ports/emulators/virtualbox-ose-additions/work/VirtualBox-6.1.50/src/VBox/Additions/freebsd/vboxvfs/vboxvfs.h:209:2: error: unknown type name 'uma_zone_t'
  209 |         uma_zone_t      sf_node_pool;
      |         ^

Reported by:	pkg-fallout
MFH:		2024Q3

(cherry picked from commit 612ffa0271c25c55ac3d1492f1ad361ff76e0667)