devel/py-pycapsicum: unbreak build after 620968a43a5f
Restore the patch accidentally removed due to confusing comment.

_pycapsicum.c:36:10: fatal error: 'sys/capability.h' file not found
 #include "sys/capability.h"
          ^~~~~~~~~~~~~~~~~~

Reported by:	pkg-fallout

(cherry picked from commit c85f76fcf7a48834ad29bcdd3c6508636ec4eedf)