net/mosh: fix build on powerpc*
ocb_internal.cc:138:10: warning: 'bswap32' macro redefined [-Wmacro-redefined]
        #define bswap32(x)                                              \
                ^
/usr/include/sys/endian.h:68:9: note: previous definition is here
        ^
ocb_internal.cc:142:26: error: static declaration of '__builtin_bswap64' follows non-static declaration
         static inline uint64_t bswap64(uint64_t x) {
                                ^
/usr/include/sys/endian.h:69:20: note: expanded from macro 'bswap64'
                        ^
/usr/include/sys/_endian.h:78:22: note: expanded from macro '__bswap64'
                        ^
ocb_internal.cc:142:26: note: previous implicit declaration is here
/usr/include/sys/endian.h:69:20: note: expanded from macro 'bswap64'
                        ^
/usr/include/sys/_endian.h:78:22: note: expanded from macro '__bswap64'
                        ^
1 warning and 1 error generated.

(cherry picked from commit 711fba0c7a832f99e111165c69c26acaa01127e9)