MFH: r546122
textproc/qr: fix build on GCC architectures

sqrt() is only defined since C99:
/tmp/ccn0UwwD.o:(.text+0x1cc): undefined reference to `sqrt'

Approved by:	portmgr (fix build blanket)