deskutils/calibre: Fix at runtime after commit 47912ce2e613 (sqlite3)
In commit 47912ce2e613 to sqlite3 the default has been changed for the DQS option.

Thius causes calibre to fail to open its database, reporting it as corrupted:

Traceback (most recent call last):
  File "/usr/local/lib/calibre/calibre/gui2/main.py", line 331, in initialize_db
    db = LibraryDatabase(self.library_path)
  File "/usr/local/lib/calibre/calibre/db/legacy.py", line 195, in __init__
    backend = self.backend = create_backend(library_path, default_prefs=default_prefs,
  File "/usr/local/lib/calibre/calibre/db/legacy.py", line 50, in create_backend
    return DB(library_path, default_prefs=default_prefs,
  File "/usr/local/lib/calibre/calibre/db/backend.py", line 501, in __init__
    self.initialize_custom_columns()
  File "/usr/local/lib/calibre/calibre/db/backend.py", line 698, in initialize_custom_columns
    custom_tables = self.custom_tables
  File "/usr/local/lib/calibre/calibre/db/backend.py", line 1387, in custom_tables
    return {x[0] for x in self.conn.get(
  File "/usr/local/lib/calibre/calibre/db/backend.py", line 370, in get
    ans = self.cursor().execute(*args)
  File "src/cursor.c", line 992, in APSWCursor_execute.sqlite3_prepare
apsw.SQLError: SQLError: no such column: table

This patch fixes the use of double quotes in the code accessing the library database at runtime.

Submitted upstream: 	https://github.com/kovidgoyal/calibre/pull/1830