multimedia/vlc: unbreak with dav1d 1.0.0
codec/dav1d.c:286:14: error: no member named 'n_tile_threads' in 'struct Dav1dSettings'
    p_sys->s.n_tile_threads = var_InheritInteger(p_this, "dav1d-thread-tiles");
    ~~~~~~~~ ^
codec/dav1d.c:292:14: error: no member named 'n_frame_threads' in 'struct Dav1dSettings'
    p_sys->s.n_frame_threads = var_InheritInteger(p_this, "dav1d-thread-frames");
    ~~~~~~~~ ^

(cherry picked from commit eca2986ededb22145f7af0886e8fd79ac8c9667e)