MFH: r387782
devel/renpy: fix TKINTER regressing after r382557

Traceback (most recent call last):
  File "choose_directory.rpy", line 61, in choose_directory
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Approved by:	ports-secteam (shebang blanket)