graphics/darktable: unbreak AVIF=on after 3036600b61bd
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/darktable/plugins/imageio/format/libavif.so
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%LIBAVIF%%lib/darktable/plugins/imageio/format/libavif.so
===> Error: Plist issues found.
*** Error code 1

Pointy hat to:	jbeich