multimedia/ab-av1: back to 0.9.1 to unbreak build
===>   Updating Cargo.lock
error: failed to parse manifest at `/wrkdirs/usr/ports/multimedia/ab-av1/work/ab-av1-0.9.2/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.83.0 (5ffbef321 2024-10-29)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
*** Error code 101

Reported by:	pkg-fallout

This reverts commit 8855350ef13c37f868fa439caf27b16ece0132eb.