audio/alsa-plugins: Fix build with JACK option: use of undeclared identifier 'program_invocation_short_name'
pcm_jack.c:606:23: error: use of undeclared identifier 'program_invocation_short_name'
  606 |                 const char *pname = program_invocation_short_name;
      |                                     ^
1 error generated.

Upstream broke build on FreeBSD in commit:
https://github.com/alsa-project/alsa-plugins/commit/13a645e55a740dfa43bb3518da3f580c90be7eac
Pool request:
https://github.com/alsa-project/alsa-plugins/pull/48

PR:		280144
Reported by:	Peter Much <pmc@citylink.dinoex.sub.org>
Tested by:	Peter Much <pmc@citylink.dinoex.sub.org>
Fixes:		1a782b315786 (update 1.2.7.1 → 1.2.12)
MFH:		2024Q4