cad/openvsp: fix build without libomp
CMake Error at /usr/local/share/cmake/Modules/FindOpenMP.cmake:261 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindOpenMP.cmake:537 (_OPENMP_GET_FLAGS)
  src/vsp_aero/Solver/CMakeLists.txt:9 (FIND_PACKAGE)

-fpermissive necessary because of:
/usr/include/c++/v1/__memory/compressed_pair.h:48:9: error: invalid conversion from 'int' to 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*' [-fpermissive]