sysutils/rubygem-vagrant_cloud: fix build error due to rexml 3.3.0 update
Fix a regression from f45642e9eb010c7ef3002ad10dc776d6a6971bcc

====> Running Q/A tests (stage-qa)
Error: RubyGem dependency rexml ~> 3.2.5 is not satisfied.
*** Error code 1

Approved by:	fixit