devel/py-pythran: Fix stage-qa/package phase
Remove pkg-plist which causes the port to fail to package in poudriere
due to duplicate entries when PORTTESTING=1 is set. The port already has
USE_PYTHON=autoplist set, so the static pkg-plist is not needed.

====> Running Q/A tests (stage-qa)
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%PYTHON_SITELIBDIR%%/pythran/boost/array.hpp
Error: Missing: %%PYTHON_SITELIBDIR%%/pythran/boost/assert.hpp
Error: Missing: %%PYTHON_SITELIBDIR%%/pythran/boost/atomic.hpp
<--snip-->
Error: Missing: %%PYTHON_SITELIBDIR%%/pythran/boost/utility.hpp
Error: Missing: %%PYTHON_SITELIBDIR%%/pythran/boost/version.hpp
Error: Missing: %%PYTHON_SITELIBDIR%%/pythran/xsimd/xsimd.hpp
===> Error: Plist issues found.
*** Error code 1

=======================<phase: package        >============================
===== env: DEVELOPER_MODE=yes 'PKG_NOTES=build_timestamp built_by' 'PKG_NOTE_build_timestamp=2024-01-26T23:15:36+0000' 'PKG_NOTE_built_by=poudriere-git-3.4.99.20240105' STRICT_DEPENDS=yes USER=root UID=0 GID=0
===>  Building packages for py39-pythran-0.15.0
===>   Building py39-pythran-0.15.0
pkg-static: duplicate file listing: /usr/local/lib/python3.9/site-packages/pythran/boost/array.hpp, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/lib/python3.9/site-packages/pythran/boost/assert.hpp, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/lib/python3.9/site-packages/pythran/boost/atomic.hpp, fatal (developer mode)
<--snip-->
pkg-static: duplicate file listing: /usr/local/lib/python3.9/site-packages/pythran/boost/utility.hpp, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/lib/python3.9/site-packages/pythran/boost/version.hpp, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/lib/python3.9/site-packages/pythran/xsimd/xsimd.hpp, fatal (developer mode)
*** Error code 1

Approved by:	portmgr (blanket)