textproc/augeas: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
textproc/augeas failed to build with clang 15:

  internal.c:436:12: error: incompatible integer to pointer conversion returning 'int' from a function with result type 'const char *' [-Wint-conversion]
      return strerror_r(errnum, buf, len);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.

This is because the GNU variant of strerror_r() is erroneously chosen.
Use the BSD variant instead.

PR:		268231
Approved by:	romain (maintainer)
MFH:		2022Q4