- Fix stagedir referenced from installed files:
Error: 'bin/bash-include' is referring to /wrkdirs/usr/ports/shells/shell-include/work/stage
Error: 'bin/sh-include' is referring to /wrkdirs/usr/ports/shells/shell-include/work/stage

- Don't use random and don't use /tmp for temporary files. It's unsafe, and netstat spews warnings from the jail:

netstat: kvm not available: /dev/mem: No such file or directory

- Depend on perl as pod2man is used during build
- Fix path to pod2man

PR:		199645
Submitted by:	amdmi3
Approved by:	maintainer timeout