graphics/libgphoto2: Fix curl detection
Before:
checking for libcurl to use... autodetect
checking for LIBCURL... no
checking libcurl config program... none
...
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/libgphoto2/%%VERSION%%/lumix.so
===> Error: Plist issues found.
*** Error code 1

After:
checking for curl/curl.h... yes
checking for function curl_easy_init in libcurl... yes
checking libcurl library flags... "-L/usr/local/lib -lcurl"
checking libcurl cpp flags... "-I/usr/local/include"

Approved by:	portmgr (blanket)