multimedia/emby-server: unbreak with dav1d 1.0.0
libavcodec/libdav1d.c:137:7: error: no member named 'n_tile_threads' in 'struct Dav1dSettings'
    s.n_tile_threads = dav1d->tile_threads
    ~ ^
libavcodec/libdav1d.c:144:14: error: no member named 'n_frame_threads' in 'struct Dav1dSettings'
           s.n_frame_threads, s.n_tile_threads);
           ~ ^

(cherry picked from commit 1133c44239e4d97453dadd9a16f2c1b768a3d95c)