math/cbc: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because math/cbc's build infrastructure does not explicitly set its C++
standard, this leads to errors:

  ./CbcSymmetry.hpp:83:30: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
      inline void color_vertex(register int k) { color = k; }
                               ^~~~~~~~~
  ./CbcSymmetry.hpp:91:24: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
      inline void bounds(register double a, register double b)
                         ^~~~~~~~~

To work around the error, add USE_CXXSTD=gnu++11 to compile for C++11
with GNU extensions instead.

PR:		272101
Approved by:	yuri (maintainer)
MFH:		2023Q2