devel/glib20: unbreak GTKDOC=on after 8cef7ff47def
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/gtk-doc/html/gobject/gtype-non-instantiatable-non-classed.html
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/gtk-doc/html/gobject/gtype-non-instantiatable-classed.html
===> Error: Plist issues found.
*** Error code 1

https://gitlab.gnome.org/GNOME/glib/-/commit/783f1b864008
(cherry picked from commit 66e9d4dd64727c8acae477b64708d24112a7085c)