www/qt5-webengine: fix build with clang 21
With libc++ 21 www/qt5-webengine fails to build, with errors similar to:

    In file included from gen/third_party/blink/renderer/platform/platform_jumbo_54.cc:7:
    ./../../../../kde-qtwebengine-5.15.19p0/src/3rdparty/chromium/third_party/blink/renderer/platform/image-encoders/image_encoder_utils.cc:63:5: error: static assertion expression is not an integral constant expression
    [...]
    ../../../../kde-qtwebengine-5.15.19p0/src/3rdparty/chromium/base/metrics/histogram_macros_internal.h:45:12: note: integer value 8 is outside the valid range of values [0, 7] for the enumeration type 'RequestedImageMimeType'
       45 |     return static_cast<Enum>(
          |            ^

https://chromium.googlesource.com/chromium/src/+/bb340f66aaf44206fa5106509fb4e8c0719ee831
fixes these, but has to be slightly adjusted to make it apply to the
specific chromium version included in qt5-webengine.

PR:		293093
Approved by:	jhale (maintainer)
MFH:		2026Q1

(cherry picked from commit f9807ebb6bda547e662d094b879e68d9ff96b06b)