multimedia/ogmrip: Fix check-plist issues
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/ogmrip/container-plugins/libogmrip-mp4.a
Error: Orphaned: lib/ogmrip/container-plugins/libogmrip-mp4.so
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

The mp4 container plugins were removed in r534078 but they only depend
on gpac-mp4box at runtime, so they are built anyway. Exclude them.