math/dsdp: adding a SONAME to the shared library
When building math/py-cvxopt the following error is displayed:
Error: /usr/local/lib/python3.9/site-packages/cvxopt/dsdp.cpython-39.so is
linked to /usr/local/lib/libdsdp.so which does not have a SONAME.
math/dsdp needs to be fixed.

Since I’m there, also install the static library.

PR:		274851
Approved by:	yuri 'maintainer)