graphics/podofo: fix build with libc++ >= 20
With libc++ 20 or higher graphics/podofo fails to build, with errors
similar to:

    /wrkdirs/usr/ports/graphics/podofo/work/podofo-0.10.4/src/podofo/main/PdfColor.cpp:686:13: error: call to 'from_chars' is ambiguous
      686 |         if (std::from_chars(name.data() + 1, name.data() + name.size(), grayVal, chars_format::fixed).ec != std::errc())
          |             ^~~~~~~~~~~~~~~
    /usr/include/c++/v1/__charconv/from_chars_floating_point.h:63:1: note: candidate function
       63 | from_chars(const char* __first, const char* __last, double& __value, chars_format __fmt = chars_format::general) {
          | ^
    /wrkdirs/usr/ports/graphics/podofo/work/podofo-0.10.4/src/podofo/private/charconv_compat.h:34:30: note: candidate function
       34 |     inline from_chars_result from_chars(const char* first, const char* last,
          |                              ^

This is because libc++ 20 started offering std::from_chars() for
floating point values, and pododo does not check for this. Correct the
WANT_FROM_CHARS check to correctly check for libc++ 20 or higher.

PR:		293181
Approved by:	sunpoet (maintainer)
MFH:		2026Q1