x11-toolkits/wlroots018: unbreak build with clang 21
../xcursor/xcursor.c:605:8: error: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
  605 |         char *colon = strchr(path, ':');
      |               ^       ~~~~~~~~~~~~~~~~~

Reported by:	pkg-fallout

(cherry picked from commit 539e45eb457cbd442b34fedf5d75868f5ba8803a)