textproc/opensp: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because textproc/opensp's build infrastructure does not explicitly set
its C++ standard, this leads to an error:

  Recognizer.cxx:42:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register const Trie *pos = trie_.pointer();
    ^~~~~~~~~

To work around the error, define the register keyword away using
CPPFLAGS.

PR:		271851
Approved by:	fernape
MFH:		2023Q2