databases/mysql80-server: fix build of client on powerpc
On powerpc, clang miscompiles comp_err, which later fails at runtime with:
->  0x102ff48c <+16>: .long  0x0006ee74                ; unknown opcode
The problem happens because of line:
frame #0: 0x10323eb4 comp_err`set_my_errno(my_errno=-10608) at my_thr_init.cc:344:47

GCC can compile client, but without -malign-double. It also needs to link to
libatomic (so building without GCC installed wouldn't work anyway).

This only fixes client. Server still fails to build because of:
/wrkdirs/usr/ports/databases/mysql80-server/work/mysql-8.0.32/storage/innobase/include/log0sys.h:190:60: error: static assertion failed
  190 |   static_assert(decltype(write_to_file_requests_interval)::is_always_lock_free);