devel/spirv-llvm-translator: unbreak build after 30e46ca60676
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: llvm18/lib/libLLVMSPIRVLib.so.18.1
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: llvm18/lib/libLLVMSPIRVLib.so.18
===> Error: Plist issues found.
*** Error code 1

Reported by:	pkg-fallout