www/dooble: Fix compiling on 16-CURRENT
In file included from Source/dooble_charts_file.cc:30:
In file included from /usr/local/include/qt6/QtQml/QJSEngine:1:
In file included from /usr/local/include/qt6/QtQml/qjsengine.h:13:
/usr/local/include/qt6/QtCore/qtimezone.h:86:9: error: '= delete' with a message is a C++2c extension [-Werror,-Wc++26-extensions]
   86 |         "Would be treated as int offsetSeconds. "
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   87 |         "Use QTimeZone::UTC or QTimeZone::LocalTime instead.");
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/qt6/QtCore/qcompilerdetection.h:1046:49: note: expanded from macro 'Q_DECL_EQ_DELETE_X'
 1046 | #    define Q_DECL_EQ_DELETE_X(reason) = delete(reason)
      |                                                 ^~~~~~

PR:		299033
Reported by:	pkg-fallout
Sponsored by:	UNIS Labs (vvd, commit patch)
MFH:		2026Q4

(cherry picked from commit f45ab0387ebdd351b5164e7cdc9898a640c5aa77)