devel/bazel: fix build on powerpc*
bazel uses a bundled abseil. To build on powerpc*, abseil requires a trivial
patch.

In file included from external/com_google_absl/absl/base/internal/unscaledcycleclock.cc:27:
/usr/include/sys/sysctl.h:1185:25: error: unknown type name 'u_int'
int     sysctl(const int *, u_int, void *, size_t *, const void *, size_t);
                            ^
external/com_google_absl/absl/base/internal/unscaledcycleclock.cc:91:10: error: unknown type name 'once_flag'
  static once_flag init_timebase_frequency_once;
         ^
external/com_google_absl/absl/base/internal/unscaledcycleclock.cc:93:18: error: no member named 'LowLevelCallOnce' in namespace 'absl::lts_2020_02_25::base_internal'
  base_internal::LowLevelCallOnce(&init_timebase_frequency_once, [&]() {
  ~~~~~~~~~~~~~~~^

PR:	259056
Approved by:	ehlig@linta.de (maintainer)