www/py-qh3: fix build with LLVM_DEFAULT=19
When building with LLVM_DEFAULT set to 19, www/py-qh3 errors out with:

  error[E0425]: cannot find function, tuple struct or tuple variant `ERR_GET_LIB_RUST` in this scope
    --> /wrkdirs/usr/ports/www/py-qh3/work-py311/qh3-1.0.9/cargo-crates/aws-lc-sys-0.20.1/src/lib.rs:74:14
     |
  74 |     unsafe { ERR_GET_LIB_RUST(packed_error) }
     |              ^^^^^^^^^^^^^^^^ not found in this scope

  error[E0425]: cannot find function, tuple struct or tuple variant `ERR_GET_REASON_RUST` in this scope
    --> /wrkdirs/usr/ports/www/py-qh3/work-py311/qh3-1.0.9/cargo-crates/aws-lc-sys-0.20.1/src/lib.rs:80:14
     |
  80 |     unsafe { ERR_GET_REASON_RUST(packed_error) }
     |              ^^^^^^^^^^^^^^^^^^^ not found in this scope

  error[E0425]: cannot find function, tuple struct or tuple variant `ERR_GET_FUNC_RUST` in this scope
    --> /wrkdirs/usr/ports/www/py-qh3/work-py311/qh3-1.0.9/cargo-crates/aws-lc-sys-0.20.1/src/lib.rs:86:14
     |
  86 |     unsafe { ERR_GET_FUNC_RUST(packed_error) }
     |              ^^^^^^^^^^^^^^^^^ not found in this scope

  error[E0425]: cannot find function, tuple struct or tuple variant `BIO_ctrl` in this scope
    --> /wrkdirs/usr/ports/www/py-qh3/work-py311/qh3-1.0.9/cargo-crates/aws-lc-sys-0.20.1/src/lib.rs:91:14
     |
  91 |     unsafe { BIO_ctrl(b, BIO_CTRL_INFO, 0, pp.cast::<c_void>()) }
     |              ^^^^^^^^ not found in this scope

  error[E0425]: cannot find function, tuple struct or tuple variant `CRYPTO_library_init` in this scope
    --> /wrkdirs/usr/ports/www/py-qh3/work-py311/qh3-1.0.9/cargo-crates/aws-lc-sys-0.20.1/src/lib.rs:95:14
     |
  95 |     unsafe { CRYPTO_library_init() }
     |              ^^^^^^^^^^^^^^^^^^^ not found in this scope

In https://github.com/aws/aws-lc-rs/issues/476#issuecomment-2402442254
justsmth mentions:

> With the release of bindgen 0.69.5 this problem should now be resolved.

Bumping the bindgen CARGO_CRATES entry to 0.69.5 indeed allows the port
to built against llvm 19.

PR:		284667
Approved by:	maintainer timeout (2 weeks)
MFH:		2025Q1

(cherry picked from commit 9cccbd8cf04893ddf7fef2f2653487e06f0b94d8)