sysutils/reptyr: Fix buld under LLVM 13 on FreeBSD
Fix the following error under LLVM 13 on FreeBSD.

In file included from platform/freebsd/freebsd_ptrace.c:69:
In file included from platform/freebsd/arch/amd64.h:23:
platform/freebsd/arch/x86_common.h:45:6: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
        int ret;
            ^
platform/freebsd/arch/x86_common.h:54:6: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
        int ret;
            ^
2 errors generated.

This patch has been submitted to upstream in pull request
https://github.com/nelhage/reptyr/pull/134.

(cherry picked from commit db939cf00140485662e03f3fe6c6f50277448001)