math/gfan: fix build with clang 19
Clang 19 has become more strict about errors in member functions, which
results in errors building math/gfan:

  src/gfanlib_matrix.h:123:18: error: no member named 'vectormultiply' in 'Matrix<typ>'
    123 |         ret[i]=a.vectormultiply(b.column(i));
        |                ~ ^

The `vectormultiply` method has been commented out by upstream for
unknown reasons, but the `operator*` method that references it is also
never used, so stub it out.

PR:		282851
Approved by:	maintainer timeout (2 weeks)
MFH:		2024Q4

(cherry picked from commit 9020eeb540c2246c678a06098b916282e7251c11)