multimedia/onevpl: respect PYTHON_DEFAULT
$ pkg install python311
$ make -V PYTHON_DEFAULT
3.8
$ make clean all
[...]
-- Found Python3: /usr/local/bin/python3.11 (found version "3.11.0") found components: Interpreter Development Development.Module Development.Embed
[...]
CMake Warning:
  Manually-specified variables were not used by the project:
[...]
    Python_ADDITIONAL_VERSIONS
[...]
$ make check-plist
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PYTHON_LIBDIR%%/pyvpl.cpython-311.so
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%PYTHON_LIBDIR%%/pyvpl%%PYTHON_EXT_SUFFIX%%.so
===> Error: Plist issues found.
*** Error code 1

PR:		261415