x11-fonts/firacode: Fix plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%FONTSDIR%%/FiraCode-SemiBold.otf

http://package21.nyi.freebsd.org/data/113amd64-default-qat/537452/logs/errors/firacode-4.log