editors/gnome-text-editor: fix dependencies
src/editorconfig/libeditorconfig/meson.build:9:0: ERROR: Dependency "libpcre" not found, tried pkgconfig

====> Running Q/A tests (stage-qa)
Error: /usr/local/bin/gnome-text-editor is linked to /usr/local/lib/libcairo.so.2 from graphics/cairo but it is not declared as a dependency
Warning: you need USE_GNOME+=cairo
Error: /usr/local/bin/gnome-text-editor is linked to /usr/local/lib/libpcre.so.1 from devel/pcre but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libpcre.so:devel/pcre

PR:		266466
Reported by:	antoine (via exp-run)
Regressed by:	https://gitlab.gnome.org/GNOME/glib/-/commit/8d5a44dc8f36