net/cryptcat: Fix numerous LLVM15 build errors
Fix numerous instances of,

netcat.c:241:22: error: incompatible integer to pointer conversion passing 'unsigned int' to parameter of type 'char *' [-Wint-conversion]
    bail (wrote_txt, wrote_net, wrote_out);
                     ^~~~~~~~~

While at it assume care and feeding of this port.

(cherry picked from commit 18bba8441a4ddd827edf80284c23dddf41979069)