Mk/Uses/meson.mk: temporarily disable Python bytecode after 19804e371694
$ poudriere testport -j 131amd64 devel/blueprint-compiler
[...]
====> Running Q/A tests (stage-qa)
Error: 'lib/python3.9/site-packages/blueprintcompiler/language/__pycache__/gobject_property.cpython-39.pyc' is referring to /wrkdirs/usr/ports/devel/blueprint-compiler/work/stage
Error: 'lib/python3.9/site-packages/blueprintcompiler/language/__pycache__/gobject_object.cpython-39.pyc' is referring to /wrkdirs/usr/ports/devel/blueprint-compiler/work/stage
Error: 'lib/python3.9/site-packages/blueprintcompiler/language/__pycache__/adw_breakpoint.cpython-39.pyc' is referring to /wrkdirs/usr/ports/devel/blueprint-compiler/work/stage
[...]
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PYTHON_SITELIBDIR%%/blueprintcompiler/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/blueprintcompiler/__pycache__/ast_utils%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/blueprintcompiler/__pycache__/completions%%PYTHON_EXT_SUFFIX%%.pyc
[...]

PR:		272276