MFH: r456078
net/ns3: require C++11 toolchain (on powerpc*, mips*, sparc*)

cc1plus: error: unrecognized command line option "-std=c++11"

../examples/wireless/wifi-multi-tos.cc:124:24: error: no matching constructor for initialization of 'std::vector<uint8_t>' (aka 'vector<unsigned char>')
  std::vector<uint8_t> tosValues = {0x70, 0x28, 0xb8, 0xc0}; //AC_BE, AC_BK, AC_VI, AC_VO
                       ^           ~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/4.2/bits/stl_vector.h:266:9: note: candidate constructor template not viable: requires at most 3 arguments, but 4 were provided
        vector(_InputIterator __first, _InputIterator __last,
        ^
/usr/include/c++/4.2/bits/stl_vector.h:224:7: note: candidate constructor not viable: requires at most 3 arguments, but 4 were provided
      vector(size_type __n, const value_type& __value = value_type(),
      ^
/usr/include/c++/4.2/bits/stl_vector.h:212:7: note: candidate constructor not viable: requires single argument '__a', but 4 arguments were provided
      vector(const allocator_type& __a)
      ^
/usr/include/c++/4.2/bits/stl_vector.h:242:7: note: candidate constructor not viable: requires single argument '__x', but 4 arguments were provided
      vector(const vector& __x)
      ^
/usr/include/c++/4.2/bits/stl_vector.h:208:7: note: candidate constructor not viable: requires 0 arguments, but 4 were provided
      vector()
      ^
1 error generated.

Reported by:	pkg-fallout (mips64)
Approved by:	ports-secteam blanket