devel/zls: update to 0.13.0 after b2b3906286ed
zls-0.12.0/build.zig:496:9: error:
Your Zig version does not meet the minimum build requirement:
  required Zig version: 0.12.0
  actual   Zig version: 0.13.0

PR:		279604
Changes:	https://github.com/zigtools/zls/releases/tag/0.13.0
Reported by:	GitHub (watch releases)