editors/vscode: restore patch mistakenly removed during code style clean up
First I thought the patch was unnecessary because there are no update
services provided for FreeBSD. However, without the change code-oss
does not start with the following error:

Error: [invokeFunction] unknown service 'updateService'

Reported by:	ykla (via GitHub Issues https://github.com/tagattie/FreeBSD-VSCode/issues/44#issuecomment-2994754085)