lang/mono: Fix build on current with _WITH_CPU_SET_T
mono-proclib.c:776:3: error: unknown type name 'cpu_set_t'; did you mean 'cpuset_t'?
                cpu_set_t set;
                ^~~~~~~~~
                cpuset_t
/usr/include/sys/_cpuset.h:50:24: note: 'cpuset_t' declared here
typedef struct _cpuset cpuset_t;
                       ^
mono-proclib.c:777:7: error: implicit declaration of function 'sched_getaffinity' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                if (sched_getaffinity (mono_process_current_pid (), sizeof (set), &set) == 0)
                    ^
mono-proclib.c:778:11: error: implicit declaration of function 'CPU_COUNT' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        return CPU_COUNT (&set);
                               ^
3 errors generated.

(cherry picked from commit 83c19a7238e9f5f46a9186e3ce58d03585691e5d)