graphics/gnash: give up and expire
In file included from /usr/local/lib/gcc49/include/c++/bits/stl_algobase.h:65:0,
                 from /usr/local/lib/gcc49/include/c++/list:60,
                 from asobj/flash/display/BitmapData_as.h:24,
                 from asobj/flash/display/BitmapData_as.cpp:21:
/usr/local/lib/gcc49/include/c++/bits/stl_iterator_base_types.h: In instantiation of 'struct std::iterator_traits<unsigned int* const>':
/usr/local/include/boost/iterator/iterator_traits.hpp:28:74:   required from 'struct boost::iterators::iterator_reference<unsigned int* const>'
/usr/local/include/boost/iterator/zip_iterator.hpp:90:61:   required from 'struct boost::iterators::detail::dereference_iterator::result<boost::iterators::detail::dereference_iterator(unsigned int* const&)>'
/usr/local/include/boost/utility/result_of.hpp:189:8:   required from 'struct boost::detail::result_of_nested_result<boost::iterators::detail::dereference_iterator, boost::iterators::detail::dereference_iterator(unsigned int* const&)>'
/usr/local/include/boost/utility/result_of.hpp:193:8:   required from 'struct boost::detail::tr1_result_of_impl<boost::iterators::detail::dereference_iterator, boost::iterators::detail::dereference_iterator(unsigned int* const&), false>'
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:27:8:   required from 'struct boost::tr1_result_of<boost::iterators::detail::dereference_iterator(unsigned int* const&)>'
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:159:8:   [ skipping 16 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/local/lib/gcc49/include/c++/bits/stl_algobase.h:398:70:   required from '_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >; _OI = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >]'
/usr/local/lib/gcc49/include/c++/bits/stl_algobase.h:436:38:   required from '_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >; _OI = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >]'
/usr/local/lib/gcc49/include/c++/bits/stl_algobase.h:468:17:   required from '_OI std::copy(_II, _II, _OI) [with _II = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >; _OI = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >]'
asobj/flash/display/BitmapData_as.cpp:412:73:   required from 'void gnash::{anonymous}::PerlinNoise<T, Size, Offset>::init(int) [with T = double; unsigned int Size = 256u; unsigned int Offset = 1327u]'
asobj/flash/display/BitmapData_as.cpp:310:18:   required from 'gnash::{anonymous}::PerlinNoise<T, Size, Offset>::PerlinNoise(int) [with T = double; unsigned int Size = 256u; unsigned int Offset = 1327u]'
asobj/flash/display/BitmapData_as.cpp:1371:23:   required from here
/usr/local/lib/gcc49/include/c++/bits/stl_iterator_base_types.h:165:53: error: 'unsigned int* const' is not a class, struct, or union type
       typedef typename _Iterator::iterator_category iterator_category;
                                                     ^
/usr/local/lib/gcc49/include/c++/bits/stl_iterator_base_types.h:166:53: error: 'unsigned int* const' is not a class, struct, or union type
       typedef typename _Iterator::value_type        value_type;
                                                     ^
/usr/local/lib/gcc49/include/c++/bits/stl_iterator_base_types.h:167:53: error: 'unsigned int* const' is not a class, struct, or union type
       typedef typename _Iterator::difference_type   difference_type;
                                                     ^
/usr/local/lib/gcc49/include/c++/bits/stl_iterator_base_types.h:168:53: error: 'unsigned int* const' is not a class, struct, or union type
       typedef typename _Iterator::pointer           pointer;
                                                     ^
/usr/local/lib/gcc49/include/c++/bits/stl_iterator_base_types.h:169:53: error: 'unsigned int* const' is not a class, struct, or union type
       typedef typename _Iterator::reference         reference;
                                                     ^
In file included from /usr/local/include/boost/fusion/adapted/boost_tuple/detail/convert_impl.hpp:11:0,
                 from /usr/local/include/boost/fusion/adapted/boost_tuple.hpp:20,
                 from /usr/local/include/boost/iterator/zip_iterator.hpp:21,
                 from asobj/flash/display/BitmapData_as.cpp:28:
/usr/local/include/boost/fusion/adapted/boost_tuple/detail/build_cons.hpp: In instantiation of 'static boost::fusion::detail::build_tuple_cons<First, Last, false>::type boost::fusion::detail::build_tuple_cons<First, Last, false>::call(const First&, const Last&) [with First = boost::fusion::transform_view_iterator<boost::fusion::boost_tuple_iterator<const boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >, boost::iterators::detail::dereference_iterator>; Last = boost::fusion::transform_view_iterator<boost::fusion::boost_tuple_iterator<const boost::tuples::null_type>, boost::iterators::detail::dereference_iterator>; boost::fusion::detail::build_tuple_cons<First, Last, false>::type = boost::tuples::cons<unsigned int&, boost::tuples::cons<boost::array<double, 2u>&, boost::tuples::null_type> >; typename boost::fusion::detail::build_tuple_cons<typename boost::fusion::result_of::next<Iterator>::type, Last>::type = boost::tuples::cons<boost::array<double, 2u>&, boost::tuples::null_type>; typename boost::fusion::result_of::value_of<First>::type = unsigned int&]':
/usr/local/include/boost/fusion/adapted/boost_tuple/detail/convert_impl.hpp:43:87:   required from 'static boost::fusion::extension::convert_impl<boost::fusion::boost_tuple_tag>::apply<Sequence>::type boost::fusion::extension::convert_impl<boost::fusion::boost_tuple_tag>::apply<Sequence>::call(Sequence&) [with Sequence = boost::fusion::transform_view<const boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>, boost::iterators::detail::dereference_iterator, boost::fusion::void_>; boost::fusion::extension::convert_impl<boost::fusion::boost_tuple_tag>::apply<Sequence>::type = boost::tuples::cons<unsigned int&, boost::tuples::cons<boost::array<double, 2u>&, boost::tuples::null_type> >]'
/usr/local/include/boost/fusion/sequence/convert.hpp:47:29:   required from 'typename boost::fusion::result_of::convert<Tag, Sequence>::type boost::fusion::convert(Sequence&) [with Tag = boost::fusion::boost_tuple_tag; Sequence = boost::fusion::transform_view<const boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>, boost::iterators::detail::dereference_iterator, boost::fusion::void_>; typename boost::fusion::result_of::convert<Tag, Sequence>::type = boost::tuples::cons<unsigned int&, boost::tuples::cons<boost::array<double, 2u>&, boost::tuples::null_type> >]'
/usr/local/include/boost/iterator/zip_iterator.hpp:214:44:   required from 'static reference boost::iterators::detail::converter<reference>::call(Seq) [with Seq = boost::fusion::transform_view<const boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>, boost::iterators::detail::dereference_iterator, boost::fusion::void_>; reference = boost::tuples::cons<unsigned int&, boost::tuples::cons<boost::array<double, 2u>&, boost::tuples::null_type> >]'
/usr/local/include/boost/iterator/zip_iterator.hpp:289:42:   required from 'typename boost::iterators::detail::zip_iterator_base<IteratorTuple>::type::reference boost::iterators::zip_iterator<IteratorTuple>::dereference() const [with IteratorTuple = boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>; typename boost::iterators::detail::zip_iterator_base<IteratorTuple>::type::reference = boost::tuples::cons<unsigned int&, boost::tuples::cons<boost::array<double, 2u>&, boost::tuples::null_type> >]'
/usr/local/include/boost/iterator/iterator_facade.hpp:549:32:   required from 'static typename Facade::reference boost::iterators::iterator_core_access::dereference(const Facade&) [with Facade = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >; typename Facade::reference = boost::tuples::cons<unsigned int&, boost::tuples::cons<boost::array<double, 2u>&, boost::tuples::null_type> >]'
/usr/local/include/boost/iterator/iterator_facade.hpp:655:69:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/local/lib/gcc49/include/c++/bits/stl_algobase.h:398:70:   required from '_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >; _OI = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >]'
/usr/local/lib/gcc49/include/c++/bits/stl_algobase.h:436:38:   required from '_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >; _OI = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >]'
/usr/local/lib/gcc49/include/c++/bits/stl_algobase.h:468:17:   required from '_OI std::copy(_II, _II, _OI) [with _II = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >; _OI = boost::iterators::zip_iterator<boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >]'
asobj/flash/display/BitmapData_as.cpp:412:73:   required from 'void gnash::{anonymous}::PerlinNoise<T, Size, Offset>::init(int) [with T = double; unsigned int Size = 256u; unsigned int Offset = 1327u]'
asobj/flash/display/BitmapData_as.cpp:310:18:   required from 'gnash::{anonymous}::PerlinNoise<T, Size, Offset>::PerlinNoise(int) [with T = double; unsigned int Size = 256u; unsigned int Offset = 1327u]'
asobj/flash/display/BitmapData_as.cpp:1371:23:   required from here
/usr/local/include/boost/fusion/adapted/boost_tuple/detail/build_cons.hpp:53:59: error: no match for 'operator*' (operand type is 'const boost::fusion::transform_view_iterator<boost::fusion::boost_tuple_iterator<const boost::tuples::tuple<unsigned int*, boost::array<double, 2u>*, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >, boost::iterators::detail::dereference_iterator>')
             typename result_of::value_of<First>::type v = *f;
                                                           ^
/usr/local/include/boost/fusion/adapted/boost_tuple/detail/build_cons.hpp:53:59: note: candidate is:
In file included from /usr/local/include/boost/fusion/adapted/boost_tuple/detail/build_cons.hpp:14:0,
                 from /usr/local/include/boost/fusion/adapted/boost_tuple/detail/convert_impl.hpp:11,
                 from /usr/local/include/boost/fusion/adapted/boost_tuple.hpp:20,
                 from /usr/local/include/boost/iterator/zip_iterator.hpp:21,
                 from asobj/flash/display/BitmapData_as.cpp:28:
/usr/local/include/boost/fusion/iterator/deref.hpp:69:5: note: template<class Iterator> typename boost::fusion::result_of::deref<Iterator>::type boost::fusion::operator*(const boost::fusion::iterator_base<Derived>&)
     operator*(iterator_base<Iterator> const& i)
     ^
/usr/local/include/boost/fusion/iterator/deref.hpp:69:5: note:   substitution of deduced template arguments resulted in errors seen above

PR:		199601
Reported by:	antoine (via exp-run)