deskutils/budgie-desktop-view: unbreak build with Meson 1.4.0
src/org.buddiesofbudgie.budgie-desktop-view.p/desktop_item.c:195:66: error: unused parameter '_sender' [-Werror,-Wunused-parameter]
_desktop_item_on_enter_gtk_widget_enter_notify_event (GtkWidget* _sender,
                                                                 ^
src/org.buddiesofbudgie.budgie-desktop-view.p/desktop_item.c:205:66: error: unused parameter '_sender' [-Werror,-Wunused-parameter]
_desktop_item_on_leave_gtk_widget_leave_notify_event (GtkWidget* _sender,
                                                                 ^
src/org.buddiesofbudgie.budgie-desktop-view.p/desktop_item.c:865:35: error: unused parameter 'klass_data' [-Werror,-Wunused-parameter]
                         gpointer klass_data)
                                  ^
src/org.buddiesofbudgie.budgie-desktop-view.p/desktop_item.c:879:43: error: unused parameter 'self' [-Werror,-Wunused-parameter]
desktop_item_instance_init (DesktopItem * self,
                                          ^
src/org.buddiesofbudgie.budgie-desktop-view.p/desktop_item.c:880:38: error: unused parameter 'klass' [-Werror,-Wunused-parameter]
                            gpointer klass)
                                     ^
src/org.buddiesofbudgie.budgie-desktop-view.p/desktop_item.c:913:6: error: passing 'typeof (*(&desktop_item_type_id__once)) *' (aka 'volatile unsigned long *') to parameter of type 'gsize *' (aka 'unsigned long *') discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        if (g_once_init_enter (&desktop_item_type_id__once)) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/glib-2.0/glib/gthread.h:262:7: note: expanded from macro 'g_once_init_enter'
    (!g_atomic_pointer_get (location) &&                             \
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/glib-2.0/glib/gatomic.h:131:38: note: expanded from macro 'g_atomic_pointer_get'
    __atomic_load (gapg_temp_atomic, &gapg_temp_newval, __ATOMIC_SEQ_CST); \
                                     ^~~~~~~~~~~~~~~~~
src/org.buddiesofbudgie.budgie-desktop-view.p/application.c:93:130: error: 'G_APPLICATION_FLAGS_NONE' is deprecated: Use 'G_APPLICATION_DEFAULT_FLAGS' instead [-Werror,-Wdeprecated-declarations]
        self = (BudgieDesktopViewApp*) g_object_new (object_type, "application-id", "org.buddiesofbudgie.budgie-desktop-view", "flags", G_APPLICATION_FLAGS_NONE, NULL);
                                                                                                                                        ^
/usr/local/include/glib-2.0/gio/gioenums.h:1540:28: note: 'G_APPLICATION_FLAGS_NONE' has been explicitly marked deprecated here
  G_APPLICATION_FLAGS_NONE GIO_DEPRECATED_ENUMERATOR_IN_2_74_FOR(G_APPLICATION_DEFAULT_FLAGS),
                           ^
/usr/local/include/glib-2.0/gio/gio-visibility.h:858:50: note: expanded from macro 'GIO_DEPRECATED_ENUMERATOR_IN_2_74_FOR'
                                                 ^
/usr/local/include/glib-2.0/glib/gmacros.h:1312:43: note: expanded from macro 'GLIB_DEPRECATED_ENUMERATOR_FOR'
                                          ^
/usr/local/include/glib-2.0/glib/gmacros.h:1272:44: note: expanded from macro 'G_DEPRECATED_FOR'
                                           ^
src/org.buddiesofbudgie.budgie-desktop-view.p/application.c:140:46: error: unused parameter 'klass_data' [-Werror,-Wunused-parameter]
                                    gpointer klass_data)
                                             ^
src/org.buddiesofbudgie.budgie-desktop-view.p/application.c:147:63: error: unused parameter 'self' [-Werror,-Wunused-parameter]
budgie_desktop_view_app_instance_init (BudgieDesktopViewApp * self,
                                                              ^
src/org.buddiesofbudgie.budgie-desktop-view.p/application.c:148:49: error: unused parameter 'klass' [-Werror,-Wunused-parameter]
                                       gpointer klass)
                                                ^
src/org.buddiesofbudgie.budgie-desktop-view.p/application.c:165:6: error: passing 'typeof (*(&budgie_desktop_view_app_type_id__once)) *' (aka 'volatile unsigned long *') to parameter of type 'gsize *' (aka 'unsigned long *') discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        if (g_once_init_enter (&budgie_desktop_view_app_type_id__once)) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/glib-2.0/glib/gthread.h:262:7: note: expanded from macro 'g_once_init_enter'
    (!g_atomic_pointer_get (location) &&                             \
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/glib-2.0/glib/gatomic.h:131:38: note: expanded from macro 'g_atomic_pointer_get'
    __atomic_load (gapg_temp_atomic, &gapg_temp_newval, __ATOMIC_SEQ_CST); \
                                     ^~~~~~~~~~~~~~~~~
/usr/local/include/X11/Xregion.h:59:9: error: 'TRUE' macro redefined [-Werror,-Wmacro-redefined]
        ^
/usr/local/include/glib-2.0/glib/gmacros.h:928:9: note: previous definition is here
        ^
In file included from src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:33:
/usr/local/include/X11/Xregion.h:60:9: error: 'FALSE' macro redefined [-Werror,-Wmacro-redefined]
        ^
/usr/local/include/glib-2.0/glib/gmacros.h:924:9: note: previous definition is here
        ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:667:169: error: missing field 'padding' initializer [-Werror,-Wmissing-field-initializers]
static const GDBusInterfaceVTable _raven_dbus_interface_vtable = {raven_dbus_interface_method_call, raven_dbus_interface_get_property, raven_dbus_interface_set_property};
                                                                                                                                                                        ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:695:34: error: unused parameter 'iface' [-Werror,-Wunused-parameter]
raven_default_init (RavenIface * iface,
                                 ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:696:30: error: unused parameter 'iface_data' [-Werror,-Wunused-parameter]
                    gpointer iface_data)
                             ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:718:6: error: passing 'typeof (*(&raven_type_id__once)) *' (aka 'volatile unsigned long *') to parameter of type 'gsize *' (aka 'unsigned long *') discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        if (g_once_init_enter (&raven_type_id__once)) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/glib-2.0/glib/gthread.h:262:7: note: expanded from macro 'g_once_init_enter'
    (!g_atomic_pointer_get (location) &&                             \
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/glib-2.0/glib/gatomic.h:131:38: note: expanded from macro 'g_atomic_pointer_get'
    __atomic_load (gapg_temp_atomic, &gapg_temp_newval, __ATOMIC_SEQ_CST); \
                                     ^~~~~~~~~~~~~~~~~
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:734:35: error: unused parameter 'proxy' [-Werror,-Wunused-parameter]
raven_proxy_g_signal (GDBusProxy* proxy,
                                  ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:735:36: error: unused parameter 'sender_name' [-Werror,-Wunused-parameter]
                      const gchar* sender_name,
                                   ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:736:36: error: unused parameter 'signal_name' [-Werror,-Wunused-parameter]
                      const gchar* signal_name,
                                   ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:737:33: error: unused parameter 'parameters' [-Werror,-Wunused-parameter]
                      GVariant* parameters)
                                ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:748:40: error: unused parameter 'source_object' [-Werror,-Wunused-parameter]
_vala_g_async_ready_callback (GObject *source_object,
                                       ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:847:52: error: unused parameter 'connection' [-Werror,-Wunused-parameter]
raven_dbus_interface_method_call (GDBusConnection* connection,
                                                   ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:848:48: error: unused parameter 'sender' [-Werror,-Wunused-parameter]
                                  const gchar* sender,
                                               ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:849:48: error: unused parameter 'object_path' [-Werror,-Wunused-parameter]
                                  const gchar* object_path,
                                               ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:850:48: error: unused parameter 'interface_name' [-Werror,-Wunused-parameter]
                                  const gchar* interface_name,
                                               ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:877:11: error: variable 'object' set but not used [-Werror,-Wunused-but-set-variable]
        gpointer object;
                 ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:868:53: error: unused parameter 'connection' [-Werror,-Wunused-parameter]
raven_dbus_interface_get_property (GDBusConnection* connection,
                                                    ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:869:49: error: unused parameter 'sender' [-Werror,-Wunused-parameter]
                                   const gchar* sender,
                                                ^
src/org.buddiesofbudgie.budgie-desktop-view.p/budgie_desktop_view.c:870:49: error: unused parameter 'object_path' [-Werror,-Wunused-parameter]
                                   const gchar* object_path,
                                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

PR:		277354
Reported by:	antoine (via exp-run)
Regressed by:	https://github.com/mesonbuild/meson/commit/5f659af87001