www/firefox: fix build on 12
  In file included from /wrkdirs/usr/ports/www/firefox/work/firefox-106.0/third_party/libwebrtc/rtc_base/ip_address.cc:24:
  /usr/include/netinet/ip.h:53:2: error: unknown type name 'u_char'; did you mean 'char'?

requires sys/types.h

Reported by:	pkg-fallout