net/keycloak: Update to 24.0.4
ChangeLog: https://www.keycloak.org/2024/05/keycloak-2404-released.html

Enhancements

 #27508 Use new remote-store options in HA guides
 #28429 Add details to error messages, especially around refresh tokens
 #28729 Emphasize the need for setting container limit docs
 #28880 Upgrade to Quarkus 3.8.4 dist/quarkus
 #29183 Minor corrections to High Availability Guide docs

Bugs

 #16345 Unable to delete realm names with invalid URL characters admin/api
 #22617 kc export fails when using User Federation (LDAP) with file-based Vault
 enabled import-export
 #24568 iframe for frontend logout gets blocked if a custom CSP header is used
 core
 #24878 NoClassDefFoundError for Apache XML and EAP8 adapter/jee-saml
 #27021 Workflow failure: Fuse adapter tests ci
 #27080 Workflow failure: Operator CI -
 KeycloakTruststoresTests#testTrustroreExists ci
 #27514 Uncaught server error: java.lang.IllegalArgumentException: Path
 parameter not provided oidc
 #28079 Group search does not work in user view admin/ui
 #28187 Admin UI drag & drop in flow config seems to delete actions admin/ui
 #28220 Admin API: User PUT operation clears firstname, lastname email fields
 admin/api
 #28303 WARN - Event object wasn't available in remote cache after event was
 received infinispan
 #28377 Broken lists in import/export server guide docs
 #28431 Dedicated client scopes always show up when searching admin/ui
 #28514 Message for searchClientRegistration is missing admin/ui
 #28666 Accessing a transient (lightweight) user through client session fails in
 admin-api/-ui admin/ui
 #28684 "Extend to children" button in authorization group policies is wrongly
 disabled admin/ui
 #28911 clients_saml_test.spec.ts fails in main admin/ui
 #29072 Startup probe should check for existence of an Admin user before
 returning 200 dist/quarkus
 #29094 Fix the client name help grammatical error admin/ui
 #29133 DuplicateEmailValidator causes two DB queries on every login if a user
 has an email address core
 #29147 local user login not possible after LDAP connection problem ldap
 #29154 Update docs to distinguish between product names and CR names docs
 #29233 Broken link in documentation docs

PR:		278856
Reported by:	freebsd@rheinwolf.de (maintainer)