x11-drivers/xf86-video-nv: fix build on powerpc*
nv_driver.c:1387:40: error: incompatible integer to pointer conversion passing 'CARD32' (aka 'unsigned int') to parameter of type 'CARD8 *' (aka 'unsigned char *') [-Wint-conversion]
 1387 |     vgaHWSetMmioFuncs(VGAHWPTR(pScrn), pNv->IOAddress, 0);
      |                                        ^~~~~~~~~~~~~~
/usr/local/include/xorg/vgaHW.h:180:62: note: passing argument to parameter 'base' here
  180 | extern _X_EXPORT void vgaHWSetMmioFuncs(vgaHWPtr hwp, CARD8 *base, int offset);
      |                                                              ^
1 error generated.

It's fine to just pass NULL here because IOAddress is NULL at this line
anyway.