deskutils/health: unbreak build on i386
fatal runtime error: Rust cannot catch foreign exceptions
thread 'coordinator' panicked at compiler/rustc_middle/src/util/bug.rs:36:26:
/wrkdirs/usr/ports/lang/rust/work/rustc-1.77.0-src/compiler/rustc_codegen_ssa/src/back/write.rs:1588:29: worker thread panicked
(signal: 6, SIGABRT: process abort signal)

Reported by:	pkg-fallout

(cherry picked from commit b74febdcf13b52b2e168a75c49549229fa7f283a)