multimedia/gstreamer1-libav: unbreak with ffmpeg 5.0
gstavdemux.c:486:26: error: no member named 'index_entries' in 'struct AVStream'
      fftarget = stream->index_entries[keyframeidx].timestamp;
                 ~~~~~~  ^

PR:		261302
Regressed by:	https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/cea7c19cda0e