games/veloren-weekly: disable LTO on i386 after 6f656934f1aa
thread '<unnamed>fatal runtime error: Rust cannot catch foreign exceptions
' panicked at '/wrkdirs/usr/ports/lang/rust/work/rustc-1.69.0-src/compiler/rustc_codegen_ssa/src/back/write.rs:1534:21: worker thread panicked', compiler/rustc_middle/src/util/bug.rs:36:26

(signal: 6, SIGABRT: process abort signal)

Reported by:	pkg-fallout

(cherry picked from commit 57487937f313091ba223fd3fc3a2b5ca33d0b7be)