textproc/ripgrep: Unbreak with CPUTYPE=haswell and rust>=1.48.0
error[E0432]: unresolved import `crate::arch::x86_64::_mm_shuffle_pi8`
   --> /usr/ports/textproc/ripgrep/work/ripgrep-12.1.1/cargo-crates/packed_simd-0.3.3/src/codegen/shuffle1_dyn.rs:40:29
    |
40  |                         use crate::arch::x86_64::_mm_shuffle_pi8;
    |                             ^^^^^^^^^^^^^^^^^^^^^---------------
    |                             |                    |
    |                             |                    help: a similar name exists in the module: `_mm_shuffle_epi8`
    |                             no `_mm_shuffle_pi8` in `arch::x86_64`
...
297 | impl_shuffle1_dyn!(u8x8);
    | ------------------------- in this macro invocation
    |

Pull in newer packed_simd crate to fix it.  Newer versions are
published as packed_simd_2 because the original author is MIA.

PR:		251425
Reported by:	Tomoaki AOKI <junchoon@dec.sakura.ne.jp>