x11-servers/xwayland-devel: unbreak ssh -X like 151096d9f308
$ ssh -X localhost xeyes
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
Error: Can't open display:

$ xauth generate $DISPLAY .
xauth:  file /home/foo/.Xauthority does not exist
xauth: (argv):1:  couldn't query Security extension on display ":0"

Note, SECURITY extension uses XACE internally while more fine-grained
SELinux extension isn't supported on FreeBSD.

Inspired by:	Alpine, Arch, Fedora, openSUSE, Void