sysutils/uhidd: unbreak build on 11.0
Only call basename(3) when qualifying for "const" as /dev/ prefix in
/dev/ugen%d.%d is unused.

uhidd.c:234:16: error: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                    basename(hi->dev));
                             ^~~~~~~
/usr/include/libgen.h:38:22: note: passing argument to parameter here
char    *basename(char *);
                        ^
Reported by:	antoine (exp-run), ed (ping)
PR:		209747