cad/PrusaSlicer: unbreak build after 620968a43a5f
Restore the patch accidentally removed due to an out of date comment.
8a4af427075f removed pthread_setname_np references.

src/libslic3r/Thread.cpp:13:10: fatal error: 'tbb/tbb_thread.h' file not found
 #include <tbb/tbb_thread.h>
          ^~~~~~~~~~~~~~~~~~