multimedia/py-openlp: Update 2.1.6 -> 2.4.6
- adds LICENSE_FILE
- copies OpenLP to ${PREFIX}/bin (= renamed copy of openlp.py)
  with appropriate workaround for the openlp.desktop file.
  This is required to start the software. Otherwise it yields the
  following error:
  ImportError: No module named 'openlp.core'; 'openlp' is not a package.
- added INSTALLS_ICONS to pet portlint
- merged pre-build target into post-build target
- sorted variables a bit

PR:		211665
Submitted by:	Kai <freebsd_ports@k-worx.org>
Changes:	https://openlp.org/blog/2017/04/02/fix-all-the-bugs-openlp-246
		https://openlp.org/blog/2017/02/05/a-few-more-bugs-fixed-openlp-245
		https://openlp.org/blog/2016/11/27/openlp-244-released
		https://openlp.org/blog/2016/09/25/openlp-243-and-personal-news
		https://openlp.org/blog/2016/06/26/openlp-242-released
		https://openlp.org/blog/2016/05/01/openlp-241-released
		https://openlp.org/blog/2016/02/14/openlp-24-released
		https://openlp.org/blog/2015/11/01/first-22-series-bugfix-release-openlp-221
		https://openlp.org/blog/2015/10/18/openlp-22-released