graphics/timg: Set NOT_FOR_ARCHS=i386
On i386 the build causes an error:
/wrkdirs/usr/ports/graphics/timg/work/timg-1.6.1/src/timg-time.h:59:37:
error: non-constant-expression cannot be narrowed from type 'int64_t'
(aka 'long long') to 'long' in initializer list [-Wc++11-narrowing]

(cherry picked from commit 342f30257a4d6ff0320f4cf88770b798da08ec69)