net/aoe: fix build on FreeBSD 12
Still broken on FreeBSD 13+, but for a different reason now:

aoenet.c:313:22: error: use of undeclared identifier 'ifnet'; did you mean 'ifunit'?
        IFNET_FOREACH(ifp, &ifnet, if_link) {
                            ^~~~~
                            ifunit

PR:		239891
MFH:		2023Q3

(cherry picked from commit ac47064e4aac2fedc24270363fbb1b26eaf0b2bd)