graphics/jogl: pin to java 8
After removing source="1.4" from build.xml it still errors on
classes that are removed from jdk11.

gluegen/src/java/net/highteq/nativetaglet/NativeTaglet.java:3: error: package com.sun.tools.doclets does not exist

PR:	292241
Approved-by:	peterj@