biology/biosig: fix build with libc++ 19
With libc++ 19, biology/biosig fails to compile, with errors similar to:

  /usr/include/c++/v1/__math/special_functions.h:51:16: error: expected unqualified-id
     51 |   if (!__math::isfinite(__H_n)) {
        |                ^
  ./t230/../biosig-dev.h:932:22: note: expanded from macro 'isfinite'
    932 | # define isfinite(a) (-INFINITY < (a) && (a) < INFINITY)
        |                      ^

This is because biosig attempts to define its own isfinite() macro,
which it should not do. Stub out the incompatible definition.

PR:		281976
Approved by:	yuri (maintainer)
MFH:		2024Q4