x11/xscreensaver: remove XFT option
Xft isn't optional: it is mandatory, and xscreensaver configure
complains if it isn't there (but completes with a successful
exit code, which is a bit strange). Without XFT, the build
eventually fails like so:

dialog.c:695:52: error: use of undeclared identifier 'FcChar32'
      if (XftCharExists (ws->dpy, ws->label_font, (FcChar32) *uc))

PR:		263869
Reported by:	riggs
Approved by:	build-fix blanket