graphics/vulkan-validation-layers: unbreak build after 25856cf8cf38
layers/gpu_validation/gpu_validation.cpp:1014:48: error: use of undeclared identifier 'kInstBindlessBoundsOutDescSet'; did you mean 'kInstBindlessBoundsOutDescIndex'?
            strm << "(set = " <<  debug_record[kInstBindlessBoundsOutDescSet] << ", binding = " << debug_record[kInstBindlessBoundsOutDescBinding] << ") Index of "
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                               kInstBindlessBoundsOutDescIndex
/usr/local/include/spirv-tools/instrument.hpp:149:18: note: 'kInstBindlessBoundsOutDescIndex' declared here
static const int kInstBindlessBoundsOutDescIndex = kInstStageOutCnt + 1;
                 ^
layers/gpu_validation/gpu_validation.cpp:1014:113: error: use of undeclared identifier 'kInstBindlessBoundsOutDescBinding'
            strm << "(set = " <<  debug_record[kInstBindlessBoundsOutDescSet] << ", binding = " << debug_record[kInstBindlessBoundsOutDescBinding] << ") Index of "
                                                                                                                ^
layers/gpu_validation/gpu_validation.cpp:1019:47: error: use of undeclared identifier 'kInstBindlessUninitOutDescSet'; did you mean 'kInstBindlessUninitOutDescIndex'?
            strm << "(set = " << debug_record[kInstBindlessUninitOutDescSet] << ", binding = " << debug_record[kInstBindlessUninitOutBinding] << ") Descriptor index "
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                              kInstBindlessUninitOutDescIndex
/usr/local/include/spirv-tools/instrument.hpp:155:18: note: 'kInstBindlessUninitOutDescIndex' declared here
static const int kInstBindlessUninitOutDescIndex = kInstStageOutCnt + 1;
                 ^
layers/gpu_validation/gpu_validation.cpp:1019:112: error: use of undeclared identifier 'kInstBindlessUninitOutBinding'
            strm << "(set = " << debug_record[kInstBindlessUninitOutDescSet] << ", binding = " << debug_record[kInstBindlessUninitOutBinding] << ") Descriptor index "
                                                                                                               ^
layers/gpu_validation/gpu_validation.cpp:1033:51: error: use of undeclared identifier 'kInstBindlessBuffOOBOutDescSet'; did you mean 'kInstBindlessBuffOOBOutDescIndex'?
                strm << "(set = " << debug_record[kInstBindlessBuffOOBOutDescSet] << ", binding = " << debug_record[kInstBindlessBuffOOBOutDescBinding]
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  kInstBindlessBuffOOBOutDescIndex
/usr/local/include/spirv-tools/instrument.hpp:162:18: note: 'kInstBindlessBuffOOBOutDescIndex' declared here
static const int kInstBindlessBuffOOBOutDescIndex = kInstStageOutCnt + 1;
                 ^
layers/gpu_validation/gpu_validation.cpp:1033:117: error: use of undeclared identifier 'kInstBindlessBuffOOBOutDescBinding'; did you mean 'kInstBindlessBuffOOBOutDescIndex'?
                strm << "(set = " << debug_record[kInstBindlessBuffOOBOutDescSet] << ", binding = " << debug_record[kInstBindlessBuffOOBOutDescBinding]
                                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                    kInstBindlessBuffOOBOutDescIndex
/usr/local/include/spirv-tools/instrument.hpp:162:18: note: 'kInstBindlessBuffOOBOutDescIndex' declared here
static const int kInstBindlessBuffOOBOutDescIndex = kInstStageOutCnt + 1;
                 ^
layers/gpu_validation/gpu_validation.cpp:1038:51: error: use of undeclared identifier 'kInstBindlessBuffOOBOutDescSet'; did you mean 'kInstBindlessBuffOOBOutDescIndex'?
                strm << "(set = " << debug_record[kInstBindlessBuffOOBOutDescSet] << ", binding = " << debug_record[kInstBindlessBuffOOBOutDescBinding]
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  kInstBindlessBuffOOBOutDescIndex
/usr/local/include/spirv-tools/instrument.hpp:162:18: note: 'kInstBindlessBuffOOBOutDescIndex' declared here
static const int kInstBindlessBuffOOBOutDescIndex = kInstStageOutCnt + 1;
                 ^
layers/gpu_validation/gpu_validation.cpp:1038:117: error: use of undeclared identifier 'kInstBindlessBuffOOBOutDescBinding'; did you mean 'kInstBindlessBuffOOBOutDescIndex'?
                strm << "(set = " << debug_record[kInstBindlessBuffOOBOutDescSet] << ", binding = " << debug_record[kInstBindlessBuffOOBOutDescBinding]
                                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                    kInstBindlessBuffOOBOutDescIndex
/usr/local/include/spirv-tools/instrument.hpp:162:18: note: 'kInstBindlessBuffOOBOutDescIndex' declared here
static const int kInstBindlessBuffOOBOutDescIndex = kInstStageOutCnt + 1;
                 ^
layers/gpu_validation/gpu_validation.cpp:1052:51: error: use of undeclared identifier 'kInstBindlessBuffOOBOutDescSet'; did you mean 'kInstBindlessBuffOOBOutDescIndex'?
                strm << "(set = " << debug_record[kInstBindlessBuffOOBOutDescSet] << ", binding = " << debug_record[kInstBindlessBuffOOBOutDescBinding]
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  kInstBindlessBuffOOBOutDescIndex
/usr/local/include/spirv-tools/instrument.hpp:162:18: note: 'kInstBindlessBuffOOBOutDescIndex' declared here
static const int kInstBindlessBuffOOBOutDescIndex = kInstStageOutCnt + 1;
                 ^
layers/gpu_validation/gpu_validation.cpp:1052:117: error: use of undeclared identifier 'kInstBindlessBuffOOBOutDescBinding'; did you mean 'kInstBindlessBuffOOBOutDescIndex'?
                strm << "(set = " << debug_record[kInstBindlessBuffOOBOutDescSet] << ", binding = " << debug_record[kInstBindlessBuffOOBOutDescBinding]
                                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                    kInstBindlessBuffOOBOutDescIndex
/usr/local/include/spirv-tools/instrument.hpp:162:18: note: 'kInstBindlessBuffOOBOutDescIndex' declared here
static const int kInstBindlessBuffOOBOutDescIndex = kInstStageOutCnt + 1;
                 ^
layers/gpu_validation/gpu_validation.cpp:1057:51: error: use of undeclared identifier 'kInstBindlessBuffOOBOutDescSet'; did you mean 'kInstBindlessBuffOOBOutDescIndex'?
                strm << "(set = " << debug_record[kInstBindlessBuffOOBOutDescSet] << ", binding = " << debug_record[kInstBindlessBuffOOBOutDescBinding]
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  kInstBindlessBuffOOBOutDescIndex
/usr/local/include/spirv-tools/instrument.hpp:162:18: note: 'kInstBindlessBuffOOBOutDescIndex' declared here
static const int kInstBindlessBuffOOBOutDescIndex = kInstStageOutCnt + 1;
                 ^
layers/gpu_validation/gpu_validation.cpp:1057:117: error: use of undeclared identifier 'kInstBindlessBuffOOBOutDescBinding'; did you mean 'kInstBindlessBuffOOBOutDescIndex'?
                strm << "(set = " << debug_record[kInstBindlessBuffOOBOutDescSet] << ", binding = " << debug_record[kInstBindlessBuffOOBOutDescBinding]
                                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                    kInstBindlessBuffOOBOutDescIndex
/usr/local/include/spirv-tools/instrument.hpp:162:18: note: 'kInstBindlessBuffOOBOutDescIndex' declared here
static const int kInstBindlessBuffOOBOutDescIndex = kInstStageOutCnt + 1;
                 ^

Regressed by:	https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/da7711a4f0ab