www/csso: Fix a runtime error
- Add a temporary patch to fix the following error:

/usr/local/share/csso/lib/csso.js:69
    print(fs.readFileSync(__dirname.slice(0, __dirname.lastIndexOf('/')) + '/' + filename).toString());
    ^

TypeError: print is not a function
    at printFile (/usr/local/share/csso/lib/csso.js:69:5)
    at Object.<anonymous> (/usr/local/share/csso/lib/csso.js:28:5)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

This happens because the function util.print() has been removed by recent
versions of node.

- Install the file VERSION (required when using --version switch)
- Reorder variables in Makefile
- Bump PORTREVISION (pkg-plist changed)

PR:	268010
Reported by:	Chris Hutchinson <portmaster@bsdforge.com>