lang/gcc10: fix runtime on powerpc64le
It looks like this part was omitted during upstreaming.
Its lack causes gcc to be compiled successfully, but fail at building simple programs:
/usr/local/bin/ld: /usr/local/lib/gcc10/libgcc_s.so: undefined reference to `.__udivmodti4'
/usr/local/bin/ld: /usr/local/lib/gcc10/libgcc_s.so: undefined reference to `.__ctzdi2'
/usr/local/bin/ld: /usr/local/lib/gcc10/libgcc_s.so: undefined reference to `.__parityti2'
/usr/local/bin/ld: /usr/local/lib/gcc10/libgcc_s.so: undefined reference to `.__enable_execute_stack'