graphics/libjxl: unbreak JPEG=off after 115fc1237eeb
Error: Missing: bin/cjpeg_hdr

https://github.com/libjxl/libjxl/commit/759a29f9e6e0

PR:		271124
Submitted by:	fsbruva@yahoo.com

(cherry picked from commit 0bafdac68158d54d6aa6a06c96b566809066d770)