www/py-asgiref: Add missing dependencies
* Python versions prior 3.11 requires devel/py-typing-extensions as
  noted in the setup.cfg.  Otherwise it leads to following error [1]:

  [...]
      from asgiref.sync import sync_to_async
    File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 27, in <module>
      from .current_thread_executor import CurrentThreadExecutor
    File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 10, in <module>
      from typing_extensions import ParamSpec
  ModuleNotFoundError: No module named 'typing_extensions'
  [...]

* Bump PORTREVISION due changed dependencies.

Reported by:	pkg-fallout [1] (for www/py-django-treebeard)
Approved by:	portmgr (buildfix blanket)
Fixes:	8a94364e8648 www/py-asgiref: Update to 3.7.2