graphics/pygts: convert to autoplist
- convert to autoplist
- limit python version to 2.x

===>  Configuring for pygts-0.3.1_5
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 60
    raise RuntimeError, result[0]
                      ^
SyntaxError: invalid syntax
*** Error code 1