devel/indi: Mark BROKEN on FreeBSD 11
FAILED: CMakeFiles/indi_getprop.dir/libs/indicom.c.o
/usr/local/libexec/ccache/cc -DGIT_TAG_STRING=\"1.9.0-tgz\" -DWITH_ENCLEN -I. -I/wrkdirs/usr/ports/devel/indi/work/indi-1.9.0 -I/wrkdirs/usr/ports/devel/indi/work/indi-1.9.0/libs -I/wrkdirs/usr/ports/devel/indi/work/indi-1.9.0/libs/indibase -I/wrkdirs/usr/ports/devel/indi/work/indi-1.9.0/libs/indibase/property -I/wrkdirs/usr/ports/devel/indi/work/indi-1.9.0/libs/indibase/timer -I/wrkdirs/usr/ports/devel/indi/work/indi-1.9.0/libs/indibase/thread -I/usr/local/include -I/wrkdirs/usr/ports/devel/indi/work/indi-1.9.0/libs/dsp -I/wrkdirs/usr/ports/devel/indi/work/indi-1.9.0/libs/stream -I/usr/local/include/libnova -I/wrkdirs/usr/ports/devel/indi/work/indi-1.9.0/libs/webcam -O2 -pipe  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -std=gnu99 -D_FORTIFY_SOURCE=2 -fstack-protector-all -fPIE  -Wall -Wextra -gline-tables-only -Wno-unused-command-line-argument -O2 -pipe  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -fPIE -MD -MT CMakeFiles/indi_getprop.dir/libs/indicom.c.o -MF CMakeFiles/indi_getprop.dir/libs/indicom.c.o.d -o CMakeFiles/indi_getprop.dir/libs/indicom.c.o -c /wrkdirs/usr/ports/devel/indi/work/indi-1.9.0/libs/indicom.c
/wrkdirs/usr/ports/devel/indi/work/indi-1.9.0/libs/indicom.c:331:5: warning: implicit declaration of function 'timespec_get' is invalid in C99 [-Wimplicit-function-declaration]
    timespec_get(&ts, TIME_UTC);
    ^
/wrkdirs/usr/ports/devel/indi/work/indi-1.9.0/libs/indicom.c:331:23: error: use of undeclared identifier 'TIME_UTC'
    timespec_get(&ts, TIME_UTC);
                      ^
1 warning and 1 error generated.

Approved by:	portmgr (blanket)