devel/p5-IO-AIO: Fix build on FreeBSD 14+
In file included from AIO.xs:173:
In file included from /usr/include/sys/timerfd.h:33:
In file included from /usr/include/sys/proc.h:47:
/usr/include/sys/condvar.h:46:8: error: redefinition of 'cv'
struct cv {
       ^
/usr/local/lib/perl5/5.34/mach/CORE/sv.h:243:8: note: previous definition is here
struct cv {
       ^
618 warnings and 1 error generated.

Tested on:	14.0-ALPHA4

(cherry picked from commit 600ca97fd58482c907708888a7af879219540a79)