MFH: r423626
graphics/poppler: ignore installed NSS for now

$ make install -C security/nss
$ DEVELOPER=1 make -C graphics/poppler
[...]
====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/libpoppler.so.63.0.0 is linked to /usr/local/lib/nss/libnss3.so from security/nss but it is not declared as a dependency
Error: /usr/local/lib/libpoppler.so.63.0.0 is linked to /usr/local/lib/nss/libsmime3.so from security/nss but it is not declared as a dependency
Error: /usr/local/lib/libpoppler.so.63.0.0 is linked to /usr/local/lib/nss/libssl3.so from security/nss but it is not declared as a dependency
Error: /usr/local/lib/libpoppler.so.63.0.0 is linked to /usr/local/lib/nss/libnssutil3.so from security/nss but it is not declared as a dependency
Error: /usr/local/lib/libpoppler.so.63.0.0 is linked to /usr/local/lib/libplds4.so from devel/nspr but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libplds4.so:devel/nspr
Error: /usr/local/lib/libpoppler.so.63.0.0 is linked to /usr/local/lib/libplc4.so from devel/nspr but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libplc4.so:devel/nspr
Error: /usr/local/lib/libpoppler.so.63.0.0 is linked to /usr/local/lib/libnspr4.so from devel/nspr but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libnspr4.so:devel/nspr

Reported by:	Walter Schwarzenfeld (via r423591 regression)
Approved by:	portmgr blanket
Approved by:	ports-secteam blanket