www/typo3-10: Update to 10.4.16
- Use a small workarourd fix for:
---
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: @dir %%WWWDIR%%_src-10.4.16/vendor/symfony/string/Resources/bin
===> Checking for items in pkg-plist which are not in STAGEDIR
---
with
---
do-install: ${RMDIR} ${WRKSRC}/vendor/symfony/string/Resources/bin
---
to delete that empty directory.

ChangeLog: https://get.typo3.org/release-notes/10.4.16

PR:		255783
Approved by:	dbaio, garga (mentors, implicit)