emulators/yuzu: require gcc11+ after 50709831d2dd
In file included from src/./video_core/gpu_thread.h:13,
                 from src/video_core/gpu_thread.cpp:13:
src/./common/bounded_threadsafe_queue.h: In destructor 'Common::mpsc::Slot<T>::~Slot()':
src/./common/bounded_threadsafe_queue.h:34:18: error: 'struct std::atomic_flag' has no member named 'test'
   34 |         if (turn.test()) {
      |                  ^~~~
src/./common/bounded_threadsafe_queue.h: In instantiation of 'void Common::mpsc::Queue<T, Allocator>::Pop(T&, std::stop_token) [with T = VideoCommon::GPUThread::CommandDataContainer; Allocator = std::allocator<Common::mpsc::Slot<VideoCommon::GPUThread::CommandDataContainer> >]':
src/video_core/gpu_thread.cpp:35:41:   required from here
src/./common/bounded_threadsafe_queue.h:129:32: error: 'struct std::atomic_flag' has no member named 'test'
  129 |         if (false == slot.turn.test()) {
      |                      ~~~~~~~~~~^~~~
src/./common/bounded_threadsafe_queue.h:131:60: error: 'struct std::atomic_flag' has no member named 'test'
  131 |             cv.wait(lock, stop, [&slot] { return slot.turn.test(); });
      |                                                  ~~~~~~~~~~^~~~
src/./common/bounded_threadsafe_queue.h:136:19: error: 'struct std::atomic_flag' has no member named 'notify_one'
  136 |         slot.turn.notify_one();
      |         ~~~~~~~~~~^~~~~~~~~~
src/./common/bounded_threadsafe_queue.h: In instantiation of 'void Common::mpsc::Queue<T, Allocator>::emplace(Args&& ...) [with Args = {VideoCommon::GPUThread::CommandDataContainer}; T = VideoCommon::GPUThread::CommandDataContainer; Allocator = std::allocator<Common::mpsc::Slot<VideoCommon::GPUThread::CommandDataContainer> >]':
src/./common/bounded_threadsafe_queue.h:123:16:   required from 'void Common::mpsc::Queue<T, Allocator>::Push(P&&) [with P = VideoCommon::GPUThread::CommandDataContainer; <template-parameter-2-2> = void; T = VideoCommon::GPUThread::CommandDataContainer; Allocator = std::allocator<Common::mpsc::Slot<VideoCommon::GPUThread::CommandDataContainer> >]'
src/video_core/gpu_thread.cpp:122:81:   required from here
src/./common/bounded_threadsafe_queue.h:146:19: error: 'struct std::atomic_flag' has no member named 'wait'
  146 |         slot.turn.wait(true);
      |         ~~~~~~~~~~^~~~

Regressed by:	https://github.com/yuzu-emu/yuzu/commit/4dd6bcd20639