x11/kitty: unbreak build after aec9c6c9cf90
glfw/wl_window.c:522:17: error: enumeration value 'XDG_TOPLEVEL_STATE_SUSPENDED' not handled in switch [-Werror,-Wswitch]
        switch (*state) {
                ^

Reported by:	pkg-fallout
Inspired by:	Alpine Linux

(cherry picked from commit 4ee5c96d5b5dc6ebcab12f7f2af98915111282b5)