x11-toolkits/gtk40: enable GSTREAMER by default
Required for Gtk.MediaFile by video-trimmer and fractal >= 5 e.g.,

  $ video-trimmer foo.mp4
  (video-trimmer:12345): VideoTrimmer-WARNING **: src/video_preview.rs:142: Error in MediaFile: GTK could not find a media module. Check your installation.