www/qt6-webengine: Switch to bundled re2
* Prepare the port for newer versions of devel/re2, which also require
  devel/abseil.  This combination however causes build errors [1] due
  to missing symbols:

[...]
In file included from gen/extensions/browser/browser_sources_jumbo_8.cc:6:
./../../../../../qtwebengine-everywhere-src-6.5.2/src/3rdparty/chromium/extensions/browser/api/web_request/form_data_parser.cc:429:11: error: no member named 'set' in 'absl::string_view'
  source_.set(source.data(), source.size());
  ~~~~~~~ ^
./../../../../../qtwebengine-everywhere-src-6.5.2/src/3rdparty/chromium/extensions/browser/api/web_request/form_data_parser.cc:573:11: error: no member named 'set' in 'absl::string_view'
  source_.set(source.data(), source.size());
  ~~~~~~~ ^
[...]

  Unbundling abseil and its-subcomponents via "replace_gn_files.py" didn't
  help hence switch to the bundled re2 for now to have a consistent
  combination of re2 and abseil.

* Bump PORTREVISION due dependency change.

PR:		260402 [1]
Reported by:	diizzy [1]
Reviewed by:	diizzy, tcberner
Differential Revision:	https://reviews.freebsd.org/D41571