www/py-flask-login: update to 0.6.3 after f8bb06643e33
Required to fix the following:

>>> import flask_login
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/flask_login/__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "/usr/local/lib/python3.9/site-packages/flask_login/login_manager.py", line 33, in <module>
    from .utils import _create_identifier
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 14, in <module>
    from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)

Changes:	https://github.com/maxcountryman/flask-login/releases/tag/0.6.3
Approved by:	portmgr blanket