databases/mysql80-client: Fix stage-qa after 567557abbfc0a4deec492983ffc01da78c62bae4
====> Running Q/A tests (stage-qa)
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/mysql/private/libprotobuf-lite.so.3.19.4
Error: Orphaned: lib/mysql/private/libprotobuf.so.3.19.4
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/databases/mysql80-client
=>> Error: check-plist failures detected

Approved by:	portmgr (blanket)