sysutils/barrier: unbreak build on non-OpenSSL 3 systems (12 and 13)
Builds of barrier started failing on non-OpenSSL 3 systems after
commit 29ba81195ab384a6b4de7c953cb6ac8ca2fff557 with the following
error:

/wrkdirs/usr/ports/sysutils/barrier/work/barrier-2.4.0/src/lib/net/SecureUtils.cpp:163:25: error: use of undeclared identifier 'EVP_RSA_gen'
    auto* private_key = EVP_RSA_gen(2048);
                        ^
1 warning and 1 error generated.

Applying the patch in commit 29ba81195ab384a6b4de7c953cb6ac8ca2fff557
conditionally solves the issue.

Approved by:	portmgr (build fix blanket)