multimedia/gstreamer1-plugins-rust: respect GTK4=off if gtk4 is installed after 7f9937ae4015
====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/gstreamer-1.0/libgstgtk4.so is linked to /usr/local/lib/libgtk-4.so.1 from x11-toolkits/gtk40 but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libgtk-4.so:x11-toolkits/gtk40
Error: /usr/local/lib/gstreamer-1.0/libgstgtk4.so is linked to /usr/local/lib/libgraphene-1.0.so.0 from graphics/graphene but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libgraphene-1.0.so:graphics/graphene
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
===> No pkg-plist issues found (check-plist)