games/veloren-weekly: downgrade to s20250903
error[E0658]: `let` expressions in this position are unstable
   --> common/src/interaction.rs:212:16
    |
212 |               && let Some(CharacterState::Interact(crate::states::interact::Data {
    |  ________________^
213 | |                 static_data:
214 | |                     crate::states::interact::StaticData {
215 | |                         interact:
...   |
222 | |                 ..
223 | |             })) = character_states.get(interactor)
    | |__________________________________________________^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
    = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
   --> common/src/interaction.rs:254:12
    |
254 |           if let Some(character_state) = interactor
    |  ____________^
255 | |             .and_then(|interactor| character_states.get_mut(interactor))
256 | |             .as_deref_mut()
    | |___________________________^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
    = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
   --> common/src/interaction.rs:257:16
    |
257 |               && let CharacterState::Interact(crate::states::interact::Data {
    |  ________________^
258 | |                 static_data:
259 | |                     crate::states::interact::StaticData {
260 | |                         interact:
...   |
268 | |                 ..
269 | |             }) = *character_state
    | |_________________________________^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
    = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
   --> common/src/path.rs:618:12
    |
618 |         if let Some(end) = self.route.as_ref().map(|(_, _, end)| *end)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
    = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
   --> common/src/recipe.rs:993:12
    |
993 |           if let Some(item) = match item {
    |  ____________^
994 | |             Slot::Equip(slot) => inv.equipped(slot),
995 | |             Slot::Inventory(slot) => inv.get(slot),
...   |
998 | |         } && let Some(repair_recipe) = self.repair_recipe(item)
    | |_________^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
    = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
   --> common/src/recipe.rs:998:14
    |
998 |         } && let Some(repair_recipe) = self.repair_recipe(item)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
    = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
   --> common/src/slowjob.rs:187:16
    |
187 |             if let Some(c) = queued.get_mut(&n)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
    = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
   --> common/src/states/combo_melee2.rs:169:24
    |
169 |                     && let CharacterState::ComboMelee2(c) = &mut update.character
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
    = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
   --> common/src/states/utils.rs:650:37
    |
650 |     let (tilt_ori, efficiency) = if let Body::Ship(ship) = data.body
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
    = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
    --> common/src/states/utils.rs:1168:16
     |
1168 |             if let Some(sprite_interact) = sprite_interact
     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
     = help: add `#![feature(let_chains)]` to the crate attributes to enable
     = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
    --> common/src/states/utils.rs:1406:8
     |
1406 |     if let Some(ability_input) = input.into()
     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
     = help: add `#![feature(let_chains)]` to the crate attributes to enable
     = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
    --> common/src/states/utils.rs:1407:12
     |
1407 |           && let Some((ability, from_offhand, spec_ability)) = data
     |  ____________^
1408 | |             .active_abilities
1409 | |             .and_then(|a| {
1410 | |                 a.activate_ability(
...    |
1425 | |             })
1426 | |             .filter(|(ability, _, _)| ability.requirements_paid(data, update))
     | |______________________________________________________________________________^
     |
     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
     = help: add `#![feature(let_chains)]` to the crate attributes to enable
     = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
    --> common/src/states/utils.rs:1806:8
     |
1806 |     if let CharacterState::Roll(roll) = data.character
     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
     = help: add `#![feature(let_chains)]` to the crate attributes to enable
     = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
    --> common/src/states/utils.rs:1807:12
     |
1807 |         && let Some(dir) = roll.prev_aimed_dir
     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
     = help: add `#![feature(let_chains)]` to the crate attributes to enable
     = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
   --> common/src/terrain/chonk.rs:307:16
    |
307 |             if let Some((sub_chunk_min_z, ref mut inner)) = self.opt_inner
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
    = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

error[E0658]: `let` expressions in this position are unstable
   --> common/src/terrain/chonk.rs:308:20
    |
308 |                 && let Some(mut pos) = inner.next()
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
    = note: this compiler was built on 2025-05-09; consider upgrading it if it is out of date

For more information about this error, try `rustc --explain E0658`.
error: could not compile `veloren-common` (lib) due to 42 previous errors

Reported by:	pkg-fallout

(direct commit to 2025Q3 as 096f1677e033 is missing on the branch)
This reverts commit 1697689b55cb97ca665e86a23a920986ab5630da.