net-mgmt/aircrack-ng: further improve the port (+)
- Show in the configure summary if PCRE support had been disabled
- USES+=pkgconfig is required for successful configure regardless
  of the selected options, without it fail with ``configure.ac:62:
  error: possibly undefined macro: AC_SUBST''
- Allow to build against GNU crypt library, rather than OpenSSL,
  as a crypto engine