accessibility/wl-gammarelay-rs: back to 1.0.0
===>   Updating Cargo.lock
error: failed to parse manifest at `/wrkdirs/usr/ports/accessibility/wl-gammarelay-rs/work/wl-gammarelay-rs-1.0.1/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.83.0 (5ffbef321 2024-10-29)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
*** Error code 101

Reported by:	pkg-fallout

(direct commit to 2025Q1 as 0bd1fd4d884c is missing on the branch)
This reverts commit 47331ee3f3c22c5ca780b22a4e93492fd54ab245.