databases/firebird30-*: Fix consumers build
After firebird25-* was removed from the tree firebird30-* bacem the new
default. And some consumers of firebird started failing to build with
the error "/usr/local/include/ibase.h:6:10: fatal error:
'../jrd/ibase.h' file not found".

In previous the src headers files were installed which were not
sanitized and required other header files from the source tree. This
patch properly installs the sanitized header files and fixes the
consumer builds.

While I am here fix the patches to be makepatch compatible.

Approved by:	portmgr(just-fix-it)