MFH: r545108
multimedia/php-pHash: fix build on GCC architectures

x265 requires C++11 compiler:
/usr/local/lib/libx265.so.179: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'

Approved by:	portmgr (fix build blanket)