Update to 0.37
- Add LICENSE_FILE

This update fix a build error with FreeBSD 13:

/wrkdirs/usr/ports/www/mod_setenvifplus/work/mod_setenvifplus-0.22/apache2/mod_setenvifplus.c:179:18: error: variable has incomplete type 'EVP_CIPHER_CTX' (aka 'struct evp_cipher_ctx_st')
  EVP_CIPHER_CTX cipher_ctx;
                 ^
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of 'struct evp_cipher_ctx_st'
typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
               ^
/wrkdirs/usr/ports/www/mod_setenvifplus/work/mod_setenvifplus-0.22/apache2/mod_setenvifplus.c:227:18: error: variable has incomplete type 'EVP_CIPHER_CTX' (aka 'struct evp_cipher_ctx_st')
  EVP_CIPHER_CTX cipher_ctx;
                 ^
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of 'struct evp_cipher_ctx_st'
typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;

MFH:		2018Q4
Sponsored by:	Netzkommune GmbH