devel/physfs: Fix PLIST
- While I'm here, sort PLIST
- Bump PORTREVISION for package change

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/cmake/PhysFS/PhysFSConfig-%%CMAKE_BUILD_TYPE%%.cmake
Error: Orphaned: lib/cmake/PhysFS/PhysFSConfig.cmake
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Approved by:	portmgr (blanket)