graphics/libjxl: fails to build on powerpc64
third_party/highway/hwy/nanobenchmark.cc:50:10: fatal error: 'sys/platform/ppc.h' file not found
 #include <sys/platform/ppc.h>  // NOLINT __ppc_get_timebase_freq
          ^~~~~~~~~~~~~~~~~~~~

Reported by:	pkg-fallout

(cherry picked from commit c350bf15e24eb44eb5576db28322d78bee7ab23b)