x11-wm/enlightenment: fix build with GCC architectures
This port needs include sys/types.h in src/modules/sysinfo/cpuclock/cpuclock_sysctl.c:
/usr/include/sys/sysctl.h:1062: error: expected declaration specifiers or '...' before 'u_int'

It also needs USES=compiler:c11 because of pragma GCC diagnostic.

PR:		239407
Approved by:	enlightenment (maintainer timeout), linimon (mentor)
Differential Revision:	https://reviews.freebsd.org/D21399