multimedia/dav1d: unbreak TEST=on on FreeBSD < 13 after 17e9745faede
../tests/checkasm/checkasm.c:623:13: error: unknown type name 'cpu_set_t'; did you mean 'cpuset_t'?
            cpu_set_t set;
            ^~~~~~~~~
            cpuset_t
/usr/include/sys/_cpuset.h:50:24: note: 'cpuset_t' declared here
typedef struct _cpuset cpuset_t;
                       ^

PR:		270977
Reported by:	Ross McKelvie

(cherry picked from commit a50457696509832e70738d2afa9f68e11ab4e171)