www/py-django-recaptcha: Fix stage QA issues
* Fix poudriere bulk -t by partially restoring removed PKGNAMEPREFIX
  from fd2ba60b94f9:

[...]
====> Running Q/A tests (stage-qa)
Error: Package names are not unique with flavors:
py311: django-recaptcha-4.1.0
py312: django-recaptcha-4.1.0
py313: django-recaptcha-4.1.0
py313t: django-recaptcha-4.1.0
py314: django-recaptcha-4.1.0
py310: django-recaptcha-4.1.0
Error: maybe use <flavor>_PKGNAMEPREFIX/SUFFIX.
[...]

Approved by:	portmgr (build fix blanket)
Fixes:	fd2ba60b94f9 www/py-django-recaptcha: Update to 4.0.0