devel/intel-graphics-compiler: pacify stage-qa after 80eadab44ca1
Error: /usr/local/lib/libigc.so.1.0.1 is linked to /usr/local/llvm13/lib/libLLVM-13.so from devel/llvm13 but it is not declared as a dependency
(cherry picked from commit 913ccecf2a920e26fa891a2a92537c2c01fc92f5)