While working on the ports fallout due to the private Heimdal in base project, a port (www/squid-devel) was discovered to be grumpy due to numerous errors such as below:
/usr/local/include/krb5/krb5.h:3566:19: error: 'register' storage class
specifier is deprecated and incompatible with C++17
[-Werror,-Wdeprecated-register]
                  register char **name);
                  ^~~~~~~~~

The "register" keyword is meaningless and can cause grief among ports
that build against any of the krb5 ports.