emulators/yuzu: unbreak with sdl < 2.0.14 after c61770cb8015
src/input_common/sdl/sdl_impl.cpp:95:20: error: 'SDL_ControllerSensorEvent' has not been declared
   95 |     void SetMotion(SDL_ControllerSensorEvent event) {
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~
src/input_common/sdl/sdl_impl.cpp: In member function 'void InputCommon::SDL::SDLJoystick::EnableMotion()':
src/input_common/sdl/sdl_impl.cpp:79:17: error: 'SDL_GameControllerHasSensor' was not declared in this scope; did you mean 'SDL_GameControllerGetVendor'?
   79 |             if (SDL_GameControllerHasSensor(controller, SDL_SENSOR_ACCEL) && !has_accel) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 SDL_GameControllerGetVendor
src/input_common/sdl/sdl_impl.cpp:80:17: error: 'SDL_GameControllerSetSensorEnabled' was not declared in this scope; did you mean 'SDL_GameControllerGetVendor'?
   80 |                 SDL_GameControllerSetSensorEnabled(controller, SDL_SENSOR_ACCEL, SDL_TRUE);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 SDL_GameControllerGetVendor
src/input_common/sdl/sdl_impl.cpp:83:17: error: 'SDL_GameControllerHasSensor' was not declared in this scope; did you mean 'SDL_GameControllerGetVendor'?
   83 |             if (SDL_GameControllerHasSensor(controller, SDL_SENSOR_GYRO) && !has_gyro) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 SDL_GameControllerGetVendor
src/input_common/sdl/sdl_impl.cpp:84:17: error: 'SDL_GameControllerSetSensorEnabled' was not declared in this scope; did you mean 'SDL_GameControllerGetVendor'?
   84 |                 SDL_GameControllerSetSensorEnabled(controller, SDL_SENSOR_GYRO, SDL_TRUE);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 SDL_GameControllerGetVendor
src/input_common/sdl/sdl_impl.cpp: In member function 'void InputCommon::SDL::SDLJoystick::SetMotion(int)':
src/input_common/sdl/sdl_impl.cpp:98:37: error: request for member 'timestamp' in 'event', which is of non-class type 'int'
   98 |         u64 time_difference = event.timestamp - last_motion_update;
      |                                     ^~~~~~~~~
src/input_common/sdl/sdl_impl.cpp:99:36: error: request for member 'timestamp' in 'event', which is of non-class type 'int'
   99 |         last_motion_update = event.timestamp;
      |                                    ^~~~~~~~~
src/input_common/sdl/sdl_impl.cpp:100:23: error: request for member 'sensor' in 'event', which is of non-class type 'int'
  100 |         switch (event.sensor) {
      |                       ^~~~~~
src/input_common/sdl/sdl_impl.cpp:102:56: error: request for member 'data' in 'event', which is of non-class type 'int'
  102 |             const Common::Vec3f acceleration = {-event.data[0], event.data[2], -event.data[1]};
      |                                                        ^~~~
src/input_common/sdl/sdl_impl.cpp:102:71: error: request for member 'data' in 'event', which is of non-class type 'int'
  102 |             const Common::Vec3f acceleration = {-event.data[0], event.data[2], -event.data[1]};
      |                                                                       ^~~~
src/input_common/sdl/sdl_impl.cpp:102:87: error: request for member 'data' in 'event', which is of non-class type 'int'
  102 |             const Common::Vec3f acceleration = {-event.data[0], event.data[2], -event.data[1]};
      |                                                                                       ^~~~
src/input_common/sdl/sdl_impl.cpp:102:94: error: could not convert '{<expression error>, <expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'const Vec3f' {aka 'const Common::Vec3<float>'}
  102 |             const Common::Vec3f acceleration = {-event.data[0], event.data[2], -event.data[1]};
      |                                                                                              ^
      |                                                                                              |
      |                                                                                              <brace-enclosed initializer list>
src/input_common/sdl/sdl_impl.cpp:107:52: error: request for member 'data' in 'event', which is of non-class type 'int'
  107 |             const Common::Vec3f gyroscope = {event.data[0], -event.data[2], event.data[1]};
      |                                                    ^~~~
src/input_common/sdl/sdl_impl.cpp:107:68: error: request for member 'data' in 'event', which is of non-class type 'int'
  107 |             const Common::Vec3f gyroscope = {event.data[0], -event.data[2], event.data[1]};
      |                                                                    ^~~~
src/input_common/sdl/sdl_impl.cpp:107:83: error: request for member 'data' in 'event', which is of non-class type 'int'
  107 |             const Common::Vec3f gyroscope = {event.data[0], -event.data[2], event.data[1]};
      |                                                                                   ^~~~
src/input_common/sdl/sdl_impl.cpp:107:90: error: could not convert '{<expression error>, <expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'const Vec3f' {aka 'const Common::Vec3<float>'}
  107 |             const Common::Vec3f gyroscope = {event.data[0], -event.data[2], event.data[1]};
      |                                                                                          ^
      |                                                                                          |
      |                                                                                          <brace-enclosed initializer list>
src/input_common/sdl/sdl_impl.cpp: In member function 'void InputCommon::SDL::SDLState::HandleGameControllerEvent(const SDL_Event&)':
src/input_common/sdl/sdl_impl.cpp:355:10: error: 'SDL_CONTROLLERSENSORUPDATE' was not declared in this scope; did you mean 'SDL_CONTROLLERBUTTONUP'?
  355 |     case SDL_CONTROLLERSENSORUPDATE: {
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |          SDL_CONTROLLERBUTTONUP
src/input_common/sdl/sdl_impl.cpp:356:57: error: 'const SDL_Event' {aka 'const union SDL_Event'} has no member named 'csensor'; did you mean 'sensor'?
  356 |         if (auto joystick = GetSDLJoystickBySDLID(event.csensor.which)) {
      |                                                         ^~~~~~~
      |                                                         sensor
src/input_common/sdl/sdl_impl.cpp:357:39: error: 'const SDL_Event' {aka 'const union SDL_Event'} has no member named 'csensor'; did you mean 'sensor'?
  357 |             joystick->SetMotion(event.csensor);
      |                                       ^~~~~~~
      |                                       sensor
src/input_common/sdl/sdl_impl.cpp: In function 'Common::ParamPackage InputCommon::SDL::{anonymous}::SDLEventToMotionParamPackage(InputCommon::SDL::SDLState&, const SDL_Event&)':
src/input_common/sdl/sdl_impl.cpp:1008:10: error: 'SDL_CONTROLLERSENSORUPDATE' was not declared in this scope; did you mean 'SDL_CONTROLLERBUTTONUP'?
 1008 |     case SDL_CONTROLLERSENSORUPDATE: {
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |          SDL_CONTROLLERBUTTONUP
src/input_common/sdl/sdl_impl.cpp:1012:19: error: 'const SDL_Event' {aka 'const union SDL_Event'} has no member named 'csensor'; did you mean 'sensor'?
 1012 |         if (event.csensor.sensor == SDL_SENSOR_ACCEL) {
      |                   ^~~~~~~
      |                   sensor
src/input_common/sdl/sdl_impl.cpp:1013:56: error: 'const SDL_Event' {aka 'const union SDL_Event'} has no member named 'csensor'; did you mean 'sensor'?
 1013 |             const Common::Vec3f acceleration = {-event.csensor.data[0], event.csensor.data[2],
      |                                                        ^~~~~~~
      |                                                        sensor
src/input_common/sdl/sdl_impl.cpp:1013:79: error: 'const SDL_Event' {aka 'const union SDL_Event'} has no member named 'csensor'; did you mean 'sensor'?
 1013 |             const Common::Vec3f acceleration = {-event.csensor.data[0], event.csensor.data[2],
      |                                                                               ^~~~~~~
      |                                                                               sensor
src/input_common/sdl/sdl_impl.cpp:1014:56: error: 'const SDL_Event' {aka 'const union SDL_Event'} has no member named 'csensor'; did you mean 'sensor'?
 1014 |                                                 -event.csensor.data[1]};
      |                                                        ^~~~~~~
      |                                                        sensor
src/input_common/sdl/sdl_impl.cpp:1014:71: error: could not convert '{<expression error>, <expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'const Vec3f' {aka 'const Common::Vec3<float>'}
 1014 |                                                 -event.csensor.data[1]};
      |                                                                       ^
      |                                                                       |
      |                                                                       <brace-enclosed initializer list>
src/input_common/sdl/sdl_impl.cpp:1020:19: error: 'const SDL_Event' {aka 'const union SDL_Event'} has no member named 'csensor'; did you mean 'sensor'?
 1020 |         if (event.csensor.sensor == SDL_SENSOR_GYRO) {
      |                   ^~~~~~~
      |                   sensor
src/input_common/sdl/sdl_impl.cpp:1021:52: error: 'const SDL_Event' {aka 'const union SDL_Event'} has no member named 'csensor'; did you mean 'sensor'?
 1021 |             const Common::Vec3f gyroscope = {event.csensor.data[0], -event.csensor.data[2],
      |                                                    ^~~~~~~
      |                                                    sensor
src/input_common/sdl/sdl_impl.cpp:1021:76: error: 'const SDL_Event' {aka 'const union SDL_Event'} has no member named 'csensor'; did you mean 'sensor'?
 1021 |             const Common::Vec3f gyroscope = {event.csensor.data[0], -event.csensor.data[2],
      |                                                                            ^~~~~~~
      |                                                                            sensor
src/input_common/sdl/sdl_impl.cpp:1022:52: error: 'const SDL_Event' {aka 'const union SDL_Event'} has no member named 'csensor'; did you mean 'sensor'?
 1022 |                                              event.csensor.data[1]};
      |                                                    ^~~~~~~
      |                                                    sensor
src/input_common/sdl/sdl_impl.cpp:1022:67: error: could not convert '{<expression error>, <expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'const Vec3f' {aka 'const Common::Vec3<float>'}
 1022 |                                              event.csensor.data[1]};
      |                                                                   ^
      |                                                                   |
      |                                                                   <brace-enclosed initializer list>
src/input_common/sdl/sdl_impl.cpp:1032:69: error: 'const SDL_Event' {aka 'const union SDL_Event'} has no member named 'csensor'; did you mean 'sensor'?
 1032 |         if (const auto joystick = state.GetSDLJoystickBySDLID(event.csensor.which)) {
      |                                                                     ^~~~~~~
      |                                                                     sensor
src/input_common/sdl/sdl_impl.cpp: In member function 'std::optional<Common::ParamPackage> InputCommon::SDL::Polling::SDLMotionPoller::FromEvent(const SDL_Event&) const':
src/input_common/sdl/sdl_impl.cpp:1300:14: error: 'SDL_CONTROLLERSENSORUPDATE' was not declared in this scope; did you mean 'SDL_CONTROLLERBUTTONUP'?
 1300 |         case SDL_CONTROLLERSENSORUPDATE:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |              SDL_CONTROLLERBUTTONUP

Reported by:	pkg-fallout

(cherry picked from commit bd9872793c6e27cff9aef8891905ff8200f79986)