devel/git-cinnabar: update to 0.4.0.13 to unbreak with git 2.13
../cinnabar-helper.c:859:4: warning: implicit declaration of function 'sha1_array_append' is invalid
      in C99 [-Wimplicit-function-declaration]
                        sha1_array_append(array, sha1);
                        ^
../cinnabar-helper.c:866:20: error: variable has incomplete type 'struct sha1_array'
        struct sha1_array nodes = SHA1_ARRAY_INIT;
                          ^

Changes:	https://github.com/glandium/git-cinnabar/compare/cd0e1bb...a93db61
MFH:		2017Q2 (chasing r440558)