textproc/htmltolatex: fix build with GCC-based architectures
Add USES=compiler:c++11-lang.

Add include <cstring> and <strings.h> to CH2L.cpp.

Add include <cstring> to util.cpp.

Required to build with GCC (used on GCC architectures):
undefined reference to std::__cxx11::basic_string

PR:		237549
Approved by:	pi (maintainer), tcberner (mentor)
Differential Revision:	https://reviews.freebsd.org/D20050