graphics/aqsis: unbreak with boost 1.67
/usr/bin/ld: undefined reference to symbol `pthread_condattr_init@@FBSD_1.0' (try adding -lthr)

PR:		227427
Reported by:	antoine (via exp-run)
Regressed by:	https://github.com/boostorg/thread/commit/1e84b978b2bb