games/veloren-weekly: mark BROKEN on i386 after 76756d2f6d52
error[E0432]: unresolved import `wasmtime_asm_macros::asm_sym`
  --> cargo-crates/wasmtime-fiber-17.0.0/src/unix/x86.rs:13:37
   |
13 | use wasmtime_asm_macros::{asm_func, asm_sym};
   |                                     ^^^^^^^ no `asm_sym` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `wasmtime-fiber` (lib) due to previous error

Reported by:	pkg-fallout

(cherry picked from commit 0459a82c11ca55e1fe2bfc69d5165670bb7b2312)