Fix build with clang 3.8.0.
During a recent exp-run for bug 206074, it was found that x11-servers/x11rdp
gives errors with clang 3.8.0:

/wrkdirs/usr/ports/x11-servers/x11rdp/work/x11rdp_xorg71/build_dir/include/X11/Xtrans/Xtranssock.c:1027:50: error: reference to 'in6addr_any' is ambiguous
        ((struct sockaddr_in6 *)&sockname)->sin6_addr = in6addr_any;
                                                                ^

This is because Xtranssock.c attempts to redefine in6addr_any as a weak symbol,
which does not work with clang 3.8.0. As a fix, place the customized
in6addr_any definition between #ifdef __FreeBSD__ guards.

PR:		207192
Submitted by:	dim
Reviewed by:	Koichiro IWAO <meta+ports@vmeta.jp> (maintainer)