textproc/py-jq: update to v1.2.1
Adds Python 3.10 support (see [1]), else see the
Changelog:
https://github.com/mwilliamson/jq.py/blob/1.2.1/CHANGELOG.rst#changelog

Note that Python 3.10 cannot currently execute self-tests,
assistance solicited:

______ ERROR collecting tests/jq_old_tests.py _____
<frozen importlib._bootstrap>:939: in _find_spec
    ???
E   AttributeError: 'AssertionRewritingHook' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.10/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1002: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:941: in _find_spec
    ???
<frozen importlib._bootstrap>:915: in _find_spec_legacy
    ???
/usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:169: in find_module
    source_stat, co = _rewrite_test(self.config, fn_pypath)
/usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:406: in _rewrite_test
    co = compile(tree, fn.strpath, "exec", dont_inherit=True)
E   TypeError: required field "lineno" missing from alias
___________________________________________________

[1] https://github.com/mwilliamson/jq.py/commit/337c0f8baf77a59f9054eefc07460fffe91702ce