multimedia/ffmpeg4: unbreak GLSLANG=on build after d35ea7b74f4a
libavfilter/glslang.cpp:164:5: error: use of undeclared identifier 'assert'
    assert(glslang_refcount);
    ^

PR:		276469
Tested by:	vvd
Regressed by:	https://github.com/KhronosGroup/glslang/commit/6f9ab3c2deb6
See also:	https://github.com/ffmpeg/ffmpeg/commit/246f841b53e1