databases/cego: 2.33.12 -> 2.33.14
- Design modification in CegoAction for semantic action ( execXXX methods )
  An analysed statement is now just executed after complete succesful
  parsing of the given input. This avoid protocol effects for queries
  like "select * from t1;;" where the query is executed but the
  second semicolon is detected as an parse error which also is sent
  to the client.
  For this the new method CegoAction::execute has introduced which
  is ( explicitly ) called after successful CegoAction::parse
- Fix for distinct handling in CegoAggreation
  Fix for alias handling regarding view creates. Alias definitions
  are mandatory now for aggregated attribute definitions, e.g.
  create view v1 as select count(*) from t1;
  => returns now
  ERROR: Missing alias reference for view create
  and must be written as
  create view v1 as select count(*) as c from t1;

Submitted by:	Bjoern Lemke <lemke@lemke-it.com>