games/moonlight-qt: Build fails on i386: cannot initialize a member subobject of type 'VkSurfaceKHR' (aka 'unsigned long long') with an rvalue of type 'std::nullptr_t'
In file included from /wrkdirs/usr/ports/games/moonlight-qt/work/moonlight-qt-6.0.1/app/streaming/video/ffmpeg.cpp:48:
/wrkdirs/usr/ports/games/moonlight-qt/work/moonlight-qt-6.0.1/app/streaming/video/ffmpeg-renderers/plvk.h:57:32: error: cannot initialize a member subobject of type 'VkSurfaceKHR' (aka 'unsigned long long') with an rvalue of type 'std::nullptr_t'
   57 |     VkSurfaceKHR m_VkSurface = nullptr;
      |                                ^~~~~~~

Upstream bug-report:
https://github.com/moonlight-stream/moonlight-qt/issues/1367

PR:	280425
MFH:	2024Q3
(cherry picked from commit 54b259414cb8dc56bacff02399b3668bf1d03f9b)