lang/rust: Fix docs building.
Add the missing "pub struct sockcred2" in module "libc".
Error:
error[E0412]: cannot find type `sockcred2` in module `libc`
   --> library/std/src/os/unix/net/ancillary.rs:211:29
    |
211 | pub struct SocketCred(libc::sockcred2);
    |                             ^^^^^^^^^ not found in `libc`

Reported by:		kib
Differential Revision:	https://reviews.freebsd.org/D40509