java/openjdk8: fix build on 32 bit arm
Fixes:
In file included from /wrkdirs/usr/ports/java/openjdk8/work/jdk8u-jdk8u422-b05.1/hotspot/src/os/bsd/vm/os_perf_bsd.cpp:61:
In file included from /usr/include/sys/user.h:51:
In file included from /usr/include/vm/pmap.h:88:
In file included from /usr/include/machine/pmap.h:48:
In file included from /usr/include/sys/systm.h:46:
/usr/include/machine/cpufunc.h:184:1: error: static declaration of 'breakpoint' follows non-static declaration
  184 | breakpoint(void)
      | ^
/wrkdirs/usr/ports/java/openjdk8/work/jdk8u-jdk8u422-b05.1/hotspot/src/share/vm/utilities/globalDefinitions_gcc.hpp:224:17: note: previous declaration is here
  224 | extern "C" void breakpoint();
      |                 ^

- bumped portrevision to easily spot if future bug reports are about this change.

PR:	281991
Approved by:	early maintainer timeout java@ (the build is broken and the patch does not affect other architectures)
Obtained from:	Mikael Urankar <mikael@> via Attachment 254105 in bug #255662

(cherry picked from commit e13c81137266603a6a0700810b6bad419f9d98c8)