net-im/cawbird: unbreak build with Meson 1.4.0
libcawbird.a.p/src/list/TweetListEntry.c:1215:6: error: implicit declaration of function 'cb_tweet_has_quoted_inline_media' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (cb_tweet_has_quoted_inline_media (tweet)) {
            ^
libcawbird.a.p/src/TweetInfoPage.c:3374:20: error: implicit declaration of function 'cb_tweet_model_index_of_retweet' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                replied_to_idx = cb_tweet_model_index_of_retweet (_tmp3_, reply_id);
                                 ^

PR:		277354
Reported by:	antoine (via exp-run)
Regressed by:	https://github.com/mesonbuild/meson/commit/5f659af87001