net/xprobe: Fix build with Clang 16 and remove the workaround
random_shuffle has bee deprecated in C++14 and removed since C++17. Use shuffle instead.

target.cc:373:3: error: use of undeclared identifier 'random_shuffle'
                random_shuffle(ports.begin(), ports.end());
                ^
5 warnings and 1 error generated.

Tested on:	14.0-CURRENT (1400093)