x11/wayst: broken on armv7
In file included from src/gfx_gl2.c:3:
src/vt.h:278:1: error: requested alignment is less than minimum alignment of 8 for type 'VtCommand'
  278 | DEF_RC_PTR(VtCommand, VtCommand_destroy);
      | ^
src/rcptr.h:24:9: note: expanded from macro 'DEF_RC_PTR'
   24 |         alignas(alignof(void*)) t payload;                                                         \
      |         ^
/usr/include/stdalign.h:34:19: note: expanded from macro 'alignas'
   34 | #define alignas                 _Alignas
      |                                 ^

MFH:		2026Q1
See also:	https://github.com/91861/wayst/issues/120
Approved by:	portmgr (build fix blanket)

(cherry picked from commit 71e8bf055bf2be2092d87e2b9f688699cca89d3e)