audio/alsa-plugins: unbreak FFMPEG=on after 685e477b807c
checking for LIBAV... no
checking for avcodec_open in -lavcodec... no
[...]
configure:13617: checking for LIBAV
configure:13624: $PKG_CONFIG --exists --print-errors "libavcodec libavutil libavresample"
Package libavresample was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavresample.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libavresample', required by 'virtual:world', not found
configure:13627: $? = 1
[...]
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: etc/alsa/conf.d/10-rate-lav.conf
Error: Missing: etc/alsa/conf.d/60-a52-encoder.conf
Error: Missing: lib/alsa-lib/libasound_module_pcm_a52.la
Error: Missing: lib/alsa-lib/libasound_module_pcm_a52.so
Error: Missing: lib/alsa-lib/libasound_module_rate_lavrate.la
Error: Missing: lib/alsa-lib/libasound_module_rate_lavrate.so
Error: Missing: lib/alsa-lib/libasound_module_rate_lavrate_fast.so
Error: Missing: lib/alsa-lib/libasound_module_rate_lavrate_faster.so
Error: Missing: lib/alsa-lib/libasound_module_rate_lavrate_high.so
Error: Missing: lib/alsa-lib/libasound_module_rate_lavrate_higher.so
Error: Missing: share/alsa/alsa.conf.d/10-rate-lav.conf
Error: Missing: share/alsa/alsa.conf.d/60-a52-encoder.conf
===> Error: Plist issues found.
*** Error code 1

PR:		271641 272337
(cherry picked from commit df94027c843002a2abe044fa124eb5956a385932)