graphics/netpbm: Fix build with older netpbm versions installed
The build currently fails when older netpbm version are still
installed in the build environment e.g. when upgrading from 10.35.98
to 10.80.00 the build fails with

ppmtompeg.o: In function `main':
ppmtompeg.c:(.text+0x9a5): undefined reference to `pm_strfree'
ppmtompeg.o: In function `getUserFrameFile':
ppmtompeg.c:(.text+0xcb1): undefined reference to `pm_asprintf'
ppmtompeg.c:(.text+0xcfb): undefined reference to `pm_strfree'
ppmtompeg.c:(.text+0xd04): undefined reference to `pm_strfree'

- Use explicit paths when linking with libnetpbm
- Remove UPDATING entry that previously recommended deinstalling
  netpbm first when using portmaster/portupgrade

PR:		223724