x11-clocks/wlclock: unbreak long options
$ wlclock --corner-radius 90
ERROR: Radius configuration requires one or four arguments.

Reported by:	S. R. Gal (private mail)

(cherry picked from commit d28e388a9a1e09ad8181a37575ed35e681a426ce)