Mark BROKEN:
In file included from platform/freebsd/platform.c:19:
In file included from ./platform/freebsd/platform-freebsd.h:26:
/usr/include/sys/capability.h:43:2: error: this file includes <sys/capability.h> which is deprecated [-Werror,-W#warnings]
#warning this file includes <sys/capability.h> which is deprecated