www/qt5-webengine: Fix aarch64 build on CURRENT
../../../../kde-qtwebengine-5.15.18p2/src/3rdparty/chromium/third_party/crc32c/src/src/crc32c_arm64.cc:87:20:
error: always_inline function 'vmull_p64' requires target feature 'aes',
but would be inlined into function 'ExtendArm64' that is compiled
without support for 'aes'

Reported by:	pkg-fallout
Obtained from:	Chromium upstream (https://chromium-review.googlesource.com/c/chromium/src/+/4137218)
MFH:		2024Q4

(cherry picked from commit 41aaa32c1fd0d2c1b7e99f24de766c3b7819f816)