sysutils/bareos-server: unbreak build after devel/cli11 updated from 2.5.0 to 2.6.1 (+)
cli11 update have moved some definitions to new place.
Follow it by include new source.

/wrkdirs/usr/ports/sysutils/bareos-server/work/bareos-Release-24.0.5/core/src/tools/gentestdata.cc:34:24: error: no member named 'AsSizeValue' in namespace 'CLI'
   34 |       ->transform(CLI::AsSizeValue{k_is_1000})
      |                   ~~~~~^
1 error generated.

Reported by:	bulk -t
Approved by:	portmgr blanket (trivial build fix)