devel/py-terminaltexteffects: Update to 0.14.0
- Change the build dependency
- Add a patch to fix the following error:

*** Error compiling '/usr/local/poudriere/ports/default/devel/py-terminaltexteffects/work-py311/stage/usr/local/lib/python3.11/site-packages/terminaltexteffects/template/effect_template
.py'...
  File "/usr/local/lib/python3.11/site-packages/terminaltexteffects/template/effect_template.py", line 72
    "steps will create a smoother and longer gradient animation."
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: keyword argument repeated: action

*** Error compiling '/usr/local/poudriere/ports/default/devel/py-terminaltexteffects/work-py311/stage/usr/local/lib/python3.11/site-packages/terminaltexteffects/template/effect_template
.py'...
  File "/usr/local/lib/python3.11/site-packages/terminaltexteffects/template/effect_template.py", line 72
    "steps will create a smoother and longer gradient animation."
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: keyword argument repeated: action

Release changes:	https://github.com/ChrisBuilds/terminaltexteffects/releases/tag/release-0.14.0
Reported by:	ChrisBuilds <notifications@github.com>