devel/py-pipdeptree: Fix runtime
At runtime the program crashes due to an error like the following:
ImportError: cannot import name '__version__' from 'pipdeptree.version'

Which is caused due to the new template format of the setuptools_scm.
Currently this is just a dirty hack to support older(<7) setuptools_scm
format.

PR:		274101
Reported by:	vedran@miletic.net