emulators/yuzu: exclude on non-amd64 for now
In file included from src/common/wall_clock.cpp:7:
src/./common/uint128.h:16:10: fatal error: x86intrin.h: No such file or directory
   16 | #include <x86intrin.h>
      |          ^~~~~~~~~~~~~

Reported by:	pkg-fallout

(cherry picked from commit 51c03a9dbe214e813cffd342fa040b9c753fc756)