emulators/rpcs3: unbreak aarch64 build after a036b104b872
3rdparty/wolfssl/wolfssl/wolfcrypt/src/cpuid.c:262:28: error: use of undeclared identifier 'CPUID_AARCH64_FEAT_PMULL'
            if (features & CPUID_AARCH64_FEAT_PMULL)
                           ^

Reported by:	pkg-fallout

(cherry picked from commit 91e4d1cd95968d2db3e84d73592e8e71a73b077a)