misc/codex: Update to 0.160.1
While here:
- add "fast-build" target to reduce LTO link time
- add patches to re-enable cut/paste after it was somehow excluded
  upstream
- add patches to enable the daemon to avoid this warning at startup:
  Error: this CLI has no complete local package; install a packaged
  Codex CLI or use the standalone installer. To work without the
  background server, rerun the same command with
  --no-daemon (including resume or fork and its arguments).

Changelog:
- https://github.com/openai/codex/releases/tag/rust-v0.156.0
- https://github.com/openai/codex/releases/tag/rust-v0.156.1
- https://github.com/openai/codex/releases/tag/rust-v0.157.0
- https://github.com/openai/codex/releases/tag/rust-v0.157.1
- https://github.com/openai/codex/releases/tag/rust-v0.158.0
- https://github.com/openai/codex/releases/tag/rust-v0.159.0
- https://github.com/openai/codex/releases/tag/rust-v0.159.1
- https://github.com/openai/codex/releases/tag/rust-v0.159.2
- https://github.com/openai/codex/releases/tag/rust-v0.159.3
- https://github.com/openai/codex/releases/tag/rust-v0.160.0
- https://github.com/openai/codex/releases/tag/rust-v0.160.1

PR:		298989
Reported by:	Vedran Miletic <vedran@miletic.net>
Differential Revision:	https://reviews.freebsd.org/D60412
Co-authored-by:	Hiroki Tagato <tagattie@FreeBSD.org>