textproc/opensearch-dashboards: fix PLIST issue
Fixes the following warnings:
====> Running Q/A tests (stage-qa)
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: @dir %%WWWDIR%%/plugins/observabilityDashboards/server/adaptors/integrations/__test__
Error: Orphaned: @dir %%WWWDIR%%/plugins/observabilityDashboards/server/adaptors/integrations/repository/__test__
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Alerts/components/AlertFlyout
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/CreateDetector/components/ConfigureAlerts/components/AlertCondition
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/components/AlertTriggerView
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/components/DetectorBasicDetailsView
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/components/DetectorRulesView
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/components/FieldMappingsView
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/components/UpdateAlertConditions
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/components/UpdateDetectorBasicDetails
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/components/UpdateDetectorRules
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/components/UpdateFieldMappings
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/containers/AlertTriggersView
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/containers/DetectorDetails
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/containers/DetectorDetailsView
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/containers/Detectors
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Detectors/containers/EditFieldMappings
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Rules/components/DeleteModal
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Rules/components/RuleEditor/components
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityAnalyticsDashboards/test/mocks/Rules/components/RulesTable
Error: Orphaned: @dir %%WWWDIR%%/plugins/securityDashboards/server/multitenancy/test
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.