databases/ldb fix mtree build error due to tevent.pyc
Tested via tinderbox-4.0.x build

tevent builds without errors
ldb build fails with mtree error


    Fatal error: filesystem was touched prior to 'make install' phase
    usr/local/lib/python2.7/site-packages/tevent.pyc extra

During build, python imports tevent.py library, which generates and caches the tevent.pyc bytecode.

Setting environment variable to disable bytecode generation during compilation resolves this error.

Rebuilt tevent and ldb after this patch, both builds completed without errors.