multimedia/gstreamer1-plugins-rust: Fix build on i386
Ring assumes SSE and SSE2 are available on i386. This workaround assumes
the same, so the build will still fail on ancient hardware without these
instruction sets.

error[E0080]: evaluation of constant value failed
  --> /wrkdirs/usr/ports/multimedia/gstreamer1-plugins-rust/work/gst-plugins-rs-0.13.3/cargo-crates/ring-0.17.8/src/cpu/intel.rs:28:9
   |
28 |         assert!(cfg!(target_feature = "sse") && cfg!(target_feature = "sse2"));
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
the evaluated program panicked at 'assertion failed: cfg!(target_feature = "sse") && cfg!(target_feature = "sse2")',
/wrkdirs/usr/ports/multimedia/gstreamer1-plugins-rust/work/gst-plugins-rs-0.13.3/cargo-crates/ring-0.17.8/src/cpu/intel.rs:28:9

Reported by:	pkg-fallout