textproc/jade: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because textproc/jade's Makefile does not explicitly set its C++
standard, this leads to an error:

  Recognizer.cxx:40:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register const Trie *pos = trie_.pointer();
    ^~~~~~~~~

Add USE_CXXSTD=gnu++98 to compile for C++98 with GNU extensions instead.

PR:		271494
Approved by:	cy (maintainer)
MFH:		2023Q2