devel/ccls: fix build with LLVM_DEFAULT=19
When building against llvm 19, several errors appear:

  /wrkdirs/usr/ports/devel/ccls/work/ccls-0.20240202/src/include_complete.cc:117:37: error: no member named 'endswith' in 'llvm::StringRef'; did you mean 'ends_
    117 |                 if (StringRef(path).endswith(suffix))                                                                                                         |                                     ^~~~~~~~
        |                                     ends_with
  /wrkdirs/usr/ports/devel/ccls/work/ccls-0.20240202/src/clang_tu.cc:32:22: error: no member named 'startswith' in 'llvm::StringRef'; did you mean 'starts_with'
     32 |   if (file.getName().startswith("/../")) {
        |                      ^~~~~~~~~~                                                                                                                               |                      starts_with
  /wrkdirs/usr/ports/devel/ccls/work/ccls-0.20240202/src/clang_tu.cc:340:21: error: no member named 'OMPArraySection' in 'clang::BuiltinType'; did you mean 'Arr
    340 |   case BuiltinType::OMPArraySection:
        |        ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
        |                     ArraySection                                                                                                                        /wrkdirs/usr/ports/devel/ccls/work/ccls-0.20240202/src/indexer.cc:1130:64: error: non-virtual member function marked 'override' hides virtual member function
   1130 |                           SrcMgr::CharacteristicKind fileType) override {
        |                                                                ^

Pull in a number of upstream patches to fix these.

PR:		284422
Appproved by:	maintainer timeout (2 weeks)
MFH:		2025Q1

(cherry picked from commit 9025f32b1592396d53026ee4a4c00879499f860e)