graphics/mesa-devel: unbreak standalone build after 4c2cc95952a6
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: include/vulkan/vulkan_intel.h

PR:		255082
Reported by:	Evgeniy Khramtsov
Regressed by:	https://gitlab.freedesktop.org/mesa/mesa/-/commit/5e6db1916860