graphics/mesa-devel: unbreak standalone build after 85ef7d020401
$ echo DEFAULT_VERSIONS+=gl=mesa-devel >>/etc/make.conf
$ make restage check-plist
[...]
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: include/EGL/eglextchromium.h
===> Error: Plist issues found.
*** Error code 1

PR:		265784
Regressed by:	https://gitlab.freedesktop.org/mesa/mesa/-/commit/f5bb9dd738ac

(cherry picked from commit b9e8d13bc3549849f78e707cc1e09e2c93984e90)