devel/glib20: unbreak some C++ consumers after 27fe5eff9577
$ make -C lang/gjs
[...]
../util/log.cpp:106:25: error: no matching function for call to 'strcmp'
    if (debug_output && g_str_equal(debug_output, "stderr")) {
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/glib-2.0/glib/ghash.h:165:30: note: expanded from macro 'g_str_equal'
 #define g_str_equal(v1, v2) (strcmp ((gconstpointer) (v1), (gconstpointer) (v2)) == 0)
                              ^~~~~~
/usr/include/string.h:82:6: note: candidate function not viable: cannot convert argument of incomplete type 'gconstpointer' (aka 'const void *') to 'const char *' for 1st argument
int      strcmp(const char *, const char *) __pure;
         ^

Reported by:	fluffy, cmt
Regressed by:	https://gitlab.gnome.org/GNOME/glib/-/commit/b46ed37c972f