lang/guile2: define _WITH_CPU_SET_T to fix build on -CURRENT
Changes in 90fa9705d5cd hide functionality behind _WITH_CPU_SET_T,
    and require consumers to opt-in.

posix.c:2114:29: error: unknown type name 'cpu_set_t'; did you mean 'cpuset_t'?
cpu_set_to_bitvector (const cpu_set_t *cs)
                            ^~~~~~~~~
                            cpuset_t
/usr/include/sys/_cpuset.h:50:24: note: 'cpuset_t' declared here
typedef struct _cpuset cpuset_t;
                       ^
MFH after:	3 days