astro/kosmorro: Fix PLIST issue with py-poetry-core 2.0.0+
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%PYTHON_SITELIBDIR%%/CHANGELOG.md
===> Error: Plist issues found.
*** Error code 1

Approved by:	portmgr (blanket)
With hat:	python