www/qt6-webengine: unbreak build on aarch64 (+)
Backport Skia m103 changes to eliminate build error on arm64/aarch64:

In file included from ../../../../../qtwebengine-everywhere-src-6.4.2/src/3rdparty/chromium/third_party/skia/src/core/SkOpts.cpp:46:
../../../../../qtwebengine-everywhere-src-6.4.2/src/3rdparty/chromium/third_party/skia/src/opts/SkRasterPipeline_opts.h:1007:5: warning: 'memcpy' will always overflow; destination buffer has size 2, but
 size argument is 8 [-Wfortify-source]
    memcpy(&fp16, &h, sizeof(U16));
    ^
../../../../../qtwebengine-everywhere-src-6.4.2/src/3rdparty/chromium/third_party/skia/src/opts/SkRasterPipeline_opts.h:1032:19: error: functional-style cast from 'neon::F' (aka 'V<float>') to '__fp16'
is not allowed
    __fp16 fp16 = __fp16(f);
                  ^~~~~~~~
1 warning and 1 error generated.

Sponsored by:	Serenity Cybersecurity, LLC