emulators/yuzu: avoid gcc* dep via shlib_required after 4021ff7b85d9
Error: /usr/local/bin/yuzu is linked to /usr/local/lib/gcc11/libgcc_s.so.1 from lang/gcc11 but it is not declared as a dependency
(cherry picked from commit 64c2cc440f5882a61fc5a13f4f1d4a0216946698)