games/veloren-weekly: unbreak build after 288ed9fed935
error[E0658]: use of unstable library feature 'result_option_inspect'
   --> server/src/sys/terrain.rs:573:34
    |
573 | ...                   .inspect_err(|data| {
    |                        ^^^^^^^^^^^
    |
    = note: see issue #91345 <https://github.com/rust-lang/rust/issues/91345> for more information
    = help: add `#![feature(result_option_inspect)]` to the crate attributes to enable

Reported by:	pkg-fallout
(direct commit to 2024Q1 as 2252f9df9da7 is missing on the branch)