x11-wm/hyprland: track libdrm dependency after ca9b785803a6
Error: /usr/local/bin/Hyprland is linked to /usr/local/lib/libdrm.so.2 from graphics/libdrm but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libdrm.so:graphics/libdrm

https://github.com/hyprwm/Hyprland/commit/6f733292bf2d
(cherry picked from commit cbb86eb9e89b2cc0cba4835bf60a78de9ef7e709)