www/gitlab-ce: fix dependency problem
Starting gitlab fails with error:
rake aborted!
NoMethodError: undefined method `active_record_options' for #<Doorkeeper::Config:0x000000081fb0f0c8 @orm=:active_record, @default_generator_method=:hex, @authenticate_resource_owner=#<Proc:0x000000081fb0ed80 /usr/local/www/gitlab-ce/config/initializers/doorkeeper.rb:13>, @resource_owner_from_credentials=#<Proc:0x000000081fb0ec68 /usr/local/www/gitlab-ce/config/initializers/doorkeeper.rb:25>, @refresh_token_enabled=true, @enforce_configured_scopes=true, @force_ssl_in_redirect_uri=false, @forbid_redirect_uri=#<Proc:0x000000081fb0ea10 /usr/local/www/gitlab-ce/config/initializers/doorkeeper.rb:67>, @enable_application_owner=true, @default_scopes=#<Doorkeeper::OAuth::Scopes:0x000000081fb17e30 @scopes=["api"]>, @optional_scopes=#<Doorkeeper::OAuth::Scopes:0x000000081fb177f0 @scopes=["read_api", "read_user", "read_repository", "write_repository", "sudo", "openid", "profile", "email"]>, @access_token_methods=[:from_access_token_param, :from_bearer_authorization, :from_bearer_param], @token_secret_strategy=Gitlab::DoorkeeperSecretStoring::Token::Pbkdf2Sha512, @token_secret_fallback_strategy=Doorkeeper::SecretStoring::Plain, @application_secret_strategy=Gitlab::DoorkeeperSecretStoring::Secret::Pbkdf2Sha512, @application_secret_fallback_strategy=Doorkeeper::SecretStoring::Plain, @grant_flows=["authorization_code", "password", "client_credentials"], @skip_authorization=#<Proc:0x000000081fb1ce58 /usr/local/www/gitlab-ce/config/initializers/doorkeeper.rb:109>, @base_controller="::Gitlab::BaseDoorkeeperController", @skip_client_authentication_for_password_grant=true, @application_model=Doorkeeper::Application(id: integer, name: string, uid: string, secret: string, redirect_uri: text, scopes: string, created_at: datetime, updated_at: datetime, owner_id: integer, owner_type: string, trusted: boolean, confidential: boolean, expire_access_tokens: boolean), @access_grant_model=Doorkeeper::AccessGrant(id: integer, resource_owner_id: integer, application_id: integer, token: string, expires_in: integer, redirect_uri: text, created_at: datetime, revoked_at: datetime, scopes: string, code_challenge: text, code_challenge_method: text), @access_token_model=Doorkeeper::AccessToken(id: integer, resource_owner_id: integer, application_id: integer, token: string, refresh_token: string, expires_in: integer, revoked_at: datetime, created_at: datetime, scopes: string)>

          if Doorkeeper.configuration.active_record_options[:establish_connection]
                                     ^^^^^^^^^^^^^^^^^^^^^^
/usr/local/www/gitlab-ce/config/environment.rb:7:in `<top (required)>'

This is caused by a breaking change in doorkeeper 5.6.3, so fix on version 5.6.2 for now.
https://github.com/doorkeeper-gem/doorkeeper/blob/main/CHANGELOG.md

An upgrade of doorkeeper-openid_connect to 1.8.5 is not possible, as this brings
another breaking dependency shift from json-jwt to jwt, which causes again other
dependecy breaks.

Downgrading doorkeeper is for now the best solution.