- Mark BROKEN, fails to install
===>  Checking if sysutils/rubygem-chef-solr already installed
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: chef-solr requires chef (= 10.24.0)
*** [do-install] Error code 1