textproc/py-python-pptx: Update to 0.6.22
ChangeLog: https://github.com/scanny/python-pptx/blob/v0.6.22/HISTORY.rst

* Add imgW, imgH params to shapes.add_ole_object()
* fix: _Relationships.items() raises
* fix: quote in autoshape name must be escaped
* fix: update Python 3.x support in docs
* fix: setup's license should be short string
* fix: AttributeError: module 'collections' has no attribute 'abc'
       (Windows Python 3.10+)

PR:		273603