devel/arduino-bsd-mk: Update to 2.0
Changes since 1.5:

 - Add support for Arduino 1.0 through 1.8 by autodetecting paths.

 - Add -fno-threadsafe-statics to fix "undefined reference to
   `__cxa_guard_release'" error that can occur because gcc enables
   thread-safe initialization by default.

Honor PREFIX in Python script and require 3.6+ due to its use of
f-strings.