devel/fpc-fcl-db: unbreak after e40d870fc3cb
$ make check-plist
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: /you/have/to/check/what/makeplist/gives/you
===> Error: Plist issues found.
*** Error code 1