multimedia/libva: unbreak X11=off build after 07b46bb45fbe
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: include/va/va_trace.h
===> Error: Plist issues found.
*** Error code 1

PR:		277690