textproc/hs-pandoc: fix build on powerpc64le
powerpc64le is also 64-bit. Otherwise:
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] trying: tasty-1.5.3 (user goal)
[__1] unknown package: unbounded-delays (dependency of tasty)
[__1] fail (backjumping, conflict set: tasty, unbounded-delays)