databases/mysql80-server: fix build with clang/libc++ 17
Building databases/mysql80-server with clang and libc++ 17 results in
the following errors:

  In file included from /wrkdirs/usr/ports/databases/mysql80-server/work/mysql-8.0.33/sql/auth/sql_authorization.cc:23:
  In file included from /wrkdirs/usr/ports/databases/mysql80-server/work/mysql-8.0.33/sql/auth/sql_authorization.h:26:
  In file included from /usr/include/c++/v1/functional:515:
  In file included from /usr/include/c++/v1/__algorithm/search.h:23:
  /usr/include/c++/v1/__utility/pair.h:613:22: error: invalid operands to binary expression ('const Auth_id' and 'const MYSQL_LEX_CSTRING')
    613 |     return __x.first == __y.first && __x.second == __y.second;
        |            ~~~~~~~~~ ^  ~~~~~~~~~
  /usr/include/c++/v1/__algorithm/find.h:34:41: note: in instantiation of function template specialization 'std::__1::operator==<const Auth_id, Auth_id, MYSQL_LEX_CSTRING, MYSQL_LEX_CSTRING>' requested here
     34 |     if (std::__invoke(__proj, *__first) == __value)
        |                                         ^
  /usr/include/c++/v1/__algorithm/find.h:72:21: note: in instantiation of function template specialization 'std::__find_impl<std::__hash_map_iterator<std::__hash_iterator<std::__hash_node<std::__hash_value_type<Auth_id, Auth_id>, void *> *>>, std::__hash_map_iterator<std::__hash_iterator<std::__hash_node<std::__hash_value_type<Auth_id, Auth_id>, void *> *>>, std::pair<MYSQL_LEX_CSTRING, MYSQL_LEX_CSTRING>, std::__identity>' requested here
     72 |       __first, std::__find_impl(std::__unwrap_iter(__first), std::__unwrap_iter(__last), __value, __proj));
        |                     ^
  /wrkdirs/usr/ports/databases/mysql80-server/work/mysql-8.0.33/sql/auth/sql_authorization.cc:6591:11: note: in instantiation of function template specialization 'std::find<std::__hash_map_iterator<std::__hash_iterator<std::__hash_node<std::__hash_value_type<Auth_id, Auth_id>, void *> *>>, std::pair<MYSQL_LEX_CSTRING, MYSQL_LEX_CSTRING>>' requested here
   6591 |       if (find(role_it, role_end, *it) == role_end) {
        |           ^
  [... long list of candidates elided ...]

This is because an equality operator for Role_id and LEX_CSTRING is
missing. Add such an operator to work around the problem.

PR:		274464
Approved by:	joneum (maintainer)
MFH:		2023Q4