japanese/scim-anthy: Fix build with Clang 6
/usr/local/include/scim-1.0/scim_types.h:38:11: warning: '__STDC_ISO_10646__' macro redefined [-Wmacro-redefined]
#  define __STDC_ISO_10646__
          ^
<command line>:6:9: note: previous definition is here
#define __STDC_ISO_10646__ 1
        ^
scim_anthy_prefs.cpp:98:9: error: cannot initialize a member subobject of type 'void *' with an rvalue of type 'bool'
        false,
        ^~~~~

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p478276_s338342/logs/errors/ja-scim-anthy-1.2.7_5.log

- scim-anthy finds dependencies in LOCALBASE on its own
- __STDC_ISO_10646__ no longer needs to be specified manually
- Add license while here