graphics/xwpick: Fix LLVM15 build
Fix the following error:

ImgToolKit.c:272:10: error: incompatible pointer to integer conversion assigning to 'Atom' (aka 'unsigned long') from 'void *' [-Wint-conversion]
    type = NULL;
         ^ ~~~~

While at it assume maintainership of this unmaintained port.

(cherry picked from commit 53c230b247d1f52f4793c9bdb969303a49ad39ba)