multimedia/mythtv: unbreak with dav1d 1.0.0
libavcodec/libdav1d.c:135:7: error: no member named 'n_tile_threads' in 'struct Dav1dSettings'
    s.n_tile_threads = dav1d->tile_threads
    ~ ^
libavcodec/libdav1d.c:138:7: error: no member named 'n_frame_threads' in 'struct Dav1dSettings'
    s.n_frame_threads = dav1d->frame_threads
    ~ ^

(cherry picked from commit 3efc49fffd5ace5b83292d1037b4f3fc03164815)