emulators/rpcs3: unbreak build after d458041ef5aa
Utilities/rXml.cpp:56:47: error: no matching member function for call to 'attribute'
                if (const pugi::xml_attribute attr = handle.attribute(name))
                                                     ~~~~~~~^~~~~~~~~
/usr/local/include/pugixml.hpp:546:17: note: candidate function not viable: no known conversion from 'std::string_view' (aka 'basic_string_view<char>') to 'const char_t *' (aka 'const char *') for 1st argument
                xml_attribute attribute(const char_t* name) const;
                              ^
/usr/local/include/pugixml.hpp:551:17: note: candidate function not viable: requires 2 arguments, but 1 was provided
                xml_attribute attribute(const char_t* name, xml_attribute& hint) const;
                              ^

Reported by:	pkg-fallout
(direct commit to 2025Q1 as bbc08dcb46a3 is missing on the branch)