emulators/citra: mark BROKEN on aarch64 after 2627d61105ad
externals/cryptopp/cryptopp/crc_simd.cpp:100:13: error: use of undeclared identifier '__crc32w'
        w = __crc32w(w,x);
            ^
externals/cryptopp/cryptopp/crc_simd.cpp:101:13: error: use of undeclared identifier '__crc32h'
        w = __crc32h(w,y);
            ^
externals/cryptopp/cryptopp/crc_simd.cpp:102:13: error: use of undeclared identifier '__crc32b'
        w = __crc32b(w,z);
            ^
externals/cryptopp/cryptopp/crc_simd.cpp:103:13: error: use of undeclared identifier '__crc32cw'
        w = __crc32cw(w,x);
            ^
externals/cryptopp/cryptopp/crc_simd.cpp:104:13: error: use of undeclared identifier '__crc32ch'
        w = __crc32ch(w,y);
            ^
externals/cryptopp/cryptopp/crc_simd.cpp:105:13: error: use of undeclared identifier '__crc32cb'
        w = __crc32cb(w,z);
            ^
externals/cryptopp/cryptopp/crc_simd.cpp:125:13: error: use of undeclared identifier '__crc32b'
        c = __crc32b(c, *s);
            ^
externals/cryptopp/cryptopp/crc_simd.cpp:128:13: error: use of undeclared identifier '__crc32w'
        c = __crc32w(c, *(const word32 *)(void*)s);
            ^
externals/cryptopp/cryptopp/crc_simd.cpp:131:13: error: use of undeclared identifier '__crc32b'
        c = __crc32b(c, *s);
            ^
externals/cryptopp/cryptopp/crc_simd.cpp:137:13: error: use of undeclared identifier '__crc32cb'
        c = __crc32cb(c, *s);
            ^
externals/cryptopp/cryptopp/crc_simd.cpp:140:13: error: use of undeclared identifier '__crc32cw'
        c = __crc32cw(c, *(const word32 *)(void*)s);
            ^
externals/cryptopp/cryptopp/crc_simd.cpp:143:13: error: use of undeclared identifier '__crc32cb'
        c = __crc32cb(c, *s);
            ^

Reported by:	pkg-fallout

(cherry picked from commit fafe77a7d7039a1096c5aa49fa2d1d2a8863b812)