x11/xkeywrap: Work around LLVM15 build errors
Work around the following errors, for now:

cc -c xkeywrap.c -I/usr/local/include  -O2 -pipe -pipe  -fstack-protector-strong -fno-strict-aliasing  -pipe  -DVERSION=\"XKeyWrap-1.1\"
xkeywrap.c:45:15: error: incompatible pointer to integer conversion initializing 'Cursor' (aka 'unsigned long') with an expression of type 'void *' [-Wint-conversion]
static Cursor select_cursor = NULL;      /* <BD><D0><CE><CF><C0>襦<A5><A4><A5><F3><A5>ɥ<A6><BB><D8><C4><EA><BB><FE><A4>Υ<AB><A1><BC><A5><BD><A5><EB> */
              ^               ~~~~
xkeywrap.c:422:31: warning: passing 'int *' to parameter of type 'unsigned int *' converts between pointers to integer types with different sign [-Wpointer-sign]
             &r, &p, &children_list, &children_number);
                                     ^~~~~~~~~~~~~~~~
/usr/local/include/X11/Xlib.h:3034:1: note: passing argument to parameter here
);
^
1 warning and 1 error generated.
*** [xkeywrap.o] Error code 1

make[2]: stopped in /export/wrkdir/amd64/export/freebsd/git/ports/x11/xkeywrap/work/xkeywrap-1.1
--- xkeywrap.1.gz ---
gzip -f xkeywrap.1
1 error

make[2]: stopped in /export/wrkdir/amd64/export/freebsd/git/ports/x11/xkeywrap/work/xkeywrap-1.1
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make[1]: stopped in /export/freebsd/git/ports/x11/xkeywrap
*** Error code 1

Stop.
make: stopped in /export/freebsd/git/ports/x11/xkeywrap

While at it, assume maintainership.

(cherry picked from commit 02e6b7b0d4c4f475af607cc07e3fa6b1b62af44c)