www/qt5-webengine: switch to using bundled re2
See 9d23691afbbc151dbc63933dc8ea370afc391eed for a similar change in
www/qt6-webengine.

Using system re2 leads to compile failures with:

[...]
../../../../qtwebengine-everywhere-src-5.15.8/src/3rdparty/chromium/gpu/command_buffer/service/program_manager.cc:627:25: error: no member named 'as_string' in 'absl::string_view'
  return output + input.as_string();
                  ~~~~~ ^
[...]

* PORTREVISION intentionally was not bumped.