science/mmdb2: fix build with libc++ 21
With libc++ 21 science/mmdb2 fails to build, with errors similar to:

    In file included from mmdb2/mmdb_machine_.cpp:41:
    mmdb2/mmdb_machine_.h:296:13: error: unknown type name 'size_t'; did you mean 'std::size_t'?
      296 |     typedef size_t fpstr_size_t;
          |             ^~~~~~
          |             std::size_t
    /usr/include/c++/v1/__cstddef/size_t.h:20:7: note: 'std::size_t' declared here
       20 | using size_t = decltype(sizeof(int));
          |       ^

This is because mmdb2 apparently relies on transitive includes getting
the declaration of size_t, but with libc++ 21 this no longer works. Add
an include of <stddef.h> to work around it.

PR:		293180
Approved by:	maintainer timeout (2 weeks)
MFH:		2026Q1