devel/fccf: fix build on non-x86
immintrin.h is only used on amd64 and i386.

In file included from /wrkdirs/usr/ports/devel/fccf/work/fccf-0.6.0/source/sse2_strstr.cpp:5:
In file included from /usr/lib/clang/13.0.0/include/immintrin.h:17:
/usr/lib/clang/13.0.0/include/mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^