www/mediawiki130: Add missing PHP module dependency
When upgrading from MediaWiki 1.29:

Error: Missing one or more required components of PHP.
You are missing a required extension to PHP that MediaWiki needs.
Please install:
 * fileinfo <https://secure.php.net/fileinfo>

MFH:		2018Q1