sysutils/yazi: Update to 26.8.15
- Define the environment variable VERGEN_GIT_SHA, otherwise the build stage
  fails with error:

error: environment variable `VERGEN_GIT_SHA` not defined at compile time
 --> yazi-version/src/lib.rs:3:76
  |
3 | pub fn version() -> &'static str { concat!(env!("CARGO_PKG_VERSION"), " ", env!("VERGEN_GIT_SHA")) }
  |                                                                            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: use `std::env::var("VERGEN_GIT_SHA")` to read the variable at run time

error: environment variable `VERGEN_GIT_SHA` not defined at compile time
 --> yazi-version/src/lib.rs:9:3
  |
9 |         env!("VERGEN_GIT_SHA"),
  |         ^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: use `std::env::var("VERGEN_GIT_SHA")` to read the variable at run time

warning: yazi-version@26.8.15: not within a suitable 'git' worktree!
warning: yazi-version@26.8.15: Unable to set VERGEN_GIT_SHA
error: could not compile `yazi-version` (lib) due to 2 previous errors

ChangeLog:	https://github.com/sxyazi/yazi/blob/main/CHANGELOG.md#v26815
Reported by:	"github-actions[bot]" <notifications@github.com>