www/dillo2: Fix llvm 19 build
Fix error with llvm 19 compile:

./misc.hh:384:13: error: no member named 'arrayExtra' in 'NotSoSimpleVector<T>'
  384 |       this->arrayExtra = NULL;
      |       ~~~~  ^

(cherry picked from commit cd19f8511637fb6cdc5f077cccd496fe07fb7aa3)