www/qt6-webengine: fix build with clang 18
Clang 18 has become more stringent about narrowing in initializer lists,
resulting in errors when building www/qt6-webengine:

  ../../../../../qtwebengine-everywhere-src-6.6.1/src/3rdparty/chromium/third_party/webrtc/pc/legacy_stats_collector.cc:192:54: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing-const-reference]
    192 |       {StatsReport::kStatsValueNameTotalAudioEnergy, info.total_output_energy},
        |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~
  ../../../../../qtwebengine-everywhere-src-6.6.1/src/3rdparty/chromium/third_party/webrtc/pc/legacy_stats_collector.cc:194:8: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing-const-reference]
    194 |        info.total_output_duration}};
        |        ^~~~~~~~~~~~~~~~~~~~~~~~~~

Cherry-pick https://webrtc.googlesource.com/src/+/267f9bdd53 into the
thirdparty directory, which fixes these errors.

PR:		276997
MFH:		2024Q1
(cherry picked from commit 0707093c0a5df15911d72c3b2e8001b3428f2e2e)