MFH: r404012
www/firefox: bump required harfbuzz version

  In file included from gfx/thebes/Unified_cpp_gfx_thebes1.cpp:11:
  gfx/thebes/gfxHarfBuzzShaper.cpp:1571:41: error: use of
    undeclared identifier 'HB_BUFFER_CLUSTER_LEVEL_MONOTONE_CHARACTERS'
    hb_buffer_set_cluster_level(buffer, HB_BUFFER_CLUSTER_LEVEL_MONOTONE_CHARACTERS);
    ^
Reported by:	graemeg on forums.freebsd.org
Approved by:	ports-secteam (feld)