textproc/py-enrich: remove non-functional test code
PyPI tarballs do not contain any of the test code.  Attempting to
build against code from GitHub results in:

  LookupError: setuptools-scm was unable to detect version for ...

since the GitHub tarballs are missing some other important metadata.