games/jumpy: mark BROKEN with unsigned char after ead5b0f5fcd7
error[E0308]: mismatched types
   --> cargo-crates/netdev-0.25.0/src/bpf/unix.rs:122:29
    |
122 |         iface.ifr_name[i] = c as i8;
    |         -----------------   ^^^^^^^ expected `u8`, found `i8`
    |         |
    |         expected due to the type of this binding

error[E0308]: mismatched types
   --> cargo-crates/netdev-0.25.0/src/interface/unix.rs:167:28
    |
167 |             let nlen: i8 = (*sa).sa_data[3];
    |                       --   ^^^^^^^^^^^^^^^^ expected `i8`, found `u8`
    |                       |
    |                       expected due to this
    |
help: you can convert a `u8` to an `i8` and panic if the converted value doesn't fit
    |
167 |             let nlen: i8 = (*sa).sa_data[3].try_into().unwrap();
    |                                            ++++++++++++++++++++

error[E0308]: mismatched types
   --> cargo-crates/netdev-0.25.0/src/interface/unix.rs:168:28
    |
168 |             let alen: i8 = (*sa).sa_data[4];
    |                       --   ^^^^^^^^^^^^^^^^ expected `i8`, found `u8`
    |                       |
    |                       expected due to this
    |
help: you can convert a `u8` to an `i8` and panic if the converted value doesn't fit
    |
168 |             let alen: i8 = (*sa).sa_data[4].try_into().unwrap();
    |                                            ++++++++++++++++++++

For more information about this error, try `rustc --explain E0308`.

Reported by:	pkg-fallout

(cherry picked from commit ee340a5981cbffb4f0334c33e2495cba10322eb3)