sysutils/py-psutil: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
sysutils/py-psutil failed to build with clang 15:

  psutil/arch/freebsd/sys_socks.c:70:25: warning: comparison between pointer and integer ('kvaddr_t' (aka 'unsigned long long') and 'void *') [-Wpointer-integer-compare]
          if (xf->xf_data == sock)
              ~~~~~~~~~~~ ^  ~~~~
  psutil/arch/freebsd/sys_socks.c:182:40: error: incompatible integer to pointer conversion passing 'kvaddr_t' (aka 'unsigned long long') to parameter of type 'void *' [-Wint-conversion]
          xf = psutil_get_file_from_sock(so->xso_so);
                                         ^~~~~~~~~~
  psutil/arch/freebsd/sys_socks.c:65:33: note: passing argument to parameter 'sock' here
  psutil_get_file_from_sock(void *sock) {
                                  ^
  psutil/arch/freebsd/sys_socks.c:303:40: error: incompatible integer to pointer conversion passing 'kvaddr_t' (aka 'unsigned long long') to parameter of type 'void *' [-Wint-conversion]
          xf = psutil_get_file_from_sock(xup->xu_socket.xso_so);
                                         ^~~~~~~~~~~~~~~~~~~~~
  psutil/arch/freebsd/sys_socks.c:65:33: note: passing argument to parameter 'sock' here
  psutil_get_file_from_sock(void *sock) {
                                  ^
  1 warning and 2 errors generated.

This can be fixed by adjusting the psutil_get_file_from_sock() function
to take a kvaddr_t instead of a void pointer.

PR:		268233
Approved by:	portmgr (tcberner)
MFH:		2022Q4