multimedia/helvum: respect LLVM_DEFAULT
     Running `/usr/ports/multimedia/helvum/work/target/release/build/libspa-sys-c217eca9770760b4/build-script-build`
[...]
[libspa-sys 0.4.1] thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /usr/ports/multimedia/helvum/work/helvum-094681637ec8f9f2acdb993230e10da88aa3fedb/cargo-crates/bindgen-0.59.2/src/lib.rs:2144:31

Reported by:	DPorts

(cherry picked from commit 9f02596679c921cee05de43ceb858e08837b41f9)