graphics/mesa-devel: unbreak WITH_FORTIFY{,_PORTS} on FreeBSD >= 15
../src/gallium/auxiliary/vl/vl_csc.c:196:35: error: too many arguments provided to function-like macro invocation
  196 |             { 0.595254, 0.349314, 0.055432, 0.0 },
      |                                   ^
/usr/include/ssp/string.h:124:9: note: macro 'memcpy' defined here
  124 | #define memcpy(dst, src, len) __ssp_bos_check3(memcpy, dst, src, len)
      |         ^
../src/gallium/auxiliary/vl/vl_csc.c:195:10: note: parentheses are required around macro argument containing braced initializer list
  195 |          memcpy(matrix, &(vl_csc_matrix){
      |          ^
      |                         (
  196 |             { 0.595254, 0.349314, 0.055432, 0.0 },
  197 |             { 0.081244, 0.891503, 0.027253, 0.0 },
  198 |             { 0.015512, 0.081912, 0.902576, 0.0 },
  199 |          }, sizeof(vl_csc_matrix));
      |
      |           )
../src/gallium/auxiliary/vl/vl_csc.c:205:37: error: too many arguments provided to function-like macro invocation
  205 |             {  0.939543,  0.050181, 0.010276, 0.0 },
      |                                     ^
/usr/include/ssp/string.h:124:9: note: macro 'memcpy' defined here
  124 | #define memcpy(dst, src, len) __ssp_bos_check3(memcpy, dst, src, len)
      |         ^
../src/gallium/auxiliary/vl/vl_csc.c:204:10: note: parentheses are required around macro argument containing braced initializer list
  204 |          memcpy(matrix, &(vl_csc_matrix){
      |          ^
      |                         (
  205 |             {  0.939543,  0.050181, 0.010276, 0.0 },
  206 |             {  0.017772,  0.965793, 0.016435, 0.0 },
  207 |             { -0.001622, -0.004370, 1.005991, 0.0 },
  208 |          }, sizeof(vl_csc_matrix));
      |
      |           )
../src/gallium/auxiliary/vl/vl_csc.c:218:37: error: too many arguments provided to function-like macro invocation
  218 |             {  1.776133, -0.687820, -0.088313, 0.0 },
      |                                     ^
/usr/include/ssp/string.h:124:9: note: macro 'memcpy' defined here
  124 | #define memcpy(dst, src, len) __ssp_bos_check3(memcpy, dst, src, len)
      |         ^
../src/gallium/auxiliary/vl/vl_csc.c:217:10: note: parentheses are required around macro argument containing braced initializer list
  217 |          memcpy(matrix, &(vl_csc_matrix){
      |          ^
      |                         (
  218 |             {  1.776133, -0.687820, -0.088313, 0.0 },
  219 |             { -0.161375,  1.187315, -0.025940, 0.0 },
  220 |             { -0.015881, -0.095931,  1.111812, 0.0 },
  221 |          }, sizeof(vl_csc_matrix));
      |
      |           )
../src/gallium/auxiliary/vl/vl_csc.c:227:37: error: too many arguments provided to function-like macro invocation
  227 |             {  1.660491, -0.587641, -0.072850, 0.0 },
      |                                     ^
/usr/include/ssp/string.h:124:9: note: macro 'memcpy' defined here
  124 | #define memcpy(dst, src, len) __ssp_bos_check3(memcpy, dst, src, len)
      |         ^
../src/gallium/auxiliary/vl/vl_csc.c:226:10: note: parentheses are required around macro argument containing braced initializer list
  226 |          memcpy(matrix, &(vl_csc_matrix){
      |          ^
      |                         (
  227 |             {  1.660491, -0.587641, -0.072850, 0.0 },
  228 |             { -0.124550,  1.132900, -0.008349, 0.0 },
  229 |             { -0.018151, -0.100579,  1.118729, 0.0 },
  230 |          }, sizeof(vl_csc_matrix));
      |
      |           )
../src/gallium/auxiliary/vl/vl_csc.c:241:37: error: too many arguments provided to function-like macro invocation
  241 |             {  1.065379, -0.055401, -0.009978, 0.0 },
      |                                     ^
/usr/include/ssp/string.h:124:9: note: macro 'memcpy' defined here
  124 | #define memcpy(dst, src, len) __ssp_bos_check3(memcpy, dst, src, len)
      |         ^
../src/gallium/auxiliary/vl/vl_csc.c:240:10: note: parentheses are required around macro argument containing braced initializer list
  240 |          memcpy(matrix, &(vl_csc_matrix){
      |          ^
      |                         (
  241 |             {  1.065379, -0.055401, -0.009978, 0.0 },
  242 |             { -0.019633,  1.036363, -0.016731, 0.0 },
  243 |             {  0.001632,  0.004412,  0.993956, 0.0 },
  244 |          }, sizeof(vl_csc_matrix));
      |
      |           )
../src/gallium/auxiliary/vl/vl_csc.c:249:35: error: too many arguments provided to function-like macro invocation
  249 |             { 0.627404, 0.329283, 0.043313, 0.0 },
      |                                   ^
/usr/include/ssp/string.h:124:9: note: macro 'memcpy' defined here
  124 | #define memcpy(dst, src, len) __ssp_bos_check3(memcpy, dst, src, len)
      |         ^
../src/gallium/auxiliary/vl/vl_csc.c:248:10: note: parentheses are required around macro argument containing braced initializer list
  248 |          memcpy(matrix, &(vl_csc_matrix){
      |          ^
      |                         (
  249 |             { 0.627404, 0.329283, 0.043313, 0.0 },
  250 |             { 0.069097, 0.919540, 0.011362, 0.0 },
  251 |             { 0.016391, 0.088013, 0.895595, 0.0 },
  252 |          }, sizeof(vl_csc_matrix));
      |
      |           )
6 errors generated.

PR:		292394
(cherry picked from commit e0b3815503369be0a8b24fc1b9998ddf20e05382)