devel/py-pbr: Update to 1.6.0, Backport sphinx fix
- Update to 1.6.0
- Backport upstream fix [1] for sphinx 1.3+ causing the following error
  in ports that utilise pbr and that build documentation, like
  virtualenvwrapper (currently BROKEN):

  TypeError: init_values() takes exactly 2 arguments (1 given)

[1] https://review.openstack.org/#/c/193462/
[2] https://bugs.launchpad.net/oslotest/+bug/1379998