Update devel/libkolab to 0.6.3.
Note, that 0.6.3 is the last version for Qt4.
From 1.0.0 on libkolab uses Qt5 -- so we can't stop portscout from complaining :)

While here, make stage-qa happy.

> Error: /usr/local/lib/libkolab.so.0.6.3 is linked to /usr/local/lib/libxerces-c-3.1.so from textproc/xerces-c3 but it is not declared as a dependency
> Warning: you need LIB_DEPENDS+=libxerces-c-3.1.so:textproc/xerces-c3
> Error: /usr/local/lib/libkolab.so.0.6.3 is linked to /usr/local/lib/libboost_thread.so.1.55.0 from devel/boost-libs but it is not declared as a dependency
> Warning: you need LIB_DEPENDS+=libboost_thread.so:devel/boost-libs
> Error: /usr/local/lib/libkolab.so.0.6.3 is linked to /usr/local/lib/libboost_system.so.1.55.0 from devel/boost-libs but it is not declared as a dependency
> Warning: you need LIB_DEPENDS+=libboost_system.so:devel/boost-libs
> Error: /usr/local/lib/libkolab.so.0.6.3 is linked to /usr/local/lib/libboost_chrono.so.1.55.0 from devel/boost-libs but it is not declared as a dependency
> Warning: you need LIB_DEPENDS+=libboost_chrono.so:devel/boost-libs
> Error: /usr/local/lib/libkolab.so.0.6.3 is linked to /usr/local/lib/libboost_date_time.so.1.55.0 from devel/boost-libs but it is not declared as a dependency
> Warning: you need LIB_DEPENDS+=libboost_date_time.so:devel/boost-libs
> Error: /usr/local/lib/libkolab.so.0.6.3 is linked to /usr/local/lib/libboost_atomic.so.1.55.0 from devel/boost-libs but it is not declared as a dependency
> Warning: you need LIB_DEPENDS+=libboost_atomic.so:devel/boost-libs
> Error: /usr/local/lib/libkolab.so.0.6.3 is linked to /usr/local/lib/libcurl.so.4 from ftp/curl but it is not declared as a dependency
> Warning: you need LIB_DEPENDS+=libcurl.so:ftp/curl
> Error: /usr/local/lib/libkolab.so.0.6.3 is linked to /usr/local/lib/qt4/libQtNetwork.so.4 from net/qt4-network but it is not declared as a dependency
> Warning: you need USE_QT4+=network
> Error: /usr/local/lib/libkolab.so.0.6.3 is linked to /usr/local/lib/qt4/libQtDBus.so.4 from devel/dbus-qt4 but it is not declared as a dependency
> Warning: you need USE_QT4+=dbus
> Error: /usr/local/lib/libkolab.so.0.6.3 is linked to /usr/local/lib/qt4/libQtSvg.so.4 from graphics/qt4-svg but it is not declared as a dependency
> Warning: you need USE_QT4+=svg

Reviewed by:	rakuco
Approved by:	rakuco (mentor)
Differential Revision:	https://reviews.freebsd.org/D7856