graphics/osgearth: Fix build with protobuf 22+
Note that this port has a PLIST issue if libzip is installed.

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/osgPlugins-3.6.5/osgdb_zip.so
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1