graphics/libGLU: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because graphics/libGLU's Makefile does not explicitly set its C++ standard,
this leads to several errors:

  ../src/libnurbs/internals/varray.cc:76:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
      register long ds = sgn(arc->tail()[0] - arc->prev->tail()[0]);
      ^~~~~~~~~
  ../src/libnurbs/internals/varray.cc:77:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
      register long dt = sgn(arc->tail()[1] - arc->prev->tail()[1]);
      ^~~~~~~~~

Upstream already noticed this, and committed
https://gitlab.freedesktop.org/mesa/glu/-/commit/b6c308172993 as a fix,
so add this as an additional patch, until the next version is released.

PR:		271055
Approved by:	manu (maintainer)
MFH:		2023Q2