www/pecl-yar: Cosmetic change
Add more information about the breakage.
Mark IGNORE with PHP 8.2.0 beta 1+ (5da33bb9b44197233147df3ac9ffdc943ac3662b)

PHP 8.2.0 beta 1 introduces random extension [1] which break this port.

 cc -I. -I/wrkdirs/usr/ports/www/pecl-yar/work-php82/yar-2.3.2 -I/wrkdirs/usr/ports/www/pecl-yar/work-php82/yar-2.3.2/include -I/wrkdirs/usr/ports/www/pecl-yar/work-php82/yar-2.3.2/main -I/wrkdirs/usr/ports/www/pecl-yar/work-php82/yar-2.3.2 -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include -isystem /usr/local/include -DHAVE_CONFIG_H -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -D_GNU_SOURCE -DZEND_COMPILE_DL_EXT=1 -c /wrkdirs/usr/ports/www/pecl-yar/work-php82/yar-2.3.2/yar_response.c -MMD -MF yar_response.dep -MT yar_response.lo  -fPIC -DPIC -o .libs/yar_response.o
--- yar_request.lo ---
/wrkdirs/usr/ports/www/pecl-yar/work-php82/yar-2.3.2/yar_request.c:37:10: error: use of undeclared identifier 'mt_rand_is_seeded'
        if (!BG(mt_rand_is_seeded)) {
                ^
1 warning and 1 error generated.
*** [yar_request.lo] Error code 1

Reported by:	pkg-fallout
Reference:	http://beefy16.nyi.freebsd.org/data/130amd64-default/92e0e1e3191a/logs/php82-pecl-yar-2.3.2.log
Reference:	https://github.com/php/php-src/commit/4d8dd8d258ff365b146bcadcb277ede8992706d0 [1]