devel/z88dk: unbreak the build when MALLOC_PRODUCTION is unset
In debug mode, malloc() writes some junk to newly allocated memory to
help developers discover memory allocation bugs, which results in the
subtle compilation errors for this port:

  gmake --no-print-directory -C stdio
  zcc +test -O2 -vn -c -c -o obj/_freopen1.o _freopen1.c
  _freopen1.c:19:36: error: Attempt to modify const lvalue 'mode'
  _freopen1.c:21:21: error: Attempt to modify const lvalue 'access'
  _freopen1.c:22:33: error: Attempt to modify const lvalue 'flags'
  _freopen1.c:25:38: error: Attempt to modify const lvalue 'access'
  _freopen1.c:26:33: error: Attempt to modify const lvalue 'flags'
  _freopen1.c:29:38: error: Attempt to modify const lvalue 'access'
  _freopen1.c:30:33: error: Attempt to modify const lvalue 'flags'
  _freopen1.c:37:15: error: Attempt to modify const lvalue 'mode'
  _freopen1.c:39:25: error: Attempt to modify const lvalue 'access'
  _freopen1.c:40:34: error: Attempt to modify const lvalue 'flags'

Idea from:	cy (commit 50324bba317c in x11/cde)
Reported by:	pkg-fallout