devel/google-perftools: Fix build on armv6
Build was failing on armv6 with this error:
ld: error: ./.libs/libtcmalloc_debug.so: undefined reference to unw_getcontext

Reported by:	fallout

(cherry picked from commit feeb97235234964fc8e304fc99ef1500c22375e6)