devel/rsvndump: Resolve DEVELOPER LIB_DEPENDS warnings
Resolve the following LIB_DEPENDS warnings:

Error: /usr/local/bin/rsvndump is linked to
/usr/local/lib/libapr-1.so.0 from devel/apr1 but it is not declared
as a dependency
Warning: you need LIB_DEPENDS+=libapr-1.so:devel/apr1
Error: /usr/local/bin/rsvndump is linked to
/usr/local/lib/libaprutil-1.so.0 from devel/apr1 but it is not declared
as a dependency
Warning: you need LIB_DEPENDS+=libaprutil-1.so:devel/apr1
Error: /usr/local/bin/rsvndump is linked to
/usr/local/lib/libdb-5.3.so.0 from databases/db5 but it is not declared
as a dependency
Warning: you need USES+=bdb
Error: /usr/local/bin/rsvndump is linked to /usr/local/lib/libgdbm.so.6
from databases/gdbm but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libgdbm.so:databases/gdbm
Error: /usr/local/bin/rsvndump is linked to /usr/local/lib/libexpat.so.1
from textproc/expat2 but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libexpat.so:textproc/expat2

(cherry picked from commit 7ca778484e34feba3457b0bf68245fe03673016e)