x11-toolkits/pangomm: unbreak build with pango >= 1.50
attrlist.cc:38:20: error: use of undeclared identifier 'pango_parse_markup'
  gboolean bTest = pango_parse_markup(markup_text.c_str(), -1 /* means null-terminated */, accel_marker,
                   ^
attrlist.cc:65:20: error: use of undeclared identifier 'pango_parse_markup'
  gboolean bTest = pango_parse_markup(markup_text.c_str(), -1 /* means null-terminated */, accel_marker,
                   ^

PR:		260916
Regressed by:	https://gitlab.gnome.org/GNOME/pango/-/commit/d8df0da73752