games/veloren-weekly: Fix build with rust 1.75.0
error[E0557]: feature has been removed
 --> rtsim/src/lib.rs:5:5
  |
5 |     generators,
  |     ^^^^^^^^^^ feature has been removed
  |
  = note: renamed to `coroutines`

error[E0635]: unknown feature `generator_trait`
 --> rtsim/src/lib.rs:4:5
  |
4 |     generator_trait,

PR:		276033
Approved by:	portmgr (build fix blanket)