During the exp-run in bug 208158, it was found that graphics/gource gives errors with libc++ 3.8.0:
src/dirnode.cpp:585:27: error: no matching function for call to 'max'
    this->parent_radius = std::max(1.0, sqrt(total_file_area) * gGourceDirPadding);
                          ^~~~~~~~

This is because max() is being called with two arguments of different
type (double and float).  Fix this by using 0.0f instead (and casting
the result of sqrt to float like two lines above, though this should
strictly not be necessary).

Approved by:	demon (maintainer)
PR:		208844
MFH:		2016Q2