x11/wdisplays: unbreak build with textproc/py-scour
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/icons/hicolor/scalable/apps/network.cycles.wdisplays.svg
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/icons/hicolor/scalable/apps/wdisplays.svg
===> Error: Plist issues found.
*** Error code 1

PR:		270525
Reported by:	Chad Jacob Milios

(cherry picked from commit fdf37ec6360d430f2a71f85f85cc2e70ae7fc60f)