graphics/darktable: USES+=perl5
This is to make sure that PERL_LEVEL gets defined,
which in turn is needed to make sure that perl's Pod::Parser
gets defined if it is not part of the respective Perl version's install.

Approved by: (blanket, trivial tested build fix)

Error log in poudriere before patch:
[00:17:46] [ 97% 727/747] cd /wrkdirs/usr/ports/graphics/darktable/work/darktable-3.4.1/doc/man && sh -c /usr/local/bin/po4a-translate\ -f\ pod\ -m\ darktable-generate-cache.pod\ -p\ po/es.po\ -l\ /wrkdirs/usr/ports/graphics/darktable/work/.build/doc/man/es/darktable-generate-cache.pod\ -k\ 0
[00:17:46] FAILED: doc/man/es/darktable-generate-cache.pod
[00:17:46] cd /wrkdirs/usr/ports/graphics/darktable/work/darktable-3.4.1/doc/man && sh -c /usr/local/bin/po4a-translate\ -f\ pod\ -m\ darktable-generate-cache.pod\ -p\ po/es.po\ -l\ /wrkdirs/usr/ports/graphics/darktable/work/.build/doc/man/es/darktable-generate-cache.pod\ -k\ 0
[00:17:46] Unknown format type: pod.
[00:17:46] po4a::chooser: Module loading error: Can't locate Pod/Parser.pm in @INC (you may need to install the Pod::Parser module) (@INC contains: /usr/local/lib/perl5/site_perl/mach/5.32 /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/mach /usr/local/lib/perl5/5.32) at /usr/local/lib/perl5/site_perl/Locale/Po4a/Pod.pm line 14.
[00:17:46] BEGIN failed--compilation aborted at /usr/local/lib/perl5/site_perl/Locale/Po4a/Pod.pm line 14.
[00:17:46] Compilation failed in require at (eval 33) line 1.
[00:17:46] BEGIN failed--compilation aborted at (eval 33) line 1.