www/flexget: revert r560450 due to regressing transmission-rpc
ERROR    transmission-rpc foo      Error: Expecting value: line 1 column 1 (char 0)
ERROR    transmission-rpc foo      Request: "{"tag": 0, "method": "session-get", "arguments": {}}"
ERROR    transmission-rpc foo      HTTP data: "<h1>404: Not Found</h1>/transmission/"
CRITICAL task          foo      BUG: Unhandled error in plugin transmission:
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/transmission_rpc/client.py", line 277, in _request
    data = json.loads(http_data)
           |    |     -> '<h1>404: Not Found</h1>/transmission/'
           |    -> <function loads at 0x8028b3160>
           -> <module 'json' from '/usr/local/lib/python3.9/json/__init__.py'>
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           |                |      -> '<h1>404: Not Found</h1>/transmission/'
           |                -> <function JSONDecoder.decode at 0x80284da60>
           -> <json.decoder.JSONDecoder object at 0x8028459d0>
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               |    |          |      |  -> '<h1>404: Not Found</h1>/transmission/'
               |    |          |      -> <built-in method match of re.Pattern object at 0x8027d6b70>
               |    |          -> '<h1>404: Not Found</h1>/transmission/'
               |    -> <function JSONDecoder.raw_decode at 0x80284daf0>
               -> <json.decoder.JSONDecoder object at 0x8028459d0>
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          |                                  -> '<h1>404: Not Found</h1>/transmission/'
          -> <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)