devel/onetbb: fix build on armv7
error: option 'cf-protection=return' cannot be specified on this target
error: option 'cf-protection=branch' cannot be specified on this target

Same fix as for powerpc.

Approved by:	portmgr (build fix blanket)
MFH:		2025Q4

(cherry picked from commit a1137c10faf7a0ba93fce9f87df89af8601f359b)