multimedia/obs-studio: fix build with clang 19
Clang 19 has become more strict about mixing different enum types, which
results in an error building multimedia/obs-studio:

  /wrkdirs/usr/ports/multimedia/obs-studio/work/obs-studio-30.2.3/plugins/obs-outputs/flv-mux.c:659:37: error: bitwise operation between different enumeration types ('enum multitrack_type_t' and 'enum packet_type_t') [-Werror,-Wenum-enum-conversion]
    659 |                 s_w8(&s, MULTITRACKTYPE_ONE_TRACK | PACKETTYPE_METADATA);
        |                          ~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~

This can be fixed by explicitly casting each enum type to uint8_t.

PR:		281890
Approved by:	yuri (maintainer)
MFH:		2024Q3

(cherry picked from commit f0e9df3448bd5a567b9447dc711d0a5f0341a327)