www/webkit2-gtk3: fix build with clang 19
Clang 19 now implements CWG 96 [1], which requires a template argument
list after a 'template' keyword, resulting in errors similar to:

    /wrkdirs/usr/ports/www/webkit2-gtk3/work/webkitgtk-2.34.6/Source/JavaScriptCore/assembler/AbstractMacroAssembler.h:974:65: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
      974 |         AssemblerType::repatchCompact(dataLabelCompact.template dataLocation(), value);
          |                                                                 ^

In these cases, appending "<>" is enough to satisfy the constraint.
Upstream has committed a fix to their main branch [2], but since some
code has moved around, and other functions have been removed, it does
not apply cleanly to 2.34.6. Therefore, apply only the necessary fixes
manually for now.

[1] https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#96
[2] https://github.com/WebKit/WebKit/commit/62b6e2db547e

PR:		280728
Approved by:	fluffy (maintainer)
MFH:		2024Q3