devel/qt6-base: Add missing include
Fixes build of x11-wm/plasma6-kwin.

/usr/local/include/qt6/QtCore/qcompare_impl.h:26:49: error: no member named 'is_null_pointer_v' in namespace 'std'
   26 |     template <typename T, std::enable_if_t<std::is_null_pointer_v<T>, bool> = true>

Not bumping PORTREVISION again. The previous commit to qt6-base covers
that.

MFH:		2025Q1