databases/leofs: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because Makefile does not explicitly set its C++ standard, this leads
to the error when building eleveldb:

  util/bloom.cc:100:10: error: no template named 'auto_ptr' in namespace 'std'
      std::auto_ptr<const FilterPolicy> m_Item;
      ~~~~~^

Add USE_CXXSTD=gnu++11 to avoid this error.