sysutils/pfstat: Fix build on FreeBSD 15, take maintainership
pf.c:174:16: error: use of undeclared identifier 'DIOCGETSTATUS'
  174 |         if (ioctl(fd, DIOCGETSTATUS, &s)) {
      |                       ^

Improve port:
- Replace PORTVERSION with DISTVERSION.
- Remove legacy unnecessary MAKE_ARGS and REINPLACE_CMD.
- Replace REINPLACE_CMD in pf.c with CFLAGS+=-I/usr/include/net.
- Reduce number of INSTALL_* calls in do-install.

PR:		291607
MFH:		2025Q4
Co-authored-by:	David Marec <david.marec@proton.me>
Co-authored-by:	Vladimir Druzenko <vvd@FreeBSD.org>
(cherry picked from commit c701d6805046f1928a33188d265821b4579204c3)