databases/sabiql: Update to 3.0.1
- Pass argument --ignore-rust-version to cargo command, otherwise
  the port fails to build/install with the following error:

error: rustc 1.97.1 is not supported by the following packages:
  sabiql@3.0.1 requires rustc 1.98
  sabiql-app@3.0.1 requires rustc 1.98
  sabiql-domain@3.0.1 requires rustc 1.98
  sabiql-infra@3.0.1 requires rustc 1.98
  sabiql-ui@3.0.1 requires rustc 1.98

*** Error code 101

ChangeLog:

1. https://github.com/riii111/sabiql/releases/tag/v3.0.1

Reported by:	riii111 <notifications@github.com>