multimedia/v4l-utils: Fix build on CURRENT/STABLE
In file included from dvbv5-daemon.c:43:
/usr/include/search.h:80:7: error: expected identifier or '('
   80 | void     tdestroy(void *, void (*)(void *));
      |          ^
dvbv5-daemon.c:24:23: note: expanded from macro 'tdestroy'
   24 | #define tdestroy(...) do {} while (0)
      |                       ^
In file included from dvbv5-daemon.c:43:
/usr/include/search.h:80:7: error: while loop outside of a function
dvbv5-daemon.c:24:29: note: expanded from macro 'tdestroy'
   24 | #define tdestroy(...) do {} while (0)
      |                             ^

Use native tdestroy(3) on 16-CURRENT and 15-STABLE after [1] and [2],
respectively.

[1] https://cgit.freebsd.org/src/commit/?id=b8c99e7d912f0dad84cec80f8c4331646b87a3ec
[2] https://cgit.freebsd.org/src/commit/?h=stable/15&id=6197518ee90541a5e04d03dffda760b888d3a3e7

Reported by:	pkg-fallout
MFH:		2026Q1

(cherry picked from commit c694950c1722d69f69965d0956ad964a597232c7)