x11-toolkits/wlroots-devel: unbreak X11=off build after 4aaa83fcff45
../backend/libinput/tablet_tool.c:4:10: fatal error: 'linux/input.h' file not found
 #include <linux/input.h>
          ^~~~~~~~~~~~~~~

https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/94dbb3cfb529
(cherry picked from commit b2de74f1e7e041e1d0498a75030b173b5aed7bce)