multimedia/tautulli: Fix missing runtime dependency
With modern python setuptools are not just installed.

Starting tautulli.
Traceback (most recent call last):
  File "/usr/local/www/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/usr/local/www/tautulli/plexpy/__init__.py", line 33, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/usr/local/www/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'

PR:		295759
Approved by:	christer.edwards@gmail.com (maintainer, timeout 3 months)
Sponsored by:	UNIS Labs
MFH:		2026Q3