graphics/alizams: fix build on big-endian
/wrkdirs/usr/ports/graphics/alizams/work/AlizaMS-1.9.3/mdcm/Source/Common/mdcmSwapper.h:92:16: error: read-only variable is not assignable
      array[i] = Swap<T>(array[i]);
      ~~~~~~~~ ^

While here switch to CMake switch for disabling SIMD.