devel/hyprlang: unbreak build with libc++ 16
src/config.cpp:276:42: error: no member named 'format' in namespace 'std'
                    result.setError(std::format("special category's first value must be the key. Key for <{}> is <{}>", PCAT->name, PCAT->key));
                                    ~~~~~^
src/config.cpp:287:34: error: no member named 'format' in namespace 'std'
            result.setError(std::format("config option <{}> does not exist.", valueName));
                            ~~~~~^
src/config.cpp:297:38: error: no member named 'format' in namespace 'std'
                result.setError(std::format("failed parsing an int: {}", e.what()));
                                ~~~~~^
src/config.cpp:306:38: error: no member named 'format' in namespace 'std'
                result.setError(std::format("failed parsing a float: {}", e.what()));
                                ~~~~~^
src/config.cpp:324:38: error: no member named 'format' in namespace 'std'
                result.setError(std::format("failed parsing a vec2: {}", e.what()));
                                ~~~~~^
src/config.cpp:533:38: error: no member named 'format' in namespace 'std'
            impl->parseError += std::format("Config error in file {} at line {}: {}", file, linenum, RET.errorStdString);
                                ~~~~~^
src/config.cpp:546:38: error: no member named 'format' in namespace 'std'
            impl->parseError += std::format("Config error in file {}: Unclosed category at EOF", file);
                                ~~~~~^

Reported by:	pkg-fallout