devel/ccls: lock llvm-version at 9
LLVM_DEFAULT will be bumped to 15, this port fails with:
	[...]
	/wrkdirs/usr/ports/devel/ccls/work/ccls-0.20210330/src/indexer.cc:530:21: error: use of undeclared identifier 'isIdentifierBody'; did you mean 'IdentifierLoc'?
		     ((i && isIdentifierBody(name[i - 1])) ||
			    ^
	[...]

PR:             263456