games/ponscripter-07th-mod: pacify stage-qa after 3507e8bb40e0
Error: /usr/local/bin/ponscr is linked to /usr/local/lib/libgobject-2.0.so.0 from devel/glib20 but it is not declared as a dependency
Warning: you need USE_GNOME+=glib20
(cherry picked from commit cc4055cac0511ca23ae937e73653bfc6e742991f)