math/sleef: fix build on powerpc64 elfv2
clang doesn't find vec_nand:
In file included from /wrkdirs/usr/ports/math/sleef/work/sleef-3.4.0/src/libm/sleefsimdsp.c:145:
/wrkdirs/usr/ports/math/sleef/work/sleef-3.4.0/src/arch/helperpower_128.h:266:54: warning: implicit declaration of function 'vec_nand' is invalid in C99 [-Wimplicit-function-declaration]
static INLINE vopmask vnot_vo_vo(vopmask o) { return vec_nand(o, o); }
                                                     ^
/wrkdirs/usr/ports/math/sleef/work/sleef-3.4.0/src/arch/helperpower_128.h:266:54: error: returning 'int' from a function with incompatible result type 'vopmask' (vector of 4 'unsigned int' values)
static INLINE vopmask vnot_vo_vo(vopmask o) { return vec_nand(o, o); }
                                                     ^~~~~~~~~~~~~~

-mpower8-vector is needed because vec_nand is behind #ifdef __POWER8_VECTOR__ in clang's altivec.h.

PR:		242143
Approved by:	linimon (mentor), jmd (maintainer)