sysutils/uhidd: unbreak build after 620968a43a5f
Restore the patch accidentally removed due to confusing comment.

uhidd_vhid_cuse.c:195:16: error: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                    basename(hi->dev), hi->ndx);
                             ^~~~~~~
/usr/include/libgen.h:61:74: note: expanded from macro 'basename'
 #define basename(x)     __generic(x, const char *, __old_basename, basename)(x)
                                                                              ^
/usr/include/libgen.h:56:28: note: passing argument to parameter here
char    *__old_basename(char *);
                              ^

Reported by:	pkg-fallout

(cherry picked from commit 644d695c79fa5a7e45c0e87d8cfeb9351a8553b5)