devel/shiboken2: explicitely disable numpy support
Build failure due to numpy being present in the environment:
	[...]
	error: use of undeclared identifier 'NPY_ARRAY_UPDATEIFCOPY'
		if ((flags & NPY_ARRAY_UPDATEIFCOPY) != 0)
				^
	[...]

Reported by:		rhurlin