x11/hyprpicker: unbreak build without libglvnd
In file included from src/main.cpp:5:
In file included from src/hyprpicker.hpp:3:
In file included from src/defines.hpp:5:
src/includes.hpp:30:10: fatal error: 'GLES3/gl32.h' file not found
 #include <GLES3/gl32.h>
          ^~~~~~~~~~~~~~

PR:		277449
Reported by:	Elena

(cherry picked from commit a170bb5d71597ba851ec31dbc0a4a98fe8f6d4d9)