Fix stage-qa of shebang with PYTHON option disabled after r522484
The error message (in poudriere) is as follows:
====> Running Q/A tests (stage-qa)
Error: '/usr/local/bin/python' is an invalid shebang you need USES=shebangfix for 'share/vim/vim82/tools/demoserver.py.bak'

r522484 adds a new REINPLACE_CMD check which is enabled when DEVELOPER=yes. It
does not respect REINPLACE_ARGS (-i ''), thus runtime/tools/demoserver.py.bak is
generated. Vim installs everything in runtime/tools [1] which fails in stage-qa
for invalid shebang.

This workaround uses USES=python:env. It will replace the shebang with default
python (/usr/local/bin/python3.7).

[1] from src/Makefile:
# install the runtime tools
	$(INSTALL_DATA_R) $(TOOLSSOURCE)/* $(DEST_TOOLS)

PR:		243961
Reported by:	salvadore
Submitted by:	sunpoet (myself)
Approved by:	adamw (maintainer)