x11/brisk-menu: fix dependencies, remove duplicate plist entry
====> Running Q/A tests (stage-qa)
Error: /usr/local/libexec/brisk-menu is linked to /usr/local/lib/libX11.so.6 from x11/libX11 but it is not declared as a dependency
Warning: you need USE_XORG+=x11
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/glib-2.0/schemas/com.solus-project.brisk-menu.gschema.xml
===> Error: Plist issues found.

The schema is already packaged via GLIB_SCHEMAS.

http://package21.nyi.freebsd.org/data/113amd64-default-qat/532906/logs/brisk-menu-0.6.0.log