devel/libcjson: fix build on GCC architectures
Disable -Werror, along with other -W flags, that cause build to break with GCC (builds with Clang as well):
/wrkdirs/usr/ports/devel/libcjson/work/cJSON-1.7.13/cJSON.c:559:15: error: conversion from 'double' to 'float' may change value [-Werror=float-conversion]

MFH:		2020Q3 (fix build blanket)