misc/librepo: Attempt to fix compilation failure on 13.2 amd64 and i386:
This error is due to the label at the very end of tghe function:
/wrkdirs/usr/ports/misc/librepo/work/librepo-1.17.0/librepo/gpg_gpgme.c:147:1: error: expected statement
}
^
1 error generated.

Reported by:	fallout