devel/build2: fix build with clang 18 rc1
As of rc1, clang 18 has a version id formatted as "18.1.0rc". Similarly,
builds from the upstream main branch typically have a version id looking
like "19.0.0git". Due to the way it parses version strings, devel/build2
cannot handle this format, and fails with:

  LC_ALL=C c++ -v
  error: unable to extract Clang minor version from '18'
    info: use config.cxx.version to override

I submitted https://github.com/build2/build2/issues/360 upstream, and
they committed a fix: https://github.com/build2/build2/commit/0e1b73e3,
which should eventually end up in 0.17.0.

The fix applies without issues on 0.16.0, so add it as a patch.

PR:		276785
Approved by:	fuz (maintainer)
MFH:		2024Q1