Fix type for abs() calls in graphics/inkscape
During the exp-run in bug 208158, it was found that graphics/inkscape
gives errors with libc++ 3.8.0:

libavoid/connector.cpp:888:29: error: call to 'abs' is ambiguous
                COLA_ASSERT(abs(i->pathNext->id.objID - i->id.objID) != 2);
                            ^~~

This is because abs() is called with unsigned arguments.  Fix it
by casting the arguments to the appropriate signed types.  This
mimics what happens with older libraries where the only version of
abs() was the one in <stdlib.h>, which is prototyped:
	int abs(int)
The expression used in ConnRef::generatePath() is not strictly correct
because it depends on details of integer overflow that are undefined
by the C++ standard.

PR:		209675
Submitted by:	dim