japanese/zinnia: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because japanese/zinnia's build infrastructure does not explicitly set
its C++ standard, this leads to an error:

  svm.cpp:50:10: error: no member named 'random_shuffle' in namespace 'std'
      std::random_shuffle(index.begin(), index.begin() + active_size);
      ~~~~~^

This is because std::random_shuffle has been removed from C++17. An
suitable replacement is std::shuffle, using a std::random_device in
combination with std::mt19937 as the random number engine.

PR:		271953
Approved by:	fernape
MFH:		2023Q2