emulators/sameboy: Try to unreak build with multiple make jobs
gmake -C ../ build/bin/BootROMs/agb_boot.bin
gmake[3]: Entering directory '/wrkdirs/usr/ports/emulators/sameboy/work/SameBoy-0.14.2'
gmake -C ../ build/bin/BootROMs/cgb_boot.bin
gmake[3]: Entering directory '/wrkdirs/usr/ports/emulators/sameboy/work/SameBoy-0.14.2'
rgbasm -i build/obj/BootROMs/ -i BootROMs/ -o build/bin/BootROMs/agb_boot.bin.tmp BootROMs/agb_boot.asm
rgblink -o build/bin/BootROMs/agb_boot.bin.tmp2 build/bin/BootROMs/agb_boot.bin.tmp
dd if=build/bin/BootROMs/agb_boot.bin.tmp2 of=build/bin/BootROMs/agb_boot.bin count=1 bs=2304 2> /dev/null
gmake[3]: Leaving directory '/wrkdirs/usr/ports/emulators/sameboy/work/SameBoy-0.14.2'
rgbasm -i build/obj/BootROMs/ -i BootROMs/ -o build/bin/BootROMs/cgb_boot.bin.tmp BootROMs/cgb_boot.asm
rgbasm -i build/obj/BootROMs/ -i BootROMs/ -o build/bin/BootROMs/cgb_boot.bin.tmp BootROMs/cgb_boot.asm
rgblink -o build/bin/BootROMs/cgb_boot.bin.tmp2 build/bin/BootROMs/cgb_boot.bin.tmp
dd if=build/bin/BootROMs/cgb_boot.bin.tmp2 of=build/bin/BootROMs/cgb_boot.bin count=1 bs=2304 2> /dev/null
rgblink -o build/bin/BootROMs/cgb_boot.bin.tmp2 build/bin/BootROMs/cgb_boot.bin.tmp
error: Could not open file build/bin/BootROMs/cgb_boot.bin.tmp: No such file or directory
rgbasm -i build/obj/BootROMs/ -i BootROMs/ -o build/bin/BootROMs/agb_boot.bin.tmp BootROMs/agb_boot.asm

http://package18.nyi.freebsd.org/data/122amd64-default-foo/2021-04-10_08h07m32s/logs/errors/sameboy-0.14.2.log

I believe this is because at the moment the sdl program and libretro
module are built in one go but both depend on the bootroms and
should actually be built in separate steps.  Try that before adding
MAKE_JOBS_UNSAFE.