net/norm: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because net/norm's build system does not explicitly set the C++
standard, this leads to several errors:

  ../src/common/normEncoderRS8.cpp:264:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
      USE_GF_MULC ;
      ^
  ../src/common/normEncoderRS8.cpp:136:21: note: expanded from macro 'USE_GF_MULC'
  #define USE_GF_MULC register gf * __gf_mulc_
                      ^
  ../src/common/normEncoderRS8.cpp:265:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
      register gf* dst = dst1;
      ^~~~~~~~~
  ../src/common/normEncoderRS8.cpp:266:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
      register gf* src = src1 ;
      ^~~~~~~~~

Add USE_CXXSTD=gnu++98 to compile for C++98 with GNU extensions instead,
as net/norm does not seem to use any C++11 or later constructs.

PR:		271415
Approved by:	portmgr (build fix blanket)
MFH:		2023Q2