games/punchy: unbreak build on i386
fatal runtime error: Rust cannot catch foreign exceptions
thread '<unnamed>' panicked at '/wrkdirs/usr/ports/lang/rust/work/rustc-1.70.0-src/compiler/rustc_codegen_ssa/src/back/write.rs:1535:21: worker thread panicked', compiler/rustc_middle/src/util/bug.rs:36:26

(signal: 6, SIGABRT: process abort signal)

Reported by:	pkg-fallout

(cherry picked from commit ad1d79583b285d7a320f7a8b844bc568142670e0)