security/zeek: fix build on powerpc64*
In file included from /wrkdirs/usr/ports/security/zeek/work/zeek-4.0.3/auxil/highwayhash/highwayhash/arch_specific.cc:27:
/usr/include/sys/sysctl.h:1185:25: error: unknown type name 'u_int'
int     sysctl(const int *, u_int, void *, size_t *, const void *, size_t);

(cherry picked from commit b91d1bd03771d45095637061c58baba5e62fc991)