multimedia/qt6-multimedia: unbreak ALSA=on PULSEAUDIO=off after 230148d80ee0
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%QT_INCDIR%%/QtMultimedia/%%FULLVER%%/QtMultimedia/private/qalsaaudiodevice_p.h
Error: Orphaned: %%QT_INCDIR%%/QtMultimedia/%%FULLVER%%/QtMultimedia/private/qalsaaudiosink_p.h
Error: Orphaned: %%QT_INCDIR%%/QtMultimedia/%%FULLVER%%/QtMultimedia/private/qalsaaudiosource_p.h
Error: Orphaned: %%QT_INCDIR%%/QtMultimedia/%%FULLVER%%/QtMultimedia/private/qalsamediadevices_p.h
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%QT_INCDIR%%/QtMultimedia/%%FULLVER%%/QtMultimedia/private/qaudioengine_pulse_p.h
Error: Missing: %%QT_INCDIR%%/QtMultimedia/%%FULLVER%%/QtMultimedia/private/qpulseaudiodevice_p.h
Error: Missing: %%QT_INCDIR%%/QtMultimedia/%%FULLVER%%/QtMultimedia/private/qpulseaudiomediadevices_p.h
Error: Missing: %%QT_INCDIR%%/QtMultimedia/%%FULLVER%%/QtMultimedia/private/qpulseaudiosink_p.h
Error: Missing: %%QT_INCDIR%%/QtMultimedia/%%FULLVER%%/QtMultimedia/private/qpulseaudiosource_p.h
Error: Missing: %%QT_INCDIR%%/QtMultimedia/%%FULLVER%%/QtMultimedia/private/qpulsehelpers_p.h
===> Error: Plist issues found.
*** Error code 1

PR:		272736