audio/ocp: fix build on powerpc64 with gcc
GCC is still used on stable/11 and stable/12. It needs sys/types.h in lzh.h, because some types are not recognized.

Force newer compiler due to:
pfilesel.c:3312: error: #pragma GCC diagnostic not allowed inside functions

Because of libstdc++ ABI changes due to forcing new compiler, audio/libadplug and devel/libbinio in order for audio/ocp to build.

PR:		247377
Approved by:	ehaupt (maintainer)