graphics/libwmf: track gdk-pixbuf2 dependency after 84531028a865
Installing libgd-2.3.3_3,1...
`-- Installing libavif-0.11.1...
|   `-- Installing aom-3.5.0...
|   | `-- Installing libjxl-0.7.0...
|   |   `-- Installing gdk-pixbuf2-2.42.10...
|   |   | `-- Installing glib-2.74.1,2...

====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders/io-wmf.so is linked to /usr/local/lib/libgdk_pixbuf-2.0.so.0 from graphics
/gdk-pixbuf2 but it is not declared as a dependency
Warning: you need USE_GNOME+=gdkpixbuf2
Error: /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders/io-wmf.so is linked to /usr/local/lib/libgobject-2.0.so.0 from devel/glib20 but it is not declared as a dependency
Warning: you need USE_GNOME+=glib20
Error: /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders/io-wmf.so is linked to /usr/local/lib/libglib-2.0.so.0 from devel/glib20 but it is not declared as a dependency
Warning: you need USE_GNOME+=glib20
Error: /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders/io-wmf.so is linked to /usr/local/lib/libintl.so.8 from devel/gettext-runtime but it is not declared as a dependency
Warning: you need USES+=gettext-runtime
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/gdk-pixbuf-2.0/2.10.0/loaders/io-wmf.a
Error: Orphaned: lib/gdk-pixbuf-2.0/2.10.0/loaders/io-wmf.so
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1