science/PETSc: fix packaging with python!=3.12
Eliminate oblivously writed %%PYTHON_SUFFIX%% for ex312.c filename

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%DATADIR%%/examples/src/mat/tests/ex312.c
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%DATADIR%%/examples/src/mat/tests/ex%%PYTHON_SUFFIX%%.c
===> Error: Plist issues found.
*** Error code 1

Reported by:    bulk -t
Approved by:    portmgr blanket