MFH: r444937 net/py-rainbowstream: Make pocket (really) optional
rainbowstream has configurable Pocket support (via settings) but declares
the dependency in install_requires, making it a compulsory run-time dependency
checked/varified by setuptools.

When first committed, given the pocket Python package had not yet been ported,
it was (obviously) not included in RUN_DEPENDS, but it was not removed from
setup.py:install_requires, resulting in the following runtime error:

  pkg_resources.DistributionNotFound: The 'pocket' distribution was not found
  and is required by rainbowstream

This could be rectified by the user by installing the package from pip, which
is convenient, but which we explicitly recommend against [1].

This commit patches setup.py moving pocket to setup.py:extras_require and the
main module to conditionally import pocket, instead of failing as follows:

    from pocket import Pocket
  ImportError: No module named pocket

While I'm here:

- Remove upper bound/limit on 3.x version support

[1] See devel/py-pip/pkg-message

PR:		220312
Reported by:	Petr Fischer <petr.fischer me com>

Approved by:	ports-secteam (blanket)