x11/xcoloredit: Fix LLVM15 error
xcoloredit.c:356:14: error: incompatible pointer to integer conversion assigning to 'int' from 'void *' [-Wint-conversion]
        bars_locked = NULL;
                    ^ ~~~~

While at it adopt this feral port.

(cherry picked from commit 8fc5e393c4a9e1589291f6580415636786dfd105)