math/csdp: fix build on powerpc
LLVM on powerpc doesn't have libomp:
cc -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -fopenmp -ansi -Wall -DBIT64 -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include   -c -o op_o.o op_o.c
op_o.c:15:10: fatal error: 'omp.h' file not found