devel/kyua: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because devel/kyua's Makefile does not explicitly set its C++ standard,
this leads to several errors:

  In file included from cli/cmd_about.cpp:29:
  In file included from ./cli/cmd_about.hpp:35:
  ./cli/common.hpp:71:14: error: no template named 'auto_ptr' in namespace 'std'
  typedef std::auto_ptr< cli_command > cli_command_ptr;
          ~~~~~^
  In file included from cli/cmd_db_exec.cpp:29:
  In file included from ./cli/cmd_db_exec.hpp:37:
  ./cli/common.hpp:71:14: error: no template named 'auto_ptr' in namespace 'std'
  typedef std::auto_ptr< cli_command > cli_command_ptr;
          ~~~~~^
  In file included from cli/cmd_db_migrate.cpp:29:
  In file included from ./cli/cmd_db_migrate.hpp:35:
  ./cli/common.hpp:71:14: error: no template named 'auto_ptr' in namespace 'std'
  typedef std::auto_ptr< cli_command > cli_command_ptr;
          ~~~~~^
  In file included from cli/cmd_config.cpp:29:
  In file included from ./cli/cmd_config.hpp:35:
  ./cli/common.hpp:71:14: error: no template named 'auto_ptr' in namespace 'std'
  typedef std::auto_ptr< cli_command > cli_command_ptr;
          ~~~~~^

Add USE_CXXSTD=gnu++98 to avoid these errors.

PR:		271054
Approved by:	maintainer timeout (2 weeks)
MFH:		2023Q2