databases/mysql91-client: Fix PLIST when SASLCLIENT is disabled
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/mysql/plugin/mysql_native_password.so
===> Error: Plist issues found.

Approved by:	portmgr (blanket)