www/py-yarl: Add missing dependencies
The update to 1.18.0 was not properly tested, missed runtime
dependencies and was broken:

```
% python3 -c 'import yarl'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/yarl/__init__.py", line 2, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/usr/local/lib/python3.11/site-packages/yarl/_url.py", line 13, in <module>
    from propcache.api import under_cached_property as cached_property
ModuleNotFoundError: No module named 'propcache'
```

Add missing RUN_DEPEND on a recently added py-propcache, and add missing
test dependencies as well.

PR:		282913
Pointyhat to:	bapt