databases/mariadb101-server: fix build on powerpc64 elfv2
Like other SQL servers, this port fails to build due to Clang bug:
Wrong types for attribute: inalloca nest noalias nocapture nonnull readnone readonly signext sret zeroext byval dereferenceable(1) dereferenceable_or_null(1)
  %call54 = call signext i32 @my_atomic_cas32(i32* %62, i32* %64, %union.U_32 signext %65)
in function lf_hash_insert
fatal error: error in backend: Broken function found, compilation aborted!