x11-wm/river: update to 0.3.4 after b2b3906286ed
river-0.3.2/build.zig:151:61: error: no field named 'path' in union 'Build.LazyPath'
/usr/local/lib/zig/std/Build.zig:2171:22: note: union declared here

PR:		279604
Changes:	https://codeberg.org/river/river/releases/tag/v0.3.3
Changes:	https://codeberg.org/river/river/releases/tag/v0.3.4
Reported by:	Repology