net-mgmt/monitoring-plugins: Remove sudo from check_mailq
Fixes error:
/usr/local/libexec/nagios/check_mailq
Global symbol "$sudo" requires explicit package name (did you forget to declare "my $sudo"?) at /usr/local/libexec/nagios/check_mailq line 580.
Execution of /usr/local/libexec/nagios/check_mailq aborted due to compilation errors.

Upstream removed sudo for check_mailq completely in version 3.0.3.

Changes:	https://github.com/monitoring-plugins/monitoring-plugins/releases/tag/v3.0.3
PR:		297472