japanese/canna-lib: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
japanese/canna-lib failed to build with clang 15:

  crxgram.c:421:33: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'char *' [-Wint-conversion]
                  alert("unknown operation %c", op);
                                                ^~
  rkc.c:2741:38: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'unsigned char *' [-Wint-conversion]
    nkanji = _RkwGetSimpleKanji(cxnum, dicname, cbuf, len,
                                       ^~~~~~~

This is mostly expected as canna-lib is very old K&R code, and clang 15
has -Wint-conversion as an error by default.

Pass -Wno-error=int-conversion in CCOPTIONS to make the warning
non-fatal. This should work for both clang and gcc.

PR:		268256
Approved by:	portmgr (tcberner)
MFH:		2022Q4