security/py-certbot: Fix configargparse 0.12.0 regression
This is caused by the recent release of configargparse version 0.12.0.
The variable ACTION_TYPES_THAT_DONT_NEED_A_VALUE was changed from a set
to a tuple in that release.

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.13.0', 'console_scripts', 'certbot')()
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 738, in main
    args = cli.prepare_and_parse_args(plugins, cli_args)
  File "/usr/local/lib/python2.7/site-packages/certbot/cli.py", line 1072, in prepare_and_parse_args
    helpful.add_deprecated_argument("--agree-dev-preview", 0)
  File "/usr/local/lib/python2.7/site-packages/certbot/cli.py", line 726, in add_deprecated_argument
    self.parser.add_argument, argument_name, num_args)
  File "/usr/local/lib/python2.7/site-packages/certbot/util.py", line 440, in add_deprecated_argument
    configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE.add(ShowWarning)
AttributeError: 'tuple' object has no attribute 'add'

PR:		219306
Reported by:	GKK <netbackup.gs@gmail.com>
Approved by:	koobs (maintainer)
Obtained from:	https://github.com/certbot/certbot/commit/42d07d756df0cf96c9d20b44e772858391d48384