www/onlyoffice-documentserver: Fix build with MYSQL option
Add missing "localbase" to the USES list.

Error message:
Error: Command failed: /bin/sh -c ./configure --with-system-zlib --with-system-libpng --prefix="/wrkdirs/usr/ports/www/onlyoffice-documentserver/work/DocumentServer-7.0.1/web-apps/build/node_modules/optipng-bin/vendor" --bindir="/wrkdirs/usr/ports/www/onlyoffice-documentserver/work/DocumentServer-7.0.1/web-apps/build/node_modules/optipng-bin/vendor"

Checking for system libpng...
./configure: error: missing libpng or incorrect libpng version
./configure: note: libpng version 1.2.9 or higher is required

Reported and tested by: Martin Waschbüsch