MFH: r521784
math/gretl: fix build on GCC architectures

Since the last upgrade, gretl requires C11:
../lib/src/bhhh_max.c:37: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Lval'

Fix this by adding USES=compiler:c11 and replacing OPENMP_USES=compiler:openmp with OPENMP_USE=GCC=yes. This sets the correct CC.

PR:		243027
Approved by:	yuri (maintainer)
Approved by:	portmgr (fix build blanket)