x11/sirula: Unbreak build
Fix typo:
error: expected one of `(`, `.`, `::`, `;`, `?`, `}`, or an operator, found `:`
   --> /build/cargo-vendor-dir/osstrtools-0.2.2/src/lib.rs:754:42
    |
754 |         unsafe { (bytes as *const _).cast:() }
    |                                          ^ expected one of 7 possible tokens

error: could not compile `osstrtools` (lib) due to previous error

Typo was added in https://github.com/rabite0/osstrtools/commit/1179a979dbf22209547a74ce98d84745d1e54ef4

Approved by:	portmgr (build fix blanket)