www/gitlab: fix database migration error
main: -- execute("ALTER TABLE \"ci_pipelines\" DROP CONSTRAINT \"ci_pipelines_pkey\" \n")
main: == [advisory_lock_connection] object_id: 52240, pg_backend_pid: 3944
rake aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

PG::DependentObjectsStillExist: ERROR:  cannot drop constraint ci_pipelines_pkey on table ci_pipelines because other objects depend on it
DETAIL:  constraint fk_c262d728d4 on table p_ci_builds depends on index ci_pipelines_pkey
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

https://gitlab.com/gitlab-org/gitlab/-/issues/462591#top
https://gitlab.com/gitlab-org/gitlab/-/merge_requests/153560