sysutils/bacula13-server: Adding missing patch
This patch was overlooked in the previous commit.

This fixes the fallout reports:

bxattr_freebsd.c:106:18: error: use of undeclared identifier 'bRC_XACL_ok'; did you mean 'bRC_BXATTR_ok'?