math/qhull: Fix stage-qa after 6db564e9a16951384daf415e1323e71f71693316
====> Running Q/A tests (stage-qa)
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/cmake/Qhull/QhullTargets-%%CMAKE_BUILD_TYPE%%.cmake
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/math/qhull
=>> Error: check-plist failures detected

Approved by:	portmgr (blanket)