textproc/aspell: fix build with clang 19
With clang 19 and gcc 15, textproc/aspell fails to compile, with errors
similar to:

    In file included from modules/speller/default/readonly_ws.cpp:51:
    modules/speller/default/vector_hash-t.hpp:186:43: error: no member named 'e' in 'VectorHashTable<Parms>'
      186 |     for (iterator i = begin(); i != this->e; ++i, ++this->_size);
          |                                     ~~~~  ^
    modules/speller/default/vector_hash-t.hpp:186:59: error: no member named '_size' in 'VectorHashTable<Parms>'; did you mean 'size_'?
      186 |     for (iterator i = begin(); i != this->e; ++i, ++this->_size);
          |                                                           ^~~~~
          |                                                           size_
    modules/speller/default/vector_hash.hpp:182:17: note: 'size_' declared here
      182 |     size_type   size_;
          |                 ^

Upstream commit <https://github.com/GNUAspell/aspell/commit/ee6cbb1>
fixes this this, so add it as a PATCHFILES entry in the Makefile, until
the next version of aspell is released.

PR:		280675
Approved by:	fluffy (maintainer)
MFH:		2024Q3

(cherry picked from commit 24ae74c0e2045c689b20b4e336e9ca9912fdb270)