audio/gnome-podcasts: unbreak build on i386
fatal runtime error: Rust cannot catch foreign exceptions
thread '<unnamed>' panicked at '/wrkdirs/usr/ports/lang/rust/work/rustc-1.71.0-src/compiler/rustc_codegen_ssa/src/back/write.rs:1535:21: worker thread panicked', compiler/rustc_middle/src/util/bug.rs:36:26

(signal: 6, SIGABRT: process abort signal)

Reported by:	pkg-fallout

(cherry picked from commit b67c43c411247180e964a69807af21716c17f443)