multimedia/vmaf: unbreak legacy API consumers after 1868dedecc9a
$ aomenc --tune=vmaf --output=foo.mp4 foo.y4m
Pass 1/2 frame    1/0          0B       0 us 0.00 fpm [ETA  unknown] libvmaf ERROR could not read model from path: "/usr/local/share/model/vmaf_v0.6.1.json"
Fatal error: Failed to load VMAF model.

$ ffmpeg -i foo.y4m -i bar.y4m -lavfi libvmaf -f null -
[...]
libvmaf INFO `compute_vmaf()` is deprecated and will be removed in a future libvmaf version
libvmaf ERROR could not read model from path: "/usr/local/share/model/vmaf_v0.6.1.pkl"
libvmaf ERROR support for pkl model files has been removed, use json
libvmaf ERROR problem loading model file: /usr/local/share/model/vmaf_v0.6.1.pkl
[Parsed_libvmaf_0 @ 0x8061b3b40] libvmaf encountered an error, check log for details