devel/onscripter: update to 20160726 while fixing
====> Running Q/A tests (stage-qa)
Error: /usr/local/bin/nsaconv is linked to /usr/local/lib/libjpeg.so.8 from graphics/jpeg-turbo but it is not declared as a dependency
Warning: you need USES+=jpeg

MFH:		2016Q3