Update to 20150425 snapshot to unbreak gcc5 build
src/systems/base/koepac_voice_archive.cc:142:27: error:
narrowing conversion of '255' from 'int' to 'int8_t {aka signed char}' inside { }
     0x7e, 0x81, 0x7f, 0x80};
                           ^
Changes:	https://github.com/eglaysher/rlvm/compare/589e3d2...373a3db
Reported by:	DPorts
MFH:		2015Q2