MFH: r484444
mail/rss2email2: Add workaround for filtering out bad tags

This can apparently be triggered with malformed RSS feeds.

Traceback (most recent call last):
  File "/usr/share/rss2email/rss2email.py", line 711, in run
    tagline = ",".join(taglist)
TypeError: sequence item 1: expected string or Unicode, NoneType found

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=734327

- Reset maintainer due to the long timeout

PR:		214934
Submitted by:	jonathan@invertedearth.net
Approved by:	srg@guglielmo.us (maintainer timeout, ~2 years)

Approved by:	ports-secteam runtime fix blanket