editors/openoffice-*: Fix build error with clang 19
Fix this build error:

In file included from /wrkdirs/usr/ports/editors/openoffice-4/work/aoo-4.1.15/main/writerfilter/source/ooxml/OOXMLFactory.cxx:28:
In file included from /wrkdirs/usr/ports/editors/openoffice-4/work/aoo-4.1.15/main/writerfilter/source/ooxml/OOXMLFactory.hxx:39:
In file included from /wrkdirs/usr/ports/editors/openoffice-4/work/aoo-4.1.15/main/writerfilter/source/ooxml/OOXMLFastContextHandler.hxx:38:
/wrkdirs/usr/ports/editors/openoffice-4/work/aoo-4.1.15/main/writerfilter/source/ooxml/RefAndPointer.hxx:104:18: error: no member named 'getHandler' in 'RefAndPointer<Interface, ChildClass>'; did you mean 'mpHandler'?
  104 |         set(rSrc.getHandler());
      |                  ^~~~~~~~~~
      |                  mpHandler
/wrkdirs/usr/ports/editors/openoffice-4/work/aoo-4.1.15/main/writerfilter/source/ooxml/RefAndPointer.hxx:39:26: note: 'mpHandler' declared here
   39 |     mutable ChildClass * mpHandler;
      |                          ^

when building with:

FreeBSD clang version 19.1.2 (https://github.com/llvm/llvm-project.git llvmorg-19.1.2-0-g7ba7d8e2f7b6)

It appears that clang 19 does more sanity checks of unused class
methods than gcc, old versions of Microsoft Visual C++ used by the
AOO project, and older versions of clang.

The assign method in the RefAndPointer class has been broken since
forever and appears to be unused, so comment it out.

This is only a build fix and does not affect the generated code with
older compilers, so there is no PORTREVISION bump.

Reported by:	pkg-fallout

(cherry picked from commit e9090c817e496dd0e45b88b57bff0063385e8ad8)