math/pdal: fix build on powerpc64
vec_sqrt() requires VSX:
/wrkdirs/usr/ports/math/pdal/work/PDAL-2.3.0/vendor/eigen/Eigen/src/Core/arch/AltiVec/PacketMath.h:1296:32: error: use of undeclared identifier 'vec_sqrt'; did you mean 'vec_rsqrte'?
  BF16_TO_F32_UNARY_OP_WRAPPER(vec_sqrt, a);
                               ^~~~~~~~
                               vec_rsqrte