MFH: r544792
misc/xiphos: fix build on GCC architectures

Use C11 compiler:
/usr/local/include/unicode/localpointer.h:224: error: expected ';' before 'noexcept'

Also required is bumping GCC for misc/biblesync because of libstdc++ ABI error.

Approved by:	portmgr (fix build blanket)