sysutils/tiramisu: unbreak build with clang 16
src/notification.vala.c:580:31: error: incompatible function pointer types passing 'void (gconstpointer, gconstpointer, gpointer)' (aka 'void (const void *, const void *, void *)') to parameter of type 'GHFunc' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-function-pointer-types]
        g_hash_table_foreach (hints, ___lambda4__gh_func, _data1_);
                                     ^~~~~~~~~~~~~~~~~~~
/usr/local/include/glib-2.0/glib/ghash.h:114:61: note: passing argument to parameter 'func' here
                                            GHFunc          func,
                                                            ^
src/notification.vala.c:747:31: error: incompatible function pointer types passing 'void (gconstpointer, gconstpointer, gpointer)' (aka 'void (const void *, const void *, void *)') to parameter of type 'GHFunc' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-function-pointer-types]
        g_hash_table_foreach (hints, ___lambda5__gh_func, _data2_);
                                     ^~~~~~~~~~~~~~~~~~~
/usr/local/include/glib-2.0/glib/ghash.h:114:61: note: passing argument to parameter 'func' here
                                            GHFunc          func,
                                                            ^

Reported by:	pkg-fallout

(cherry picked from commit f45d33bcfa053cd8e72a9ec9d05c610d5afa270a)