databases/soci: fix build with libc++ 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
databases/soci failed to build with clang 15:

  In file included from /wrkdirs/usr/ports/databases/soci/work/soci-4.0.3/tests/empty/test-empty.cpp:8:
  In file included from /wrkdirs/usr/ports/databases/soci/work/soci-4.0.3/include/soci/soci.h:12:
  In file included from /wrkdirs/usr/ports/databases/soci/work/soci-4.0.3/include/soci/soci-platform.h:18:
  In file included from /usr/include/c++/v1/string:551:
  In file included from /usr/include/c++/v1/string_view:222:
  In file included from /usr/include/c++/v1/algorithm:1851:
  In file included from /usr/include/c++/v1/__algorithm/ranges_sample.h:13:
  In file included from /usr/include/c++/v1/__algorithm/sample.h:18:
  /usr/include/c++/v1/__random/uniform_int_distribution.h:235:5: error: static assertion failed due to requirement '__libcpp_random_is_valid_urng<Catch::RandomNumberGenerator, void>::value':
      static_assert(__libcpp_random_is_valid_urng<_URNG>::value, "");
      ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/include/c++/v1/__algorithm/shuffle.h:154:35: note: in instantiation of function template specialization 'std::uniform_int_distribution<long>::operator()<Catch::RandomNumberGenerator>' requested here
              difference_type __i = __uid(__g, _Pp(0, __d));
                                    ^
  /usr/include/c++/v1/__algorithm/shuffle.h:166:14: note: in instantiation of function template specialization 'std::__shuffle<std::_ClassicAlgPolicy, std::__wrap_iter<Catch::TestCase *>, std::__wrap_iter<Catch::TestCase *>, Catch::RandomNumberGenerator &>' requested here
    (void)std::__shuffle<_ClassicAlgPolicy>(
               ^
  /wrkdirs/usr/ports/databases/soci/work/soci-4.0.3/tests/catch.hpp:7186:18: note: in instantiation of function template specialization 'std::shuffle<std::__wrap_iter<Catch::TestCase *>, Catch::RandomNumberGenerator &>' requested here
              std::shuffle( vector.begin(), vector.end(), rng );
                   ^
  /wrkdirs/usr/ports/databases/soci/work/soci-4.0.3/tests/catch.hpp:7204:44: note: in instantiation of function template specialization 'Catch::RandomNumberGenerator::shuffle<std::vector<Catch::TestCase>>' requested here
                      RandomNumberGenerator::shuffle( sorted );
                                             ^

This is because soci declares its RandomNumberGenerator class with a
result_type of std::ptrdiff_t, which is signed. However, the urng class
used for std::shuffle must have an unsigned integer type as its result
type. Use std::size_t instead.

PR:		269035
Approved by:	nc (maintainer)
MFH:		2023Q1