x11-toolkits/qt5-gui: unbreak with libglvnd >= 1.3.4
executing config test egl-x11
[...]
> main.cpp:13:14: error: cannot initialize a variable of type 'Display *' (aka '_XDisplay *') with an rvalue of type 'EGLNativeDisplayType' (aka 'void *')
>     Display *dpy = EGL_DEFAULT_DISPLAY;
>              ^     ~~~~~~~~~~~~~~~~~~~
[...]
QPA backends:
  XCB:
    GL integrations:
      EGL-X11 Plugin ..................... no
[...]
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%QT_CMAKEDIR%%/Qt5Gui/Qt5Gui_QXcbEglIntegrationPlugin.cmake
Error: Missing: %%QT_PLUGINDIR%%/xcbglintegrations/libqxcb-egl-integration.so
===> Error: Plist issues found.
*** Error code 1

PR:		258269
See also:	https://bugs.gentoo.org/810343