java/openjdk8: fix build on powerpc64* with clang 15
/wrkdirs/usr/ports/java/openjdk8/work/jdk8u-jdk8u362-b09.1/hotspot/agent/src/os/bsd/symtab.c:266:14: warning: call to undeclared function 'find_section_by_name'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  opd_sect = find_section_by_name(".opd", fd, &ehdr, scn_cache);
             ^
/wrkdirs/usr/ports/java/openjdk8/work/jdk8u-jdk8u362-b09.1/hotspot/agent/src/os/bsd/symtab.c:266:12: error: incompatible integer to pointer conversion assigning to 'struct elf_section *' from 'int' [-Wint-conversion]
  opd_sect = find_section_by_name(".opd", fd, &ehdr, scn_cache);
           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bump PORTREVISION because the issue actually existed with previous clang versions, but didn't cause an error.
find_section_by_name() is copied from Linux's symtab.c.