emulators/virtualbox-ose-legacy: fix build emulators/virtualbox-ose-additions{,-nox11}-legacy on main: error: unknown type name 'uma_zone_t'
In file included from /wrkdirs/usr/ports/emulators/virtualbox-ose-additions-legacy/work/VirtualBox-5.2.44/src/VBox/Additions/freebsd/vboxvfs/vboxvfs_prov.c:42:
/wrkdirs/usr/ports/emulators/virtualbox-ose-additions-legacy/work/VirtualBox-5.2.44/src/VBox/Additions/freebsd/vboxvfs/vboxvfs.h:242:2: error: unknown type name 'uma_zone_t'
  242 |         uma_zone_t      sf_node_pool;
      |         ^

Reported by:	pkg-fallout
MFH:		2024Q3

(cherry picked from commit 6c6dcbf4e4864cb61234a3d09a73d0d607fbe657)