Fix build of polish/kadu
The update of qxmpp to the latest upstream release made qxmpp
require C++17, for std::optional. Kadu is forcing C++14, which
breaks in the build like this:
    In file included from plugins/jabber_protocol/services/jabber-room-chat-service.cpp:35:
    /usr/local/include/qxmpp/QXmppMessage.h:250:10: error: no template named 'optional' in namespace 'std'
        std::optional<QXmppMixInvitation> mixInvitation() const;

Bump the C++ requirement and patch the CMake bits that DTWT.