emulators/rpcs3: back out r507922 due to bustage on 11.2/12.0
- Broken with libc++ 6 and there's not enough time before the next bulk build.
- PORTEPOCH isn't necessary as if built it's good, and the update will return

rpcs3/util/atomic.cpp:55:51: error: no type named 'node_type' in 'std::__1::multimap<const void *, (anonymous namespace)::waiter, std::__1::less<const void *>, std::__1::allocator<std::__1::pair<const void *const, (anonymous namespace)::waiter> > >'; did you mean 'size_type'?
        thread_local std::multimap<const void*, waiter>::node_type s_tls_waiter = []()
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
                                                         size_type
/usr/include/c++/v1/map:1507:60: note: 'size_type' declared here
    typedef typename __alloc_traits::size_type             size_type;
                                                           ^
rpcs3/util/atomic.cpp:59:16: error: no member named 'extract' in 'std::__1::multimap<const void *, (anonymous namespace)::waiter, std::__1::less<const void *>, std::__1::allocator<std::__1::pair<const void *const, (anonymous namespace)::waiter> > >'
                return dummy.extract(dummy.emplace(nullptr, &s_tls_waiter));
                       ~~~~~ ^
rpcs3/util/atomic.cpp:55:61: error: cannot initialize a variable of type 'std::multimap<const void *, waiter>::size_type' (aka 'unsigned long') with an rvalue of type 'void'
        thread_local std::multimap<const void*, waiter>::node_type s_tls_waiter = []()
                                                                   ^              ~~~~
rpcs3/util/atomic.cpp:92:69: error: no type named 'node_type' in 'std::__1::multimap<const void *, (anonymous namespace)::waiter, std::__1::less<const void *>, std::__1::allocator<std::__1::pair<const void *const, (anonymous namespace)::waiter> > >'; did you mean 'size_type'?
                const auto ptls = static_cast<std::multimap<const void*, waiter>::node_type*>(found->second.tls_ptr);
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
                                                                                  size_type
/usr/include/c++/v1/map:1507:60: note: 'size_type' declared here
    typedef typename __alloc_traits::size_type             size_type;
                                                           ^
rpcs3/util/atomic.cpp:93:21: error: no member named 'extract' in 'std::__1::multimap<const void *, (anonymous namespace)::waiter, std::__1::less<const void *>, std::__1::allocator<std::__1::pair<const void *const, (anonymous namespace)::waiter> > >'
                *ptls = wmap.list.extract(found);
                        ~~~~~~~~~ ^
rpcs3/util/atomic.cpp:94:7: error: member reference base type 'unsigned long' is not a structure or union
                ptls->mapped().cond.notify_one();
                ~~~~^ ~~~~~~
6 errors generated.