sysutils/cni-dnsname: Fix arm64 build
golang.org/x/sys/unix fails to build on aarch64 because the pinned vendored
FpReg references an undefined uint128 type, at least on FreeBSD arm64:

  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go:400:12: undefined: uint128

Fake it with an equivalent 16x byte array, which is what upstream now does:

https://github.com/golang/go/blob/master/src/cmd/vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go#L337-L342

Sponsored by:	SkunkWerks, GmbH
Differential Revision:	https://reviews.freebsd.org/D59776
Approved by:	adrian