- Update to 6.47, announce message:
 Avoid crashing when users have the antiquated PyXML package
 installed. Python tries to be nice and loads it when we import xml, but it
 isn't compatible. Instead, we force Python to use the standard library xml
 module. [Daniel Miller]

 Fix a bug in DiffViewer causing this crash:
 TypeError: GtkTextBuffer.set_text() argument 1 must be string or read-only
 buffer, not NmapParserSAX
 Crash happened when trying to compare two scans within Zenmap. [Daniel Miller]

- USES python instead of USE_PYTHON=yes
- Use USE_PYTHON=distutils instead of USE_PYDISTUTILS=yes
- Use USE_PYTHON=autoplist instead of PYDISTUTILS_AUTOPLIST=yes