devel/py-virtualenv: Update to 20.16.7
- Update (BUILD|RUN|TEST)_DEPENDS list
- Update patch for docs/conf.pyp file
- Use pytest for testing
- Set the environment variable SETUPTOOLS_SCM_PRETEND_VERSION to fix the
  exception:

    LookupError: setuptools-scm was unable to detect version

- Disable QA_depends_blacklist when executing the test target, because
  virtualenv also requires python2 executable for some tests
- Set the test environment variable PYTHONPATH, so pytest can find the
  virtualenv library
- Force setuptools to create a temporary egg_info in build/lib during the build
  stage, so that sphinx can then create docs. Exception occurred:

  File "/usr/local/poudriere/ports/default/devel/py-virtualenv/work-py39/virtualenv-20.16.7/build/lib/
virtualenv/run/plugin/discovery.py", line 20, in get_discover
    default=next(iter(choices)),
StopIteration

  (raised only when virtualenv is not already installed in the system)
- Add devel/py-importlib-metadata to RUN_DEPENDS when using python3.7
- Reorder variables in Makefile

Port tested with all versions of Python currently supported.

Changelog:  https://github.com/pypa/virtualenv/releases/tag/20.16.7