games/openfodder: mark BROKEN on armv[67]
In file included from Source/ScriptingEngine.cpp:24:
In file included from ./Source/Utils/dukglue/dukglue.h:3:
In file included from ./Source/Utils/dukglue/register_function.h:3:
In file included from ./Source/Utils/dukglue/detail_function.h:3:
In file included from ./Source/Utils/dukglue/detail_stack.h:6:
In file included from ./Source/Utils/dukglue/detail_types.h:160:
./Source/Utils/dukglue/detail_primitive_types.h:52:3: error: redefinition of 'DukType<long long>'
                DUKGLUE_SIMPLE_VALUE_TYPE(time_t, duk_is_number, duk_get_uint, duk_push_uint, value)
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./Source/Utils/dukglue/detail_primitive_types.h:17:10: note: expanded from macro 'DUKGLUE_SIMPLE_VALUE_TYPE'
                struct DukType<TYPE> { \
                       ^~~~~~~~~~~~~
./Source/Utils/dukglue/detail_primitive_types.h:46:3: note: previous definition is here
                DUKGLUE_SIMPLE_VALUE_TYPE(int64_t, duk_is_number, duk_get_number, duk_push_number, value) // have to cast to double
                ^
./Source/Utils/dukglue/detail_primitive_types.h:17:10: note: expanded from macro 'DUKGLUE_SIMPLE_VALUE_TYPE'
                struct DukType<TYPE> { \
                       ^

Reported by:	pkg-fallout

(cherry picked from commit ca917fbf53d048edd527d7442a09ecb628a26ec8)