sysutils/flashrom: fix build on big-endian
compare_region_with_dump() is used only in a code for little-endian:
../libflashrom.c:458:12: error: unused function 'compare_region_with_dump' [-Werror,-Wunused-function]
  458 | static int compare_region_with_dump(const struct romentry *const a, const struct romentry *const b)
      |            ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.