devel/kf5-kio: fix compilation against ACL on recent current
The update of KDE Frameworks to 5.87 [1] broke compilation of devel/kf5-kio
on recent current:

	/usr/ports/devel/kf5-kio/work/kio-5.87.0/src/core/../aclhelpers_p.h:18:10:
	fatal error: 'acl/libacl.h' file not found
	#include <acl/libacl.h>
          ^~~~~~~~~~~~~~

Switch to using the compatiblity shim acl_portability.h.

[1] c1f36e0f27920678c4d9d1f80d5b02f8c8f40c38

PR:		259032
Reported by:	rhurlin