devel/llvm-devel: Update to new snapshot
Also disable OpenMP runtime on 12.  It fails to compile with:

/wrkdirs/usr/ports/devel/llvm-devel/work-default/llvm-project-6df5464a463b8ada2df167595286aa2b6510dd16/openmp/libomptarget/plugins-nextgen/common/PluginInterface/PluginInterface.cpp:425:14: error: call to deleted constructor of 'llvm::Error'
      return Err;
             ^~~
/wrkdirs/usr/ports/devel/llvm-devel/work-default/llvm-project-6df5464a463b8ada2df167595286aa2b6510dd16/llvm/include/llvm/Support/Error.h:185:3: note: 'Error' has been explicitly marked deleted here
  Error(const Error &Other) = delete;
  ^
/wrkdirs/usr/ports/devel/llvm-devel/work-default/llvm-project-6df5464a463b8ada2df167595286aa2b6510dd16/llvm/include/llvm/Support/Error.h:492:18: note: passing argument to parameter 'Err' here
  Expected(Error Err)
                 ^
1 error generated.