emulators/yuzu: unbreak on FreeBSD < 14 after 2b1bfad1edc3
externals/dynarmic/src/dynarmic/frontend/A64/translate/impl/simd_table_lookup.cpp:14:31: error: implicit instantiation of undefined template 'std::vector<Dynarmic::IR::TypedValue<Dynarmic::IR::Type::U128>>'
        std::vector<IR::U128> result;
                              ^
/usr/include/c++/v1/iosfwd:251:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
externals/dynarmic/src/dynarmic/frontend/A64/translate/impl/simd_table_lookup.cpp:13:34: error: no matching member function for call to 'VectorTable'
    const IR::Table table = v.ir.VectorTable([&] {
                            ~~~~~^~~~~~~~~~~
externals/dynarmic/src/dynarmic/../dynarmic/ir/ir_emitter.h:313:11: note: candidate function not viable: cannot convert argument of incomplete type 'void' to 'std::vector<U64>' (aka 'vector<TypedValue<Type::U64>>') for 1st argument
    Table VectorTable(std::vector<U64> values);
          ^
externals/dynarmic/src/dynarmic/../dynarmic/ir/ir_emitter.h:314:11: note: candidate function not viable: cannot convert argument of incomplete type 'void' to 'std::vector<U128>' (aka 'vector<TypedValue<Type::U128>>') for 1st argument
    Table VectorTable(std::vector<U128> values);
          ^

Reported by:	pkg-fallout

(cherry picked from commit 5699677747b1a52321aa7c2fc30517d87478cce7)