biology/libbigwig: Fix name-clashing in roundup
Rename the roundup method defined in bwValues.c as it clashes with the
roundup macro defined in sys/param.h

/wrkdirs/usr/ports/biology/libbigwig/work/libBigWig-0.4.7/bwValues.c:9:35:
error: too few arguments provided to function-like macro invocation
static uint32_t roundup(uint32_t v) {
                                  ^
/usr/include/sys/param.h:300:9: note: macro 'roundup' defined here
        ^
/wrkdirs/usr/ports/biology/libbigwig/work/libBigWig-0.4.7/bwValues.c:9:24:
error: expected ';' after top level declarator
static uint32_t roundup(uint32_t v) {
                       ^
                       ;
/wrkdirs/usr/ports/biology/libbigwig/work/libBigWig-0.4.7/bwValues.c:350:30:
error: too few arguments provided to function-like macro invocation
        o->m = roundup(o->l+1);
                             ^
/usr/include/sys/param.h:300:9: note: macro 'roundup' defined here
        ^
/wrkdirs/usr/ports/biology/libbigwig/work/libBigWig-0.4.7/bwValues.c:370:30:
error: too few arguments provided to function-like macro invocation
        o->m = roundup(o->l+1);
                             ^
/usr/include/sys/param.h:300:9: note: macro 'roundup' defined here
        ^
4 errors generated.

Approved by:	portmgr (blanket)