www/waterfox: unbreak with Rust 1.23
error: unused import: `std::ascii::AsciiExt`
  --> servo/components/style/gecko_string_cache/mod.rs:16:5
   |
16 | use std::ascii::AsciiExt;
   |     ^^^^^^^^^^^^^^^^^^^^
   |
note: lint level defined here
  --> servo/components/style/lib.rs:26:9
   |
26 | #![deny(warnings)]
   |         ^^^^^^^^
   = note: #[deny(unused_imports)] implied by #[deny(warnings)]

https://users.rust-lang.org/t/psa-dealing-with-warning-unused-import-std-ascii-asciiext-in-today-s-nightly/13726

Obtained from:	upstream