audio/HVSC-Update: Fix build with Clang 6
The configure check for ios::binary fails with

/usr/include/stdlib.h:97:1: error: function declared '[[noreturn]]' after its first declaration
_Noreturn void   exit(int);
^
/usr/include/sys/cdefs.h:280:22: note: expanded from macro '_Noreturn'
#define _Noreturn               [[noreturn]]
                                  ^
conftest.cc:9:6: note: declaration missing '[[noreturn]]' attribute is here
void exit (int);
     ^

which leads to the build falling back to using ios::bin due to
having HAVE_IOS_BIN defined.

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p475478_s336801/logs/errors/HVSC-Update-2.8.7.log