multimedia/vdr: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because multimedia/vdr's Makefile does not explicitly set its C++
standard, this leads to an error:

  util.c:269:4: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
     register int i;
     ^~~~~~~~~

Because the port's own Makefile is rather non-standard it does not
respect USE_CXXSTD=, so patch away the 'register' keyword instead.

PR:		271707
Approved by:	fernape
MFH:		2023Q2