devel/libunicode-contour: fix build on powerpc64le
Use clang's SSE translation, libunicode has intrinsics implemented
only for amd64 and arm64:
/wrkdirs/usr/ports/devel/libunicode-contour/work/libunicode-0.6.0/src/libunicode/scan.cpp:110:5: error: use of undeclared identifier 'intrinsics'
  110 |     intrinsics::m128i const ControlCodeMax = intrinsics::set1_epi8(0x20); // 0..0x1F
      |     ^

(cherry picked from commit b4adf0f2dd79607d012ab9c15503f3390f9fbc38)