multimedia/vdr-plugin-markad: fix build on GCC architectures
Linking to libx265 requires newer GCC:
//usr/local/lib/libx265.so.179: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
//usr/local/lib/libx265.so.179: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'