net-p2p/xbt: fix build on ARM / POWER
Tracker/tracker_input.cpp:6:49: error: constant expression evaluates to -1 which cannot be narrowed to type 'char' [-Wc++11-narrowing]
        std::array<char, 16> res = { 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0 };
                                                       ^~

(cherry picked from commit 735a7f11b1c53e58d7ab011b274724a84a8e5e15)