multimedia/gavl: opt in to sched* functions
Make sched* functions available as required by
	https://cgit.freebsd.org/src/commit/?id=90fa9705d5cd29cf11c5dc7319299788dec2546a

	benchmark.c:1854:7: warning: implicit declaration of function
	'sched_setaffinity' is invalid in C99
	[-Wimplicit-function-declaration] if(!sched_setaffinity(0,
	sizeof(cpuset), &cpuset))

PR:		259787