emulators/rpcs3: unbreak build on aarch64 after ee309cdf6c6f
Utilities/Thread.cpp:1799:48: error: comparison of integers of different signs: 'uptr' (aka 'unsigned long') and '__register_t' (aka 'long') [-Werror,-Wsign-compare]
        const bool is_executing = uptr(info->si_addr) == RIP(context);
                                  ~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~

Reported by:	pkg-fallout

(cherry picked from commit 9f3b835b596086e4def2fc1dc9c8d56e6253fb6d)