devel/raylib: mark as broken on arm7
In file included from /wrkdirs/usr/ports/devel/raylib/work/raylib-5.0/src/rtextures.c:216:
/wrkdirs/usr/ports/devel/raylib/work/raylib-5.0/src/external/stb_image_resize2.h:2422:22: error: implicit declaration of function 'vld1q_f16' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    float16x8_t in = vld1q_f16(input);
                     ^

Upstream bug report: https://github.com/nothings/stb/issues/1650

PR:	279369
MFH:	2024Q3
(cherry picked from commit 47f964b00b865120bd3a1935b7a4c84a3f15ed17)