Update to 20200424 to fix python 3.9 compatibility
The current version fails to build with Python 3.9:
triangle/core.c:20740:77: error: no member named 'tp_print' in 'struct _typeobject'
  __pyx_type_8triangle_4core___pyx_scope_struct____pyx_f_8triangle_4core_ii.tp_print = 0;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
triangle/core.c:20746:78: error: no member named 'tp_print' in 'struct _typeobject'
  __pyx_type_8triangle_4core___pyx_scope_struct_1___pyx_f_8triangle_4core_dd.tp_print = 0;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^

etc.

The latest version has been regenerated with newer Cython which supports 3.9.

PR:		ports/251469
Reported by:	Greg V <greg@unrelenting.technology>