www/py-qh3: fix build on big-endian architectures
Little-endian is misdetected and the little-endian code path is used:
/wrkdirs/usr/ports/www/py-qh3/work-py311/qh3-1.0.9/cargo-crates/aws-lc-sys-0.20.1/aws-lc/crypto/fipsmodule/sha/sha1-altivec.c:107:5: error: call to undeclared function 'vec_vsx_ld'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]