games/punchy: unbreak build on armv7
Fix files/patch-v8 to compile on armv7 by refactoring it to use
ELF auxilliary vectors in the CPU detection code and by adding
some missing includes.

cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:137:20: warning: implicit declaration of function 'READ_SPECIALREG' is invalid in C99 [-Wimplicit-function-declaration]
    id_aa64isar0 = READ_SPECIALREG(id_aa64isar0_el1);
                   ^
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:137:36: error: use of undeclared identifier 'id_aa64isar0_el1'; did you mean 'id_aa64isar0'?
    id_aa64isar0 = READ_SPECIALREG(id_aa64isar0_el1);
                                   ^~~~~~~~~~~~~~~~
                                   id_aa64isar0
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:136:14: note: 'id_aa64isar0' declared here
    uint64_t id_aa64isar0;
             ^
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:138:9: warning: implicit declaration of function 'ID_AA64ISAR0_AES' is invalid in C99 [-Wimplicit-function-declaration]
    if (ID_AA64ISAR0_AES_VAL(id_aa64isar0) == ID_AA64ISAR0_AES_PMULL)
        ^
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:42:30: note: expanded from macro 'ID_AA64ISAR0_AES_VAL'
 #define ID_AA64ISAR0_AES_VAL ID_AA64ISAR0_AES
                              ^
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:138:47: error: use of undeclared identifier 'ID_AA64ISAR0_AES_PMULL'; did you mean 'ID_AA64ISAR0_AES'?
    if (ID_AA64ISAR0_AES_VAL(id_aa64isar0) == ID_AA64ISAR0_AES_PMULL)
                                              ^~~~~~~~~~~~~~~~~~~~~~
                                              ID_AA64ISAR0_AES
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:138:9: note: 'ID_AA64ISAR0_AES' declared here
    if (ID_AA64ISAR0_AES_VAL(id_aa64isar0) == ID_AA64ISAR0_AES_PMULL)
        ^
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:42:30: note: expanded from macro 'ID_AA64ISAR0_AES_VAL'
 #define ID_AA64ISAR0_AES_VAL ID_AA64ISAR0_AES
                              ^
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:140:9: warning: implicit declaration of function 'ID_AA64ISAR0_CRC32' is invalid in C99 [-Wimplicit-function-declaration]
    if (ID_AA64ISAR0_CRC32_VAL(id_aa64isar0) == ID_AA64ISAR0_CRC32_BASE)
        ^
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:45:32: note: expanded from macro 'ID_AA64ISAR0_CRC32_VAL'
 #define ID_AA64ISAR0_CRC32_VAL ID_AA64ISAR0_CRC32
                                ^
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:140:49: error: use of undeclared identifier 'ID_AA64ISAR0_CRC32_BASE'; did you mean 'ID_AA64ISAR0_CRC32'?
    if (ID_AA64ISAR0_CRC32_VAL(id_aa64isar0) == ID_AA64ISAR0_CRC32_BASE)
                                                ^~~~~~~~~~~~~~~~~~~~~~~
                                                ID_AA64ISAR0_CRC32
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:140:9: note: 'ID_AA64ISAR0_CRC32' declared here
    if (ID_AA64ISAR0_CRC32_VAL(id_aa64isar0) == ID_AA64ISAR0_CRC32_BASE)
        ^
cargo-crates/v8-0.47.1/third_party/zlib/cpu_features.c:45:32: note: expanded from macro 'ID_AA64ISAR0_CRC32_VAL'
 #define ID_AA64ISAR0_CRC32_VAL ID_AA64ISAR0_CRC32
                                ^

PR:		271076
Reported by:	pkg-fallout

(cherry picked from commit 5acf5a02777bd9c6cce20980859c4316b267f6f2)