finance/favagtk: Add missing dependency
- The program requires www/webkit2-gtk@60, otherwise it fails with
the error:

Traceback (most recent call last):
  File "/usr/local/bin/favagtk", line 45, in <module>
    from favagtk import main
  File "/usr/local/share/favagtk/favagtk/main.py", line 20, in <module>
    from .app import FavagtkApplication
  File "/usr/local/share/favagtk/favagtk/app.py", line 27, in <module>
    from .window import FavagtkWindow
  File "/usr/local/share/favagtk/favagtk/window.py", line 25, in <module>
    gi.require_versions({"Gtk": "4.0", "WebKit": "6.0"})
  File "/usr/local/lib/python3.11/site-packages/gi/__init__.py", line 145, in require_versions
    require_version(module_name, module_version)
  File "/usr/local/lib/python3.11/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available

- Bump PORTREVISION