databases/firebird25-server: unbreak with ICU 63
In file included from ../src/jrd/unicode_util.cpp:41:
In file included from /usr/local/include/unicode/utrans.h:20:
/usr/local/include/unicode/localpointer.h:221:40: error: expected ';' at end of declaration list
    LocalPointer(LocalPointer<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                                       ^
/usr/local/include/unicode/localpointer.h:366:36: error: expected ';' at end of declaration list
    LocalArray(LocalArray<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                                   ^
In file included from ../src/jrd/unicode_util.cpp:41:
In file included from /usr/local/include/unicode/utrans.h:23:
/usr/local/include/unicode/uenum.h:68:1: error: expected ';' at end of declaration list
U_DEFINE_LOCAL_OPEN_POINTER(LocalUEnumerationPointer, UEnumeration, uenum_close);
^
/usr/local/include/unicode/localpointer.h:493:60: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                           ^
/usr/local/include/unicode/platform.h:503:23: note: expanded from macro 'U_NOEXCEPT'
 #   define U_NOEXCEPT noexcept
                       ^
In file included from ../src/jrd/unicode_util.cpp:41:
In file included from /usr/local/include/unicode/utrans.h:24:
/usr/local/include/unicode/uset.h:330:1: error: expected ';' at end of declaration list
U_DEFINE_LOCAL_OPEN_POINTER(LocalUSetPointer, USet, uset_close);
^
/usr/local/include/unicode/localpointer.h:493:60: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                           ^
/usr/local/include/unicode/platform.h:503:23: note: expanded from macro 'U_NOEXCEPT'
 #   define U_NOEXCEPT noexcept
                       ^
In file included from ../src/jrd/unicode_util.cpp:41:
/usr/local/include/unicode/utrans.h:255:1: error: expected ';' at end of declaration list
U_DEFINE_LOCAL_OPEN_POINTER(LocalUTransliteratorPointer, UTransliterator, utrans_close);
^
/usr/local/include/unicode/localpointer.h:493:60: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                           ^
/usr/local/include/unicode/platform.h:503:23: note: expanded from macro 'U_NOEXCEPT'
 #   define U_NOEXCEPT noexcept
                       ^
In file included from ../src/jrd/unicode_util.cpp:43:
/usr/local/include/unicode/ucnv.h:585:1: error: expected ';' at end of declaration list
U_DEFINE_LOCAL_OPEN_POINTER(LocalUConverterPointer, UConverter, ucnv_close);
^
/usr/local/include/unicode/localpointer.h:493:60: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                           ^
/usr/local/include/unicode/platform.h:503:23: note: expanded from macro 'U_NOEXCEPT'
 #   define U_NOEXCEPT noexcept
                       ^
In file included from ../src/jrd/unicode_util.cpp:44:
In file included from /usr/local/include/unicode/ucol.h:17:
In file included from /usr/local/include/unicode/unorm.h:25:
/usr/local/include/unicode/unorm2.h:261:1: error: expected ';' at end of declaration list
U_DEFINE_LOCAL_OPEN_POINTER(LocalUNormalizer2Pointer, UNormalizer2, unorm2_close);
^
/usr/local/include/unicode/localpointer.h:493:60: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                           ^
/usr/local/include/unicode/platform.h:503:23: note: expanded from macro 'U_NOEXCEPT'
 #   define U_NOEXCEPT noexcept
                       ^
In file included from ../src/jrd/unicode_util.cpp:44:
/usr/local/include/unicode/ucol.h:538:1: error: expected ';' at end of declaration list
U_DEFINE_LOCAL_OPEN_POINTER(LocalUCollatorPointer, UCollator, ucol_close);
^
/usr/local/include/unicode/localpointer.h:493:60: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                           ^
/usr/local/include/unicode/platform.h:503:23: note: expanded from macro 'U_NOEXCEPT'
 #   define U_NOEXCEPT noexcept
                       ^

Regressed by:	https://github.com/unicode-org/icu/commit/35ce5296c1d3
PR:		232300
Reported by:	antoine (via exp-run)