multimedia/wl-screenrec: document cagebreak isn't supported unlike cage
$ cagebreak
$ wl-screenrec
thread 'main' panicked at src/main.rs:851:14:
Your compositor does not seem to support the wlr-output-manager protocol. wl-screenrec requires a wlroots based compositor like sway or Hyprland: NotPresent
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace