security/openvpn-devel: fix up shebang of totpauth.py script
...and we also need to add USES+=python:build to fix
stage-qa complaints of the following kind:

Error: '/usr/local/bin/python' is an invalid shebang you need
USES=shebangfix for 'share/examples/openvpn/sample-scripts/totpauth.py'

ALTHOUGH the shebangfix has worked and replaced /usr/bin/python3
by /usr/local/bin/python (with /usr/local from LOCALBASE apparently).