databases/percona57-server: Mark IGNORE_SSL
- Fails to build with OpenSSL 3.0.0 and later with
  error: duplicate symbol: ossl_sa_ and as MySQL 5.7 did not get any
  updates for OpenSSL 3.0.0 and later it is highly unlikely that Percona
  will also get one.
- mark DEPRECATED as upstream will reach EOL on 2023-10-01
  See:
  https://www.percona.com/services/policies/percona-software-support-lifecycle
- Set EXPIRATION_DATE to 2023-10-01
- Fix a EOL space in pkg-plist
- Bump to show DEPRECATED message

Approved by:	portmgr (blanket)