x11-toolkits/wlroots: unbreak DRM=off build after a8bed4f81662
Error: Missing: include/wlr/types/wlr_drm_lease_v1.h

https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/59205cd93e8a
(cherry picked from commit c431da294b8278e30af4661f6caae2d3e708c3dd)