www/deno: attempt to fix the build on armv7
The v8 build system tries to pass --target=arm-linux-gnueabihf to
LLVM when building on ARM.  We are not Linux, so this confuses clang
to the point where it no longer finds basic include files.  Remove
that option to fix the build.  Some other ports were already patched
the same way.

With this roadblock out of the way, the port now fails as follows:

  In file included from ../../../deno-2.2.9/cargo-crates/v8-135.1.0/src/binding.cc:9:
  ../../../deno-2.2.9/cargo-crates/v8-135.1.0/v8/include/cppgc/allocation.h:175:9: error: static assertion failed due to requirement 'kWantedAlignment <= internal::api_constants::kMaxSupportedAlignment': Requested alignment larger than alignof(std::max_align_t) bytes. Please file a bug to possibly get this restriction lifted.
    175 |         kWantedAlignment <= internal::api_constants::kMaxSupportedAlignment,
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Approved by:	portmgr (build fix blanket)
MFH:		2025Q3