security/wolfssl: fix packageing (+)
Unbreak packaging after 5638b5ef1ff5d825cda9432d97540fd1fe4caa8c

===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/libwolfssl.so.35.5.1
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/libwolfssl.so.35.4.0
===> Error: Plist issues found.

Reported by:	poudriere fallout
Approved by:	portmgr blanket