multimedia/qt6-multimedia: track X11 dependencies after 230148d80ee0
====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/qt6/plugins/multimedia/libffmpegmediaplugin.so is linked to /usr/local/lib/libX11.so.6 from x11/libX11 but it is not declared as a dependency
Warning: you need USE_XORG+=x11
Error: /usr/local/lib/qt6/plugins/multimedia/libffmpegmediaplugin.so is linked to /usr/local/lib/libXrandr.so.2 from x11/libXrandr but it is not declared as a dependency
Warning: you need USE_XORG+=xrandr
Error: /usr/local/lib/qt6/plugins/multimedia/libffmpegmediaplugin.so is linked to /usr/local/lib/libXext.so.6 from x11/libXext but it is not declared as a dependency
Warning: you need USE_XORG+=xext

PR:		272736
Reported by:	Florian Walpen
Regressed by:	https://codereview.qt-project.org/c/qt/qtmultimedia/+/459506