x11-toolkits/libadwaita: temporarily block the next update
For example, updating to 1.0.0-alpha.4 (aka 2021-09-14 snapshot)
is currently blocked by the following:

https://gitlab.gnome.org/GNOME/libadwaita/-/commit/ad09941a6ae4
https://gitlab.gnome.org/World/Rust/libadwaita-rs/-/commit/45f6ac3e8e06

$ pkg install authenticator gnome-keyring-daemon
$ dbus-run-session sh
$ export $(gnome-keyring-daemon -r -d)
$ secret-tool store --label=Default foo bar
$ RUST_BACKTRACE=1 authenticator
<Click on Menu (hamburger button) then Providers (Ctrl+P)>
(<unknown>:1234): Gtk-CRITICAL **: Error building template class 'ProviderPage' for an instance of type 'ProviderPage': .:0:0 Invalid type 'AdwEnumValueObject'
thread 'main' panicked at 'assertion failed: !self.ptr.is_null()', gtk4-rs-13a8317a2ef8738362b9fa7f55a29dd5d3dbc459/gtk4/src/subclass/widget.rs:1147:13
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <gtk4::subclass::widget::TemplateChild<T> as core::ops::deref::Deref>::deref
             at gtk4-rs-13a8317a2ef8738362b9fa7f55a29dd5d3dbc459/gtk4/src/subclass/widget.rs:1147:13
   4: authenticator::widgets::providers::page::ProviderPage::setup_widgets
             at Authenticator-ba1894159358275be2765bc42ef89782a2d1d45d/src/widgets/providers/page.rs:415:9
   5: <authenticator::widgets::providers::page::imp::ProviderPage as glib::subclass::object::ObjectImpl>::constructed
             at Authenticator-ba1894159358275be2765bc42ef89782a2d1d45d/src/widgets/providers/page.rs:132:13
   6: glib::subclass::object::constructed
             at gtk3-rs-6e3c8739f9f5b8dc0a234f4a485e254574af5953/glib/src/subclass/object.rs:109:5
[...]