devel/loki: broken, deprecate
This is a support library for games/asc, which was removed from ports
in 2019.  Last upstream change was 2009, he's dead jim.  Also doesn't
build anywhere:

../include/loki/SmartPtr.h:1323:33: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
 1323 |             return OP::template Merge( rhs );
      |                                 ^

MFH:		2026Q1