databases/pyspatialite: Fix LOCALBASE substitution
Fix %%LOCALBASE substitution in patch-setup.cfg causing header detection to
fail with:

  __main__.HeaderNotFoundException: cannot find proj_api.h, bailing out

Reported by:		antoine, pkg-fallout
Differential Revision:	https://reviews.freebsd.org/D2704