games/CWR-CE: fix build on powerpc64le
In file included from /wrkdirs/usr/ports/games/CWR-CE/work/CWR-CE-9abbdf2769f3008d76c47ac0af219388ff0323dc/engine/Poseidon/Foundation/Math/V3QuadsP3.cpp:16:
/usr/lib/clang/19/include/ppc_wrappers/x86intrin.h:18:2: error: "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
   18 | #error "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
      |  ^

(cherry picked from commit 1b44bb905fa6afe491ddbeb82495684af6a85bc6)