multimedia/gstreamer1-plugins-rust: temp disable CSOUND on aarch64
error[E0308]: mismatched types
   --> cargo-crates/csound-sys-0.1.2/src/lib.rs:382:27
    |
382 |             device_name: [0i8; 64usize],
    |                           ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
382 |             device_name: [0u8; 64usize],
    |                           ^^^

error[E0308]: mismatched types
   --> cargo-crates/csound-sys-0.1.2/src/lib.rs:383:25
    |
383 |             device_id: [0i8; 64usize],
    |                         ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
383 |             device_id: [0u8; 64usize],
    |                         ^^^

error[E0308]: mismatched types
   --> cargo-crates/csound-sys-0.1.2/src/lib.rs:384:25
    |
384 |             rt_module: [0i8; 64usize],
    |                         ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
384 |             rt_module: [0u8; 64usize],
    |                         ^^^

error[E0308]: mismatched types
   --> cargo-crates/csound-sys-0.1.2/src/lib.rs:434:27
    |
434 |             device_name: [0i8; 64usize],
    |                           ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
434 |             device_name: [0u8; 64usize],
    |                           ^^^

error[E0308]: mismatched types
   --> cargo-crates/csound-sys-0.1.2/src/lib.rs:435:30
    |
435 |             interface_name: [0i8; 64usize],
    |                              ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
435 |             interface_name: [0u8; 64usize],
    |                              ^^^

error[E0308]: mismatched types
   --> cargo-crates/csound-sys-0.1.2/src/lib.rs:436:25
    |
436 |             device_id: [0i8; 64usize],
    |                         ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
436 |             device_id: [0u8; 64usize],
    |                         ^^^

error[E0308]: mismatched types
   --> cargo-crates/csound-sys-0.1.2/src/lib.rs:437:27
    |
437 |             midi_module: [0i8; 64usize],
    |                           ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
437 |             midi_module: [0u8; 64usize],
    |                           ^^^

Reported by:	pkg-fallout

(cherry picked from commit 90ca4606655b40d0be1abb162e087ec23a971792)