Mark net/kio-gdrive broken
/wrkdirs/usr/ports/net/kio-gdrive/work/kio-gdrive-1.2.6/src/kio_gdrive.cpp:382:38: error: no member named 'Id' in 'KGAPI2::Drive::FileFetchJob'
    fetchJob.setFields(FileFetchJob::Id | FileFetchJob::Title | FileFetchJob::Labels);

This was fixed upstream in 01ec4d87b2e28de5eb3c23ec469c6c746f573520,
but there hasn't been a release since then (and the number of commits
and fixes since 1.2.6 release is pretty large, I don't want to chase
backports just now).

Reported by:	pkg-fallout