devel/bossa: fix build with clang 18
Clang 18 has a new warning about variable length arrays used in C++,
which is emitted when building devel/bossa:

  src/Flasher.cpp:115:28: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
    115 |             uint8_t buffer[bufferSize];
        |                            ^~~~~~~~~~
  src/Flasher.cpp:115:28: note: read of non-const variable 'bufferSize' is not allowed in a constant expression
  src/Flasher.cpp:114:22: note: declared here
    114 |             uint32_t bufferSize = _samba.writeBufferSize();
        |                      ^
  [... more of these ...]

Since refactoring the code to no longer use VLAs is rather intrusive,
suppress the warnings instead.

While here, pet portlint.

PR:		276804
Approved by:	maintainer timeout (2 weeks)
MFH:		2024Q1