games/ecwolf: fix build
/usr/bin/c++ -DNO_GTK=1 -DUSE_GPL -Dstricmp=strcasecmp -Dstrnicmp=strncasecmp -I/wrkdirs/usr/ports/games/ecwolf/work/.build/src -I/wrkdirs/usr/ports/games/ecwolf/work/ecwolf-1.4.1-src/src -I/wrkdirs/usr/ports/games/ecwolf/work/ecwolf-1.4.1-src/src/g_shared -I/wrkdirs/usr/ports/games/ecwolf/work/ecwolf-1.4.1-src/deps/lzma/C -I/wrkdirs/usr/ports/games/ecwolf/work/.build/deps/gdtoa -I/wrkdirs/usr/ports/games/ecwolf/work/ecwolf-1.4.1-src/deps/gdtoa -isystem /usr/local/include/SDL2 -O2 -pipe -mcpu=power9 -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -O2 -pipe -mcpu=power9 -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -DNDEBUG -std=gnu++98 -Wall -Wextra -Wno-unused -Wno-unused-parameter -Wno-missing-field-initializers -MD -MT src/CMakeFiles/engine.dir/resourcefiles/file_vgagraph.cpp.o -MF src/CMakeFiles/engine.dir/resourcefiles/file_vgagraph.cpp.o.d -o src/CMakeFiles/engine.dir/resourcefiles/file_vgagraph.cpp.o -c /wrkdirs/usr/ports/games/ecwolf/work/ecwolf-1.4.1-src/src/resourcefiles/file_vgagraph.cpp
In file included from /wrkdirs/usr/ports/games/ecwolf/work/ecwolf-1.4.1-src/src/resourcefiles/file_vgagraph.cpp:40:
/wrkdirs/usr/ports/games/ecwolf/work/ecwolf-1.4.1-src/src/tmemory.h:479:11: error: cannot assign to variable 'other' with const-qualified type 'const Self &' (aka 'const TWeakPtr<Type> &')
  479 |                 other.r = oldref;
      |                 ~~~~~~~ ^
/wrkdirs/usr/ports/games/ecwolf/work/ecwolf-1.4.1-src/src/tmemory.h:472:24: note: variable 'other' declared const here
  472 |         void Swap(const Self &other)
      |                   ~~~~~~~~~~~~^~~~~
1 error generated.