Fix PLIST
- Bump PORTREVISION for package change
- While I'm here, sort *_DEPENDS

===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PYTHON_SITELIBDIR%%/xcffib/__pycache__/_ffi.cpython-36.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/xcffib/__pycache__/_ffi.cpython-36.pyc

Approved by:	portmgr (blanket)