lang/gnat15: remove -Werror
Compilation fails on arm64 because
enable-execute-stack.c:33:13: error: 'check_enabling' declared 'static' but never defined [-Werror=unused-function]
   33 | static void check_enabling (void) __attribute__ ((unused));
      |             ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors

PR:		292708
Reported by:	pkg-fallout