x11/eww: unbreak build after 6b9789547d5e
error[E0557]: feature has been removed
 --> crates/simplexpr/src/lib.rs:3:12
  |
3 | #![feature(box_syntax)]
  |            ^^^^^^^^^^ feature has been removed
  |
  = note: replaced with `#[rustc_box]`

error: `box_syntax` has been removed
  --> crates/simplexpr/src/eval.rs:72:58
   |
72 |             BinOp(span, box a, op, box b) => BinOp(span, box a.try_map_var_refs(f)?, op, box b.try_map_var_refs(f)?),
   |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: use `Box::new()` instead
   |
72 |             BinOp(span, box a, op, box b) => BinOp(span, Box::new(a.try_map_var_refs(f)?), op, box b.try_map_var_refs(f)?),
   |                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: `box_syntax` has been removed
  --> crates/simplexpr/src/eval.rs:72:90
   |
72 |             BinOp(span, box a, op, box b) => BinOp(span, box a.try_map_var_refs(f)?, op, box b.try_map_var_refs(f)?),
   |                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: use `Box::new()` instead
   |
72 |             BinOp(span, box a, op, box b) => BinOp(span, box a.try_map_var_refs(f)?, op, Box::new(b.try_map_var_refs(f)?)),
   |                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: `box_syntax` has been removed
  --> crates/simplexpr/src/eval.rs:74:59
   |
74 |             UnaryOp(span, op, box a) => UnaryOp(span, op, box a.try_map_var_refs(f)?),
   |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: use `Box::new()` instead
   |
74 |             UnaryOp(span, op, box a) => UnaryOp(span, op, Box::new(a.try_map_var_refs(f)?)),
   |                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: `box_syntax` has been removed
  --> crates/simplexpr/src/eval.rs:76:30
   |
76 |                 IfElse(span, box a.try_map_var_refs(f)?, box b.try_map_var_refs(f)?, box c.try_map_var_refs(f)?)
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: use `Box::new()` instead
   |
76 |                 IfElse(span, Box::new(a.try_map_var_refs(f)?), box b.try_map_var_refs(f)?, box c.try_map_var_refs(f)?)
   |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: `box_syntax` has been removed
  --> crates/simplexpr/src/eval.rs:76:58
   |
76 |                 IfElse(span, box a.try_map_var_refs(f)?, box b.try_map_var_refs(f)?, box c.try_map_var_refs(f)?)
   |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: use `Box::new()` instead
   |
76 |                 IfElse(span, box a.try_map_var_refs(f)?, Box::new(b.try_map_var_refs(f)?), box c.try_map_var_refs(f)?)
   |                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: `box_syntax` has been removed
  --> crates/simplexpr/src/eval.rs:76:86
   |
76 |                 IfElse(span, box a.try_map_var_refs(f)?, box b.try_map_var_refs(f)?, box c.try_map_var_refs(f)?)
   |                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: use `Box::new()` instead
   |
76 |                 IfElse(span, box a.try_map_var_refs(f)?, box b.try_map_var_refs(f)?, Box::new(c.try_map_var_refs(f)?))
   |                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: `box_syntax` has been removed
  --> crates/simplexpr/src/eval.rs:78:64
   |
78 |             JsonAccess(span, box a, box b) => JsonAccess(span, box a.try_map_var_refs(f)?, box b.try_map_var_refs(f)?),
   |                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: use `Box::new()` instead
   |
78 |             JsonAccess(span, box a, box b) => JsonAccess(span, Box::new(a.try_map_var_refs(f)?), box b.try_map_var_refs(f)?),
   |                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: `box_syntax` has been removed
  --> crates/simplexpr/src/eval.rs:78:92
   |
78 |             JsonAccess(span, box a, box b) => JsonAccess(span, box a.try_map_var_refs(f)?, box b.try_map_var_refs(f)?),
   |                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: use `Box::new()` instead
   |
78 |             JsonAccess(span, box a, box b) => JsonAccess(span, box a.try_map_var_refs(f)?, Box::new(b.try_map_var_refs(f)?)),
   |                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Reported by:	pkg-fallout