devel/cargo-c: unbreak WITH_DEBUG in consumers after c9724410bb38
error: The argument '--debug <debug>' requires a value but none was supplied

Reported by:	mizhka
Regressed by:	https://github.com/lu-zero/cargo-c/commit/32f7e107b17c