devel/elfutils: Fix build with GCC 9
In file included from ../config.h:132,
                 from elf32_fsize.c:31:
libelfP.h:47:30: error: '__elf32_msize' specifies less restrictive attribute than its target 'elf32_fsize': 'const' [-Werror=missing-attributes]
   47 | #define __elfw2_(Bits, Name) __elf##Bits##_##Name
      |                              ^~~~~

http://package22.nyi.freebsd.org/data/112amd64-default-PR238330/2019-06-09_20h29m30s/logs/errors/elfutils-0.174_2.log

Cherry pick upstream commit be8080bdd746ac2b07fb0bcad23a9677844bb200

PR:		238538
Submitted by:	tobik
Reported by:	gerald, antoine (via exp-run)
Approved by:	cem (maintainer)