japanese/FreeWnn-lib: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
japanese/FreeWnn-lib failed to build with clang 15:

  js.c:1029:28: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'int' [-Wint-conversion]
    handler_of_jserver_dead (NULL);
                                 ^~~~
  /usr/include/sys/_null.h:34:14: note: expanded from macro 'NULL'
  #define NULL    ((void *)0)
                      ^~~~~~~~~~~
  js.c:150:24: note: expanded from macro 'handler_of_jserver_dead'
                  return err_val; \
                             ^~~~~~~

This is because the js_disconnect() function should return an integer,
not a pointer. Use the error value -1 instead.

PR:	268816