MFH: r526357 devel/py-Faker: Add missing dependencies
None of the packages upstream specified dependencies were declared in the
port. This change adds those missing dependencies.

The issue was identified while QA'ing www/py-freenit via bug 242817

File "/usr/local/lib/python3.7/site-packages/faker/providers/internet/__init__.py", line 4, in <module>
    from text_unidecode import unidecode
ModuleNotFoundError: No module named 'text_unidecode'

While I'm here, level up ports (and Python ports) compliance and add test
target.

Approved by:	portmgr (blanket(s): missing dependencies, ports (Python) compliance)

Approved by:	ports-secteam (blanket(s): missing dependencies, ports (Python) compliance)