x11/xdg-desktop-portal-luminous: mark BROKEN on 32-bit after 2190ca1e79e6
error[E0283]: type annotations needed
   --> src/remotedesktop/state.rs:139:47
    |
139 |                 if state == KeyState::Pressed.into() {
    |                          --                   ^^^^
    |                          |
    |                          type must be known at this point
    |
    = note: multiple `impl`s satisfying `u32: PartialEq<_>` found in the following crates: `core`, `glib`:
            - impl PartialEq for u32;
            - impl PartialEq<glib::types::ULong> for u32;
help: try using a fully qualified path to specify the expected types
    |
139 -                 if state == KeyState::Pressed.into() {
139 +                 if state == <KeyState as Into<T>>::into(KeyState::Pressed) {
    |

error[E0283]: type annotations needed
   --> src/remotedesktop/state.rs:146:47
    |
146 |                 if state == KeyState::Pressed.into() {
    |                          --                   ^^^^
    |                          |
    |                          type must be known at this point
    |
    = note: multiple `impl`s satisfying `u32: PartialEq<_>` found in the following crates: `core`, `glib`:
            - impl PartialEq for u32;
            - impl PartialEq<glib::types::ULong> for u32;
help: try using a fully qualified path to specify the expected types
    |
146 -                 if state == KeyState::Pressed.into() {
146 +                 if state == <KeyState as Into<T>>::into(KeyState::Pressed) {
    |

Reported by:	pkg-fallout

(cherry picked from commit 4e191f5c257c3fd646a940b60308d789f778b3f9)