sysutils/44bsd-more: Fix build with LLVM16
main.c:440:22: error: incompatible function pointer types passing 'int (void *, char *, size_t)' (aka 'int (void *, char *, unsigned long)') to parameter of type 'int (* _Nullable)(void *, char *, int)' [-Wincompatible-function-pointer-types]
                fd = fropen(DEFRC, str_read);
                                   ^~~~~~~~

MFH:	2023Q3
(cherry picked from commit 6bef86a7ad93c1c38df8c3266340796746e0aa32)