devel/android-tools-adb: switch to LIBUSB_CAP_HAS_HOTPLUG whitelist
$ adb connect 1.2.3.4
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 1193
--- adb starting (pid 1193) ---
adb I 12-31 10:41:58  1193     1 main.cpp:56] Android Debug Bridge version 1.0.40
adb I 12-31 10:41:58  1193     1 main.cpp:56] Version 28.0.0-0
adb I 12-31 10:41:58  1193     1 main.cpp:56] Installed as /usr/pkg/bin/adb
adb I 12-31 10:41:58  1193     1 main.cpp:56]
adb F 12-31 10:41:58  1193     1 usb_libusb.cpp:517] failed to register libusb hotplug callback

* failed to start daemon
error: cannot connect to daemon