emulators/mupen64plus-video-glide64mk2: fix build with clang 18
I am unsure if clang 18 actually has anything to do with it, but
whatever the case, emulators/mupen64plus-video-glide64mk2 does not
build:

    CXX _obj/Glide64/rdp.o
../../src/Glide64/rdp.cpp:1863:11: error: use of undeclared identifier 'bswap32'
 1863 |     *v5 = bswap32(v12);
      |           ^

And a bunch more of these. Fix it by including <sys/endian.h> in the
__FreeBSD__ case in src/Glide64/Util.h.

PR:		278001
Approved by:	maintainer timeout (2 weeks)
MFH:		2024Q2

(cherry picked from commit 39dd48012d9233d058e7622db3e45d0f2f5e28e3)