MFH: r485645
www/google-sitemapgen: Fix obvious typo

It causes problems later:

Writing index file "sitemap_index.xml" with 13 Sitemaps
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sitemap_gen.py", line 2092, in <module>
    sitemap.Generate()
  File "/usr/local/lib/python2.7/site-packages/sitemap_gen.py", line 1665, in Generate
    self.WriteIndex()
  File "/usr/local/lib/python2.7/site-packages/sitemap_gen.py", line 1810, in WriteIndex
    fd.write(sitemap_index_header)
UnboundLocalError: local variable 'sitemap_index_header' referenced before assignment

PR:		233427
Submitted by:	Vladislav Movchan <vladislav.movchan@gmail.com>

Approved by:	ports-secteam blanket