graphics/embree: fix build with clang 19
Clang 19 has become more strict about errors in member functions, which
results in errors building graphics/embree:

  /wrkdirs/usr/ports/graphics/embree/work/embree-3.13.5/kernels/geometry/../common/../subdiv/bezier_curve.h:138:56: error: no member named 'u' in 'QuadraticBezierCurve<V>'
    138 |         return cout << "QuadraticBezierCurve ( (" << a.u.lower << ", " << a.u.upper << "), " << a.v0 << ", " << a.v1 << ", " << a.v2 << ")";
        |                                                      ~ ^
  /wrkdirs/usr/ports/graphics/embree/work/embree-3.13.5/kernels/geometry/../common/../subdiv/bezier_curve.h:138:77: error: no member named 'u' in 'QuadraticBezierCurve<V>'
    138 |         return cout << "QuadraticBezierCurve ( (" << a.u.lower << ", " << a.u.upper << "), " << a.v0 << ", " << a.v1 << ", " << a.v2 << ")";
        |                                                                           ~ ^

Upstream fixed this for https://github.com/RenderKit/embree/issues/486
in https://github.com/RenderKit/embree/commit/cda4cf191, so add a
PATCHFILES entry for it.

PR:		281868
Approved by:	danfe (maintainer)
MFH:		2024Q3

(cherry picked from commit 7bf7810c8515f9008d6c86ca88a9838aeb886942)