MFH: r414065
During the exp-run in bug 208158, it was found that dns/powerdns gives
errors with libc++ 3.8.0:

dnspacket.cc:645:6: error: call to 'abs' is ambiguous
  if(abs(trc->d_time - now) > trc->d_fudge) {
     ^~~

This is because abs() is being called with unsigned arguments.  Import
upstream commit f2d05dd to fix it.

Approved by:	portmgr (junovitch)
PR:		208725