graphics/birdfont: fix build on powerpc
ld: error: ./build/bin/libbirdgems.so: undefined reference to sqrt [--no-allow-shlib-undefined]
(cherry picked from commit 95c8e8dc31a0c1c9692ef646dd361421b8c4a1dd)