security/krb5-120: MIT KRB5 1.20 does not support LibreSSL
MIT KRB5 does not support LibreSSL and requires a function only
found in OpenSSL. Therefore mark libressl and libressl-devel IGNORE.

pkinit_crypto_openssl.c:334:14: error: implicit declaration of function
'EVP_PKEY_param_check' is invalid in C99
[-Werror,-Wimplicit-function-declaration]
    result = EVP_PKEY_param_check(ctx);

EVP_PKEY_param_check(), an OpenSSL function, is not supported by LibreSSL.