audio/py-aubio: Fix build with Clang >= 16
python/ext/ufuncs.c:48:3: error: incompatible function pointer types
initializing 'PyUFuncGenericFunction'

Const qualifiers were added to the dimension and strides arguments of
PyUFuncGenericFunction in NumPy 1.19.0 [1]. This was previously a
warning, but Clang 16 has -Werror=incompatible-function-pointer-types
turned on by default.

[1] https://github.com/numpy/numpy/commit/e94cec800304a6a467cf90ce4e7d3e207770b4b4

Reported by:	pkg-fallout