sysutils/syslog-ng: Fix plist error when building with PYTHON option
When building with python support:

---Begin OPTIONS List---
===> The following configuration options are available for syslog-ng-4.4.0:
[...]
     PYTHON=on: Build with Python 3.9 support

Some files are orphaned:

===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/syslog-ng/python/syslogng/__pycache__/reloc%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: lib/syslog-ng/python/syslogng/reloc.py

The initial patch was created by romain@ and the updated patch came from
Peter Czanik, a syslog-ng developer.

PR:		274187
Submitted by:	Original patch by romain@
Submitted by:	Peter Czanik (CzP) <peter.czanik@oneidentity.com>
                Balabit (a OneIdentity company) / syslog-ng upstream
		Updated patch
MFH:		2023Q4