emulators/wine-devel: Fix the build in dlls/nsiproxy.sys
In what looks like a change between FreeBSD 11 and FreeBSD 12 and later
we now need to explicitly include sys/queue.h to avoid

   In file included from dlls/nsiproxy.sys/tcp.c:42:
   /usr/include/netinet/tcp_var.h:516:2: error:
   expected specifier-qualifier-list before 'TAILQ_ENTRY'
   516 | TAILQ_ENTRY(tcptw)  tw_2msl;

I submitted this upstream already where it got accepted, so this patch
files/patch-dlls-nsiproxy.sys is only a temporary stop gap.