games/anki: Switch to PyQt6
* This also fixes runtime errors [1] that occur in environments where
  PyQt5 and PyQt6 are present.  In that case Anki prefers PyQt6 over
  PyQt5 upon invocation which leads then to following error:

$ anki
Running with temporary Qt5 compatibility shims.
Run with DISABLE_QT5_COMPAT=1 to confirm compatibility with Qt6.
Traceback (most recent call last):
  File "/usr/local/bin/anki", line 7, in <module>
    import aqt
  File "/usr/local/share/anki/aqt/__init__.py", line 74, in <module>
    from aqt.main import AnkiQt  # isort:skip
  File "/usr/local/share/anki/aqt/main.py", line 20, in <module>
    import aqt.forms
  File "/usr/local/share/anki/aqt/forms/__init__.py", line 1, in <module>
    from . import about
  File "/usr/local/share/anki/aqt/forms/about.py", line 3, in <module>
    from .about_qt6 import *
  File "/usr/local/share/anki/aqt/forms/about_qt6.py", line 45, in <module>
    import icons_rc
ModuleNotFoundError: No module named 'icons_rc'

* Amend a minor issue while I'm here:  devel/py-sip is only required for
  build, set it accordingly.

* Bump PORTREVISION due changed dependencies and to regenerate the code
  (rust, js) in conjunction with PyQt6.

Reported by:	Robin Dapp, Michael Reim (via e-mail) [1]
MFH:		No (PyQt6 not present in 2023Q1)