graphics/py-s2: fix build on powerpc64 head
__builtin_bpermd with clang requires POWER7 or later:
In file included from CMakeFiles/_pywraps2.dir/s2PYTHON_wrap.cxx:4427:
In file included from /usr/local/include/s2/util/coding/coder.h:32:
In file included from /usr/local/include/s2/util/coding/varint.h:41:
/usr/local/include/s2/util/bits/bits.h:509:19: error: this builtin is only valid on POWER7 or later CPUs
  uint64 result = __builtin_bpermd(0x3f3e3d3c3b3a3938, temp);

But GCC can use __builtin_bpermd without resorting to forcing POWER7.