security/vuxml: Fix missing <name> field
I wasn't able to see my mistake based on the error "make validate"
gave me:

    Traceback (most recent call last):
      File "/usr/local/poudriere/ports/current-patched/security/vuxml/files/extra-validation.py", line 99, in <module>
	if (re_invalid_package_name.search(name.text) is not None):
    TypeError: expected string or bytes-like object
    *** Error code 1

Thanks to Dan for the pointy hat save.

Reported by:	Dan Langille