devel/py-apispec: py-prance is required as a runtime dependency
When running apispec, the following message has been displayed:

ModuleNotFoundError: validate_spec requires prance to be installed.

Installing devel/py-prance fixed the problem.

PR:		262344
Approved by:	Goran Mekić (maintainer)