audio/festival: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because audio/festival's build infrastructure does not explicitly set
its C++ standard, this leads to an error:

  regexp.cc:178:22: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  STATIC char *regnext(register char *p);
                       ^~~~~~~~~

To work around the error, add USE_CXXSTD=gnu++11 to compile for C++11
with GNU extensions instead. While here, pet portlint a little.

PR:		272014
Approved by:	fernape
MFH:		2023Q2