Add upstream commit to fix build errors with -pedantic.
This fixes at least devel/ccrtp's build on 9.3, which is currently broken:

  In file included from ccrtp/crypto/gcrypt/gcrypthmac.cpp:23:
  /usr/local/include/gcrypt.h:509: error: comma at end of enumerator list
  /usr/local/include/gcrypt.h:1346: error: comma at end of enumerator list
  Makefile:571: recipe for target 'gcrypthmac.lo' failed

MFH'ing this is not necessary, this bug is only present in libgcrypt 1.6.4.

PR:		205000
Approved by:	maintainer timeout (15 days)