devel/ocaml-cmdliner: prepare for OCaml 4.06+
- Update to version 1.0.4, now licensed under ISCL
- Set LICENSE_FILE as it is not just a boilerplate but contains
  actual copyright information
- Drop dependency on `devel/ocaml-ocamlbuild' (unused since v1.0.3)
- Don't hand-roll build and installation routines, use provided
- Convert to static pkg-plist and install documentation files
- Mark as parallel build unsafe for the moment due to this error:

    File "cmdliner.ml", line 1:
    Error: Corrupted compilation unit description

  or this:

    File "cmdliner.ml", line 1:
    Error: The files cmdliner_arg.cmi and cmdliner_term.cmi
    make inconsistent assumptions over interface Cmdliner_term