www/dooble: Fix build on 16-CURRENT
In file included from Source/dooble_charts_file.cc:30:
In file included from /usr/local/include/qt6/QtQml/QJSEngine:1:
In file included from /usr/local/include/qt6/QtQml/qjsengine.h:12:
/usr/local/include/qt6/QtCore/qtimezone.h:85:9: error: '= delete' with a message is a C++2c extension [-Werror,-Wc++26-extensions]
   85 |         "Would be treated as int offsetSeconds. "
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   86 |         "Use QTimeZone::UTC or QTimeZone::LocalTime instead.");
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/qt6/QtCore/qcompilerdetection.h:1041:49: note: expanded from macro 'Q_DECL_EQ_DELETE_X'
 1041 | #    define Q_DECL_EQ_DELETE_X(reason) = delete(reason)
      |                                                 ^~~~~~

PR:		295116
Reported by:	pkg-fallout
Sponsored by:	UNIS Labs
MFH:		2026Q2

(cherry picked from commit ce86bc65f1a6f19fb2861f03f1c902efd45f067c)