x11/waybar: prevent fetch during build
Run-time dependency catch2 found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency catch2
Downloading catch2 source from https://github.com/catchorg/Catch2/archive/v3.1.0.tar.gz
Download size: 1031425
Downloading: ..........
Downloading catch2 patch from https://wrapdb.mesonbuild.com/v2/catch2_3.1.0-1/get_patch
Download size: 4889
Downloading: ..........

Executing subproject catch2

catch2| Project name: catch2
catch2| Project version: 3.1.0
catch2| C++ compiler for the host machine: c++ (clang 13.0.0 "FreeBSD clang version 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)")
catch2| C++ linker for the host machine: c++ ld.lld 13.0.0
catch2| Configuring catch_user_config.hpp using configuration
catch2| Build targets in project: 39
catch2| Subproject catch2 finished.

Dependency catch2 from subproject subprojects/Catch2-3.1.0 found: YES 3.1.0

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: include/catch2/benchmark/catch_benchmark.hpp
[...]
Error: Orphaned: include/catch2/catch_all.hpp
[...]
Error: Orphaned: lib/libCatch2.a
Error: Orphaned: lib/libCatch2Main.a
Error: Orphaned: libdata/pkgconfig/catch2-with-main.pc
Error: Orphaned: libdata/pkgconfig/catch2.pc
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1