graphics/libyuv: track libjpeg dependency
-- Found JPEG: /usr/local/lib/libjpeg.so (found version "80")
[...]
Error: /usr/local/bin/yuvconvert is linked to /usr/local/lib/libjpeg.so.8 from graphics/jpeg-turbo but it is not declared as a dependency
Warning: you need USES+=jpeg

PR:		267163
(cherry picked from commit 78d127100976a6e431088b58b887c297ccf87573)