emulators/frodo: fix build on powerpc64le
While base GCC can build this port on 12.2, clang can't:
VIC.cpp:1407:8: error: expected unqualified-id
static asm void fastcopy(register uchar *dst, register uchar *src);
       ^
VIC.cpp:1408:8: error: expected unqualified-id
static asm void fastcopy(register uchar *dst, register uchar *src)
       ^
VIC.cpp:1838:3: error: use of undeclared identifier 'fastcopy'
                fastcopy(chunky_line_start, (uint8 *)chunky_tmp);

It also can't build with USES=compiler:gcc-c++11-lib.
Since this port doesn't have reverse dependencies, use USE_GCC=yes.