java/openjdk18: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
java/openjdk18 failed to build with clang 15:

  /wrkdirs/usr/ports/java/openjdk18/work/jdk18u-jdk-18.0.2-9-1/src/java.base/unix/native/libnet/DefaultProxySelector.c:374:41: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
      proxies = (*g_proxy_resolver_lookup)(resolver, uri, NULL, &error);
                                          ^
  /wrkdirs/usr/ports/java/openjdk18/work/jdk18u-jdk-18.0.2-9-1/src/java.base/unix/native/libnet/DefaultProxySelector.c:393:63: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
                                  (*g_network_address_parse_uri)(proxies[i], 0,
                                                                ^
  /wrkdirs/usr/ports/java/openjdk18/work/jdk18u-jdk-18.0.2-9-1/src/java.base/unix/native/libnet/DefaultProxySelector.c:398:70: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
                              phost = (*g_network_address_get_hostname)(conn);
                                                                       ^
  /wrkdirs/usr/ports/java/openjdk18/work/jdk18u-jdk-18.0.2-9-1/src/java.base/unix/native/libnet/DefaultProxySelector.c:399:66: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
                              pport = (*g_network_address_get_port)(conn);
                                                                   ^
  /wrkdirs/usr/ports/java/openjdk18/work/jdk18u-jdk-18.0.2-9-1/src/java.base/unix/native/libnet/DefaultProxySelector.c:435:22: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
          (*g_strfreev)(proxies);
                       ^

This is because clang 15 warns by default about functions without
arguments in their prototypes. Fix this by suppressing the warning.

PR:		268373
Approved by:	portmgr (tcberner)
MFH:		2022Q4