www/hurl: mark hurl build broken for i386
Hurl build fails for i386 architectures due to mismatch error during
bindgen tests for libxml.

```
error[E0080]: evaluation of constant value failed
   --> /home/jc/rust-libxml/target/debug/build/libxml-0db722a43088e767/out/bindings.rs:407:29
    |
407 |   ["Size of __max_align_t"][::std::mem::size_of::<__max_align_t>() - 20usize];
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempt to compute `16_usize - 20_usize`, which would overflow
```

A GH issue reports[1][2][3] where created for this problem and for now the only bypass
found was to disable the test. Which is wrong.

[1] https://github.com/Orange-OpenSource/hurl/issues/4400
[2] https://github.com/KWARC/rust-libxml/issues/186
[3] https://github.com/rust-lang/rust-bindgen/issues/3319