x11/i3bar-river: unbreak build after dfc55c4ee063
error[E0658]: `c".."` literals are experimental
  --> src/bar.rs:61:13
   |
61 |             c"i3bar-river".into(),
   |             ^^^^^^^^^^^^^^
   |
   = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information

error[E0658]: `c".."` literals are experimental
   --> src/wm_info_provider/river.rs:118:33
    |
118 |             PointerBtn::Left => c"set-focused-tags",
    |                                 ^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information

error[E0658]: `c".."` literals are experimental
   --> src/wm_info_provider/river.rs:119:34
    |
119 |             PointerBtn::Right => c"toggle-focused-tags",
    |                                  ^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information

Reported by:	pkg-fallout
(direct commit to 2024Q1 as 73941e6741d6 is missing on the branch)