deskutils/plan: Fix LLVM16 build
Fix the following LLVM16 error:

main.c:126:9: error: incompatible function pointer types passing 'void (int)' to parameter of type 'void (* _Nonnull)(void)' [-Wincompatible-function-pointer-types]
        atexit(plan_exit);
               ^~~~~~~~~
/usr/include/stdlib.h:92:29: note: passing argument to parameter here
int      atexit(void (* _Nonnull)(void));
                                ^

MFH:	2023Q2
(cherry picked from commit 2db8958749548677ec7b28cb449a44c6401548ec)