devel/simdjson: fix build on powerpc64
FreeBSD uses sys/endian.h header instead of byteswap.h and bswap64() instead of bswap_64().

-mpower8-vector is necessary because the port uses new SIMD introduced in POWER8.
/wrkdirs/usr/ports/devel/simdjson/work/simdjson-0.9.5/include/simdjson/ppc64/numberparsing.h:4:10: fatal error: 'byteswap.h' file not found