misc/broot: Unbreak build with CLIENT_SERVER
client-server is no longer feature gated, so
we can safely remove the OPTION all together.

===> Building for broot-1.6.1_1
error: Package `broot v1.6.1 does not have the feature `client-server`

Reported-by:	pkg-fallout