net/tigervnc-server: fix build on GCC architectures
C11 compiler is required:
../include/glx_extinit.h:33: error: redefinition of typedef '__GLXscreen'

MFH:		2020Q2 (fix build blanket)2020Q2 (fix build blanket)