www/rubygem-passenger: Fix PLIST issue
from poudriere (with -t flag):
[00:03:27] [02] [00:00:00] Building www/rubygem-passenger@apache | rubygem-passenger-apache-6.0.12_1
[00:07:27] [02] [00:04:00] Finished www/rubygem-passenger@apache | rubygem-passenger-apache-6.0.12_1: Failed: check-plist

from poudriere build log:
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: bin/%%AP_NAME%%-install-apache2-module
Error: Orphaned: bin/%%AP_NAME%%-install-nginx-module
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/www/rubygem-passenger
=>> Error: check-plist failures detected
=>> Cleaning up wrkdir
===>  Cleaning for rubygem-passenger-apache-6.0.12_1

Approved by:	portmgr (blanket)