www/varnish7: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
www/varnish7 failed to build with clang 15:

  adler32.c:189:15: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
  uLong ZEXPORT adler32(adler, buf, len)
                ^

This is because varnish needlessly builds with -Werror. Turn it off, so
the warnings can simply be ignored.

PR:		268814
Approved by:	dbaio (maintainer)
MFH:		2023Q1