audio/pulseaudio: unbreak build with clang 15
checking whether C compiler accepts -std=gnu11... no
configure: error: *** Compiler does not support -std=gnu11
[...]
configure:9379: cc -c -O2 -pipe  -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -pedantic -Werror -std=gnu11 -DLIBICONV_PLUG -isystem /usr/local/include conftest.c >&5
conftest.c:33:6: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
main ()
     ^
      void

https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/commit/1afd23363018
https://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=commitdiff;h=1717921aa6c1

PR:		268250
Reported by:	antoine (via bug 265425 exp-run)

(cherry picked from commit a968b5fd5ef3b5a20c5d507697e354cfa5d07743)