astro/cfitsio: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
astro/cfitsio failed to build with clang 15:

  drvrnet.c:3887:23: warning: call to undeclared function 'gethostbyname'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
              hostent = gethostbyname(localhost);
                        ^
  drvrnet.c:3887:21: error: incompatible integer to pointer conversion assigning to 'struct hostent *' from 'int' [-Wint-conversion]
              hostent = gethostbyname(localhost);
                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~
  1 warning and 1 error generated.

This is because the configure script defines _XOPEN_SOURCE=700, for
unclear reasons, and this hides the gethostbyname() declaration in
/usr/include/netdb.h. Fix it by removing the line that adds the define.

PR:		268302
Approved by:	portmgr (tcberner)
MFH:		2022Q4