textproc/wv: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
textproc/wv failed to build with clang 15:

  wvSummary.c:104:17: error: incompatible integer to pointer conversion initializing 'const GValue *' (aka 'const struct _GValue *') with an expression of type 'int' [-Wint-conversion]
    GValue const *val = gsf_doc_prop_get_val  (prop);
                  ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  wvSummary.c:146:21: error: incompatible integer to pointer conversion initializing 'GsfDocMetaData *' (aka 'struct _GsfDocMetaData *') with an expression of type 'int' [-Wint-conversion]
      GsfDocMetaData *meta_data = gsf_doc_meta_data_new ();
                      ^           ~~~~~~~~~~~~~~~~~~~~~~~~

Those functions are declared in <gsf/gsf-doc-meta-data.h>, but that
header is not included in wvSummary.c.

PR:		268399
Approved by:	portmgr (tcberner)
MFH:		2022Q4