Add a patch to fix the build with Clang 6.0.
    ../../../../CPP/Windows/ErrorMsg.cpp:24:10: error: case value evaluates to -2147024809, which cannot be narrowed to type 'DWORD' (aka 'unsigned int') [-Wc++11-narrowing]
        case E_INVALIDARG          : txt = "E_INVALIDARG"; break ;
             ^
    ../../../../CPP/Common/MyWindows.h:89:22: note: expanded from macro 'E_INVALIDARG'
    #define E_INVALIDARG ((HRESULT)0x80070057L)
                         ^

HRESULT causes the macro to be parsed as a signed long, so we need to force it
to be checked as an unsigned long instead.

PR:		224930