devel/rubygem-concurrent-ruby: bugfix update to 1.2.2
Release v1.2.2 (24 Feb 2023)
    (#993) Fix arguments passed to Concurrent::Map's default_proc.

Changelog:
https://github.com/ruby-concurrency/concurrent-ruby/blob/master/CHANGELOG.md

This fixes a runtime error fpr e.g. www/gitlab-ce:
rake aborted!
NoMethodError: undefined method `fetch_or_store' for {}:Concurrent::Hash

          h.fetch_or_store(key, Concurrent::Map.new)
           ^^^^^^^^^^^^^^^
/usr/local/www/gitlab-ce/config/initializers/0_postgresql_types.rb:13:in `initialize_type_map'
/usr/local/www/gitlab-ce/config/initializers/1_active_record_data_types.rb:30:in `initialize_type_map'
/usr/local/www/gitlab-ce/lib/gitlab/database/reflection.rb:144:in `connection'
/usr/local/www/gitlab-ce/lib/gitlab/database/reflection.rb:72:in `database_version'
/usr/local/www/gitlab-ce/lib/gitlab/database/reflection.rb:68:in `version'
/usr/local/www/gitlab-ce/lib/gitlab/database/reflection.rb:76:in `postgresql_minimum_supported_version?'
/usr/local/www/gitlab-ce/lib/gitlab/database.rb:157:in `block in check_postgres_version_and_print_warning'
/usr/local/www/gitlab-ce/lib/gitlab/database.rb:154:in `each'
/usr/local/www/gitlab-ce/lib/gitlab/database.rb:154:in `check_postgres_version_and_print_warning'
/usr/local/www/gitlab-ce/config/initializers/1_postgresql_only.rb:6:in `<top (required)>'
/usr/local/www/gitlab-ce/config/environment.rb:7:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)