MFH: r462698
www/squid-devel: Update to 4.0.23, Fixes security vulnerabilities

- Add a patch from upstream that fixes a problem when building on i386 arch

  Kid.cc:93:42: error: format specifies type 'long' but the argument has type
  'time_t' (aka 'int') [-Werror,-Wformat]
                 theName.termedBuf(), pid, Config.hopelessKidRevivalDelay);
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.

- Remove CXXFLAGS with clang, not necessary anymore

PR:		225447
Submitted by:	timp87@gmail.com (maintainer)
Security:	d5b6d151-1887-11e8-94f7-9c5c8e75236a

Approved by:	ports-secteam (swills)