finance/kmymoney: unbreak build (+)
KMyMoney require SqlPrivate component from Qt6 but missed in dependency declaration via find_package

/wrkdirs/usr/ports/finance/kmymoney/work/kmymoney-5.2.1/kmymoney/plugins/sqlcipher/qsql_sqlite.cpp:37:10: fatal error: 'QtSql/private/qsqlcachedresult_p.h' file not found
   37 | #include <QtSql/private/qsqlcachedresult_p.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Reported by:	bulk -t