games/veloren-weekly: unbreak without security/ca_root_nss
PanicInfo: panicked at cargo-crates/hyper-rustls-0.24.2/src/config.rs:48:9:
no CA certificates found
Game version: b47aa6ae [2024-05-09]

Backtrace:
   0: veloren_voxygen::panic_handler::set_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: authc::AuthClient::new
   7: veloren_client::Client::new::{{closure}}
   8: veloren_voxygen::menu::main::client_init::ClientInit::new::{{closure}}
   9: tokio::runtime::task::raw::poll
  10: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  11: tokio::runtime::scheduler::multi_thread::worker::run
  12: tokio::runtime::task::raw::poll
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: std::sys::pal::unix::thread::Thread::new::thread_start
  16: <unknown>
(cherry picked from commit 4e9f09f24982bde0785ab1cf8baafe0e419d161b)