math/libbraiding: work-around to build with clang 16
Adding "CXXFLAGS+=-std=c++11" to fix the build on 14-CURRENT.

Without that, it fails with this error:

./cbraid_implementation.h:1043:23: error: no member named 'bind2nd' in namespace 'std'
--- braiding.lo ---
./cbraid_implementation.h:1043:23: error: no member named 'bind2nd' in namespace 'std'
(+ many others)

Since I’m there, strip the library.

PR:		271047
Reported by:	pkg-fallout