textproc/py-pygments: Update to 2.15.0
- Convert to PEP-517
- Add devel/py-importlib-metadata to run dependencies
  when Python version < 3.8
- Rename Project name in pyproject.toml to fix the following error
  when generating the packing list, even if the best solution would
  be to rename PORTNAME:

===> Staging for py39-pygments-2.15.0
===>   py39-pygments-2.15.0 depends on file: /usr/local/bin/python3.9 - found
===>   Generating temporary packing list
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/usr/local/lib/python3.9/site-packages/installer/__main__.py", line 86, in _main
    with WheelFile.open(args.wheel) as source:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/installer/sources.py", line 122, in open
    with zipfile.ZipFile(path) as f:
  File "/usr/local/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/poudriere/ports/default/textproc/py-pygments/work-py39/Pygments-2.15.0/dist/pygments-2.15.0*.whl'
*** Error code 1

Release changes: https://pygments.org/docs/changelog/