multimedia/pipewire: unbreak xdg-desktop-portal-wlr after ea3170c51fd4
In file included from /usr/local/include/pipewire-0.3/pipewire/pipewire.h:35:
In file included from /usr/local/include/pipewire-0.3/pipewire/client.h:35:
In file included from /usr/local/include/pipewire-0.3/pipewire/proxy.h:108:
In file included from /usr/local/include/pipewire-0.3/pipewire/protocol.h:48:
In file included from /usr/local/include/pipewire-0.3/pipewire/utils.h:34:
In file included from /usr/include/sys/mount.h:38:
/usr/include/sys/ucred.h:99:2: error: unknown type name 'u_int'
        u_int   cr_version;             /* structure layout version */
        ^
/usr/include/sys/mount.h:68:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short         fid_len;                /* length of data in bytes */
        ^
/usr/include/sys/mount.h:69:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short         fid_data0;              /* force longword alignment */
        ^
/usr/include/sys/mount.h:552:2: error: unknown type name 'u_char'; did you mean 'char'?
        u_char  ex_addrlen;             /* and the net address length */
        ^
/usr/include/sys/mount.h:554:2: error: unknown type name 'u_char'; did you mean 'char'?
        u_char  ex_masklen;             /* and the smask length */
        ^
/usr/include/sys/mount.h:567:2: error: unknown type name 'u_char'; did you mean 'char'?
        u_char  ex_addrlen;             /* and the net address length */
        ^
/usr/include/sys/mount.h:569:2: error: unknown type name 'u_char'; did you mean 'char'?
        u_char  ex_masklen;             /* and the smask length */
        ^
/usr/include/sys/mount.h:585:2: error: unknown type name 'u_char'; did you mean 'char'?
        u_char  ex_addrlen;             /* and the net address length */
        ^
/usr/include/sys/mount.h:587:2: error: unknown type name 'u_char'; did you mean 'char'?
        u_char  ex_masklen;             /* and the smask length */
        ^
/usr/include/sys/mount.h:612:2: error: unknown type name 'u_int'
        u_int   vfc_version;            /* ABI version number */
        ^

PR:		256970
Reported by:	pkg-fallout
Submitted by:	Evgeniy Khramtsov <evgeniy@khramtsov.org>
Approved by:	portmgr blanket (upstream backport)

(cherry picked from commit 701a40c48b3bd06ca5ccf7d4a7215f1aa5212d32)