During the exp-run in bug 208158, it was found that graphics/cuneiform gives errors with libc++ 3.8.0:
cuneiform_src/Kern/rimage/sources/main/cricontrol.cpp:597:32: error: call to 'abs' is ambiguous
        wNewHeight = (mbMarginsFlag ? abs(mrMargins.rmBottomMarg - mrMargins.rmTopMarg) : mpSourceDIB->GetLinesNumber());
                                      ^~~

This is because abs() is being called an unsigned argument.  Fix this by
casting the argument to the appropriate signed type.

Approved by:	samm@os2.kiev.ua (maintainer)
MFH:		2016Q2