deskutils/plasma6-xdg-desktop-portal-kde: Fix build on 13.2
src/session.h:186:10: error: no template named 'unordered_map' in namespace 'std'

PR:		278658
MFH:		2024Q2
(cherry picked from commit 574f1d78b9432abc5e0e46befa91958417c80648)