devel/nasm: unbreak with clang 4.0
checking for strspn... no
configure: error: NASM requires ANSI C (specifically, "strspn")
[...]
conftest.c:56:13: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
char strspn ();
            ^
             void

Regressed by:	https://github.com/llvm-mirror/clang/commit/162749f9c543
Approved by:	portmgr blanket