devel/ninja: Roll back to 1.11.1
Despite passing an exp-run and successful local builds, there still
exists a race condition in www/qt[56]-webengine when building with
ninja 1.12.x that is proving difficult to solve. After a successful
build, it seems subsequent builds fail when using ccache with a
generated header missing before it is needed at compile time.

Even after adding //chrome/app:generated_resources_grit as a dep in
src/3rdparty/chromium/chrome/browser/devtools/BUILD.gn, the build is
still failing with:

../../../../../qtwebengine-everywhere-src-6.7.0/src/3rdparty/chromium/chrome/browser/devtools/devtools_file_helper.cc:31:10:
fatal error: 'chrome/grit/generated_resources.h' file not found

This comes very late in the build, so trial and error attempts to fix
this are tedious, costing an hour+ of build time with each attempt.
Reverting to ninja 1.11.1 gets things building again while this can
sorted out in the background under less stressful conditions.

This partially reverts bb0835fd3aa268260cc9eae4ba0cad55814d6265.

PR:		279162, 279164
Reported by:	Robert Cina <transitive@gmail.com>