net-im/fractal: Mark BROKEN
Fails to build with following error:

error: failed to select a version for the requirement `syn = "^2"`
candidate versions found which didn't match: 1.0.107
location searched: directory source `/wrkdirs/usr/ports/net-im/fractal/work/fractal-4.4.2/cargo-crates` (which is replacing registry `crates-io`)
required by package `openssl-macros v0.1.1`
    ... which satisfies dependency `openssl-macros = "^0.1.1"` of package `openssl v0.10.74`
    ... which satisfies dependency `openssl = "^0.10.29"` of package `native-tls v0.2.11`
    ... which satisfies dependency `native-tls-crate = "^0.2"` of package `reqwest v0.10.10`
    ... which satisfies dependency `reqwest = "^0.10.3"` of package `fractal-matrix-api v4.4.2 (/wrkdirs/usr/ports/net-im/fractal/work/fractal-4.4.2/fractal-matrix-api)`
    ... which satisfies path dependency `fractal_api` of package `fractal-gtk v4.4.2 (/wrkdirs/usr/ports/net-im/fractal/work/fractal-4.4.2/fractal-gtk)`
perhaps a crate was updated and forgotten to be re-vendored?
*** Error code 101

Reported by:	pkg-fallout