security/krb5-devel: Broken on FreeBSD-11, OpenSSL 1.0.2 not supported
security/krb5-devel fails to build on FreeBSD-11 due to:

main.c:1593:5: error: implicit declaration of function 'OPENSSL_clear_free'
is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    OPENSSL_clear_free(buffer, buffer_len);