MFH: r508699 textproc/py-sphinxcontrib-bitbucket: Fix Python 3 build/run
Fix Python 3 build, identified while testing devel/py-virtualenvwrapper:

Exception occurred:
  File "/usr/local/lib/python3.7/site-packages/sphinx/registry.py", line 196, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/usr/local/lib/python3.7/site-packages/sphinxcontrib/bitbucket.py", line 26
    except AttributeError, err:
                         ^
SyntaxError: invalid syntax

While I'm here, level up ports/python compliance:

  - Add python to CATEGORIES
  - Add LICENSE/LICENSE_FILE
  - Add NO_ARCH
  - Add missing RUN_DEPENDS
  - Correct RUN_DEPENDS version-specs

Approved by:	portmgr (blanket(s): build fix, ports compliance, dependencies)

Approved by:	ports-secteam (blanket: ports fixes)