devel/spirv-llvm-translator: unbreak build with clang 16
In file included from lib/SPIRV/LLVMToSPIRVDbgTran.cpp:38:
In file included from lib/SPIRV/LLVMToSPIRVDbgTran.h:42:
In file included from lib/SPIRV/libSPIRV/SPIRVModule.h:44:
In file included from lib/SPIRV/libSPIRV/SPIRVEntry.h:44:
In file included from lib/SPIRV/libSPIRV/SPIRVEnum.h:44:
In file included from lib/SPIRV/libSPIRV/SPIRVOpCode.h:45:
lib/SPIRV/libSPIRV/spirv_internal.hpp:182:5: error: integer value 16777216 is outside the valid range of values [0, 16777215] for the enumeration type 'LoopControlMask' [-Wenum-constexpr-conversion]
    static_cast<LoopControlMask>(ILoopControlLoopCountINTELMask);
    ^

Reported by:	pkg-fallout
Regressed by:	https://github.com/llvm/llvm-project/commit/b36453530418
See also:	https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/1d5694629aad