net/samba422: Fix plist error after commit 6c23ee846dd4
After commit 6c23ee846dd4 plist error happens with default options
setting as below.

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/samba4/modules/ldb/ldap.so
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/net/samba422

While here, use %%SAMBA4_MODULEDIR%% for path of
lib/samba4/modules/ldb/ldap.so and sort plist.

Fixes:	6c23ee846dd4 net/samba422: Fix plist when AD_DC and LDAP are OFF