emulators/rpcs3: unbreak on aarch64 after ee309cdf6c6f
rpcs3/Emu/Cell/PPUThread.cpp:713:19: error: no member named 'r32' in 'asmjit::arm::Gp'
                                c.ldr(args[1].r32(), arm::ptr(imm_address));
                                      ~~~~~~~ ^

Reported by:	pkg-fallout

(cherry picked from commit 6fe033573886679dc6725227d9b2d63399839bf8)