graphics/vulkan-headers: pacify stage-qa after 93b836bc9e65
Error: '/usr/bin/python3' is an invalid shebang you need USES=shebangfix for 'share/vulkan/registry/genvk.py'

genvk.py is used to generate include/vulkan/*.h but distfile already
contains pregerenated version, so the shebang is unused. Regenerating
headers isn't supported by CMake build, and requires docgenerator.py
from Vulkan-Docs repo.

PR:		268489
Reported by:	amdmi3
Regressed by:	https://github.com/KhronosGroup/Vulkan-Headers/commit/75a6b83f213d