www/nginx: drop unused ImageMagick dependency
nginx-video-thumbextractor-module-0.7.0/README.textile:

  h2(#0_5_0). v0.5.0
  * remove MagickWand dependency which cause memory leak

which saved it from being BROKEN by r358176:

  In file included from src/ngx_http_video_thumbextractor_module.c:3:
  src/ngx_http_video_thumbextractor_module_utils.c:5:10: fatal error: 'wand/magick_wand.h' file not found
  #include <wand/magick_wand.h>
	   ^
  1 error generated.
  *** Error code 1

Reported by:	antoine (via exp-run for www/tengine)