net/samba422: CLUSTER: Add missing dependency net/libpcap
    Error: /usr/local/bin/ctdb is linked to /usr/local/lib/libpcap.so.1 from net/libpcap but it is not declared as a dependency
    Warning: you need LIB_DEPENDS+=libpcap.so:net/libpcap

PR:		291104
Reported by:	vvd