net/ipsvd: fix pkg-fallout with LLVM15
./compile udpsvd.c
udpsvd.c:271:32: error: incompatible pointer to integer conversion passing 'gid_t[61]' (aka 'unsigned int[61]') to parameter of type 'unsigned long' [-Wint-conversion]
      bufnum[fmt_ulong(bufnum, ugid.gid)] =0;
                               ^~~~~~~~
and use ugid.gid[0], and -include unistd.h globally, to fix
several missing prototype warnings around execve.

Someone tell Gerrit Pape that this code needs some serious fixing
around type widths and prototypes.

Deprecate, unless the upstream fixes things, and expire end of 2023.