lang/tcl87: fix build on GCC architectures
8.7.a3 requires C11 compiler:
/wrkdirs/usr/ports/lang/tcl87/work/tcl8.7a3/compat/zlib/zconf.h:429: error: previous declaration of 'z_crc_t' was here

Approved by:	mentors (implicit approval)