devel/qt6-base: pacify check-plist after 66b0e0515e2a
$ poudriere testport -j 131amd64 devel/qt6-base
[...]
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%QT_DOCDIR%%/config/exampleurl-qtpositioning.qdocconf
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1