devel/cvise: fix build with devel/llvm15 installed
During an exp-run for llvm 15 (see bug 265425), it turned out that
devel/cvise failed to build if devel/llvm15 is also installed:

  /wrkdirs/usr/ports/devel/cvise/work/cvise-2.4.0/clang_delta/ExpressionDetector.cpp:62:16: error: 'InclusionDirective' marked 'override' but does not override any member functions
    virtual void InclusionDirective(SourceLocation HashLoc,
                 ^
  /wrkdirs/usr/ports/devel/cvise/work/cvise-2.4.0/clang_delta/ExpressionDetector.cpp:62:16: warning: '(anonymous namespace)::IncludesPPCallbacks::InclusionDirective' hides overloaded virtual function [-Woverloaded-virtual]
  /usr/local/llvm15/include/clang/Lex/PPCallbacks.h:127:16: note: hidden overloaded virtual function 'clang::PPCallbacks::InclusionDirective' declared here: type mismatch at 6th parameter ('Optional<clang::FileEntryRef>' vs 'const clang::FileEntry *')
    virtual void InclusionDirective(SourceLocation HashLoc,
                 ^
  1 warning and 1 error generated.

This is because during the configure phase, it picks up
ClangConfig.cmake from the llvm13 package, but LLVMConfig.cmake from the
llvm15 package:

  -- Found LLVM 15.0.6
  -- Using LLVMConfig.cmake in /usr/local/llvm15/lib/cmake/llvm
  -- Using ClangConfig.cmake in /usr/local/llvm13/lib/cmake/clang
  -- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.9.15", minimum required is "3.6")

Add a -DLLVM_DIR flag to CMAKE_ARGS to point to the correct directory
for LLVMConfig.cmake.

PR:		268247
Approved by:	maintainer timeout (2 weeks)
MFH:		2022Q4