graphics/wayland: add note about XDG_RUNTIME_DIR
error: XDG_RUNTIME_DIR not set in the environment.

PR:		255355
Inspired by:	hikari
Approved by:	maintainer timeout

(cherry picked from commit 2d487a43aa142c32eabdd8feeb4ca523d24c6a42)