devel/git-cinnabar: update to 0.5.0.b2.12 to unbreak after r459462
./helper/cinnabar-helper.c:405:2: warning: implicit declaration of function 'DIFF_OPT_SET' is invalid in C99 [-Wimplicit-function-declaration]
        DIFF_OPT_SET(&revs.diffopt, RECURSIVE);
        ^
./helper/cinnabar-helper.c:405:30: error: use of undeclared identifier 'RECURSIVE'
        DIFF_OPT_SET(&revs.diffopt, RECURSIVE);
                                    ^
Changes:	https://github.com/glandium/git-cinnabar/compare/c3e5bce...826f1d8
Reported by:	pkg-fallout