graphics/librsvg2-rust: fix build on powerpc64le
Add powerpc64le-unknown-freebsd target support to cfg_expr so that
system-deps can build:
thread 'main' panicked at 'Invalid TARGET: powerpc64le-unknown-freebsd', /wrkdirs/usr/ports/graphics/librsvg2-rust/work/librsvg-2.52.0/vendor/system-deps/src/lib.rs:735:32