Revert "games/jaggedalliance2: update to 0.18.0"
This reverts commit 5ec940f106b3c806592f6205540c88a40e91e399.

It tries to fetch things during the build.

===>  Configuring for ja2-0.18.0
    Updating git repository `https://github.com/selaux/android-ndk-rs`
warning: spurious network error (2 tries remaining): failed to connect to github.com: Can't assign requested address; class=Os (2)
warning: spurious network error (1 tries remaining): failed to connect to github.com: Can't assign requested address; class=Os (2)
error: failed to get `ndk` as a dependency of package `stracciatella v0.1.0 (/wrkdirs/usr/ports/games/jaggedalliance2/work/ja2-stracciatella-0.18.0/rust/stracciatella)`

Caused by:
  failed to load source for dependency `ndk`

Caused by:
  Unable to update https://github.com/selaux/android-ndk-rs

Caused by:
  failed to clone into: /wrkdirs/usr/ports/games/jaggedalliance2/work/cargo-home/git/db/android-ndk-rs-8a286ebb858b1942

Caused by:
  failed to connect to github.com: Can't assign requested address; class=Os (2)
*** Error code 101

If we fix that error it still tries to fetch things later:

-- Using src='https://github.com/mackron/miniaudio/archive/634cdb028f340075ae8e8a1126620695688d2ac3.zip'
-- Retrying...
-- Using src='https://github.com/mackron/miniaudio/archive/634cdb028f340075ae8e8a1126620695688d2ac3.zip'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/mackron/miniaudio/archive/634cdb028f340075ae8e8a1126620695688d2ac3.zip'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/mackron/miniaudio/archive/634cdb028f340075ae8e8a1126620695688d2ac3.zip'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://github.com/mackron/miniaudio/archive/634cdb028f340075ae8e8a1126620695688d2ac3.zip'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/mackron/miniaudio/archive/634cdb028f340075ae8e8a1126620695688d2ac3.zip'
CMake Error at /wrkdirs/usr/ports/games/jaggedalliance2/work/.build/dependencies/lib-miniaudio/getter/get-miniaudio-prefix/src/get-miniaudio-stamp/download-get-miniaudio.
cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/mackron/miniaudio/archive/634cdb028f340075ae8e8a1126620695688d2ac3.zip' failed
          status_code: 6
          status_string: "Couldn't resolve host name"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

PR:		255399