net/xprobe: Fix build with Clang 16+
misc.cc:21:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  register long sum;            /* assumes long == 32 bits */
  ^~~~~~~~~
misc.cc:23:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  register u_short answer;      /* assumes u_short == 16 bits */
  ^~~~~~~~~
2 errors generated.