MFH: r522036
audio/asterisk-espeak: fix build on GCC architectures

C11 compiler is required:
/usr/local/include/asterisk/lock.h: In function 'ast_atomic_fetchadd_int':
/usr/local/include/asterisk/lock.h:752: error: '__ATOMIC_RELAXED' undeclared (first use in this function)
/usr/local/include/asterisk/lock.h:752: error: (Each undeclared identifier is reported only once
/usr/local/include/asterisk/lock.h:752: error: for each function it appears in.)
/usr/local/include/asterisk/lock.h: In function 'ast_atomic_dec_and_test':
/usr/local/include/asterisk/lock.h:762: error: '__ATOMIC_RELAXED' undeclared (first use in this function)

Approved by:	portmgr (build fix blanket)