mail/mutt: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
mail/mutt failed to build with clang (and lld) 15:

  --- init.o ---
  In file included from init.c:43:
  ./init.h:3166:37: error: incompatible integer to pointer conversion initializing 'void *' with an expression of type 'int' [-Wint-conversion]
    { "quote_empty",      DT_BOOL, R_NONE, OPTQUOTEEMPTY, 1 },
                                           ^~~~~~~~~~~~~
  ./init.h:3166:37: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    { "quote_empty",      DT_BOOL, R_NONE, OPTQUOTEEMPTY, 1 },
                                           ^~~~~~~~~~~~~
                                           {            }
  ./init.h:3166:52: error: incompatible integer to pointer conversion initializing 'void *' with an expression of type 'int' [-Wint-conversion]
    { "quote_empty",      DT_BOOL, R_NONE, OPTQUOTEEMPTY, 1 },
                                                          ^
  ./init.h:3166:52: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    { "quote_empty",      DT_BOOL, R_NONE, OPTQUOTEEMPTY, 1 },
                                                          ^

This is because the QUOTE_PATCH option is on by default, and that quote
patch does not properly initialize the union members for the MuttVars
variable.

PR:		268208
Approved by:	dereks@lifeofadishwasher.com (maintainer)
MFH:		2022Q4