devel/highway: unbreak build on riscv64
In file included from hwy/nanobenchmark.cc:28:
In file included from hwy/timer-inl.h:26:
In file included from hwy/highway.h:21:
hwy/detect_targets.h:750:2: error: "Logic error: best baseline should be included in dynamic targets"
  750 | #error "Logic error: best baseline should be included in dynamic targets"
      |  ^

PR:		285977
Reported by:	Rich Dunkle
Tested by:	Rich Dunkle

(cherry picked from commit eabed8b1aa83e6b1965101c8cdd662f6a40ed7b7)