cad/netgen: fix build
ld: error: libsrc/interface/libinterface.so: undefined reference to
	pthread_create [--no-allow-shlib-undefined]

This has been happening for over a month since an LLVM update
made it more sensitive to symbol-issues. I can't spot any
direct pthreads usage in the source, though, so the patch
is just a bodge.