net/py-ldaptor: Limit to 2.7 (Does not support Python 3.x)
This port depends on Twisted, which supports Python 3.x as of a number of
versions ago for some growing number of its components. On initial view, ldaptor
appears inconsistent (at least not explicit) in its state of Python 3.x support
for its latest version (16.0.0, not this ports version, 0.0.43)

- A Python 3 compatible wheel is available on PyPI
- Python 3.3-3.5 are included in tox.ini for testing

However:

- Travis CI configuration only tests with 2.7
- Open "Python3 support #55" upstream issue [1]

Additionally, Twisted/Python3 support aside, test builds (without USES=twisted
declared), results in a build error at configure time:

  SyntaxError: invalid syntax

This change limits build support to Python 2.7 accordingly.

While I'm here:

- Pet portlint: LICENSE [2], PLIST_FILES, makepatch.

[1] https://github.com/twisted/ldaptor/issues/55
[2] https://github.com/twisted/ldaptor/commit/7e249b1586789a5c588f662ce74ee9f4338666e0

PR:		219323
Reported by:	Johannes Jost Meixner
Approved by:	portmgr (blanket)
MFH:		2017Q3