games/veloren: document Vulkan is required after 04bc03fdd5c9
In X11-only setups it's still common to have mesa-dri but not vulkan-loader.
However, Veloren defaults to Vulkan on Linux/BSD:

  PanicInfo: panicked at 'Failed to select a rendering backend! No compatible backends were found. We currently support vulkan, metal, dx12, and dx11. Installing or updating vulkan drivers may resolve this issue. If the issue persists, please include the operating system and GPU details in your bug report to help us identify the cause.', voxygen/src/main.rs:255:13

Forcing OpenGL via WGPU_BACKEND=opengl is still broken:

  PanicInfo: panicked at 'Error in Adapter::request_device: unsupported features were requested: DEPTH_CLAMPING | ADDRESS_MODE_CLAMP_TO_BORDER', .../wgpu-a92b854/wgpu/src/backend/direct.rs:113:9

See also https://veloren.net/devblog-125/