multimedia/mjpegtools: fix build with clang 19
Clang 19 has become more strict about errors in member functions, which
results in errors building multimedia/mjpegtools:

  ./Region2D.hh:439:13: error: no member named 'DoesContainPoint' in 'Region2D<INDEX, SIZE>'
    439 |                         || this->DoesContainPoint (rHere.m_tnY, tnX)))
        |                            ~~~~  ^
  ./Region2D.hh:446:22: error: no member named 'Begin' in 'Region2D<INDEX, SIZE>'
    446 |         for (itHere = this->Begin(); itHere != this->End(); ++itHere)
        |                       ~~~~  ^
  ./Region2D.hh:446:47: error: no member named 'End' in 'Region2D<INDEX, SIZE>'
    446 |         for (itHere = this->Begin(); itHere != this->End(); ++itHere)
        |                                                ~~~~  ^
  ./Region2D.hh:549:14: error: no member named 'DoesContainPoint' in 'Region2D<INDEX, SIZE>'
    549 |                         && !this->DoesContainPoint (rHere.m_tnY, tnX))
        |                             ~~~~  ^
  ./Region2D.hh:556:22: error: no member named 'Begin' in 'Region2D<INDEX, SIZE>'
    556 |         for (itHere = this->Begin(); itHere != this->End(); ++itHere)
        |                       ~~~~  ^
  ./Region2D.hh:556:47: error: no member named 'End' in 'Region2D<INDEX, SIZE>'
    556 |         for (itHere = this->Begin(); itHere != this->End(); ++itHere)
        |                                                ~~~~  ^
  ./Region2D.hh:635:16: error: no member named 'DoesContainPoint' in 'Region2D<INDEX, SIZE>'
    635 |                         if (!(this->DoesContainPoint (rHere.m_tnY, tnX)
        |                               ~~~~  ^
  ./Region2D.hh:643:22: error: no member named 'Begin' in 'Region2D<INDEX, SIZE>'
    643 |         for (itHere = this->Begin(); itHere != this->End(); ++itHere)
        |                       ~~~~  ^
  ./Region2D.hh:643:47: error: no member named 'End' in 'Region2D<INDEX, SIZE>'
    643 |         for (itHere = this->Begin(); itHere != this->End(); ++itHere)
        |                                                ~~~~  ^

The member functions `DoesContainPoint`, `Begin` and `End` are all
commented out in Region2D.hh, probably because the code was never
finished up properly. The member functions referencing them are also
never used, so comment those out too, using `#if 0`, `#endif` pairs.

PR:		281887
Approved by:	maintainer timeout (2 weeks)
MFH:		2024Q4

(cherry picked from commit 8cf728289caf3a06b225866707277d5ff170dff0)