graphics/podofo: require C++11 compiler
Fixes build of print/scribus-devel on GCC architectures:
/usr/local/bin/ld: pdf_analyzer.cpp:(.text+0x33d8): undefined reference to `PoDoFo::PdfName::GetEscapedName[abi:cxx11]() const'
/usr/local/bin/ld: scribus/CMakeFiles/scribus.dir/pdf_analyzer.cpp.o: in function `PDFAnalyzer::inspectCanvas(PoDoFo::PdfCanvas*, QList<PDFColorSpace>&, bool&, QList<PDFFont>&, QList<PDFImage>&) [clone .localalias]':