japanese/kakasi: fix build with clang 15
During an exp-run for llvm 15 (see bug 265425), it turned out that
japanese/kakasi failed to build with clang 15:

  kanjiio.c:1083:11: error: incompatible integer to pointer conversion assigning to 'iconv_t' (aka 'struct __tag_iconv_t *') from 'int' [-Wint-conversion]
          fromutf8 = -1;
                   ^ ~~
  kanjiio.c:1087:9: error: incompatible integer to pointer conversion assigning to 'iconv_t' (aka 'struct __tag_iconv_t *') from 'int' [-Wint-conversion]
          toutf8 = -1;
                 ^ ~~

This is because 'fromutf8' and 'toutf8' are of pointer type, not int.
Add a cast to silence the warning.

PR:		268815
Approved by:	portmgr (tcberner)
MFH:		2023Q1