comms/qt5-connectivity: Fix PLIST
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%QT_INCDIR%%/QtBluetooth/%%FULLVER%%/QtBluetooth/private/androidutils_p.h
Error: Orphaned: %%QT_INCDIR%%/QtBluetooth/%%FULLVER%%/QtBluetooth/private/qleadvertiser_bluez_p.h
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Approved by:	portmgr (blanket)