audio/alsa-plugins: unbreak JACK=on build after 6cd91556d4b8
pcm_jack.c:606:23: error: use of undeclared identifier 'program_invocation_short_name'
                const char *pname = program_invocation_short_name;
                                    ^

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: etc/alsa/conf.d/50-jack.conf
Error: Orphaned: share/alsa/alsa.conf.d/50-jack.conf

PR:		274792
(cherry picked from commit 609ec25809c7d1571a758ad09832fd6f6e1bc188)