MFH: r406945
Mark BROKEN: fails to build

cd /wrkdirs/usr/ports/irc/minbif/work/minbif-1.0.5/src && /usr/bin/c++    -I/usr/local/include/libpurple -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -I/wrkdirs/usr/ports/irc/minbif/work/minbif-1.0.5/src -O2 -pipe -DX_DISPLAY_MISSING -fstack-protector -fno-strict-aliasing -DHAVE_IMLIB -DHAVE_CACA -DHAVE_PAM -D_REENTRANT -D_FILE_OFFSET_BITS=64 -Wall -Wextra -Wno-unused-parameter -O2 -pipe -DX_DISPLAY_MISSING -fstack-protector -fno-strict-aliasing -o CMakeFiles/minbif.dir/im/account.cpp.o -c /wrkdirs/usr/ports/irc/minbif/work/minbif-1.0.5/src/im/account.cpp
/wrkdirs/usr/ports/irc/minbif/work/minbif-1.0.5/src/im/account.cpp: In member function 'void im::Account::setBuddyIcon(std::string)':
/wrkdirs/usr/ports/irc/minbif/work/minbif-1.0.5/src/im/account.cpp:276: error: 'ImlibLoadError' was not declared in this scope
/wrkdirs/usr/ports/irc/minbif/work/minbif-1.0.5/src/im/account.cpp:276: error: expected `;' before 'err'
/wrkdirs/usr/ports/irc/minbif/work/minbif-1.0.5/src/im/account.cpp:281: error: 'err' was not declared in this scope
/wrkdirs/usr/ports/irc/minbif/work/minbif-1.0.5/src/im/account.cpp:287: error: 'err' was not declared in this scope

Reported by:	pkg-fallout