security/libsecret: fix build with clang 16
Clang 16 has a new error about incompatible function types, which shows
up when building security/libsecret:

  libsecret/test-vala-lang.p/test-vala-lang.c:1166:51: error: incompatible function pointer types passing 'void (gpointer)' (aka 'void (void *)') to parameter of type 'GTestDataFunc' (aka 'void (*)(const void *)') [-Wincompatible-function-pointer-types]
          g_test_add_data_func ("/vala/lookup/sync", NULL, _test_lookup_sync_gtest_data_func);
                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/local/include/glib-2.0/glib/gtestutils.h:337:58: note: passing argument to parameter 'test_func' here
                                           GTestDataFunc   test_func);
                                                           ^

Since the errors all occur in vala-generated code, it does not make
sense to patch the .c files. Suppress the warning instead.

PR:		271320
Approved by:	portmgr (build fix blanket)
MFH:		2023Q2