benchmarks/vkmark: unbreak --winsys kms by reverting a8f179d5f29c
VT_PROCESS fails with EPERM because open(2) with a terminal device
on BSDs (unlike Linux/Solaris) implies O_NOCTTY.

$ vidcontrol -s 1 </dev/ttyv0
$ vkmark
Error: Failed to set VT process control mode: Operation not permitted

This reverts commit a8f179d5f29c0392909d98f8780ae84f078e925f.