dns/py-dnspython: Update to 2.1.0 for Python 3
While updating this port to 2.1.0 fixes runtime error "AttributeError:
module 'base64' has no attribute 'decodestring'" with python 3.9 or
later, it isn't compatible with Python 2.7. So update to 2.1.0 only
for Python 3.

ChangeLog:	https://github.com/rthalley/dnspython/blob/v2.1.0/doc/whatsnew.rst
PR:		260475
Approved by:	maintainer timeout (> 1 month)