MFH: r456086
textproc/ansifilter: require C++11 toolchain (on powerpc*, mips*, sparc*)

cc1plus: error: unrecognized command line option "-std=c++11"

main.cpp:118:5: error: use of undeclared identifier 'unique_ptr'
    unique_ptr<ansifilter::CodeGenerator> generator(ansifilter::CodeGenerator::getInstance(op...
    ^

Reported by:	pkg-fallout (mips64)
Approved by:	ports-secteam blanket