lang/mono6.8: register build-time conflict against archivers/brotli
The build fails if `archivers/brotli' port is installed, with the
errors quoted below.  It does not happen in pristine environments,
but may affect users who build ports locally.

  ../../external/corefx/src/Native/AnyOS/brotli/enc/dictionary_hash.c:16:1: error: unknown type name 'BROTLI_INTERNAL'
  BROTLI_INTERNAL const uint16_t kStaticDictionaryHash[32768] = {
  ^
  ../../external/corefx/src/Native/AnyOS/brotli/enc/dictionary_hash.c:16:31: error: expected ';' after top level declarator
  BROTLI_INTERNAL const uint16_t kStaticDictionaryHash[32768] = {
                                ^
                                ;
  2 errors generated.