devel/electron12: fix build
In file included from ../../third_party/nasm/asm/assemble.c:178:
../../third_party/nasm/include/compiler.h:249:21: error: static declaration of 'mempcpy' follows non-static declaration
static inline void *mempcpy(void *dst, const void *src, size_t n)
                    ^
/usr/include/string.h:70:7: note: previous declaration is here
void    *mempcpy(void * __restrict, const void * __restrict, size_t);
         ^

PR:		257378
Reported by:	Robert Cina <transitive@gmail.com>
Tested by:	meta
Approved by:	maintainer timeout (> 2 weeks)
MFH:		2021Q4

(cherry picked from commit 9cdeb88eac13fab9aed2f3972cef30d229890bde)