www/gitlab-ce: fix database migration error
Database migration step requires vite_ruby 3.3 even if a higher version is allowed.
Following error is fixed:
E, [2023-12-14T14:15:11.286071 #1116] ERROR -- : Failed to check mode for Vite: vite-plugin-ruby@^3.2.2 might not be compatible with vite_ruby-3.5.0

You may disable this check if needed: https://vite-ruby.netlify.app/config/#skipcompatibilitycheck

You may upgrade both by running:

    bundle exec vite upgrade

rake aborted!
ArgumentError: vite-plugin-ruby@^3.2.2 might not be compatible with vite_ruby-3.5.0

You may disable this check if needed: https://vite-ruby.netlify.app/config/#skipcompatibilitycheck

You may upgrade both by running:

    bundle exec vite upgrade
/usr/local/www/gitlab-ce/config/environment.rb:7:in `<top (required)>'
<internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:38:in `require'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)