devel/boost-libs: backport minor regression fix
/usr/local/include/boost/lockfree/spsc_queue.hpp:140:43: error: no member named 'next' in namespace 'boost'
        const ConstIterator last = boost::next(begin, input_count);
                                   ~~~~~~~^
/usr/local/include/boost/lockfree/spsc_queue.hpp:145:51: error: no member named 'next' in namespace 'boost'
            const ConstIterator midpoint = boost::next(begin, count0);
                                           ~~~~~~~^

Obtained from:	upstream (via Homebrew)