devel/libarea: fix build after 659620f1586e
 In file included from /wrkdirs/usr/ports/devel/libarea/work/libarea-2752cd9/PythonStuff.cpp:24:
 /usr/local/include/boost/progress.hpp:23:3: error: This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)
 # error This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)

etc.