chinese/scim-fcitx: fix build with GCC-based architectures
Apart from using new GCC on GCC architectures, this port also needs to including sys/types.h and cstring in some cpp files:
/usr/local/lib/libscim-1.0.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'

PR:		237148
Approved by:	meta (maintainer timeout), mat (mentor)
Differential Revision:	https://reviews.freebsd.org/D20106