devel/kf5-kidletime: track Wayland dependencies
====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/qt5/plugins/kf5/org.kde.kidletime.platforms/KF5IdleTimeWaylandPlugin.so is linked to /usr/local/lib/qt5/libQt5WaylandClient.so.5 from graphics/qt5-wayland but it is not declared as a dependency
Warning: you need USES=qt:5 and USE_QT+=wayland
Error: /usr/local/lib/qt5/plugins/kf5/org.kde.kidletime.platforms/KF5IdleTimeWaylandPlugin.so is linked to /usr/local/lib/libwayland-client.so.0 from graphics/wayland but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libwayland-client.so:graphics/wayland
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%QT_PLUGINDIR%%/kf5/org.kde.kidletime.platforms/KF5IdleTimeWaylandPlugin.so

Inspired by:	Alpine Linux