devel/indi: fix build with libc++ 21
With libc++ 21 devel/indi fails to build, with errors similar to:

    /wrkdirs/usr/ports/devel/indi/work/indi-2.1.7/drivers/auxiliary/gemini_flatpanel_adapters.cpp:242:14: error: use of undeclared identifier 'atoi'
      242 |     int id = atoi(id_str);
          |              ^~~~
    /wrkdirs/usr/ports/devel/indi/work/indi-2.1.7/drivers/auxiliary/gemini_flatpanel_adapters.cpp:341:14: error: use of undeclared identifier 'atoi'
      341 |     *value = atoi(value_str);
          |              ^~~~
    /wrkdirs/usr/ports/devel/indi/work/indi-2.1.7/drivers/auxiliary/gemini_flatpanel_adapters.cpp:658:14: error: use of undeclared identifier 'atoi'
      658 |     int id = atoi(id_str);
          |              ^~~~
    /wrkdirs/usr/ports/devel/indi/work/indi-2.1.7/drivers/auxiliary/gemini_flatpanel_adapters.cpp:793:14: error: use of undeclared identifier 'atoi'
      793 |     *value = atoi(value_str);
          |              ^~~~
    /wrkdirs/usr/ports/devel/indi/work/indi-2.1.7/drivers/auxiliary/gemini_flatpanel_adapters.cpp:1154:14: error: use of undeclared identifier 'atoi'
     1154 |     *value = atoi(value_str);
          |              ^~~~

This is because `atoi` is declared in `<cstdlib>`, and before libc++ 21
that header got transitively included via other standard headers, but
that is no longer the case. Include `<cstdlib>` explicitly to fix the
errors.

PR:		293394
Approved by:	acm (maintainer)
MFH:		2026Q1

(cherry picked from commit 300d6785c97c4fe8e9ee682248c4269723905ac7)