devel/pecl-intl: switch to C++11, required by ICU >= 59
In file included from /wrkdirs/usr/ports/devel/pecl-intl/work/intl-3.0.0/intl_convertcpp.cpp:21:
In file included from ./intl_convertcpp.h:26:
/usr/local/include/unicode/unistr.h:3025:7: error: delegating constructors are permitted only in C++11
      UnicodeString(ConstChar16Ptr(text)) {}
      ^~~~~~~~~~~~~
/usr/local/include/unicode/unistr.h:3087:7: error: delegating constructors are permitted only in C++11
      UnicodeString(ConstChar16Ptr(text), length) {}
      ^~~~~~~~~~~~~
/usr/local/include/unicode/unistr.h:3180:7: error: delegating constructors are permitted only in C++11
      UnicodeString(Char16Ptr(buffer), buffLength, buffCapacity) {}
      ^~~~~~~~~~~~~

PR:		218788