x11/kitty: Update to 0.46
- Add patch files/patch-kitty_colors.c to fix compilation that otherwise
  fails with the error:

cc -MMD -DNDEBUG -DEPOLL_SHIM_DISABLE_WRAPPER_MACROS -I/usr/local/include/libepoll-shim -Wextra -Wfloat-conversion -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -pe
dantic-errors -Werror -O3 -fwrapv -fstack-protector-strong -pipe -fvisibility=hidden -fno-plt -fPIC -O2 -pipe -Wno-error=invalid-utf8 -Winvalid-utf8 -fstack-protector-strong -fno-strict
-aliasing -D_FORTIFY_SOURCE=2 -flto -I/usr/local/include -fcf-protection=full -pthread -I/usr/local/include/libpng16 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/us
r/local/include -I/usr/local/include -I/usr/local/include/cairo -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/local/include/libpng16 -I/usr/local/include/harfbuzz
-I/usr/local/include/freetype2 -I/usr/local/include/libpng16 -I/usr/local/include -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/python3.11 -c kitt
y/colors.c -o build/fast_data_types-kitty-colors.c.o
kitty/colors.c:809:12: error: call to undeclared function 'strtod_l'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
  809 |     *out = strtod_l(src, &endptr, get_c_locale());
      |            ^
1 error generated.
*** Error code 1

- Use Go 1.26 (required version) explicitly to fix build in Poudriere:

[5/5] Linking launcher ...
 done
go: downloading go1.26.1 (freebsd/amd64)
go: download go1.26.1: golang.org/toolchain@v0.0.1-go1.26.1.freebsd-amd64: Get "https://proxy.golang.org/golang.org/toolchain/@v/v0.0.1-go1.26.1.freebsd-amd64.zip": dial tcp: lookup pro
xy.golang.org on 192.168.1.1:53: write udp 127.0.0.1:47459->192.168.1.1:53: write: can't assign requested address
Traceback (most recent call last):
  File "/wrkdirs/usr/ports/x11/kitty/work/github.com/kovidgoyal/kitty@v0.46.0/setup.py", line 2362, in <module>
    main()
  File "/wrkdirs/usr/ports/x11/kitty/work/github.com/kovidgoyal/kitty@v0.46.0/setup.py", line 2358, in main
    do_build(args)
  File "/wrkdirs/usr/ports/x11/kitty/work/github.com/kovidgoyal/kitty@v0.46.0/setup.py", line 2330, in do_build
    package(args, bundle_type='linux-package')
  File "/wrkdirs/usr/ports/x11/kitty/work/github.com/kovidgoyal/kitty@v0.46.0/setup.py", line 1946, in package
    build_static_kittens(args, launcher_dir=launcher_dir)
  File "/wrkdirs/usr/ports/x11/kitty/work/github.com/kovidgoyal/kitty@v0.46.0/setup.py", line 1273, in build_static_kittens
    required_go_version = subprocess.check_output(go + 'list -f {{.GoVersion}} -m'.split(), env=dict(os.environ, GO111MODULE="on")).decode().strip()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/go125', 'list', '-f', '{{.GoVersion}}', '-m']' returned non-zero exit status 1.
*** Error code 1

ChangeLog:  https://sw.kovidgoyal.net/kitty/changelog/#id1
Reported by:  kovidgoyal/kitty <kitty@noreply.github.com>