lang/gprolog: update to 1.5.0
Port changes:

- the version 1.5.0 now recognizes clang for amd64 so
  the patch files/patch-EnginePl_machine.h reduced but
  it is still needed for i386 build;
- this version correctly defines NO_MACHINE_REG_FOR_REG_BANK
  and adds -fcommon for clang, so CFLAGS reduced too;
- the patch files/patch-Ma2Asm_x86__64__any.c rebuilt for new code,
  it is still needed as build fails with an error without the patch:
Fatal Error: Segmentation Violation (bad address: 0x100ec814853)