x11-toolkits/gtk40: Fix PLIST
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: @dir lib/gtk-4.0/%%GTK4_VERSION%%/engines
Error: Orphaned: @dir lib/gtk-4.0/%%GTK4_VERSION%%/loaders
Error: Orphaned: @dir lib/gtk-4.0/%%GTK4_VERSION%%/modules
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Approved by:	portmgr (blanket)