www/tor-browser: fix build with rust 1.73.0
The crate packed_simd_2 is not maintained anymore.
firefox switched to packed_simd [1] in [2] but
it's not yet part of tor-browser 12.0.6
Backport [3] to fix the following issue:

error: unrecognized platform-specific intrinsic function: `simd_shuffle2`
  --> /wrkdirs/usr/ports/www/tor-browser/work/firefox-tor-browser-102.11.0esr-12.0-1-build1/third_party/rust/packed_simd_2/src/codegen/llvm.rs:10:5
   |
10 |     pub fn simd_shuffle2<T, U>(x: T, y: T, idx: [u32; 2]) -> U;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[1] https://github.com/rust-lang/packed_simd/
[2] https://github.com/mozilla/gecko-dev/commit/1e1bec8c6e383abf667d64ba1e556a4e68833f28
[3] https://github.com/rust-lang/packed_simd/commit/a79edf4cfc54aad30a5630b217645c4b8274d8f7

PR:		274499
Approved by:	portmgr (build fix blanket)