www/nift: Fix build
- Fix build:
In file included from Expr.cpp:1:
In file included from ./Expr.h:8:
./exprtk/exprtk.h:6343:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
 6343 |             expression_node<T>::ndb_t::template collect(branch_, node_delete_list);
      |                                                 ^
Upstream pull request: https://github.com/nifty-site-manager/nsm/pull/38

- Fix bug:
nsm.cpp:1455:20: warning: overlapping comparisons always evaluate to false [-Wtautological-overlap-compare]
 1455 |                         if(noParams < 2 && noParams > 5)
      |                            ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
1 warning generated.
Upstream pull request: https://github.com/nifty-site-manager/nsm/pull/39

- Make the choice of Lua implementation more intuitive.
- Run the strip command once for all binaries.

PR:		288379
MFH:		2025Q3
Co-authored-by:	Vladimir Druzenko <vvd@FreeBSD.org>
(cherry picked from commit dbade9f054efe783b74f6de1052da4f6964e984a)