devel/p8-platform: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because devel/p8-platform's Makefile does not explicitly set its C++
standard, this leads to an error:

  /wrkdirs/usr/ports/devel/p8-platform/work/platform-p8-platform-2.1.0.1/src/util/StringUtils.cpp:456:69: error: no member named 'ptr_fun' in the global namespace
    str.erase(str.begin(), ::find_if(str.begin(), str.end(), ::not1(::ptr_fun(isspace_c))));
                                                                    ~~^
  /wrkdirs/usr/ports/devel/p8-platform/work/platform-p8-platform-2.1.0.1/src/util/StringUtils.cpp:469:58: error: no member named 'ptr_fun' in the global namespace
    str.erase(::find_if(str.rbegin(), str.rend(), ::not1(::ptr_fun(isspace_c))).base(), str.end());
                                                         ~~^

Upstream already fixed this in
<https://github.com/Pulse-Eight/platform/commit/a7cd0d5>, via
<https://github.com/Pulse-Eight/platform/pull/45>, so apply it.

While here, pet portlint.

PR:		271710
Approved by:	mickael.maillot@gmail.com (maintainer)
MFH:		2023Q2