sysutils/fusefs-encfs: Unbreak build with llvm13
/wrkdirs/usr/ports/sysutils/fusefs-encfs/work/encfs-1.9.5/encfs/NullCipher.cpp:81:36: error: no matching constructor for initialization of 'std::shared_ptr<AbstractCipherKey>'
std::shared_ptr<AbstractCipherKey> gNullKey(new NullKey(), NullDestructor());
                                   ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Solution was taken from eacf34a1cf4b6b81e54d4fe74ad931ee93d1d8ef

(cherry picked from commit 7508209535a01298ef91e7f6d4e1b33a5e5ffd97)