textproc/scdoc: unbreak build with clang 15
In file included from src/string.c:3:
include/str.h:10:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct str *str_create();
                      ^
                       void
src/string.c:15:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct str *str_create() {
                      ^
                       void

PR:		268277
Reported by:	antoine (via bug 265425 exp-run)

(cherry picked from commit d30ead133df49f67fa29fbcc5cc4be19a2ad6af4)