x11/foot: unbreak build after aec9c6c9cf90
../wayland.c:655:17: error: enumeration value 'XDG_TOPLEVEL_STATE_SUSPENDED' not handled in switch [-Werror,-Wswitch]
        switch (*state) {
                ^

PR:		272372
(cherry picked from commit bcea2e3a260297c7127041c29a166ab447feabb0)