www/node16: Fix COREPACK option in cd47c658d43fbd29cb569b2230a05a1682ad3360
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: bin/corepack
Error: Orphaned: lib/node_modules/corepack/LICENSE.md
Error: Orphaned: lib/node_modules/corepack/README.md
Error: Orphaned: lib/node_modules/corepack/dist/corepack.js
Error: Orphaned: lib/node_modules/corepack/dist/npm.js
Error: Orphaned: lib/node_modules/corepack/dist/npx.js
Error: Orphaned: lib/node_modules/corepack/dist/pnpm.js
Error: Orphaned: lib/node_modules/corepack/dist/pnpx.js
Error: Orphaned: lib/node_modules/corepack/dist/vcc.js
Error: Orphaned: lib/node_modules/corepack/dist/yarn.js
Error: Orphaned: lib/node_modules/corepack/dist/yarnpkg.js
Error: Orphaned: lib/node_modules/corepack/package.json
Error: Orphaned: lib/node_modules/corepack/shims/corepack
Error: Orphaned: lib/node_modules/corepack/shims/corepack.cmd
Error: Orphaned: lib/node_modules/corepack/shims/corepack.ps1
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/corepack
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/corepack.cmd
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/corepack.ps1
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/npm
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/npm.cmd
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/npm.ps1
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/npx
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/npx.cmd
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/npx.ps1
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/pnpm
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/pnpm.cmd
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/pnpm.ps1
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/pnpx
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/pnpx.cmd
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/pnpx.ps1
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/vcc
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/vcc.cmd
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/vcc.ps1
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/yarn
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/yarn.cmd
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/yarn.ps1
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/yarnpkg
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/yarnpkg.cmd
Error: Orphaned: lib/node_modules/corepack/shims/nodewin/yarnpkg.ps1
Error: Orphaned: lib/node_modules/corepack/shims/npm
Error: Orphaned: lib/node_modules/corepack/shims/npm.cmd
Error: Orphaned: lib/node_modules/corepack/shims/npm.ps1
Error: Orphaned: lib/node_modules/corepack/shims/npx
Error: Orphaned: lib/node_modules/corepack/shims/npx.cmd
Error: Orphaned: lib/node_modules/corepack/shims/npx.ps1
Error: Orphaned: lib/node_modules/corepack/shims/pnpm
Error: Orphaned: lib/node_modules/corepack/shims/pnpm.cmd
Error: Orphaned: lib/node_modules/corepack/shims/pnpm.ps1
Error: Orphaned: lib/node_modules/corepack/shims/pnpx
Error: Orphaned: lib/node_modules/corepack/shims/pnpx.cmd
Error: Orphaned: lib/node_modules/corepack/shims/pnpx.ps1
Error: Orphaned: lib/node_modules/corepack/shims/yarn
Error: Orphaned: lib/node_modules/corepack/shims/yarn.cmd
Error: Orphaned: lib/node_modules/corepack/shims/yarn.ps1
Error: Orphaned: lib/node_modules/corepack/shims/yarnpkg
Error: Orphaned: lib/node_modules/corepack/shims/yarnpkg.cmd
Error: Orphaned: lib/node_modules/corepack/shims/yarnpkg.ps1
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/www/node16
=>> Error: check-plist failures detected

Approved by:	portmgr (blanket)