sysutils/reptyr: Address LLVM 13 build failure
Rather than create a patch, simply add -Wno-unused-but-set-variable,
avoiding a maintainer to backport patches any time the port is updated.

In file included from platform/freebsd/freebsd_ptrace.c:69:
In file included from platform/freebsd/arch/amd64.h:23:
platform/freebsd/arch/x86_common.h:45:6: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
        int ret;
            ^
platform/freebsd/arch/x86_common.h:54:6: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
        int ret;
            ^
2 errors generated.

(cherry picked from commit b8c4bfe660b373862165a58514f270a51e77e147)