multimedia/kodi: Fix fallout caused by curl 8.16.0
/wrkdirs/usr/ports/multimedia/kodi/work/xbmc-21.2-Omega/xbmc/filesystem/CurlFile.cpp:48:5: error: cannot initialize an array element of type 'curl_proxytype' with an rvalue of type 'long'
   48 |     CURLPROXY_HTTP,   CURLPROXY_SOCKS4,          CURLPROXY_SOCKS4A,
      |     ^~~~~~~~~~~~~~
/usr/local/include/curl/curl.h:791:35: note: expanded from macro 'CURLPROXY_HTTP'
  791 | #define CURLPROXY_HTTP            0L /* added in 7.10, new in 7.19.4 default is
      |                                   ^~

PR:	289960 289428
MFH:	2025Q4