graphics/ocaml-lablgl: fix build with clang 16
Clang 16 has a new error about incompatible function types, which shows
up when building graphics/ocaml-lablgl:

  togl.c:820:26: error: incompatible function pointer types assigning to 'void (*)(Tk_Window, Tk_ClassProcs *, ClientData)' (aka 'void (*)(struct Tk_Window_ *, struct Tk_ClassProcs *, void *)') from 'void (Tk_Window, const Tk_ClassProcs *, ClientData)' (aka 'void (struct Tk_Window_ *, const struct Tk_ClassProcs *, void *)') [-Wincompatible-function-pointer-types]
          SetClassProcsPtr = Tk_SetClassProcs;
                           ^ ~~~~~~~~~~~~~~~~

This is because Tk_SetClassProcs() now takes a const Tk_ClassProcs
pointer as its second parameter. Fix the SetClassProcsPtr declaration to
match.

PR:		272019
Approved by:	fernape
MFH:		2023Q2