audio/zrythm: fix build on non-x86
- don't unconditionally enable SSE, it's enable conditionally for amd64 in the main meson.build anyway:
cc: warning: argument unused during compilation: '-msse' [-Wunused-command-line-argument]
cc: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
error: unknown FP unit 'sse'
- disable LTO on powerpc64 since it's broken in LLVM.