devel/py-simpleparse: Fix build with Python 3.12+
cc -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -DMX_BUILDING_MXTEXTTOOLS=1 -DPY_SSIZE_T_CLEAN=1 -DDEBUG=1 -Isimpleparse/stt/TextTools/mxTextTools -I/usr/local/include/python3.12 -c simpleparse/stt/TextTools/mxTextTools/mxTextTools.c -o build/temp.freebsd-15.0-RELEASE-p11-amd64-cpython-312/simpleparse/stt/TextTools/mxTextTools/mxTextTools.o
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:244:13: warning: call to undeclared function 'PyUnicode_GET_SIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  244 |             return PyUnicode_GET_SIZE(so->match);
      |                    ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:389:15: warning: 'PyObject_AsCharBuffer' is deprecated [-Wdeprecated-declarations]
  389 |             else if (PyObject_AsCharBuffer(so->match, &match, &match_len))
      |                      ^
/usr/local/include/python3.12/abstract.h:351:1: note: 'PyObject_AsCharBuffer' has been explicitly marked deprecated here
  351 | Py_DEPRECATED(3.0)
      | ^
/usr/local/include/python3.12/pyport.h:317:54: note: expanded from macro 'Py_DEPRECATED'
  317 | #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
      |                                                      ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:448:11: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  448 |                 match = PyUnicode_AS_UNICODE(so->match);
      |                         ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:448:9: error: incompatible integer to pointer conversion assigning to 'Py_UNICODE *' (aka 'int *') from 'int' [-Wint-conversion]
  448 |                 match = PyUnicode_AS_UNICODE(so->match);
      |                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:449:15: warning: call to undeclared function 'PyUnicode_GET_SIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  449 |                 match_len = PyUnicode_GET_SIZE(so->match);
      |                             ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:455:11: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  455 |                 match = PyUnicode_AS_UNICODE(u);
      |                         ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:455:9: error: incompatible integer to pointer conversion assigning to 'Py_UNICODE *' (aka 'int *') from 'int' [-Wint-conversion]
  455 |                 match = PyUnicode_AS_UNICODE(u);
      |                       ^ ~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:456:15: warning: call to undeclared function 'PyUnicode_GET_SIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  456 |                 match_len = PyUnicode_GET_SIZE(u);
      |                             ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:518:6: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  518 |                                         PyUnicode_AS_UNICODE(text),
      |                                         ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:518:6: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'Py_UNICODE *' (aka 'int *') [-Wint-conversion]
  518 |                                         PyUnicode_AS_UNICODE(text),
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:421:23: note: passing argument to parameter 'text' here
  421 |                                Py_UNICODE *text,
      |                                            ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:570:6: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  570 |                                         PyUnicode_AS_UNICODE(text),
      |                                         ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:570:6: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'Py_UNICODE *' (aka 'int *') [-Wint-conversion]
  570 |                                         PyUnicode_AS_UNICODE(text),
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:421:23: note: passing argument to parameter 'text' here
  421 |                                Py_UNICODE *text,
      |                                            ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:646:10: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  646 |                                             PyUnicode_AS_UNICODE(text),
      |                                             ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:646:10: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'Py_UNICODE *' (aka 'int *') [-Wint-conversion]
  646 |                                             PyUnicode_AS_UNICODE(text),
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:421:23: note: passing argument to parameter 'text' here
  421 |                                Py_UNICODE *text,
      |                                            ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:939:23: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  939 |     Py_UNICODE *def = PyUnicode_AS_UNICODE(definition);
      |                       ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:939:17: error: incompatible integer to pointer conversion initializing 'Py_UNICODE *' (aka 'int *') with an expression of type 'int' [-Wint-conversion]
  939 |     Py_UNICODE *def = PyUnicode_AS_UNICODE(definition);
      |                 ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:940:28: warning: call to undeclared function 'PyUnicode_GET_SIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  940 |     const Py_ssize_t len = PyUnicode_GET_SIZE(definition);
      |                            ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1187:12: warning: call to undeclared function 'PyUnicode_GET_SIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1187 |         Py_Assert(PyUnicode_GET_SIZE(other) == 1,
      |                   ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1191:11: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1191 |                                              PyUnicode_AS_UNICODE(other)[0]);
      |                                              ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1191:38: error: subscripted value is not an array, pointer, or vector
 1191 |                                              PyUnicode_AS_UNICODE(other)[0]);
      |                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1442:11: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1442 |                                              PyUnicode_AS_UNICODE(text),
      |                                              ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1442:11: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'Py_UNICODE *' (aka 'int *') [-Wint-conversion]
 1442 |                                              PyUnicode_AS_UNICODE(text),
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1293:22: note: passing argument to parameter 'text' here
 1293 |                               Py_UNICODE *text,
      |                                           ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1493:11: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1493 |                                              PyUnicode_AS_UNICODE(text),
      |                                              ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1493:11: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'Py_UNICODE *' (aka 'int *') [-Wint-conversion]
 1493 |                                              PyUnicode_AS_UNICODE(text),
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1293:22: note: passing argument to parameter 'text' here
 1293 |                               Py_UNICODE *text,
      |                                           ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1579:11: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1579 |                                              PyUnicode_AS_UNICODE(text),
      |                                              ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1579:11: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'Py_UNICODE *' (aka 'int *') [-Wint-conversion]
 1579 |                                              PyUnicode_AS_UNICODE(text),
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1293:22: note: passing argument to parameter 'text' here
 1293 |                               Py_UNICODE *text,
      |                                           ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1593:11: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1593 |                                              PyUnicode_AS_UNICODE(text),
      |                                              ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1593:11: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'Py_UNICODE *' (aka 'int *') [-Wint-conversion]
 1593 |                                              PyUnicode_AS_UNICODE(text),
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1293:22: note: passing argument to parameter 'text' here
 1293 |                               Py_UNICODE *text,
      |                                           ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1604:9: warning: call to undeclared function 'PyUnicode_FromUnicode'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1604 |         return PyUnicode_FromUnicode(PyUnicode_AS_UNICODE(text) + left,
      |                ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1604:31: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1604 |         return PyUnicode_FromUnicode(PyUnicode_AS_UNICODE(text) + left,
      |                                      ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1604:9: error: incompatible integer to pointer conversion returning 'int' from a function with result type 'PyObject *' (aka 'struct _object *') [-Wint-conversion]
 1604 |         return PyUnicode_FromUnicode(PyUnicode_AS_UNICODE(text) + left,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1605 |                                      max(right - left, 0));
      |                                      ~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1692:19: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1692 |         Py_UNICODE *tx = PyUnicode_AS_UNICODE(text);
      |                          ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1692:14: error: incompatible integer to pointer conversion initializing 'Py_UNICODE *' (aka 'int *') with an expression of type 'int' [-Wint-conversion]
 1692 |         Py_UNICODE *tx = PyUnicode_AS_UNICODE(text);
      |                     ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1707:7: warning: call to undeclared function 'PyUnicode_FromUnicode'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1707 |                 s = PyUnicode_FromUnicode(&tx[z], x - z);
      |                     ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1707:5: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
 1707 |                 s = PyUnicode_FromUnicode(&tx[z], x - z);
      |                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1729:7: warning: call to undeclared function 'PyUnicode_FromUnicode'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1729 |                 s = PyUnicode_FromUnicode(&tx[z], x - z);
      |                     ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:1729:5: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
 1729 |                 s = PyUnicode_FromUnicode(&tx[z], x - z);
      |                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:2815:8: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2815 |         sep = PyUnicode_AS_UNICODE(separator);
      |               ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:2815:6: error: incompatible integer to pointer conversion assigning to 'Py_UNICODE *' (aka 'int *') from 'int' [-Wint-conversion]
 2815 |         sep = PyUnicode_AS_UNICODE(separator);
      |             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:2816:12: warning: call to undeclared function 'PyUnicode_GET_SIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2816 |         sep_len = PyUnicode_GET_SIZE(separator);
      |                   ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:2825:17: warning: call to undeclared function 'PyUnicode_FromUnicode'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2825 |     newstring = PyUnicode_FromUnicode(NULL, newstring_len);
      |                 ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:2825:15: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
 2825 |     newstring = PyUnicode_FromUnicode(NULL, newstring_len);
      |               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:2828:9: warning: call to undeclared function 'PyUnicode_AS_UNICODE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2828 |     p = PyUnicode_AS_UNICODE(newstring);
      |         ^
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:2828:7: error: incompatible integer to pointer conversion assigning to 'Py_UNICODE *' (aka 'int *') from 'int' [-Wint-conversion]
 2828 |     p = PyUnicode_AS_UNICODE(newstring);
      |       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:2851:9: error: incompatible integer to pointer conversion assigning to 'Py_UNICODE *' (aka 'int *') from 'int' [-Wint-conversion]
 2851 |             st = PyUnicode_AS_UNICODE(tempstr);
      |                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simpleparse/stt/TextTools/mxTextTools/mxTextTools.c:2852:15: warning: call to undeclared function 'PyUnicode_GET_SIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2852 |             len_st = PyUnicode_GET_SIZE(tempstr);
      |                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
27 warnings and 20 errors generated.
error: command '/usr/bin/cc' failed with exit code 1

ERROR Backend subprocess exited when trying to invoke build_wheel
*** Error code 1

Reference:	https://pkg-status.freebsd.org/beefy23/data/150amd64-default/0a7946717881/logs/py312-simpleparse-2.2.4_1.log
Obtained from:	https://github.com/mcfletch/simpleparse/commit/51c058731d7faedcef29d9e0e86e1f8e97f855b6
		https://github.com/mcfletch/simpleparse/commit/3416c19053801e41eebdf108d1a60a41593ab5fb
		https://github.com/mcfletch/simpleparse/commit/83c8b6f9f9130d114b2c9cf3ce432b989b1a65cc
		https://github.com/mcfletch/simpleparse/commit/daa2638479e5484b759fdbfa1f62f965516d1415
		https://github.com/mcfletch/simpleparse/commit/797d53c827d184496a7eac815bc137bd15e068c8

(cherry picked from commit 1db8a0a12a2da4b7cb2282dcb0f4a9b527fd7ab0)