- Mark BROKEN: does not build   ./DelegatesPassedToNativeCodeMustIncludeExceptionHandlingRule.cs(496,74):   error CS1061: Type `Mono.Cecil.Cil.ExceptionHandler' does not contain a   definition for `FilterEnd' and no extension method `FilterEnd' of type   `Mono.Cecil.Cil.ExceptionHandler' could be found (are you missing a using   directive or an assembly reference?)   /usr/local/lib/mono/gac/Mono.Cecil/0.9.5.0__0738eb9f132ed756/Mono.Cecil.dll   (Location of the symbol related to previous error)
Reported by:	pointyhat