MFH: r560298 r560302 r561371 r562151 r562559 r563142 r563143 r563149 r565356 r565465 r566011 r566182
finance/quickfix: fix build on non-x86

Code uses x86 assembly, but makes it possible to use Boost atomic.

multimedia/zoneminder: enable on powerpc64

net/mpich: fix build on powerpc64

Neither __BYTE_ORDER nor __BIG_ENDIAN are defined:
In file included from src/mpi/datatype/typerep/dataloop/looputil.c:10:
./src/mpi/datatype/typerep/dataloop/looputil.h:57:2: error: This code assumes that __BYTE_ORDER and __BIG_ENDIAN are defined
#error This code assumes that __BYTE_ORDER and __BIG_ENDIAN are defined

editors/libreoffice: fix build on powerpc64 elfv2

This set of patches is applied only on powerpc* architectures.

Submitted by:	afsilva
Approved by:	tier 2 blanket

security/openconnect-gui: fix checksum

emulators/riscv-isa-sim: enable on powerpc64

sysutils/linuxfdisk: enable on powerpc64

graphics/openfx-arena: enable on powerpc64

multimedia/arcan: enable LUAJIT on powerpc64

It builds fine with luajit-openresty.

games/libretro-desmume2015: fix build on non-x86 / ARM

JIT is only for x86 and ARM.

astro/opencpn: fix build on powerpc64*

Use GCC unconditionally on powerpc64*:
In file included from /usr/lib/clang/11.0.1/include/xmmintrin.h:13:
/usr/lib/clang/11.0.1/include/mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();

editors/libreoffice6: backport powerpc* patches to libreoffice6

Approved by:	tier 2 blanket