ftp/fineftp-server: cherry-pick asio compat patch
from upstream.

"Added compatibility with asio 1.33 and up (#77)
Mostly replaced deprecated 'io_service' with 'io_context'. The
deprecated API was removed with asio 1.33."

Obtained from:	Fred Helmesjö
Obtained from:  https://github.com/eclipse-ecal/fineftp-server/commit/fc323ccece40626a9bf67b7e1983ff2addd00fe4

Failure without this patch was (14.2 poudriere):

[00:01:05] FAILED: fineftp-server/CMakeFiles/server.dir/src/server_impl.cpp.o
[00:01:05] /usr/local/libexec/ccache/c++ -DASIO_DISABLE_VISIBILITY -DASIO_STANDALONE -DDELAY_226_RESP_MS=0 -D_WIN32_WINNT=0x0601 -D__USE_FILE_OFFSET64=1 -Dserver_EXPORTS -I/wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/include -I/wrkdirs/usr/ports/ftp/fineftp-server/work/.build/fineftp-server/include -I/wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src -I/wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src/unix -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -fstack-protector-strong -fno-strict-aliasing   -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -pthread -MD -MT fineftp-server/CMakeFiles/server.dir/src/server_impl.cpp.o -MF fineftp-server/CMakeFiles/server.dir/src/server_impl.cpp.o.d -o fineftp-server/CMakeFiles/server.dir/src/server_impl.cpp.o -c /wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src/server_impl.cpp
[00:01:05] In file included from /wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src/server_impl.cpp:1:
[00:01:05] In file included from /wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src/server_impl.h:14:
[00:01:05] /wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src/ftp_session.h:36:22: error: no type named 'io_service' in namespace 'asio'
[00:01:05]    36 |     FtpSession(asio::io_service& io_service, const UserDatabase& user_database, const std::function<void()>& completion_handler, std::ostream& output, std::ostream& error);
[00:01:05]       |                ~~~~~~^
[00:01:05] /wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src/ftp_session.h:185:11: error: no type named 'io_service' in namespace 'asio'
[00:01:05]   185 |     asio::io_service&        io_service_;
[00:01:05]       |     ~~~~~~^
[00:01:05] /wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src/ftp_session.h:189:11: error: no member named 'io_service' in namespace 'asio'
[00:01:05]   189 |     asio::io_service::strand command_strand_;
[00:01:05]       |     ~~~~~~^
[00:01:05] /wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src/ftp_session.h:207:11: error: no member named 'io_service' in namespace 'asio'
[00:01:05]   207 |     asio::io_service::strand                       data_socket_strand_;
[00:01:05]       |     ~~~~~~^
[00:01:05] In file included from /wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src/server_impl.cpp:1:
[00:01:05] /wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src/server_impl.h:58:11: error: no type named 'io_service' in namespace 'asio'
[00:01:05]    58 |     asio::io_service         io_service_;
[00:01:05]       |     ~~~~~~^
[00:01:05] /wrkdirs/usr/ports/ftp/fineftp-server/work/fineftp-server-1.5.0/fineftp-server/src/server_impl.h:58:30: warning: private field 'io_service_' is not used [-Wunused-private-field]
[00:01:05]    58 |     asio::io_service         io_service_;
[00:01:05]       |                              ^
[00:01:05] 1 warning and 5 errors generated