java/openjfx14: fix build with clang 19
Clang 19 now implements CWG 96 [1], which requires a template argument
list after a 'template' keyword, resulting in errors similar to:

  /wrkdirs/usr/ports/java/openjfx14/work/jfx-14.0.2.1-1/modules/javafx.web/src/main/native/Source/JavaScriptCore/assembler/AbstractMacroAssembler.h:923:65: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
    923 |         AssemblerType::repatchCompact(dataLabelCompact.template dataLocation(), value);
        |                                                                 ^
  /wrkdirs/usr/ports/java/openjfx14/work/jfx-14.0.2.1-1/modules/javafx.web/src/main/native/Source/JavaScriptCore/runtime/JSCast.h:146:33: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
    146 |     return Dispatcher::template inherits(vm, from);
        |                                 ^
  /wrkdirs/usr/ports/java/openjfx14/work/jfx-14.0.2.1-1/modules/javafx.web/src/main/native/Source/JavaScriptCore/runtime/JSCast.h:155:37: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
    155 |     if (LIKELY(Dispatcher::template inherits(vm, from)))
        |                                     ^
  /wrkdirs/usr/ports/java/openjfx14/work/jfx-14.0.2.1-1/modules/javafx.web/src/main/native/Source/JavaScriptCore/llint/LLIntData.h:159:75: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
    159 |     return reinterpret_cast<LLIntCode>(getCodePtr<tag>(opcodeID).template executableAddress());
        |                                                                           ^

In all these cases, appending "<>" is enough to satisfy the constraint.

[1] https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#96

PR:		282473
MFH:		2024Q4
(cherry picked from commit aa9dd586527b3e2a402b9699c5a7934728a27bfe)