databases/rocksdb: Fix build on i386
utilities/transactions/pessimistic_transaction.cc:691:25: error: implicit conversion from 'type' (aka 'unsigned long long') to 'size_t' (aka 'unsigned int') changes value from 18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
                      : std::numeric_limits<uint64_t>::max();
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
utilities/transactions/pessimistic_transaction.cc:766:23: error: implicit conversion from 'type' (aka 'unsigned long long') to 'size_t' (aka 'unsigned int') changes value from 18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
                    : std::numeric_limits<uint64_t>::max();
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

(cherry picked from commit dffdaab0c8a9fadd083d0d6967231c97fb1ad053)