devel/cmake-(core|gui): Fix build with curl 8.13
Add upstream patch to fix incompatibility with curl >= 8.13.0. This is fixed
in CMake 3.31.7 and newer.

/wrkdirs/usr/ports/devel/cmake-gui/work/cmake-3.31.6/Source/cmCurl.cxx:178:26:
error: assigning to 'CURL_NETRC_OPTION' from incompatible type 'long'
  178 |       curl_netrc_level = CURL_NETRC_OPTIONAL;
      |                          ^~~~~~~~~~~~~~~~~~~
/usr/local/include/curl/curl.h:2355:29: note: expanded from macro 'CURL_NETRC_OPTIONAL'
 2355 | #define CURL_NETRC_OPTIONAL 1L /* A user:password in the URL will be preferred
      |                             ^~
/wrkdirs/usr/ports/devel/cmake-gui/work/cmake-3.31.6/Source/cmCurl.cxx:180:26:
error: assigning to 'CURL_NETRC_OPTION' from incompatible type 'long'
  180 |       curl_netrc_level = CURL_NETRC_REQUIRED;
      |                          ^~~~~~~~~~~~~~~~~~~
/usr/local/include/curl/curl.h:2357:29: note: expanded from macro 'CURL_NETRC_REQUIRED'
 2357 | #define CURL_NETRC_REQUIRED 2L /* A user:password in the URL will be ignored.
      |                             ^~
/wrkdirs/usr/ports/devel/cmake-gui/work/cmake-3.31.6/Source/cmCurl.cxx:182:26:
error: assigning to 'CURL_NETRC_OPTION' from incompatible type 'long'
  182 |       curl_netrc_level = CURL_NETRC_IGNORED;
      |                          ^~~~~~~~~~~~~~~~~~
/usr/local/include/curl/curl.h:2353:29: note: expanded from macro 'CURL_NETRC_IGNORED'
 2353 | #define CURL_NETRC_IGNORED  0L /* The .netrc will never be read.
      |                             ^~

PR:		286404
Reported by:	Ian Dickens <ian@south-border.com>, pkg-fallout

(cherry picked from commit 173806f44be4d33ab001357cea25ccc90b1c6eaf)