security/openvas: fix plist issue
poudriere -t (testport) complains about orphans
	Error: Orphaned: @dir /var/lib
even though the underlying directories **are** listed in the plist.
Add this directory as indicated.

Not bumping PORTREVISION because the package itself doesn't change.