multimedia/mpc-qt: update to 0.0.0.s20170422
And pacify stage-qa warning that appeared after r436603

Error: /usr/local/bin/mpc-qt is linked to /usr/local/lib/qt5/libQt5DBus.so.5 from devel/qt5-dbus butit is not declared as a dependency
Warning: you need USE_QT5+=dbus

Changes:	https://github.com/cmdrkotori/mpc-qt/compare/76fd545...508ddd0
MFH:		2017Q2