MFH: r505210 lang/python35: Use -std=c99
Python 3.5 is currently failing to build the pickle module on GCC-based
architectures, with the following (several) errors:

  error: 'for' loop initial declaration used outside C99 mode

This causes packaging to fail, as the pickle module filename changes on
failure to build, so the plist ends up incorrect

Python 3.6+ switched to using -std=c99 [1][2], but the changes were not
backported to 3.5

[1] https://bugs.python.org/issue28017
[2] https://hg.python.org/cpython/rev/b5b2bb56d303
[3] https://hg.python.org/cpython/rev/91017e2202ae

PR: 238821
Reviewed by: koobs (python)
Approved by: koobs (python), mat (mentor)
Differential Revision:  https://reviews.freebsd.org/D20778

Approved by:	ports-secteam (blanket: build fix)