math/z3: fix build with clang 19
Clang 19 has become more strict about errors in member functions, which
results in:

/wrkdirs/usr/ports/math/z3/work/z3-z3-4.13.0/src/math/lp/static_matrix.h:82:72: error: no member named 'get' in 'static_matrix<T, X>'; did you mean 'set'?
 82 |         ref operator=(ref & v) { m_matrix.set(m_row, m_col, v.m_matrix.get(v.m_row, v.m_col)); return *this; }
    |                                                                        ^~~
    |                                                                        set
/wrkdirs/usr/ports/math/z3/work/z3-z3-4.13.0/src/math/lp/static_matrix.h:164:10: note: 'set' declared here
164 |     void set(unsigned row, unsigned col, T const & val);
    |          ^

Upstream fixed this as part of a few other changes for gcc 15 in
<https://github.com/Z3Prover/z3/commit/2ce89e5f4>, but it does not apply
cleanly to this version, so add a backported patch.

PR:		281512
MFH:		2024Q3
(cherry picked from commit 88af7aa2d01a15a3d77380bf590921e04996ef45)