emulators/virtualbox-ose: error: use of undeclared identifier 'mempcpy'
1. There are no mempcpy on 12, on 13 before 1300513 and on 14 before 1400026.
Log with error is here:
https://lists.freebsd.org/archives/freebsd-pkg-fallout/2023-May/402233.html
2. 12 have llvm11 in base after 1203502 (llvm12 after 1203503 and llvm13
after 1203505), so not need to force build with llvm11 from ports.

Reported by:		https://portsfallout.com/fallout?port=emulators%2Fvirtualbox-ose%24
Reviewed by:		rene
Approved by:		arrowd (mentor), fuz
Differential Revision:	https://reviews.freebsd.org/D40163

(cherry picked from commit a39a00bddf995d665bb4ba4e89d7403d14060a6f)