devel/busd: unbreak without XDG_RUNTIME_DIR
$ busd
Error: No such file or directory (os error 2)

$ truss busd
[...]
socket(PF_LOCAL,SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK,0) = 9 (0x9)
bind(9,{ AF_UNIX "/run/user/1234/busd-session" },30) ERR#2 'No such file or directory'
[...]

May still fail if /var/run/user doesn't exist e.g., if neither pam_xdg
nor consolekit2 are installed. FreeBSD >= 14.1 always sets XDG_RUNTIME_DIR.

(cherry picked from commit 8b8f18da222dc7c8a23c73bf40f9d09924e436ea)