textproc/augeas: fix build with clang 16
Clang 16 has a new error about incompatible integer to pointer
conversions, which shows up when building textproc/augeas:

  augprint.c:1477:24: warning: call to undeclared function 'basename'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    char *program_name = basename(argv[0]);
			 ^
  augprint.c:1477:9: error: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
    char *program_name = basename(argv[0]);
	  ^		 ~~~~~~~~~~~~~~~~~

This is because basename(3) is declared in <libgen.h>, but augprint.c
does not include it. Upstream has already fixed this, so apply the
commit until there is a new release.

PR:		271316
Approved by:	portmgr (build fix blanket)
MFH:		2023Q2