MFH: r461855
www/waterfox: remove incompatible FF57 fix after r461852

error[E0609]: no field `for_non_inherited_property` on type `&mut values::computed::Context<'_>`
     --> objdir/toolkit/library/i686-unknown-freebsd/release/build/style-ca3e0643edd5022b/out/properties.rs:79382:25
      |
79382 |                 context.for_non_inherited_property =
      |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^

Reported by:	pkg-fallout
Pointy hat to:	jbeich (forgot to svn rm)
Approved by:	ports-secteam blanket