x11-toolkits/pangoxsl: unbreak build with pango >= 1.50
In file included from pango-xsl-attributes.c:25:
./pango-xsl-attributes.h:116:18: error: conflicting types for 'pango_attr_line_height_new'
PangoAttribute * pango_attr_line_height_new (gint line_height);
                 ^
/usr/local/include/pango-1.0/pango/pango-attributes.h:607:25: note: previous declaration is here
PangoAttribute *        pango_attr_line_height_new              (double                       factor);
                        ^
pango-xsl-attributes.c:620:1: error: conflicting types for 'pango_attr_line_height_new'
pango_attr_line_height_new (gint line_height)
^
/usr/local/include/pango-1.0/pango/pango-attributes.h:607:25: note: previous declaration is here
PangoAttribute *        pango_attr_line_height_new              (double                       factor);
                        ^

PR:		260916
Reported by:	antoine (via exp-run)
Regressed by:	https://gitlab.gnome.org/GNOME/pango/-/commit/623134f48ad9