x11-toolkits/gtk40: add missing VULKAN file
$ make check-plist
Error: Orphaned: include/gtk-4.0/gsk/vulkan/gskvulkanrenderer.h

PR:		256333
Approved by:	tcberner