x11-toolkits/pangox-compat: fix build with clang 16
Clang 16 has a new error about incompatible function types, which shows
up when building x11-toolkits/pangox-compat:

basic-x.c:687:23: error: incompatible function pointer types assigning to 'void (*)(PangoEngineShape *, PangoFont *, const char *, unsigned int, const PangoAnalysis *, PangoGlyphString *, const char *, unsigned int)' (aka 'void (*)(struct _PangoEngineShape *, struct _PangoFont *, const char *, unsigned int, const struct _PangoAnalysis *, struct _PangoGlyphString *, const char *, unsigned int)') from 'void (PangoEngineShape *, PangoFont *, const char *, gint, const PangoAnalysis *, PangoGlyphString *)' (aka 'void (struct _PangoEngineShape *, struct _PangoFont *, const char *, int, const struct _PangoAnalysis *, struct _PangoGlyphString *)') [-Wincompatible-function-pointer-types]
  class->script_shape = basic_engine_shape;
                      ^ ~~~~~~~~~~~~~~~~~~

This is because the 'script_shape' callback function in pango 1.50 has
the 'length' argument as 'unsigned int', and also two additional
parameters 'paragraph_text' and 'paragraph_length'. Even though it looks
like this callback function is never used, correct the arguments to fix
the error.

PR:		271709
Approved by:	fluffy (maintainer)
MFH:		2023Q2