multimedia/libxine: unbreak DAV1D=on after 3468f1957cf2
dav1d.c:547:12: error: no member named 'n_frame_threads' in 'struct Dav1dSettings'
  settings.n_frame_threads = (ncpu > 8) ? 4 : (ncpu < 2) ? 1 : ncpu/2;
  ~~~~~~~~ ^
dav1d.c:548:12: error: no member named 'n_tile_threads' in 'struct Dav1dSettings'
  settings.n_tile_threads = MAX(1, ncpu - settings.n_frame_threads + 1);
  ~~~~~~~~ ^
dav1d.c:548:52: error: no member named 'n_frame_threads' in 'struct Dav1dSettings'
  settings.n_tile_threads = MAX(1, ncpu - settings.n_frame_threads + 1);
                                          ~~~~~~~~ ^
dav1d.c:548:52: error: no member named 'n_frame_threads' in 'struct Dav1dSettings'
  settings.n_tile_threads = MAX(1, ncpu - settings.n_frame_threads + 1);
                                          ~~~~~~~~ ^
/usr/include/sys/param.h:306:34: note: expanded from macro 'MAX'
 #define MAX(a,b) (((a)>(b))?(a):(b))
                                  ^
dav1d.c:551:22: error: no member named 'n_frame_threads' in 'struct Dav1dSettings'
            settings.n_frame_threads, settings.n_tile_threads);
            ~~~~~~~~ ^
dav1d.c:551:48: error: no member named 'n_tile_threads' in 'struct Dav1dSettings'
            settings.n_frame_threads, settings.n_tile_threads);
                                      ~~~~~~~~ ^
../../include/xine/xineutils.h:687:40: note: expanded from macro 'xprintf'
        xine_log(xine, XINE_LOG_TRACE, __VA_ARGS__);                        \
                                       ^~~~~~~~~~~

PR:		262651
(cherry picked from commit 3b3b0fa358409a78150119c36d8cd236de7f91fc)