sysutils/fluent-bit: fix build on powerpc
/usr/local/bin/ld: bss-plt forced due to ../lib/libluajit.a(lj_vm.o)
/usr/local/bin/ld: ../library/libcmetrics.a(cmt_atomic_gcc.c.o): in function `cmt_atomic_compare_exchange':
cmt_atomic_gcc.c:(.text+0x50): undefined reference to `__atomic_compare_exchange_8'
/usr/local/bin/ld: ../library/libcmetrics.a(cmt_atomic_gcc.c.o): in function `cmt_atomic_store':
cmt_atomic_gcc.c:(.text+0x8c): undefined reference to `__atomic_store_8'
/usr/local/bin/ld: ../library/libcmetrics.a(cmt_atomic_gcc.c.o): in function `cmt_atomic_load':
cmt_atomic_gcc.c:(.text+0xc8): undefined reference to `__atomic_load_8'