games/hedgewars: mark BROKEN on i386
Link fails with 'ld: error: duplicate symbol: LandDirty_dimension_info'
on some code converted from pascal to C, so this would be non-trivial
to fix.