www/cliqz: revert r527481 for this port
***** Building *****
+ ./mach build
Traceback (most recent call last):
  File "./mach", line 269, in <module>
    main(sys.argv[1:])
  File "./mach", line 261, in main
    mach = get_mach()
  File "./mach", line 251, in get_mach
    mach = check_and_get_mach(dir_path)
  File "./mach", line 207, in check_and_get_mach
    return load_mach(dir_path, mach_path)
  File "./mach", line 195, in load_mach
    return mach_bootstrap.bootstrap(dir_path)
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/build/mach_bootstrap.py", line 399, in bootstrap
    driver.load_commands_from_file(os.path.join(mozilla_dir, path))
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/python/mach/mach/main.py", line 267, in load_commands_from_file
    imp.load_source(module_name, path)
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/remote/mach_commands.py", line 30, in <module>
    import mozprofile
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/build/mach_bootstrap.py", line 431, in __call__
    module = self._original_import(name, globals, locals, fromlist, level)
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/testing/mozbase/mozprofile/mozprofile/__init__.py", line 17, in <module>
    from mozprofile.cli import *
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/build/mach_bootstrap.py", line 431, in __call__
    module = self._original_import(name, globals, locals, fromlist, level)
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/testing/mozbase/mozprofile/mozprofile/cli.py", line 18, in <module>
    from .profile import FirefoxProfile
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/build/mach_bootstrap.py", line 431, in __call__
    module = self._original_import(name, globals, locals, fromlist, level)
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/testing/mozbase/mozprofile/mozprofile/profile.py", line 20, in <module>
    from .permissions import Permissions
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/build/mach_bootstrap.py", line 431, in __call__
    module = self._original_import(name, globals, locals, fromlist, level)
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/testing/mozbase/mozprofile/mozprofile/permissions.py", line 14, in <module>
    import sqlite3
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/build/mach_bootstrap.py", line 431, in __call__
    module = self._original_import(name, globals, locals, fromlist, level)
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/build/mach_bootstrap.py", line 431, in __call__
    module = self._original_import(name, globals, locals, fromlist, level)
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
  File "/usr/ports/www/cliqz/work/browser-f-1.33.0/mozilla-release/build/mach_bootstrap.py", line 431, in __call__
    module = self._original_import(name, globals, locals, fromlist, level)
ImportError: No module named _sqlite3
*** Error code 1

PR:		244521
Reported by:	fox (maintainer), pkg-fallout
Point hat to:	jbeich (forgot to pass "-C" to poudriere bulk)