textproc/qrcodegen: Fix run when Java 11+ is default, take maintainership
Port require Java 8 - doesn't work with 9+:
Sep 09, 2025 4:54:36 PM qrcodegen.Loader handleException
SEVERE: null
java.lang.NoClassDefFoundError: javax/xml/bind/DataBindingException

This is because the javax.xml libraries moved in Java 9.

Improve port:
- Replace PORTVERSION with DISTVERSION.
- Use zip in USES instead of zip:infozip - work fine without archivers/unzip.
- Replace do-extract with EXTRACT_BEFORE_ARGS/EXTRACT_AFTER_ARGS.
- Parametrize qrcodegen with ${PORTNAME}.
- Install all files with one INSTALL_DATA instead of 5 in loop "for".

PR:		289421
Co-authored-by:	Vladimir Druzenko <vvd@FreeBSD.org>
MFH:		2025Q3
(cherry picked from commit fa5e5ade4600c74f31e91ebc4285ae057a22903b)