games/veloren-weekly: mark BROKEN on aarch64 after d131803c879b
error: unsupported platform
   --> cargo-crates/wasmtime-39.0.0/src/runtime/vm/sys/unix/signals.rs:394:13
    |
394 |             compile_error!("unsupported platform");
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Reported by:	pkg-fallout

(cherry picked from commit 67281c666f49af11df7287ac5b624436ecc0c3f5)