MFH: r505006 devel/py-osprofiler: Add missing dependency
osprofiler requires pbr>=1.8 at build time, and fails with the following
error at configure time when it is not available:

  distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=1.8')

Reported by:	poudriere: pbr reverse dependents bulk (exp) run
Approved by:	portmgr (blanket(s): missing dependencies, build fix)

Approved by:	ports-secteam (blanket: build fix, dependencies)