games/scummvm: Unbreak build with FLUIDSYNTH=on
After commit 4c2db26adf7d the build, if the non-default option
FLUIDSYNTH is enabled, fails with:

In file included from audio/softsynth/fluidsynth.cpp:32:
In file included from /usr/local/include/fluidsynth.h:100:
[..]
audio/softsynth/fluidsynth.cpp:252:3: error:
   no matching function for call to 'fluid_sfloader_set_callbacks'
                fluid_sfloader_set_callbacks(soundFontMemoryLoader,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/fluidsynth/sfont.h:172:20: note:
   candidate function not viable:
   no known conversion from 'int (void *, int, void *)' to
   'fluid_sfloader_callback_read_t' (aka 'int (*)(void *, long long, void *)') for 3rd argument
FLUIDSYNTH_API int fluid_sfloader_set_callbacks(fluid_sfloader_t *loader,
                   ^

Obtained from:	NetBSD
MFH:		2021Q4