cad/qcad: Fix PLIST
- Bump PORTREVISION for package change

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%DATADIR%%/scripts/Tutorial/GenerateTutorial/doc/GenerateTutorial_da.html
Error: Orphaned: %%DATADIR%%/scripts/Tutorial/GenerateTutorial/doc/GenerateTutorial_es.html
Error: Orphaned: %%DATADIR%%/scripts/Tutorial/GenerateTutorial/doc/GenerateTutorial_ja.html
Error: Orphaned: %%DATADIR%%/scripts/Tutorial/GenerateTutorial/doc/GenerateTutorial_pl.html
Error: Orphaned: %%DATADIR%%/scripts/org.qcad.QCAD.png
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/applications/usr_local_bin_qcadbin.desktop
===> Error: Plist issues found.
*** Error code 1

Approved by:	portmgr (blanket)