graphics/cairo: define _WITH_CPU_SET_T to fix build on -CURRENT
Changes in 90fa9705d5cd hide functionality behind _WITH_CPU_SET_T,
and require consumers to opt-in.

Error:
	--- cairo-perf-micro.o ---
	cairo-perf-micro.c:418:5: error: unknown type name 'cpu_set_t'; did you mean 'cpusetid_t'?
	    cpu_set_t affinity;
	    ^~~~~~~~~
	    cpusetid_t
	/usr/include/sys/types.h:86:22: note: 'cpusetid_t' declared here
	typedef __cpusetid_t    cpusetid_t;
                        ^

PR:		259787
(cherry picked from commit ad03eb1e0a2f1a5af74070aa47ca837f2ab6ddb9)