audio/rhythmbox: fix plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/rhythmbox/plugins/android/android.plugin
Error: Orphaned: lib/rhythmbox/plugins/android/libandroid.so