science/dlib-cpp: fix build with clang and libc++ 19
As noted in the libc++ 19 release notes [1], std::char_traits<> is now
only provided for char, char8_t, char16_t, char32_t and wchar_t, and any
instantiation for other types will fail.

This causes science/dlib-cpp to fail to compile with clang 19 and
libc++ 19, resulting in errors similar to:

  /usr/include/c++/v1/string:820:42: error: implicit instantiation of undefined template 'std::char_traits<unsigned int>'
    820 |   static_assert(is_same<_CharT, typename traits_type::char_type>::value,
        |                                          ^
  /wrkdirs/usr/ports/science/dlib-cpp/work/dlib-19.24/dlib/bigint/../unicode/unicode.h:496:26: note: in instantiation of template class 'std::basic_string<unsigned int>' requested here
    496 |     inline const ustring convert_utf8_to_utf32 (
        |                          ^
  /usr/include/c++/v1/__fwd/string.h:23:29: note: template is declared here
     23 | struct _LIBCPP_TEMPLATE_VIS char_traits;
        |                             ^

These can be fixed by using `char32_t` instead of `uint32_t` for the
`unichar` type.

Also, clang 19 now implements CWG 96 [1], which requires a template
argument list after a 'template' keyword, resulting in errors similar
to:

  /wrkdirs/usr/ports/science/dlib-cpp/work/dlib-19.24/dlib/filtering/../global_optimization/find_max_global.h:61:130: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
     61 |             static auto go(T&& f, const matrix<double,0,1>& a) -> decltype(call_function_and_expand_args<max_unpack-1>::template go(std::forward<T>(f),a))
        |                                                                                                                                  ^

This can be fixed by adding `<>` after the `go` identifier.

[1] https://libcxx.llvm.org/ReleaseNotes/19.html#deprecations-and-removals

PR:		281975
Approved by:	arrowd (maintainer)
MFH:		2024Q3

(cherry picked from commit e8b1dca33760dc680dcc732dcd3e9c7be1d79e76)