Pending a better fix, mark broken when the RE2 option is enabled. Recent versions of devel/re2 install headers that result in error messages like so:
/usr/local/include/re2/re2.h:915:5: error: no matching function for call to 'call_once'
    std::call_once(once_, &LazyRE2::Init, this);
    ^~~~~~~~~~~~~~

No change to the default package, so no PORTREVISION bump.

PR:		219239
Submitted by:	mail+freebsd@gerritbeine.de, w.schwarzenfeld@utanet.at