databases/tablelog: Unbreak build with PostgreSQL >= 11.0
table_log.c:76:29: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
    if (!tupleDesc->attrs[i]->attisdropped) {
         ~~~~~~~~~~~~~~~~~~~^~
                            .
table_log.c:303:59: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
      if (trigdata->tg_relation->rd_att->attrs[col_nr - 1]->attisdropped) {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                                                          .
table_log.c:348:59: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
      if (trigdata->tg_relation->rd_att->attrs[col_nr - 1]->attisdropped) {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                                                          .
table_log.c:375:59: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
      if (trigdata->tg_relation->rd_att->attrs[col_nr - 1]->attisdropped) {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                                                          .
4 errors generated.

http://package18.nyi.freebsd.org/data/120amd64-default-PR239514/2019-07-29_20h41m52s/logs/tablelog-0.4.4_3.log

While here

- Mark it as deprecated.  The last release was in 2007 and upstream
  has been inactive since then.
- Fix WWW

PR:		239514
Reported by:	antoine (via exp-run)