graphics/bgfx: fix build on powerpc64* and probably riscv64
/wrkdirs/usr/ports/graphics/bgfx/work/bgfx.cmake-1.118.8398-370/bimg/3rdparty/nvtt/nvcore/debug.h:173:10: error: cast from pointer to smaller type 'uint32' (aka 'unsigned int') loses information
            if (reinterpret_cast<uint32>(ptr) == 0xcccccccc) return false;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/graphics/bgfx/work/bgfx.cmake-1.118.8398-370/bimg/3rdparty/nvtt/nvcore/debug.h:174:10: error: cast from pointer to smaller type 'uint32' (aka 'unsigned int') loses information
            if (reinterpret_cast<uint32>(ptr) == 0xcdcdcdcd) return false;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/graphics/bgfx/work/bgfx.cmake-1.118.8398-370/bimg/3rdparty/nvtt/nvcore/debug.h:175:10: error: cast from pointer to smaller type 'uint32' (aka 'unsigned int') loses information
            if (reinterpret_cast<uint32>(ptr) == 0xdddddddd) return false;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/graphics/bgfx/work/bgfx.cmake-1.118.8398-370/bimg/3rdparty/nvtt/nvcore/debug.h:176:10: error: cast from pointer to smaller type 'uint32' (aka 'unsigned int') loses information
            if (reinterpret_cast<uint32>(ptr) == 0xffffffff) return false;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit 32cf9412c58d339066e091ad088126e1236b52dd)