multimedia/celluloid: unbreak with gtk4/X11=off after 51d62dcf1e3d
../src/celluloid-video-area.c:28:10: fatal error: 'gdk/x11/gdkx.h' file not found
 #include <gdk/x11/gdkx.h>
          ^~~~~~~~~~~~~~~~

(cherry picked from commit 492fe7fbe48b568258866d01863de5eb0216b513)