net-p2p/py-transmission-rpc: add missing dependency after 5e8a1c66f255
>>> import transmission_rpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/transmission_rpc/__init__.py", line 6, in <module>
    from transmission_rpc.types import File, Group
  File "/usr/local/lib/python3.9/site-packages/transmission_rpc/types.py", line 3, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'