games/veloren: Unbreak with Rust 1.56.0
error[E0557]: feature has been removed
   --> /wrkdirs/usr/ports/games/veloren/work/veloren-e4716147a7356eb13088e7d74ace3ccdcb5cd900/cargo-crates/packed_simd_2-0.3.5/src/lib.rs:215:5
    |
215 |     const_generics,
    |     ^^^^^^^^^^^^^^ feature has been removed
    |
    = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

PR:		259251