science/cgribex: fix build on powerpc64le with LLVM 13
./minmax_val.c:324:2: error: address of register variable requested
        dmin[j] = data[0];
        ^~~~

While here, remove the __fsel implementation and switch to __builtin_ppc_fsel that LLVM provides.