devel/py-Jinja2: support staging and do general clean-up
- remove indefinite article from COMMENT
- add license (BSD3C)
- do not use easy_install for installation and convert to auto-generated packing list
- add staging support
- simplify docs installation:
  - install docs manually
  - install docs unconditionally into staging area
  - no need to install doc sources, compiled html versions are suffice
- limit python version to 2.x only:
  ===>  Configuring for py33-Jinja-1.2_3
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "setup.py", line 28
      except DistutilsError, e:
                         ^
  SyntaxError: invalid syntax
  *** Error code 1
- remove deprecated author attribution from pkg-descr and do tab->space change in WWW
- bump PORTREVISION

Approved by:	nivit (maintainer, explicitly for such changes in his ports)