sysutils/nut-devel: Update to the latest networkupstools/nut github commit
In addition to this update, the nutworkupstools upstream's check for
ltdl.h now fails on llvm as of upstream commit 17eeef008 with the
following error during configure:

conftest.c:240:10: fatal error: 'ltdl.h' file not found
         ^~~~~~~~
1 error generated.

They put the correct arguments into the CLFAGS environment variable however
llvm does not see the environment variable whereas gcc does. Adding USE_GCC
works around this problem for now.