emulators/elliott: fix unused but set variable
During an exp-run for llvm 13 (see bug 258209), it turned out that
emulators/elliott fails to build with clang 13:

emulator.c:536:20: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        int x, x1, y;
                   ^
1 error generated.

This is because x, x1 and y are used in ncurses getyx() macros, but in
this case the program is not interested in the y result. Mark it as
__unused to get rid of the warning.

PR:		258471
Approved by:	maintainer timeout (2 weeks)
MFH:		2021Q4