audio/mumble-server: fix build on i386
/wrkdirs/usr/ports/audio/mumble-server/work/mumble-1.5.613/src/murmur/Server.cpp:1044:21:
error: implicit conversion changes signedness: 'int' to 'std::vector<char>::size_type'
(aka 'unsigned int') [-Werror,-Wsign-conversion]
                bufVec.resize(len + 4);
                       ~~~~~~ ~~~~^~~
1 error generated.

Upstream issue: https://github.com/mumble-voip/mumble/issues/6377

Reported by:	pkg-fallout
Approved by:	arrowd (mentor, implicit)
MFH:		2024Q2

(cherry picked from commit f0a4c1f73b3bbdb738019d9b476e027a3ba160a8)