textproc/groff: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because textproc/groff's Makefile does not explicitly set its C++
standard, this leads to several errors:

  src/preproc/grn/hdb.cpp:38:15: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  int DBGetType(register char *s);
                ^~~~~~~~~
  src/preproc/grn/hdb.cpp:64:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register ELT *temp;
    ^~~~~~~~~
  src/preproc/grn/hdb.cpp:83:8: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  DBRead(register FILE *file)
         ^~~~~~~~~
  src/preproc/grn/hdb.cpp:85:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register int i;
    ^~~~~~~~~
  src/preproc/grn/hdb.cpp:86:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register int done;            /* flag for input exhausted */
    ^~~~~~~~~
  src/preproc/grn/hdb.cpp:87:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register double nx;           /* x holder so x is not set before orienting */
    ^~~~~~~~~
  src/preproc/grn/hdb.cpp:212:11: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  DBGetType(register char *s)
            ^~~~~~~~~

Add USE_CXXSTD=gnu++98 to avoid these errors.

Approved by:	bapt (maintainer)
MFH:		2023Q2