emulators/yuzu: unbreak build on aarch64
In file included from src/core/debugger/debugger.cpp:8:
In file included from /usr/local/include/boost/asio.hpp:20:
In file included from /usr/local/include/boost/asio/append.hpp:74:
In file included from /usr/local/include/boost/asio/impl/append.hpp:22:
In file included from /usr/local/include/boost/asio/detail/handler_alloc_helpers.hpp:21:
In file included from /usr/local/include/boost/asio/detail/recycling_allocator.hpp:20:
In file included from /usr/local/include/boost/asio/detail/thread_context.hpp:20:
In file included from /usr/local/include/boost/asio/detail/call_stack.hpp:20:
In file included from /usr/local/include/boost/asio/detail/tss_ptr.hpp:27:
In file included from /usr/local/include/boost/asio/detail/posix_tss_ptr.hpp:76:
In file included from /usr/local/include/boost/asio/detail/impl/posix_tss_ptr.ipp:23:
In file included from /usr/local/include/boost/asio/detail/throw_error.hpp:20:
In file included from /usr/local/include/boost/system/error_code.hpp:13:
In file included from /usr/local/include/boost/system/detail/error_code.hpp:15:
In file included from /usr/local/include/boost/system/detail/error_condition.hpp:18:
In file included from /usr/local/include/boost/system/detail/append_int.hpp:8:
/usr/local/include/boost/system/detail/snprintf.hpp:62:13: error: non-const lvalue reference to type '__builtin_va_list' cannot bind to a value of unrelated type 'va_list' (aka 'std::__va_list')
    va_end( args );
            ^~~~
/usr/include/sys/_stdarg.h:51:40: note: expanded from macro 'va_end'
  #define       va_end(ap)              __builtin_va_end(ap)
                                                         ^~

Reported by:	pkg-fallout

(cherry picked from commit f98c438a01911643667fecb0780638d60d3843dd)