textproc/askgit: Add missing build dependency.
  # github.com/mattn/go-sqlite3
  vendor/github.com/mattn/go-sqlite3/backup.go:12:10: fatal error: 'sqlite3.h' file not found
  #include <sqlite3.h>

Approved by:	portmgr (build fix blanket)