graphics/f-spot: Mark BROKEN (does not build)
build log:
./Hyena.Data.Gui/ListView/ListView_Rendering.cs(128,41): error CS0012: The
 type `Cairo.Context' is defined in an assembly that is not referenced.
 Consider adding a reference to assembly `Mono.Cairo, Version=4.0.0.0,
 Culture=neutral, PublicKeyToken=0738eb9f132ed756'
(cut warnings)
Compilation failed: 2 error(s), 77 warnings
gmake[5]: *** [../../../bin/Hyena.Gui.dll] Error 1
gmake[5]: Leaving directory `/wrkdirs/usr/ports/graphics/f-spot/work/
 f-spot-0.8.2/lib/Hyena/Hyena.Gui'

PR: ports/181403 (timed out)