x11-wm/hyprland: switch to wlroots-devel to simplify updates
Giving up adding more workarounds after 0.36.0 introduced

https://github.com/hyprwm/Hyprland/commit/301b48b74087
https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/20935646168f

../src/render/Renderer.cpp:2501:9: error: use of undeclared identifier 'wlr_damage_ring_rotate_buffer'
 2501 |         wlr_damage_ring_rotate_buffer(&pMonitor->damage, m_pCurrentWlrBuffer, damage.pixman());
      |         ^

This reverts commit 46de20d9e039ad2aacc3ee6d1434b9c2d604fb83.
This reverts commit 474e59a13f289a0cade43c95ea01ef042f22665b.