devel/py-platformdirs: Unbreak after 2.5.2 update
The upgrade of py-platformdirs to 2.5.2 breaks pylint (and most
certainly anything else that uses the module):

    lns 57 % pylint [...] lblcache.py
    [...]
    ModuleNotFoundError: No module named 'platformdirs'

Apply the tweak described here to adjust for the "src" subdir in
the distribution:

    https://stackoverflow.com/a/36012825/2994620

PR:		263639
Approved by:	koobs (portmgr blanket: runtime bugfix)