cad/freecad-devel: fix packaging with python!=3.12
Eliminate oblivously writed %%PYTHON_SUFFIX%% for gost-2_312 values

===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_312/cathetus.svg
Error: Orphaned: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_312/gost-2_312-intermittent.svg
Error: Orphaned: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_312/gost-2_312-non-closed.svg
Error: Orphaned: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_312/gost-2_312-site-weld.svg
Error: Orphaned: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_312/gost-2_312-smooth-processing.svg
Error: Orphaned: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_312/gost-2_312-usilenie-remove.svg
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_%%PYTHON_SUFFIX%%/cathetus.svg
Error: Missing: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_%%PYTHON_SUFFIX%%/gost-2_%%PYTHON_SUFFIX%%-intermittent.svg
Error: Missing: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_%%PYTHON_SUFFIX%%/gost-2_%%PYTHON_SUFFIX%%-non-closed.svg
Error: Missing: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_%%PYTHON_SUFFIX%%/gost-2_%%PYTHON_SUFFIX%%-site-weld.svg
Error: Missing: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_%%PYTHON_SUFFIX%%/gost-2_%%PYTHON_SUFFIX%%-smooth-processing.svg
Error: Missing: FreeCAD/share/Mod/TechDraw/Symbols/Welding/GOST/gost-2_%%PYTHON_SUFFIX%%/gost-2_%%PYTHON_SUFFIX%%-usilenie-remove.svg
===> Error: Plist issues found.
*** Error code 1

Reported by:	bulk -t
Approved by:	portmgr blanket