math/linbox: fix build with clang 19
Clang 19 has become more strict about errors in member functions, which
results in errors building math/linbox:

  ../../linbox/vector/blas-subvector.h:121:20: error: no member named 'data' in 'BlasSubvector<_Vector>'
    121 |             _ptr(V.data()+beg), _size(dim), _inc(inc), _field(&V.field()) {}
        |                  ~ ^
  ../../linbox/matrix/sparsematrix/sparse-ell-matrix.h:1216:16: error: cannot assign to non-static data member '_ld' with const-qualified type 'const size_t &' (aka 'const unsigned long &')
   1216 |                                 _ld        = iter._ld ;
        |                                 ~~~        ^
  ../../linbox/matrix/sparsematrix/sparse-ellr-matrix.h:1108:12: error: no viable overloaded '='
   1108 |                                 _rowid = iter._rowid;
        |                                 ~~~~~~ ^ ~~~~~~~~~~~

In all these cases, the methods where the errors occur are not actually
used, so until upstream sorts out their incorrect code, stub them out
using #if 0/#endif pairs.

PR:		284159
Approved by:	thierry (maintainer)
MFH:		2025Q1

(cherry picked from commit 6e2222799ebf6ff0a12bed3798fc0cc0e71e1e55)