net/rustconn: Update to 0.20.4
- Mark BROKEN on i386[1]. It does not compile:

error[E0308]: mismatched types
    --> rustconn-core/src/rdp_client/rdpdr.rs:1179:37
     |
1179 |         let omit = TimeSpec::new(0, i64::from(nix::libc::UTIME_OMIT));
     |                    -------------    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `i64`
     |                    |
     |                    arguments to this function are incorrect

ChangeLog:

1. https://github.com/totoshko88/RustConn/releases/tag/v0.21.3
2. https://github.com/totoshko88/RustConn/releases/tag/v0.21.4

Reported by:	"github-actions[bot]" <notifications@github.com>
Reported by:	pkg-fallout [1]