devel/lutok: fix build with clang 16
Since clang 16 (and gcc 11) the default C++ standard is now gnu++17.
Because devel/lutok's Makefile does not explicitly set its C++ standard,
this leads to an error:

  In file included from operations.cpp:35:
  ./stack_cleaner.hpp:75:10: error: no template named 'auto_ptr' in namespace 'std'
      std::auto_ptr< impl > _pimpl;
      ~~~~~^

Add USE_CXXSTD=gnu++98 to avoid the error. While here, pet portlint.

PR:		271053
Approved by:	maintainer timeout (2 weeks)
MFH:		2023Q2