misc/xplr: Unbreak build on FreeBSD 11-{i386,amd64}
getentropy(3) did not appear until FreeBSD 12, anything lower will
not compile, throwing an undefined reference to `getentropy'.  We can
safely remove this once FreeBSD 11 is EOL.

Reported-by:	pkg-fallout
(cherry picked from commit a3c6016fadb2d5a19fba9230cf49f17be1241f8f)