Add USES=compiler:c++11-lang.
This fixes digikam-kde4's build on 9.3 after the graphics/lensfun update in
r411373.

lensfun.h includes C++ code (class and template declarations) inside an
extern "C" block that causes base GCC to fail:

/usr/local/include/lensfun/lensfun.h:2506: error: template with C linkage
/usr/local/include/lensfun/lensfun.h:2508: error: template with C linkage