science/py-onnx: fix build with GCC-based architectures
Use C11 compiler because of:
/wrkdirs/usr/ports/science/py-onnx/work-py36/onnx-1.5.0/onnx/onnxifi_loader.c:121: error: 'struct onnxifi_library' has no member named 'functions'

Approved by:	mentors (implicit approval)