databases/mongodb60: mark ignore on FreeBSD 12.3.
Summary:
Llvm in FreeBSD 12.3 gives several compile errors.
One example:
src/mongo/s/sharding_initialization.cpp:171:49: error: no viable constructor or deduction guide for deduction of template arguments of 'weak_ptr'
    connPoolOptions.controllerFactory = [srwp = std::weak_ptr(srsp)] {

http://beefy6.nyi.freebsd.org/data/123amd64-default/0116f5c59197/logs/errors/mongodb60-6.0.2.log

12.4 is expected to work again due to new libc++

PR:	266587
Approved by: rene (mentor)
MFH:	2022Q4
Differential Revision: https://reviews.freebsd.org/D37230