databases/mongodb42: unbreak build after 620968a43a5f
Checking if C compiler supports -flto... yes
Checking if linker supports -flto... no
Link time optimization requested, but selected compiler does not honor -flto
[...]
/usr/local/bin/ld.gold: error: /usr/bin/../lib/LLVMgold.so: could not load plugin library: Cannot open "/usr/bin/../lib/LLVMgold.so"
/usr/local/bin/ld.gold: error: build/scons/opt/sconf_temp/conftest_25fe9b7eeda4aef15b03635be7f9c29c_6.o:1:3: invalid character
/usr/local/bin/ld.gold: error: build/scons/opt/sconf_temp/conftest_25fe9b7eeda4aef15b03635be7f9c29c_6.o:1:3: syntax error, unexpected $end
/usr/local/bin/ld.gold: error: build/scons/opt/sconf_temp/conftest_25fe9b7eeda4aef15b03635be7f9c29c_6.o: not an object or archive
/usr/src/lib/csu/amd64/crt1.c:76: error: undefined reference to 'main'
cc: error: linker command failed with exit code 1 (use -v to see invocation)

Reported by:	pkg-fallout
Obtained from:	upstream (via mongodb44)

(cherry picked from commit 3292ccea5b5c050100cc64bbbb9fcf13de177161)