MFH: r533584
security/nss: disable -Werror due to -Wall mine

blinit.c:122:24: error: unused variable 'getauxval' [-Werror,-Wunused-variable]
static unsigned long (*getauxval)(unsigned long) = NULL;
                       ^

pqg.c:345:16: error: comparison of constant 18446744073709551615 with expression of type 'unsigned long' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
    if (addend < MP_DIGIT_MAX) {
        ~~~~~~ ^ ~~~~~~~~~~~~

PR:		242523
Approved by:	ports-secteam blanket