- Limit python version (does not build with 3.8) - Add NO_ARCH
Failure with 3.8:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 6, in <module>
    import joblib
  File "/wrkdirs/usr/ports/devel/py-joblib/work-py38/joblib-0.13.0/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/wrkdirs/usr/ports/devel/py-joblib/work-py38/joblib-0.13.0/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/wrkdirs/usr/ports/devel/py-joblib/work-py38/joblib-0.13.0/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/wrkdirs/usr/ports/devel/py-joblib/work-py38/joblib-0.13.0/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/wrkdirs/usr/ports/devel/py-joblib/work-py38/joblib-0.13.0/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "/wrkdirs/usr/ports/devel/py-joblib/work-py38/joblib-0.13.0/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from joblib.externals import cloudpickle  # noqa: F401
  File "/wrkdirs/usr/ports/devel/py-joblib/work-py38/joblib-0.13.0/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/wrkdirs/usr/ports/devel/py-joblib/work-py38/joblib-0.13.0/joblib/externals/cloudpickle/cloudpickle.py", line 167, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/wrkdirs/usr/ports/devel/py-joblib/work-py38/joblib-0.13.0/joblib/externals/cloudpickle/cloudpickle.py", line 148, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
*** Error code 1

Approved by:	portmgr blanket