math/labplot: fix build on armv7
Something (I couldn't quite figure out what) adds -Werror=undef to the
CPPFLAGS, causing a fatal warning somewhere in the Eigen headers:

/usr/local/include/eigen3/Eigen/src/Core/arch/NEON/PacketMath.h:3924:5: error: 'EIGEN_HAS_ARM64_FP16_VECTOR_ARITHMETIC'
is not defined, evaluates to 0 [-Werror,-Wundef]
 3924 | #if EIGEN_HAS_ARM64_FP16_VECTOR_ARITHMETIC
      |     ^

Making this warning not an error fixes the build.

Approved by:	portmgr (build fix blanket)
MFH:		2025Q3

(cherry picked from commit 2d1b76e570489462b5c891f7b25f38dc864eb642)