- Add LICENSE - Add missing LIB_DEPENDS and solve a stage-qa error
libogg is a required dependency. PORTREVISION was not bumped because libogg
is already a package dependency via audio/libvorbis.

from README:

Requirements summary:
  For libtheora:
      libogg 1.1 or newer.

====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/libtheora.so.0.3.10 is linked to /usr/local/lib/libogg.so.0 from audio/libogg but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libogg.so:audio/libogg

Approved by:	portmgr (blanket)