www/node18: fix build on powerpc64*
In file included from ../deps/v8/src/compiler/backend/ppc/code-generator-ppc.cc:6:
In file included from ../deps/v8/src/codegen/assembler-inl.h:8:
In file included from ../deps/v8/src/codegen/assembler.h:46:
In file included from ../deps/v8/src/codegen/external-reference.h:9:
In file included from ../deps/v8/src/runtime/runtime.h:11:
../deps/v8/src/base/bit-field.h:43:29: error: integer value 31 is outside the valid range of values [0, 3] for the enumeration type 'AddressingMode' [-Wenum-constexpr-conversion]
  static constexpr T kMax = static_cast<T>(kNumValues - 1);

(cherry picked from commit d59ea56e40877edaaeb8a04eba0f539f9d3621d2)