MFH: r523845
fix build

in a 12.1amd64 poudriere, chromium failed:
In file included from ../../third_party/leveldatabase/port/port_chromium.cc:10:
../../third_party/snappy/src/snappy.h:76:59: error: unknown type name 'string'; did you mean 'std::string'?
  size_t Compress(const char* input, size_t input_length, string* output);
                                                          ^~~~~~
                                                          std::string
/usr/include/c++/v1/iosfwd:211:65: note: 'std::string' declared here

instead of trying to muck around with type aliasing (see
snappy-stubs-public.h.in) just reference thy type directly, as there's only
one file requiring patching.

Approved by:	portmgr (blanket: web browser, just fix it)