net/opal: unbreak with ffmpeg 4.0
h263-1998.cxx:237:22: error: use of undeclared identifier 'CODEC_FLAG_TRUNCATED'
  m_context->flags = CODEC_FLAG_TRUNCATED  // Possible missing packets
                     ^
h263-1998.cxx:346:27: error: use of undeclared identifier 'CODEC_FLAG_AC_PRED'
      m_context->flags |= CODEC_FLAG_AC_PRED;
                          ^
h263-1998.cxx:348:28: error: use of undeclared identifier 'CODEC_FLAG_AC_PRED'
      m_context->flags &= ~CODEC_FLAG_AC_PRED;
                           ^
h263-1998.cxx:356:27: error: use of undeclared identifier 'CODEC_FLAG_LOOP_FILTER'
      m_context->flags |= CODEC_FLAG_LOOP_FILTER;
                          ^
h263-1998.cxx:358:28: error: use of undeclared identifier 'CODEC_FLAG_LOOP_FILTER'
      m_context->flags &= ~CODEC_FLAG_LOOP_FILTER;
                           ^
h263-1998.cxx:422:14: error: no member named 'lmin' in 'AVCodecContext'; did you mean 'qmin'?
  m_context->lmin = m_context->qmin * FF_QP2LAMBDA;
             ^~~~
             qmin
/usr/local/include/libavcodec/avcodec.h:2355:9: note: 'qmin' declared here
    int qmin;
        ^
h263-1998.cxx:423:14: error: no member named 'lmax' in 'AVCodecContext'; did you mean 'qmax'?
  m_context->lmax = m_context->qmax * FF_QP2LAMBDA;
             ^~~~
             qmax
/usr/local/include/libavcodec/avcodec.h:2362:9: note: 'qmax' declared here
    int qmax;
        ^
h263-1998.cxx:598:24: error: use of undeclared identifier 'CODEC_FLAG_4MV'
  m_context->flags &= ~CODEC_FLAG_4MV;
                       ^

PR:		227726
Reported by:	antoine (via exp-run)