x11/shotman: unbreak build after ebf29acc6ce4
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: bin/shotman_completions
===> Error: Plist issues found.
*** Error code 1