mail/exim: unbreak build with LLVM15 (+)
Pass -Wno-int-conversion to CFLAGS fixes error with strict conversion rules introduced in LLVM15

error: incompatible pointer to integer conversion passing 'char *' to parameter of type 'BOOL' (aka 'unsigned int') [-Wint-conversion]