math/libdivide: fix build with clang 19
Clang 19 has become more strict about errors in member functions, which
results in errors building math/libdivide:

  /wrkdirs/usr/ports/math/libdivide/work/libdivide-5.0/libdivide.h:3020:41: error: no member named 'denom' in 'divider<T, ALGO>'
   3020 |         return div.denom.magic == other.denom.magic && div.denom.more == other.denom.more;
        |                                   ~~~~~ ^
  /wrkdirs/usr/ports/math/libdivide/work/libdivide-5.0/libdivide.h:3020:80: error: no member named 'denom' in 'divider<T, ALGO>'
   3020 |         return div.denom.magic == other.denom.magic && div.denom.more == other.denom.more;
        |                                                                          ~~~~~ ^

The member function `operator==()` should refer to `other.div.denom`
instead. Upstream fixed this in
https://github.com/ridiculousfish/libdivide/commit/fa020f3, so import it
as a patch.

PR:		282827
Approved by:	thierry (maintainer)
MFH:		2024Q4

(cherry picked from commit 822b0e7aebed327a924dc812b43c7cce2b19f7ea)