devel/libayatana-appindicator: fix packaging (+)
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: include/libayatana-appindicator3-0.1/libayatana-appindicator/app-indicator-version.h
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.

Fixes:		d9a29ada6b31
Reported by:	bulk -t
Approved by:	portmgr blanket