Mark broken: fails to build
On 8 and 9:
src/collision_world.cpp: In member function 'bool COLLISION_WORLD::CastRay(const MATHVECTOR<float, 3u>&, const MATHVECTOR<float, 3u>&, float, const btCollisionObject*, COLLISION_CONTACT&) const':
src/collision_world.cpp:204: error: invalid conversion from 'const btCollisionObject*' to 'btCollisionObject*'
scons: *** [build/collision_world.o] Error 1
scons: building terminated because of errors.
*** [do-build] Error code 2

On 10 and head:
scons: Reading SConscript files ...
Checking for C++ header file asio.hpp... no
You do not have the asio.hpp headers installed. Exiting.
*** Error code 1

Reported by:	pkg-fallout
With hat:	portmgr