devel/android-tools-simpleperf: lock llvm-version at 9
LLVM_DEFAULT will be bumped to 15, this port fails with:
	[...]
	/usr/local/llvm15/include/llvm/ADT/STLForwardCompat.h:74:21:
	error: no template named 'remove_cv_t' i n namespace 'std'; did
	you mean 'remove_cv'?
	  using type = std::remove_cv_t<std::remove_reference_t<T>>;
		       ~~~~~^~~~~~~~~~~
			    remove_cv
	[...]

PR:		263456