cad/opencascade: link with execinfo
Fix a failure detected in another project:
> ImportError: /usr/local/lib/libTKernel.so.7: Undefined symbol "backtrace"

PR:		261583
Reported by:	yuri

(cherry picked from commit a961a22e6f7c4287511ac582362e65236ece4725)